#!smake
#
# Makefile for libsnmp.
#
#ident	"$Revision: 1.1 $"

DEPTH=.
C++FILES= commauth.c++ remotesubagent.c++ sat.c++ sgisa.c++ snmpsa.c++ \
    subagent.c++ systemsa.c++ table.c++ traphandler.c++

include $(ROOT)/usr/include/make/libleafdefs
include $(LIBLEAFRULES)
