#define	_SGI_Dt_strerror_0	":1"
#define	_SGI_t_strerror_0	"uxlibxnet:1"
#define	_SGI_Mt_strerror_0	"uxlibxnet:1:No Error"
#define	_SGI_St_strerror_0	"No Error"
#define	_SGI_Dt_strerror_TBADADDR	":2"
#define	_SGI_t_strerror_TBADADDR	"uxlibxnet:2"
#define	_SGI_Mt_strerror_TBADADDR	"uxlibxnet:2:incorrect addr format"
#define	_SGI_St_strerror_TBADADDR	"incorrect addr format"
#define	_SGI_Dt_strerror_TBADOPT	":3"
#define	_SGI_t_strerror_TBADOPT	"uxlibxnet:3"
#define	_SGI_Mt_strerror_TBADOPT	"uxlibxnet:3:incorrect option format"
#define	_SGI_St_strerror_TBADOPT	"incorrect option format"
#define	_SGI_Dt_strerror_TACCES	":4"
#define	_SGI_t_strerror_TACCES	"uxlibxnet:4"
#define	_SGI_Mt_strerror_TACCES	"uxlibxnet:4:incorrect permissions"
#define	_SGI_St_strerror_TACCES	"incorrect permissions"
#define	_SGI_Dt_strerror_TBADF	":5"
#define	_SGI_t_strerror_TBADF	"uxlibxnet:5"
#define	_SGI_Mt_strerror_TBADF	"uxlibxnet:5:illegal transport fd"
#define	_SGI_St_strerror_TBADF	"illegal transport fd"
#define	_SGI_Dt_strerror_TNOADDR	":6"
#define	_SGI_t_strerror_TNOADDR	"uxlibxnet:6"
#define	_SGI_Mt_strerror_TNOADDR	"uxlibxnet:6:couldn't allocate addr"
#define	_SGI_St_strerror_TNOADDR	"couldn't allocate addr"
#define	_SGI_Dt_strerror_TOUTSTAT	":7"
#define	_SGI_t_strerror_TOUTSTAT	"uxlibxnet:7"
#define	_SGI_Mt_strerror_TOUTSTAT	"uxlibxnet:7:out of state"
#define	_SGI_St_strerror_TOUTSTAT	"out of state"
#define	_SGI_Dt_strerror_TBADSEQ	":8"
#define	_SGI_t_strerror_TBADSEQ	"uxlibxnet:8"
#define	_SGI_Mt_strerror_TBADSEQ	"uxlibxnet:8:bad call sequence number"
#define	_SGI_St_strerror_TBADSEQ	"bad call sequence number"
#define	_SGI_Dt_strerror_TSYSERR	":9"
#define	_SGI_t_strerror_TSYSERR	"uxlibxnet:9"
#define	_SGI_Mt_strerror_TSYSERR	"uxlibxnet:9:system error"
#define	_SGI_St_strerror_TSYSERR	"system error"
#define	_SGI_Dt_strerror_TLOOK	":10"
#define	_SGI_t_strerror_TLOOK	"uxlibxnet:10"
#define	_SGI_Mt_strerror_TLOOK	"uxlibxnet:10:event requires attention"
#define	_SGI_St_strerror_TLOOK	"event requires attention"
#define	_SGI_Dt_strerror_TBADDATA	":11"
#define	_SGI_t_strerror_TBADDATA	"uxlibxnet:11"
#define	_SGI_Mt_strerror_TBADDATA	"uxlibxnet:11:illegal amount of data"
#define	_SGI_St_strerror_TBADDATA	"illegal amount of data"
#define	_SGI_Dt_strerror_TBUFOVFLW	":12"
#define	_SGI_t_strerror_TBUFOVFLW	"uxlibxnet:12"
#define	_SGI_Mt_strerror_TBUFOVFLW	"uxlibxnet:12:buffer not large enough"
#define	_SGI_St_strerror_TBUFOVFLW	"buffer not large enough"
#define	_SGI_Dt_strerror_TFLOW	":13"
#define	_SGI_t_strerror_TFLOW	"uxlibxnet:13"
#define	_SGI_Mt_strerror_TFLOW	"uxlibxnet:13:flow control"
#define	_SGI_St_strerror_TFLOW	"flow control"
#define	_SGI_Dt_strerror_TNODATA	":14"
#define	_SGI_t_strerror_TNODATA	"uxlibxnet:14"
#define	_SGI_Mt_strerror_TNODATA	"uxlibxnet:14:no data"
#define	_SGI_St_strerror_TNODATA	"no data"
#define	_SGI_Dt_strerror_TNODIS	":15"
#define	_SGI_t_strerror_TNODIS	"uxlibxnet:15"
#define	_SGI_Mt_strerror_TNODIS	"uxlibxnet:15:discon_ind not found on queue"
#define	_SGI_St_strerror_TNODIS	"discon_ind not found on queue"
#define	_SGI_Dt_strerror_TNOUDERR	":16"
#define	_SGI_t_strerror_TNOUDERR	"uxlibxnet:16"
#define	_SGI_Mt_strerror_TNOUDERR	"uxlibxnet:16:unitdata error not found"
#define	_SGI_St_strerror_TNOUDERR	"unitdata error not found"
#define	_SGI_Dt_strerror_TBADFLAG	":17"
#define	_SGI_t_strerror_TBADFLAG	"uxlibxnet:17"
#define	_SGI_Mt_strerror_TBADFLAG	"uxlibxnet:17:bad flags"
#define	_SGI_St_strerror_TBADFLAG	"bad flags"
#define	_SGI_Dt_strerror_TNOREL	":18"
#define	_SGI_t_strerror_TNOREL	"uxlibxnet:18"
#define	_SGI_Mt_strerror_TNOREL	"uxlibxnet:18:no ord rel found on queue"
#define	_SGI_St_strerror_TNOREL	"no ord rel found on queue"
#define	_SGI_Dt_strerror_TNOTSUPPORT	":19"
#define	_SGI_t_strerror_TNOTSUPPORT	"uxlibxnet:19"
#define	_SGI_Mt_strerror_TNOTSUPPORT	"uxlibxnet:19:primitive/action not supported"
#define	_SGI_St_strerror_TNOTSUPPORT	"primitive/action not supported"
#define	_SGI_Dt_strerror_TSTATECHNG	":20"
#define	_SGI_t_strerror_TSTATECHNG	"uxlibxnet:20"
#define	_SGI_Mt_strerror_TSTATECHNG	"uxlibxnet:20:state is in process of changing"
#define	_SGI_St_strerror_TSTATECHNG	"state is in process of changing"
#define	_SGI_Dt_strerror_TNOSTRUCTYPE	":21"
#define	_SGI_t_strerror_TNOSTRUCTYPE	"uxlibxnet:21"
#define	_SGI_Mt_strerror_TNOSTRUCTYPE	"uxlibxnet:21:unsupported struct-type requested"
#define	_SGI_St_strerror_TNOSTRUCTYPE	"unsupported struct-type requested"
#define	_SGI_Dt_strerror_TBADNAME	":22"
#define	_SGI_t_strerror_TBADNAME	"uxlibxnet:22"
#define	_SGI_Mt_strerror_TBADNAME	"uxlibxnet:22:invalid transport provider name"
#define	_SGI_St_strerror_TBADNAME	"invalid transport provider name"
#define	_SGI_Dt_strerror_TBADQLEN	":23"
#define	_SGI_t_strerror_TBADQLEN	"uxlibxnet:23"
#define	_SGI_Mt_strerror_TBADQLEN	"uxlibxnet:23:qlen is zero"
#define	_SGI_St_strerror_TBADQLEN	"qlen is zero"
#define	_SGI_Dt_strerror_TADDRBUSY	":24"
#define	_SGI_t_strerror_TADDRBUSY	"uxlibxnet:24"
#define	_SGI_Mt_strerror_TADDRBUSY	"uxlibxnet:24:address in use"
#define	_SGI_St_strerror_TADDRBUSY	"address in use"
#define	_SGI_Dt_strerror_TINDOUT	":25"
#define	_SGI_t_strerror_TINDOUT	"uxlibxnet:25"
#define	_SGI_Mt_strerror_TINDOUT	"uxlibxnet:25:outstanding connection indications"
#define	_SGI_St_strerror_TINDOUT	"outstanding connection indications"
#define	_SGI_Dt_strerror_TPROVMISMATCH	":26"
#define	_SGI_t_strerror_TPROVMISMATCH	"uxlibxnet:26"
#define	_SGI_Mt_strerror_TPROVMISMATCH	"uxlibxnet:26:transport provider mismatch"
#define	_SGI_St_strerror_TPROVMISMATCH	"transport provider mismatch"
#define	_SGI_Dt_strerror_TRESADDR_A	":27"
#define	_SGI_t_strerror_TRESADDR_A	"uxlibxnet:27"
#define	_SGI_Mt_strerror_TRESADDR_A	"uxlibxnet:27:resfd specified to accept w/qlen >0"
#define	_SGI_St_strerror_TRESADDR_A	"resfd specified to accept w/qlen >0"
#define	_SGI_Dt_strerror_TRESADDR_B	":28"
#define	_SGI_t_strerror_TRESADDR_B	"uxlibxnet:28"
#define	_SGI_Mt_strerror_TRESADDR_B	"uxlibxnet:28:resfd not bound to same addr as fd"
#define	_SGI_St_strerror_TRESADDR_B	"resfd not bound to same addr as fd"
#define	_SGI_Dt_strerror_TQFULL	":29"
#define	_SGI_t_strerror_TQFULL	"uxlibxnet:29"
#define	_SGI_Mt_strerror_TQFULL	"uxlibxnet:29:incoming connection queue full"
#define	_SGI_St_strerror_TQFULL	"incoming connection queue full"
#define	_SGI_Dt_strerror_TPROTO	":30"
#define	_SGI_t_strerror_TPROTO	"uxlibxnet:30"
#define	_SGI_Mt_strerror_TPROTO	"uxlibxnet:30:XTI protocol error"
#define	_SGI_St_strerror_TPROTO	"XTI protocol error"
#define	_SGI_Dt_strerror_unknown	":31"
#define	_SGI_t_strerror_unknown	"uxlibxnet:31"
#define	_SGI_Mt_strerror_unknown	"uxlibxnet:31:%d: error unknown"
#define	_SGI_St_strerror_unknown	"%d: error unknown"
