#define	_SGI_DGETOPT_ILLOPT	":1"
#define	_SGI_GETOPT_ILLOPT	"uxlibc:1"
#define	_SGI_MGETOPT_ILLOPT	"uxlibc:1:Illegal option -- %c\n"
#define	_SGI_SGETOPT_ILLOPT	"Illegal option -- %c\n"
#define	_SGI_DGETOPT_NO_ARG	":2"
#define	_SGI_GETOPT_NO_ARG	"uxlibc:2"
#define	_SGI_MGETOPT_NO_ARG	"uxlibc:2:Option requires an argument -- %c\n"
#define	_SGI_SGETOPT_NO_ARG	"Option requires an argument -- %c\n"
#define	_SGI_DPFMT_DEF_COLON	":3"
#define	_SGI_PFMT_DEF_COLON	"uxlibc:3"
#define	_SGI_MPFMT_DEF_COLON	"uxlibc:3:: "
#define	_SGI_SPFMT_DEF_COLON	": "
#define	_SGI_DSIGNAL_0	":4"
#define	_SGI_SIGNAL_0	"uxlibc:4"
#define	_SGI_MSIGNAL_0	"uxlibc:4:Signal 0"
#define	_SGI_SSIGNAL_0	"Signal 0"
#define	_SGI_DSIGNAL_1	":5"
#define	_SGI_SIGNAL_1	"uxlibc:5"
#define	_SGI_MSIGNAL_1	"uxlibc:5:Hangup"
#define	_SGI_SSIGNAL_1	"Hangup"
#define	_SGI_DSIGNAL_2	":6"
#define	_SGI_SIGNAL_2	"uxlibc:6"
#define	_SGI_MSIGNAL_2	"uxlibc:6:Interrupt"
#define	_SGI_SSIGNAL_2	"Interrupt"
#define	_SGI_DSIGNAL_3	":7"
#define	_SGI_SIGNAL_3	"uxlibc:7"
#define	_SGI_MSIGNAL_3	"uxlibc:7:Quit"
#define	_SGI_SSIGNAL_3	"Quit"
#define	_SGI_DSIGNAL_4	":8"
#define	_SGI_SIGNAL_4	"uxlibc:8"
#define	_SGI_MSIGNAL_4	"uxlibc:8:Illegal instruction"
#define	_SGI_SSIGNAL_4	"Illegal instruction"
#define	_SGI_DSIGNAL_5	":9"
#define	_SGI_SIGNAL_5	"uxlibc:9"
#define	_SGI_MSIGNAL_5	"uxlibc:9:Trace/BPT trap"
#define	_SGI_SSIGNAL_5	"Trace/BPT trap"
#define	_SGI_DSIGNAL_6	":10"
#define	_SGI_SIGNAL_6	"uxlibc:10"
#define	_SGI_MSIGNAL_6	"uxlibc:10:Abort"
#define	_SGI_SSIGNAL_6	"Abort"
#define	_SGI_DSIGNAL_7	":11"
#define	_SGI_SIGNAL_7	"uxlibc:11"
#define	_SGI_MSIGNAL_7	"uxlibc:11:EMT trap"
#define	_SGI_SSIGNAL_7	"EMT trap"
#define	_SGI_DSIGNAL_8	":12"
#define	_SGI_SIGNAL_8	"uxlibc:12"
#define	_SGI_MSIGNAL_8	"uxlibc:12:Floating point exception"
#define	_SGI_SSIGNAL_8	"Floating point exception"
#define	_SGI_DSIGNAL_9	":13"
#define	_SGI_SIGNAL_9	"uxlibc:13"
#define	_SGI_MSIGNAL_9	"uxlibc:13:Killed"
#define	_SGI_SSIGNAL_9	"Killed"
#define	_SGI_DSIGNAL_10	":14"
#define	_SGI_SIGNAL_10	"uxlibc:14"
#define	_SGI_MSIGNAL_10	"uxlibc:14:Bus error"
#define	_SGI_SSIGNAL_10	"Bus error"
#define	_SGI_DSIGNAL_11	":15"
#define	_SGI_SIGNAL_11	"uxlibc:15"
#define	_SGI_MSIGNAL_11	"uxlibc:15:Segmentation fault"
#define	_SGI_SSIGNAL_11	"Segmentation fault"
#define	_SGI_DSIGNAL_12	":16"
#define	_SGI_SIGNAL_12	"uxlibc:16"
#define	_SGI_MSIGNAL_12	"uxlibc:16:Bad system call"
#define	_SGI_SSIGNAL_12	"Bad system call"
#define	_SGI_DSIGNAL_13	":17"
#define	_SGI_SIGNAL_13	"uxlibc:17"
#define	_SGI_MSIGNAL_13	"uxlibc:17:Broken pipe"
#define	_SGI_SSIGNAL_13	"Broken pipe"
#define	_SGI_DSIGNAL_14	":18"
#define	_SGI_SIGNAL_14	"uxlibc:18"
#define	_SGI_MSIGNAL_14	"uxlibc:18:Alarm clock"
#define	_SGI_SSIGNAL_14	"Alarm clock"
#define	_SGI_DSIGNAL_15	":19"
#define	_SGI_SIGNAL_15	"uxlibc:19"
#define	_SGI_MSIGNAL_15	"uxlibc:19:Terminated"
#define	_SGI_SSIGNAL_15	"Terminated"
#define	_SGI_DSIGNAL_16	":20"
#define	_SGI_SIGNAL_16	"uxlibc:20"
#define	_SGI_MSIGNAL_16	"uxlibc:20:User defined signal 1"
#define	_SGI_SSIGNAL_16	"User defined signal 1"
#define	_SGI_DSIGNAL_17	":21"
#define	_SGI_SIGNAL_17	"uxlibc:21"
#define	_SGI_MSIGNAL_17	"uxlibc:21:User defined signal 2"
#define	_SGI_SSIGNAL_17	"User defined signal 2"
#define	_SGI_DSIGNAL_18	":22"
#define	_SGI_SIGNAL_18	"uxlibc:22"
#define	_SGI_MSIGNAL_18	"uxlibc:22:Child exited"
#define	_SGI_SSIGNAL_18	"Child exited"
#define	_SGI_DSIGNAL_19	":23"
#define	_SGI_SIGNAL_19	"uxlibc:23"
#define	_SGI_MSIGNAL_19	"uxlibc:23:Power-fail restart"
#define	_SGI_SSIGNAL_19	"Power-fail restart"
#define	_SGI_DSIGNAL_20	":24"
#define	_SGI_SIGNAL_20	"uxlibc:24"
#define	_SGI_MSIGNAL_20	"uxlibc:24:Window size changes"
#define	_SGI_SSIGNAL_20	"Window size changes"
#define	_SGI_DSIGNAL_21	":25"
#define	_SGI_SIGNAL_21	"uxlibc:25"
#define	_SGI_MSIGNAL_21	"uxlibc:25:Urgent I/O condition"
#define	_SGI_SSIGNAL_21	"Urgent I/O condition"
#define	_SGI_DSIGNAL_22	":26"
#define	_SGI_SIGNAL_22	"uxlibc:26"
#define	_SGI_MSIGNAL_22	"uxlibc:26:Pollable event occured"
#define	_SGI_SSIGNAL_22	"Pollable event occured"
#define	_SGI_DSIGNAL_23	":27"
#define	_SGI_SIGNAL_23	"uxlibc:27"
#define	_SGI_MSIGNAL_23	"uxlibc:27:Stop signal (not from tty)"
#define	_SGI_SSIGNAL_23	"Stop signal (not from tty)"
#define	_SGI_DSIGNAL_24	":28"
#define	_SGI_SIGNAL_24	"uxlibc:28"
#define	_SGI_MSIGNAL_24	"uxlibc:28:Stop signal from tty"
#define	_SGI_SSIGNAL_24	"Stop signal from tty"
#define	_SGI_DSIGNAL_25	":29"
#define	_SGI_SIGNAL_25	"uxlibc:29"
#define	_SGI_MSIGNAL_25	"uxlibc:29:Continued"
#define	_SGI_SSIGNAL_25	"Continued"
#define	_SGI_DSIGNAL_26	":30"
#define	_SGI_SIGNAL_26	"uxlibc:30"
#define	_SGI_MSIGNAL_26	"uxlibc:30:Stopped (tty input)"
#define	_SGI_SSIGNAL_26	"Stopped (tty input)"
#define	_SGI_DSIGNAL_27	":31"
#define	_SGI_SIGNAL_27	"uxlibc:31"
#define	_SGI_MSIGNAL_27	"uxlibc:31:Stopped (tty output)"
#define	_SGI_SSIGNAL_27	"Stopped (tty output)"
#define	_SGI_DSIGNAL_28	":32"
#define	_SGI_SIGNAL_28	"uxlibc:32"
#define	_SGI_MSIGNAL_28	"uxlibc:32:Virtual time alarm"
#define	_SGI_SSIGNAL_28	"Virtual time alarm"
#define	_SGI_DSIGNAL_29	":33"
#define	_SGI_SIGNAL_29	"uxlibc:33"
#define	_SGI_MSIGNAL_29	"uxlibc:33:Profiling alarm"
#define	_SGI_SSIGNAL_29	"Profiling alarm"
#define	_SGI_DSIGNAL_30	":34"
#define	_SGI_SIGNAL_30	"uxlibc:34"
#define	_SGI_MSIGNAL_30	"uxlibc:34:Cputime limit exceeded"
#define	_SGI_SSIGNAL_30	"Cputime limit exceeded"
#define	_SGI_DSIGNAL_31	":35"
#define	_SGI_SIGNAL_31	"uxlibc:35"
#define	_SGI_MSIGNAL_31	"uxlibc:35:Filesize limit exceeded"
#define	_SGI_SSIGNAL_31	"Filesize limit exceeded"
#define	_SGI_DSIGNAL_32	":36"
#define	_SGI_SIGNAL_32	"uxlibc:36"
#define	_SGI_MSIGNAL_32	"uxlibc:36:Signal 32"
#define	_SGI_SSIGNAL_32	"Signal 32"
#define	_SGI_DSIGNAL_33	":37"
#define	_SGI_SIGNAL_33	"uxlibc:37"
#define	_SGI_MSIGNAL_33	"uxlibc:37:System reserved signal 33"
#define	_SGI_SSIGNAL_33	"System reserved signal 33"
#define	_SGI_DSIGNAL_34	":38"
#define	_SGI_SIGNAL_34	"uxlibc:38"
#define	_SGI_MSIGNAL_34	"uxlibc:38:System reserved signal 34"
#define	_SGI_SSIGNAL_34	"System reserved signal 34"
#define	_SGI_DSIGNAL_35	":39"
#define	_SGI_SIGNAL_35	"uxlibc:39"
#define	_SGI_MSIGNAL_35	"uxlibc:39:System reserved signal 35"
#define	_SGI_SSIGNAL_35	"System reserved signal 35"
#define	_SGI_DSIGNAL_36	":40"
#define	_SGI_SIGNAL_36	"uxlibc:40"
#define	_SGI_MSIGNAL_36	"uxlibc:40:System reserved signal 36"
#define	_SGI_SSIGNAL_36	"System reserved signal 36"
#define	_SGI_DSIGNAL_37	":41"
#define	_SGI_SIGNAL_37	"uxlibc:41"
#define	_SGI_MSIGNAL_37	"uxlibc:41:System reserved signal 37"
#define	_SGI_SSIGNAL_37	"System reserved signal 37"
#define	_SGI_DSIGNAL_38	":42"
#define	_SGI_SIGNAL_38	"uxlibc:42"
#define	_SGI_MSIGNAL_38	"uxlibc:42:System reserved signal 38"
#define	_SGI_SSIGNAL_38	"System reserved signal 38"
#define	_SGI_DSIGNAL_39	":43"
#define	_SGI_SIGNAL_39	"uxlibc:43"
#define	_SGI_MSIGNAL_39	"uxlibc:43:System reserved signal 39"
#define	_SGI_SSIGNAL_39	"System reserved signal 39"
#define	_SGI_DSIGNAL_40	":44"
#define	_SGI_SIGNAL_40	"uxlibc:44"
#define	_SGI_MSIGNAL_40	"uxlibc:44:System reserved signal 40"
#define	_SGI_SSIGNAL_40	"System reserved signal 40"
#define	_SGI_DSIGNAL_41	":45"
#define	_SGI_SIGNAL_41	"uxlibc:45"
#define	_SGI_MSIGNAL_41	"uxlibc:45:System reserved signal 41"
#define	_SGI_SSIGNAL_41	"System reserved signal 41"
#define	_SGI_DSIGNAL_42	":46"
#define	_SGI_SIGNAL_42	"uxlibc:46"
#define	_SGI_MSIGNAL_42	"uxlibc:46:System reserved signal 42"
#define	_SGI_SSIGNAL_42	"System reserved signal 42"
#define	_SGI_DSIGNAL_43	":47"
#define	_SGI_SIGNAL_43	"uxlibc:47"
#define	_SGI_MSIGNAL_43	"uxlibc:47:System reserved signal 43"
#define	_SGI_SSIGNAL_43	"System reserved signal 43"
#define	_SGI_DSIGNAL_44	":48"
#define	_SGI_SIGNAL_44	"uxlibc:48"
#define	_SGI_MSIGNAL_44	"uxlibc:48:System reserved signal 44"
#define	_SGI_SSIGNAL_44	"System reserved signal 44"
#define	_SGI_DSIGNAL_45	":49"
#define	_SGI_SIGNAL_45	"uxlibc:49"
#define	_SGI_MSIGNAL_45	"uxlibc:49:System reserved signal 45"
#define	_SGI_SSIGNAL_45	"System reserved signal 45"
#define	_SGI_DSIGNAL_46	":50"
#define	_SGI_SIGNAL_46	"uxlibc:50"
#define	_SGI_MSIGNAL_46	"uxlibc:50:System reserved signal 46"
#define	_SGI_SSIGNAL_46	"System reserved signal 46"
#define	_SGI_DSIGNAL_47	":51"
#define	_SGI_SIGNAL_47	"uxlibc:51"
#define	_SGI_MSIGNAL_47	"uxlibc:51:System reserved signal 47"
#define	_SGI_SSIGNAL_47	"System reserved signal 47"
#define	_SGI_DSIGNAL_48	":52"
#define	_SGI_SIGNAL_48	"uxlibc:52"
#define	_SGI_MSIGNAL_48	"uxlibc:52:System reserved signal 48"
#define	_SGI_SSIGNAL_48	"System reserved signal 48"
#define	_SGI_DSIGNAL_49	":53"
#define	_SGI_SIGNAL_49	"uxlibc:53"
#define	_SGI_MSIGNAL_49	"uxlibc:53:Real-time signal RTMIN"
#define	_SGI_SSIGNAL_49	"Real-time signal RTMIN"
#define	_SGI_DSIGNAL_50	":54"
#define	_SGI_SIGNAL_50	"uxlibc:54"
#define	_SGI_MSIGNAL_50	"uxlibc:54:Real-time signal RTMIN+1"
#define	_SGI_SSIGNAL_50	"Real-time signal RTMIN+1"
#define	_SGI_DSIGNAL_51	":55"
#define	_SGI_SIGNAL_51	"uxlibc:55"
#define	_SGI_MSIGNAL_51	"uxlibc:55:Real-time signal RTMIN+2"
#define	_SGI_SSIGNAL_51	"Real-time signal RTMIN+2"
#define	_SGI_DSIGNAL_52	":56"
#define	_SGI_SIGNAL_52	"uxlibc:56"
#define	_SGI_MSIGNAL_52	"uxlibc:56:Real-time signal RTMIN+3"
#define	_SGI_SSIGNAL_52	"Real-time signal RTMIN+3"
#define	_SGI_DSIGNAL_53	":57"
#define	_SGI_SIGNAL_53	"uxlibc:57"
#define	_SGI_MSIGNAL_53	"uxlibc:57:Real-time signal RTMIN+4"
#define	_SGI_SSIGNAL_53	"Real-time signal RTMIN+4"
#define	_SGI_DSIGNAL_54	":58"
#define	_SGI_SIGNAL_54	"uxlibc:58"
#define	_SGI_MSIGNAL_54	"uxlibc:58:Real-time signal RTMIN+5"
#define	_SGI_SSIGNAL_54	"Real-time signal RTMIN+5"
#define	_SGI_DSIGNAL_55	":59"
#define	_SGI_SIGNAL_55	"uxlibc:59"
#define	_SGI_MSIGNAL_55	"uxlibc:59:Real-time signal RTMIN+6"
#define	_SGI_SSIGNAL_55	"Real-time signal RTMIN+6"
#define	_SGI_DSIGNAL_56	":60"
#define	_SGI_SIGNAL_56	"uxlibc:60"
#define	_SGI_MSIGNAL_56	"uxlibc:60:Real-time signal RTMIN+7"
#define	_SGI_SSIGNAL_56	"Real-time signal RTMIN+7"
#define	_SGI_DSIGNAL_57	":61"
#define	_SGI_SIGNAL_57	"uxlibc:61"
#define	_SGI_MSIGNAL_57	"uxlibc:61:Real-time signal RTMIN+8"
#define	_SGI_SSIGNAL_57	"Real-time signal RTMIN+8"
#define	_SGI_DSIGNAL_58	":62"
#define	_SGI_SIGNAL_58	"uxlibc:62"
#define	_SGI_MSIGNAL_58	"uxlibc:62:Real-time signal RTMIN+9"
#define	_SGI_SSIGNAL_58	"Real-time signal RTMIN+9"
#define	_SGI_DSIGNAL_59	":63"
#define	_SGI_SIGNAL_59	"uxlibc:63"
#define	_SGI_MSIGNAL_59	"uxlibc:63:Real-time signal RTMIN+10"
#define	_SGI_SSIGNAL_59	"Real-time signal RTMIN+10"
#define	_SGI_DSIGNAL_60	":64"
#define	_SGI_SIGNAL_60	"uxlibc:64"
#define	_SGI_MSIGNAL_60	"uxlibc:64:Real-time signal RTMIN+11"
#define	_SGI_SSIGNAL_60	"Real-time signal RTMIN+11"
#define	_SGI_DSIGNAL_61	":65"
#define	_SGI_SIGNAL_61	"uxlibc:65"
#define	_SGI_MSIGNAL_61	"uxlibc:65:Real-time signal RTMIN+12"
#define	_SGI_SSIGNAL_61	"Real-time signal RTMIN+12"
#define	_SGI_DSIGNAL_62	":66"
#define	_SGI_SIGNAL_62	"uxlibc:66"
#define	_SGI_MSIGNAL_62	"uxlibc:66:Real-time signal RTMIN+13"
#define	_SGI_SSIGNAL_62	"Real-time signal RTMIN+13"
#define	_SGI_DSIGNAL_63	":67"
#define	_SGI_SIGNAL_63	"uxlibc:67"
#define	_SGI_MSIGNAL_63	"uxlibc:67:Real-time signal RTMIN+14"
#define	_SGI_SSIGNAL_63	"Real-time signal RTMIN+14"
#define	_SGI_DSIGNAL_64	":68"
#define	_SGI_SIGNAL_64	"uxlibc:68"
#define	_SGI_MSIGNAL_64	"uxlibc:68:Real-time signal RTMAX"
#define	_SGI_SSIGNAL_64	"Real-time signal RTMAX"
#define	_SGI_DUXLIBC_69	":69"
#define	_SGI_UXLIBC_69	"uxlibc:69"
#define	_SGI_MUXLIBC_69	"uxlibc:69:high priority input available"
#define	_SGI_SUXLIBC_69	"high priority input available"
#define	_SGI_DUXLIBC_70	":70"
#define	_SGI_UXLIBC_70	"uxlibc:70"
#define	_SGI_MUXLIBC_70	"uxlibc:70:disconnected device"
#define	_SGI_SUXLIBC_70	"disconnected device"
#define	_SGI_DUXLIBC_71	":71"
#define	_SGI_UXLIBC_71	"uxlibc:71"
#define	_SGI_MUXLIBC_71	"uxlibc:71: ( from process %d )"
#define	_SGI_SUXLIBC_71	" ( from process %d )"
#define	_SGI_DPFMT_SEV	":72"
#define	_SGI_PFMT_SEV	"uxlibc:72"
#define	_SGI_MPFMT_SEV	"uxlibc:72:SEV = %d"
#define	_SGI_SPFMT_SEV	"SEV = %d"
#define	_SGI_DPFMT_TO_FIX	":73"
#define	_SGI_PFMT_TO_FIX	"uxlibc:73"
#define	_SGI_MPFMT_TO_FIX	"uxlibc:73:TO FIX"
#define	_SGI_SPFMT_TO_FIX	"TO FIX"
#define	_SGI_DPFMT_ERROR	":74"
#define	_SGI_PFMT_ERROR	"uxlibc:74"
#define	_SGI_MPFMT_ERROR	"uxlibc:74:ERROR"
#define	_SGI_SPFMT_ERROR	"ERROR"
#define	_SGI_DPFMT_HALT	":75"
#define	_SGI_PFMT_HALT	"uxlibc:75"
#define	_SGI_MPFMT_HALT	"uxlibc:75:HALT"
#define	_SGI_SPFMT_HALT	"HALT"
#define	_SGI_DPFMT_WARNING	":76"
#define	_SGI_PFMT_WARNING	"uxlibc:76"
#define	_SGI_MPFMT_WARNING	"uxlibc:76:WARNING"
#define	_SGI_SPFMT_WARNING	"WARNING"
#define	_SGI_DPFMT_INFO	":77"
#define	_SGI_PFMT_INFO	"uxlibc:77"
#define	_SGI_MPFMT_INFO	"uxlibc:77:INFO"
#define	_SGI_SPFMT_INFO	"INFO"
#define	_SGI_DYACCPAR_SYNTAX	":78"
#define	_SGI_YACCPAR_SYNTAX	"uxlibc:78"
#define	_SGI_MYACCPAR_SYNTAX	"uxlibc:78:Syntax error - cannot backup"
#define	_SGI_SYACCPAR_SYNTAX	"Syntax error - cannot backup"
#define	_SGI_DYACCPAR_INITERR	":79"
#define	_SGI_YACCPAR_INITERR	"uxlibc:79"
#define	_SGI_MYACCPAR_INITERR	"uxlibc:79:Yacc initialization error"
#define	_SGI_SYACCPAR_INITERR	"Yacc initialization error"
#define	_SGI_DYACCPAR_STACK	":80"
#define	_SGI_YACCPAR_STACK	"uxlibc:80"
#define	_SGI_MYACCPAR_STACK	"uxlibc:80:Yacc stack overflow"
#define	_SGI_SYACCPAR_STACK	"Yacc stack overflow"
#define	_SGI_DSYNTAX_ERROR	":81"
#define	_SGI_SYNTAX_ERROR	"uxlibc:81"
#define	_SGI_MSYNTAX_ERROR	"uxlibc:81:Syntax error"
#define	_SGI_SSYNTAX_ERROR	"Syntax error"
#define	_SGI_DUXLIBC_82	":82"
#define	_SGI_UXLIBC_82	"uxlibc:82"
#define	_SGI_MUXLIBC_82	"uxlibc:82:Format error, no tabs after %s at line %d\n"
#define	_SGI_SUXLIBC_82	"Format error, no tabs after %s at line %d\n"
#define	_SGI_DUXLIBC_83	":83"
#define	_SGI_UXLIBC_83	"uxlibc:83"
#define	_SGI_MUXLIBC_83	"uxlibc:83:Not enough memory for the magic table"
#define	_SGI_SUXLIBC_83	"Not enough memory for the magic table"
#define	_SGI_DFILE_84	":84"
#define	_SGI_FILE_84	"uxlibc:84"
#define	_SGI_MFILE_84	"uxlibc:84:%s:\t"
#define	_SGI_SFILE_84	"%s:\t"
#define	_SGI_DUXLIBC_85	":85"
#define	_SGI_UXLIBC_85	"uxlibc:85"
#define	_SGI_MUXLIBC_85	"uxlibc:85:Can't open the magic file <%s>: %s\n"
#define	_SGI_SUXLIBC_85	"Can't open the magic file <%s>: %s\n"
#define	_SGI_DUXLIBC_86	":86"
#define	_SGI_UXLIBC_86	"uxlibc:86"
#define	_SGI_MUXLIBC_86	"uxlibc:86:Can't close %s: %s\n"
#define	_SGI_SUXLIBC_86	"Can't close %s: %s\n"
#define	_SGI_DUXLIBC_87	":87"
#define	_SGI_UXLIBC_87	"uxlibc:87"
#define	_SGI_MUXLIBC_87	"uxlibc:87:level	off	type	opcode	value	string\n"
#define	_SGI_SUXLIBC_87	"level	off	type	opcode	value	string\n"
#define	_SGI_Dregcomp_REG_NOMATCH	":88"
#define	_SGI_regcomp_REG_NOMATCH	"uxlibc:88"
#define	_SGI_Mregcomp_REG_NOMATCH	"uxlibc:88:regexec() failed to match"
#define	_SGI_Sregcomp_REG_NOMATCH	"regexec() failed to match"
#define	_SGI_Dregcomp_REG_BADPAT	":89"
#define	_SGI_regcomp_REG_BADPAT	"uxlibc:89"
#define	_SGI_Mregcomp_REG_BADPAT	"uxlibc:89:invalid regular expression"
#define	_SGI_Sregcomp_REG_BADPAT	"invalid regular expression"
#define	_SGI_Dregcomp_REG_ECOLLATE	":90"
#define	_SGI_regcomp_REG_ECOLLATE	"uxlibc:90"
#define	_SGI_Mregcomp_REG_ECOLLATE	"uxlibc:90:invalid collating element"
#define	_SGI_Sregcomp_REG_ECOLLATE	"invalid collating element"
#define	_SGI_Dregcomp_REG_ECTYPE	":91"
#define	_SGI_regcomp_REG_ECTYPE	"uxlibc:91"
#define	_SGI_Mregcomp_REG_ECTYPE	"uxlibc:91:invalid character class"
#define	_SGI_Sregcomp_REG_ECTYPE	"invalid character class"
#define	_SGI_Dregcomp_REG_EESCAPE	":92"
#define	_SGI_regcomp_REG_EESCAPE	"uxlibc:92"
#define	_SGI_Mregcomp_REG_EESCAPE	"uxlibc:92:trailing backslash (\\)"
#define	_SGI_Sregcomp_REG_EESCAPE	"trailing backslash (\\)"
#define	_SGI_Dregcomp_REG_ESUBREG	":93"
#define	_SGI_regcomp_REG_ESUBREG	"uxlibc:93"
#define	_SGI_Mregcomp_REG_ESUBREG	"uxlibc:93:invalid backreference number"
#define	_SGI_Sregcomp_REG_ESUBREG	"invalid backreference number"
#define	_SGI_Dregcomp_REG_EBRACK	":94"
#define	_SGI_regcomp_REG_EBRACK	"uxlibc:94"
#define	_SGI_Mregcomp_REG_EBRACK	"uxlibc:94:brackets ([ ]) not balanced"
#define	_SGI_Sregcomp_REG_EBRACK	"brackets ([ ]) not balanced"
#define	_SGI_Dregcomp_REG_EPAREN	":95"
#define	_SGI_regcomp_REG_EPAREN	"uxlibc:95"
#define	_SGI_Mregcomp_REG_EPAREN	"uxlibc:95:parentheses not balanced"
#define	_SGI_Sregcomp_REG_EPAREN	"parentheses not balanced"
#define	_SGI_Dregcomp_REG_EBRACE	":96"
#define	_SGI_regcomp_REG_EBRACE	"uxlibc:96"
#define	_SGI_Mregcomp_REG_EBRACE	"uxlibc:96:braces not balanced"
#define	_SGI_Sregcomp_REG_EBRACE	"braces not balanced"
#define	_SGI_Dregcomp_REG_BADBR	":97"
#define	_SGI_regcomp_REG_BADBR	"uxlibc:97"
#define	_SGI_Mregcomp_REG_BADBR	"uxlibc:97:invalid repetition count(s)"
#define	_SGI_Sregcomp_REG_BADBR	"invalid repetition count(s)"
#define	_SGI_Dregcomp_REG_ERANGE	":98"
#define	_SGI_regcomp_REG_ERANGE	"uxlibc:98"
#define	_SGI_Mregcomp_REG_ERANGE	"uxlibc:98:invalid character range"
#define	_SGI_Sregcomp_REG_ERANGE	"invalid character range"
#define	_SGI_Dregcomp_REG_ESPACE	":99"
#define	_SGI_regcomp_REG_ESPACE	"uxlibc:99"
#define	_SGI_Mregcomp_REG_ESPACE	"uxlibc:99:out of memory"
#define	_SGI_Sregcomp_REG_ESPACE	"out of memory"
#define	_SGI_Dregcomp_REG_BADRPT	":100"
#define	_SGI_regcomp_REG_BADRPT	"uxlibc:100"
#define	_SGI_Mregcomp_REG_BADRPT	"uxlibc:100:repetition-operator operand invalid"
#define	_SGI_Sregcomp_REG_BADRPT	"repetition-operator operand invalid"
#define	_SGI_Dregcomp_REG_EMPTY	":101"
#define	_SGI_regcomp_REG_EMPTY	"uxlibc:101"
#define	_SGI_Mregcomp_REG_EMPTY	"uxlibc:101:empty (sub)expression"
#define	_SGI_Sregcomp_REG_EMPTY	"empty (sub)expression"
#define	_SGI_Dregcomp_REG_ASSERT	":102"
#define	_SGI_regcomp_REG_ASSERT	"uxlibc:102"
#define	_SGI_Mregcomp_REG_ASSERT	"uxlibc:102:\"can't happen\" -- you found a bug"
#define	_SGI_Sregcomp_REG_ASSERT	"\"can't happen\" -- you found a bug"
#define	_SGI_Dregcomp_REG_INVARG	":103"
#define	_SGI_regcomp_REG_INVARG	"uxlibc:103"
#define	_SGI_Mregcomp_REG_INVARG	"uxlibc:103:invalid argument to regex routine"
#define	_SGI_Sregcomp_REG_INVARG	"invalid argument to regex routine"
#define	_SGI_Dregcomp_unknown	":104"
#define	_SGI_regcomp_unknown	"uxlibc:104"
#define	_SGI_Mregcomp_unknown	"uxlibc:104:*** unknown regexp error code ***"
#define	_SGI_Sregcomp_unknown	"*** unknown regexp error code ***"
