#define	_SGI_DMMX_csh_Interrupted	":1"
#define	_SGI_MMX_csh_Interrupted	"uxsgicsh:1"
#define	_SGI_MMMX_csh_Interrupted	"uxsgicsh:1:Interrupted"
#define	_SGI_SMMX_csh_Interrupted	"Interrupted"
#define	_SGI_DMMX_csh_2fewargs	":2"
#define	_SGI_MMX_csh_2fewargs	"uxsgicsh:2"
#define	_SGI_MMMX_csh_2fewargs	"uxsgicsh:2:Too few arguments"
#define	_SGI_SMMX_csh_2fewargs	"Too few arguments"
#define	_SGI_DMMX_csh_2manyargs	":3"
#define	_SGI_MMX_csh_2manyargs	"uxsgicsh:3"
#define	_SGI_MMMX_csh_2manyargs	"uxsgicsh:3:Too many arguments"
#define	_SGI_SMMX_csh_2manyargs	"Too many arguments"
#define	_SGI_DMMX_csh_nohome	":4"
#define	_SGI_MMX_csh_nohome	"uxsgicsh:4"
#define	_SGI_MMMX_csh_nohome	"uxsgicsh:4:No home directory"
#define	_SGI_SMMX_csh_nohome	"No home directory"
#define	_SGI_DMMX_csh_cannothome	":5"
#define	_SGI_MMX_csh_cannothome	"uxsgicsh:5"
#define	_SGI_MMMX_csh_cannothome	"uxsgicsh:5:Can't change to home directory"
#define	_SGI_SMMX_csh_cannothome	"Can't change to home directory"
#define	_SGI_DMMX_csh_noodir	":6"
#define	_SGI_MMX_csh_noodir	"uxsgicsh:6"
#define	_SGI_MMMX_csh_noodir	"uxsgicsh:6:No other directory"
#define	_SGI_SMMX_csh_noodir	"No other directory"
#define	_SGI_DMMX_csh_dsnotdeep	":7"
#define	_SGI_MMX_csh_dsnotdeep	"uxsgicsh:7"
#define	_SGI_MMMX_csh_dsnotdeep	"uxsgicsh:7:Directory stack not that deep"
#define	_SGI_SMMX_csh_dsnotdeep	"Directory stack not that deep"
#define	_SGI_DMMX_csh_invarg	":8"
#define	_SGI_MMX_csh_invarg	"uxsgicsh:8"
#define	_SGI_MMMX_csh_invarg	"uxsgicsh:8:'%s' - Invalid argument"
#define	_SGI_SMMX_csh_invarg	"'%s' - Invalid argument"
#define	_SGI_DMMX_csh_dsempty	":9"
#define	_SGI_MMX_csh_dsempty	"uxsgicsh:9"
#define	_SGI_MMMX_csh_dsempty	"uxsgicsh:9:Directory stack empty"
#define	_SGI_SMMX_csh_dsempty	"Directory stack empty"
#define	_SGI_DMMX_csh_Ambiguous	":10"
#define	_SGI_MMX_csh_Ambiguous	"uxsgicsh:10"
#define	_SGI_MMMX_csh_Ambiguous	"uxsgicsh:10:Ambiguous"
#define	_SGI_SMMX_csh_Ambiguous	"Ambiguous"
#define	_SGI_DMMX_csh_notermin	":11"
#define	_SGI_MMX_csh_notermin	"uxsgicsh:11"
#define	_SGI_MMMX_csh_notermin	"uxsgicsh:11:<< terminator not found"
#define	_SGI_SMMX_csh_notermin	"<< terminator not found"
#define	_SGI_DMMX_csh_lineov	":12"
#define	_SGI_MMX_csh_lineov	"uxsgicsh:12"
#define	_SGI_MMMX_csh_lineov	"uxsgicsh:12:Line overflow"
#define	_SGI_SMMX_csh_lineov	"Line overflow"
#define	_SGI_DMMX_csh_cmdnotfnd	":13"
#define	_SGI_MMX_csh_cmdnotfnd	"uxsgicsh:13"
#define	_SGI_MMMX_csh_cmdnotfnd	"uxsgicsh:13:Command not found"
#define	_SGI_SMMX_csh_cmdnotfnd	"Command not found"
#define	_SGI_DMMX_csh_expsyntax	":14"
#define	_SGI_MMX_csh_expsyntax	"uxsgicsh:14"
#define	_SGI_MMMX_csh_expsyntax	"uxsgicsh:14:Expression syntax"
#define	_SGI_SMMX_csh_expsyntax	"Expression syntax"
#define	_SGI_DMMX_csh_mfinqu	":15"
#define	_SGI_MMX_csh_mfinqu	"uxsgicsh:15"
#define	_SGI_MMMX_csh_mfinqu	"uxsgicsh:15:Malformed file inquiry"
#define	_SGI_SMMX_csh_mfinqu	"Malformed file inquiry"
#define	_SGI_DMMX_csh_missfilnam	":16"
#define	_SGI_MMX_csh_missfilnam	"uxsgicsh:16"
#define	_SGI_MMMX_csh_missfilnam	"uxsgicsh:16:Missing file name"
#define	_SGI_SMMX_csh_missfilnam	"Missing file name"
#define	_SGI_DMMX_csh_notfromtty	":17"
#define	_SGI_MMX_csh_notfromtty	"uxsgicsh:17"
#define	_SGI_MMMX_csh_notfromtty	"uxsgicsh:17:Can't from terminal"
#define	_SGI_SMMX_csh_notfromtty	"Can't from terminal"
#define	_SGI_DMMX_csh_xalias	":18"
#define	_SGI_MMX_csh_xalias	"uxsgicsh:18"
#define	_SGI_MMMX_csh_xalias	"uxsgicsh:18:Too dangerous to alias that"
#define	_SGI_SMMX_csh_xalias	"Too dangerous to alias that"
#define	_SGI_DMMX_csh_emptyIF	":19"
#define	_SGI_MMX_csh_emptyIF	"uxsgicsh:19"
#define	_SGI_MMMX_csh_emptyIF	"uxsgicsh:19:Empty if"
#define	_SGI_SMMX_csh_emptyIF	"Empty if"
#define	_SGI_DMMX_csh_ImprTHEN	":20"
#define	_SGI_MMX_csh_ImprTHEN	"uxsgicsh:20"
#define	_SGI_MMMX_csh_ImprTHEN	"uxsgicsh:20:Improper then"
#define	_SGI_SMMX_csh_ImprTHEN	"Improper then"
#define	_SGI_DMMX_csh_notinwf	":21"
#define	_SGI_MMX_csh_notinwf	"uxsgicsh:21"
#define	_SGI_MMMX_csh_notinwf	"uxsgicsh:21:Not in while/foreach"
#define	_SGI_SMMX_csh_notinwf	"Not in while/foreach"
#define	_SGI_DMMX_csh_invvar	":22"
#define	_SGI_MMX_csh_invvar	"uxsgicsh:22"
#define	_SGI_MMMX_csh_invvar	"uxsgicsh:22:Invalid variable"
#define	_SGI_SMMX_csh_invvar	"Invalid variable"
#define	_SGI_DMMX_csh_wordsned	":23"
#define	_SGI_MMX_csh_wordsned	"uxsgicsh:23"
#define	_SGI_MMMX_csh_wordsned	"uxsgicsh:23:Words not ()'ed"
#define	_SGI_SMMX_csh_wordsned	"Words not ()'ed"
#define	_SGI_DMMX_csh_nomatch	":24"
#define	_SGI_MMX_csh_nomatch	"uxsgicsh:24"
#define	_SGI_MMMX_csh_nomatch	"uxsgicsh:24:No match"
#define	_SGI_SMMX_csh_nomatch	"No match"
#define	_SGI_DMMX_csh_tenotfnd	":25"
#define	_SGI_MMX_csh_tenotfnd	"uxsgicsh:25"
#define	_SGI_MMMX_csh_tenotfnd	"uxsgicsh:25:then/endif not found"
#define	_SGI_SMMX_csh_tenotfnd	"then/endif not found"
#define	_SGI_DMMX_csh_endif	":26"
#define	_SGI_MMX_csh_endif	"uxsgicsh:26"
#define	_SGI_MMMX_csh_endif	"uxsgicsh:26:endif not found"
#define	_SGI_SMMX_csh_endif	"endif not found"
#define	_SGI_DMMX_csh_endsw	":27"
#define	_SGI_MMX_csh_endsw	"uxsgicsh:27"
#define	_SGI_MMMX_csh_endsw	"uxsgicsh:27:endsw not found"
#define	_SGI_SMMX_csh_endsw	"endsw not found"
#define	_SGI_DMMX_csh_end	":28"
#define	_SGI_MMX_csh_end	"uxsgicsh:28"
#define	_SGI_MMMX_csh_end	"uxsgicsh:28:end not found"
#define	_SGI_SMMX_csh_end	"end not found"
#define	_SGI_DMMX_csh_label	":29"
#define	_SGI_MMX_csh_label	"uxsgicsh:29"
#define	_SGI_MMMX_csh_label	"uxsgicsh:29:label not found"
#define	_SGI_SMMX_csh_label	"label not found"
#define	_SGI_DMMX_csh_imprmask	":30"
#define	_SGI_MMX_csh_imprmask	"uxsgicsh:30"
#define	_SGI_MMMX_csh_imprmask	"uxsgicsh:30:Improper mask"
#define	_SGI_SMMX_csh_imprmask	"Improper mask"
#define	_SGI_DMMX_csh_nolimit	":31"
#define	_SGI_MMX_csh_nolimit	"uxsgicsh:31"
#define	_SGI_MMMX_csh_nolimit	"uxsgicsh:31:No such limit"
#define	_SGI_SMMX_csh_nolimit	"No such limit"
#define	_SGI_DMMX_csh_illscale	":32"
#define	_SGI_MMX_csh_illscale	"uxsgicsh:32"
#define	_SGI_MMMX_csh_illscale	"uxsgicsh:32:Improper or unknown scale factor"
#define	_SGI_SMMX_csh_illscale	"Improper or unknown scale factor"
#define	_SGI_DMMX_csh_miss	":33"
#define	_SGI_MMX_csh_miss	"uxsgicsh:33"
#define	_SGI_MMMX_csh_miss	"uxsgicsh:33:Missing %s"
#define	_SGI_SMMX_csh_miss	"Missing %s"
#define	_SGI_DMMX_csh_nooutput	":34"
#define	_SGI_MMX_csh_nooutput	"uxsgicsh:34"
#define	_SGI_MMMX_csh_nooutput	"uxsgicsh:34:No output"
#define	_SGI_SMMX_csh_nooutput	"No output"
#define	_SGI_DMMX_csh_undefvar	":35"
#define	_SGI_MMX_csh_undefvar	"uxsgicsh:35"
#define	_SGI_MMMX_csh_undefvar	"uxsgicsh:35:Undefined variable"
#define	_SGI_SMMX_csh_undefvar	"Undefined variable"
#define	_SGI_DMMX_csh_badsig	":36"
#define	_SGI_MMX_csh_badsig	"uxsgicsh:36"
#define	_SGI_MMMX_csh_badsig	"uxsgicsh:36:Bad signal number"
#define	_SGI_SMMX_csh_badsig	"Bad signal number"
#define	_SGI_DMMX_csh_unknownsig	":37"
#define	_SGI_MMX_csh_unknownsig	"uxsgicsh:37"
#define	_SGI_MMMX_csh_unknownsig	"uxsgicsh:37:Unknown signal; kill -l lists signals"
#define	_SGI_SMMX_csh_unknownsig	"Unknown signal; kill -l lists signals"
#define	_SGI_DMMX_csh_jobproc	":38"
#define	_SGI_MMX_csh_jobproc	"uxsgicsh:38"
#define	_SGI_MMMX_csh_jobproc	"uxsgicsh:38:Arguments should be jobs or process id's"
#define	_SGI_SMMX_csh_jobproc	"Arguments should be jobs or process id's"
#define	_SGI_DMMX_csh_nocjob	":39"
#define	_SGI_MMX_csh_nocjob	"uxsgicsh:39"
#define	_SGI_MMMX_csh_nocjob	"uxsgicsh:39:No current job"
#define	_SGI_SMMX_csh_nocjob	"No current job"
#define	_SGI_DMMX_csh_nopjob	":40"
#define	_SGI_MMX_csh_nopjob	"uxsgicsh:40"
#define	_SGI_MMMX_csh_nopjob	"uxsgicsh:40:No previous job"
#define	_SGI_SMMX_csh_nopjob	"No previous job"
#define	_SGI_DMMX_csh_nojob	":41"
#define	_SGI_MMX_csh_nojob	"uxsgicsh:41"
#define	_SGI_MMMX_csh_nojob	"uxsgicsh:41:No such job"
#define	_SGI_SMMX_csh_nojob	"No such job"
#define	_SGI_DMMX_csh_jobmatch	":42"
#define	_SGI_MMX_csh_jobmatch	"uxsgicsh:42"
#define	_SGI_MMMX_csh_jobmatch	"uxsgicsh:42:No job matches pattern"
#define	_SGI_SMMX_csh_jobmatch	"No job matches pattern"
#define	_SGI_DMMX_csh_subserr	":43"
#define	_SGI_MMX_csh_subserr	"uxsgicsh:43"
#define	_SGI_MMMX_csh_subserr	"uxsgicsh:43:Subscript error"
#define	_SGI_SMMX_csh_subserr	"Subscript error"
#define	_SGI_DMMX_csh_subsout	":44"
#define	_SGI_MMX_csh_subsout	"uxsgicsh:44"
#define	_SGI_MMMX_csh_subsout	"uxsgicsh:44:Subscript out of range"
#define	_SGI_SMMX_csh_subsout	"Subscript out of range"
#define	_SGI_DMMX_csh_badnbr	":45"
#define	_SGI_MMX_csh_badnbr	"uxsgicsh:45"
#define	_SGI_MMMX_csh_badnbr	"uxsgicsh:45:Badly formed number"
#define	_SGI_SMMX_csh_badnbr	"Badly formed number"
#define	_SGI_DMMX_csh_nomorw	":46"
#define	_SGI_MMX_csh_nomorw	"uxsgicsh:46"
#define	_SGI_MMMX_csh_nomorw	"uxsgicsh:46:No more words"
#define	_SGI_SMMX_csh_nomorw	"No more words"
#define	_SGI_DMMX_csh_syntaxerr	":47"
#define	_SGI_MMX_csh_syntaxerr	"uxsgicsh:47"
#define	_SGI_MMMX_csh_syntaxerr	"uxsgicsh:47:Syntax error"
#define	_SGI_SMMX_csh_syntaxerr	"Syntax error"
#define	_SGI_DMMX_csh_mail	":48"
#define	_SGI_MMX_csh_mail	"uxsgicsh:48"
#define	_SGI_MMMX_csh_mail	"uxsgicsh:48:You have mail"
#define	_SGI_SMMX_csh_mail	"You have mail"
#define	_SGI_DMMX_csh_nmail	":49"
#define	_SGI_MMX_csh_nmail	"uxsgicsh:49"
#define	_SGI_MMMX_csh_nmail	"uxsgicsh:49:You have new mail"
#define	_SGI_SMMX_csh_nmail	"You have new mail"
#define	_SGI_DMMX_csh_mailin	":50"
#define	_SGI_MMX_csh_mailin	"uxsgicsh:50"
#define	_SGI_MMMX_csh_mailin	"uxsgicsh:50:Mail in %t"
#define	_SGI_SMMX_csh_mailin	"Mail in %t"
#define	_SGI_DMMX_csh_nmailin	":51"
#define	_SGI_MMX_csh_nmailin	"uxsgicsh:51"
#define	_SGI_MMMX_csh_nmailin	"uxsgicsh:51:New mail in %t"
#define	_SGI_SMMX_csh_nmailin	"New mail in %t"
#define	_SGI_DMMX_csh_cantexec	":52"
#define	_SGI_MMX_csh_cantexec	"uxsgicsh:52"
#define	_SGI_MMMX_csh_cantexec	"uxsgicsh:52:Cannot execute binary file"
#define	_SGI_SMMX_csh_cantexec	"Cannot execute binary file"
#define	_SGI_DMMX_csh_setuid	":53"
#define	_SGI_MMX_csh_setuid	"uxsgicsh:53"
#define	_SGI_MMMX_csh_setuid	"uxsgicsh:53:%s: Setuid program execute permission denied"
#define	_SGI_SMMX_csh_setuid	"%s: Setuid program execute permission denied"
#define	_SGI_DMMX_csh_badcomp	":54"
#define	_SGI_MMX_csh_badcomp	"uxsgicsh:54"
#define	_SGI_MMMX_csh_badcomp	"uxsgicsh:54:%s: Program not supported by architecture"
#define	_SGI_SMMX_csh_badcomp	"%s: Program not supported by architecture"
#define	_SGI_DMMX_csh_illchar	":55"
#define	_SGI_MMX_csh_illchar	"uxsgicsh:55"
#define	_SGI_MMMX_csh_illchar	"uxsgicsh:55:Illegal character in '%s' !"
#define	_SGI_SMMX_csh_illchar	"Illegal character in '%s' !"
#define	_SGI_DMMX_csh_fntrunc	":56"
#define	_SGI_MMX_csh_fntrunc	"uxsgicsh:56"
#define	_SGI_MMMX_csh_fntrunc	"uxsgicsh:56:Filename '%s' truncated !"
#define	_SGI_SMMX_csh_fntrunc	"Filename '%s' truncated !"
#define	_SGI_DMMX_csh_illenvvar	":57"
#define	_SGI_MMX_csh_illenvvar	"uxsgicsh:57"
#define	_SGI_MMMX_csh_illenvvar	"uxsgicsh:57:Environment variable '%s' ignored"
#define	_SGI_SMMX_csh_illenvvar	"Environment variable '%s' ignored"
#define	_SGI_DMMX_csh_ihppasswd	":58"
#define	_SGI_MMX_csh_ihppasswd	"uxsgicsh:58"
#define	_SGI_MMMX_csh_ihppasswd	"uxsgicsh:58:Illegal character in home path of passwd entry"
#define	_SGI_SMMX_csh_ihppasswd	"Illegal character in home path of passwd entry"
#define	_SGI_DMMX_csh_unmatched	":59"
#define	_SGI_MMX_csh_unmatched	"uxsgicsh:59"
#define	_SGI_MMMX_csh_unmatched	"uxsgicsh:59:Unmatched %s"
#define	_SGI_SMMX_csh_unmatched	"Unmatched %s"
#define	_SGI_DMMX_csh_word2long	":60"
#define	_SGI_MMX_csh_word2long	"uxsgicsh:60"
#define	_SGI_MMMX_csh_word2long	"uxsgicsh:60:Word too long"
#define	_SGI_SMMX_csh_word2long	"Word too long"
#define	_SGI_DMMX_csh_line2long	":61"
#define	_SGI_MMX_csh_line2long	"uxsgicsh:61"
#define	_SGI_MMMX_csh_line2long	"uxsgicsh:61:Line too long"
#define	_SGI_SMMX_csh_line2long	"Line too long"
#define	_SGI_DMMX_csh_no0file	":62"
#define	_SGI_MMX_csh_no0file	"uxsgicsh:62"
#define	_SGI_MMMX_csh_no0file	"uxsgicsh:62:No file for $0"
#define	_SGI_SMMX_csh_no0file	"No file for $0"
#define	_SGI_DMMX_csh_varsyntax	":63"
#define	_SGI_MMX_csh_varsyntax	"uxsgicsh:63"
#define	_SGI_MMMX_csh_varsyntax	"uxsgicsh:63:Variable syntax"
#define	_SGI_SMMX_csh_varsyntax	"Variable syntax"
#define	_SGI_DMMX_csh_badmodin	":64"
#define	_SGI_MMX_csh_badmodin	"uxsgicsh:64"
#define	_SGI_MMMX_csh_badmodin	"uxsgicsh:64:Bad : mod in $"
#define	_SGI_SMMX_csh_badmodin	"Bad : mod in $"
#define	_SGI_DMMX_csh_divby0	":65"
#define	_SGI_MMX_csh_divby0	"uxsgicsh:65"
#define	_SGI_MMMX_csh_divby0	"uxsgicsh:65:Divide by 0"
#define	_SGI_SMMX_csh_divby0	"Divide by 0"
#define	_SGI_DMMX_csh_modby0	":66"
#define	_SGI_MMX_csh_modby0	"uxsgicsh:66"
#define	_SGI_MMMX_csh_modby0	"uxsgicsh:66:Mod by 0"
#define	_SGI_SMMX_csh_modby0	"Mod by 0"
#define	_SGI_DMMX_csh_badscal	":67"
#define	_SGI_MMX_csh_badscal	"uxsgicsh:67"
#define	_SGI_MMMX_csh_badscal	"uxsgicsh:67:Bad scaling; did you mean ``%st''?"
#define	_SGI_SMMX_csh_badscal	"Bad scaling; did you mean ``%st''?"
#define	_SGI_DMMX_csh_cantsusp	":68"
#define	_SGI_MMX_csh_cantsusp	"uxsgicsh:68"
#define	_SGI_MMMX_csh_cantsusp	"uxsgicsh:68:Can't suspend a login shell (yet)"
#define	_SGI_SMMX_csh_cantsusp	"Can't suspend a login shell (yet)"
#define	_SGI_DMMX_csh_unkuser	":69"
#define	_SGI_MMX_csh_unkuser	"uxsgicsh:69"
#define	_SGI_MMMX_csh_unkuser	"uxsgicsh:69:%s: Unknown user"
#define	_SGI_SMMX_csh_unkuser	"%s: Unknown user"
#define	_SGI_DMMX_csh_toomleft	":70"
#define	_SGI_MMX_csh_toomleft	"uxsgicsh:70"
#define	_SGI_MMMX_csh_toomleft	"uxsgicsh:70:Too many words from ``"
#define	_SGI_SMMX_csh_toomleft	"Too many words from ``"
#define	_SGI_DMMX_csh_arg2long	":71"
#define	_SGI_MMX_csh_arg2long	"uxsgicsh:71"
#define	_SGI_MMMX_csh_arg2long	"uxsgicsh:71:Arguments too long"
#define	_SGI_SMMX_csh_arg2long	"Arguments too long"
#define	_SGI_DMMX_csh_path2long	":72"
#define	_SGI_MMX_csh_path2long	"uxsgicsh:72"
#define	_SGI_MMMX_csh_path2long	"uxsgicsh:72:Pathname too long"
#define	_SGI_SMMX_csh_path2long	"Pathname too long"
#define	_SGI_DMMX_csh_alloop	":73"
#define	_SGI_MMX_csh_alloop	"uxsgicsh:73"
#define	_SGI_MMMX_csh_alloop	"uxsgicsh:73:Alias loop"
#define	_SGI_SMMX_csh_alloop	"Alias loop"
#define	_SGI_DMMX_csh_toomany	":74"
#define	_SGI_MMX_csh_toomany	"uxsgicsh:74"
#define	_SGI_MMMX_csh_toomany	"uxsgicsh:74:Too many %s's"
#define	_SGI_SMMX_csh_toomany	"Too many %s's"
#define	_SGI_DMMX_csh_usage	":75"
#define	_SGI_MMX_csh_usage	"uxsgicsh:75"
#define	_SGI_MMMX_csh_usage	"uxsgicsh:75:Usage: %s"
#define	_SGI_SMMX_csh_usage	"Usage: %s"
#define	_SGI_DMMX_csh_fkfail	":76"
#define	_SGI_MMX_csh_fkfail	"uxsgicsh:76"
#define	_SGI_MMMX_csh_fkfail	"uxsgicsh:76:Fork failed"
#define	_SGI_SMMX_csh_fkfail	"Fork failed"
#define	_SGI_DMMX_csh_nojc1	":77"
#define	_SGI_MMX_csh_nojc1	"uxsgicsh:77"
#define	_SGI_MMMX_csh_nojc1	"uxsgicsh:77:No job control in this shell"
#define	_SGI_SMMX_csh_nojc1	"No job control in this shell"
#define	_SGI_DMMX_csh_nojc2	":78"
#define	_SGI_MMX_csh_nojc2	"uxsgicsh:78"
#define	_SGI_MMMX_csh_nojc2	"uxsgicsh:78:No job control in subshell"
#define	_SGI_SMMX_csh_nojc2	"No job control in subshell"
#define	_SGI_DMMX_csh_stjobs	":79"
#define	_SGI_MMX_csh_stjobs	"uxsgicsh:79"
#define	_SGI_MMMX_csh_stjobs	"uxsgicsh:79:\nThere are stopped jobs"
#define	_SGI_SMMX_csh_stjobs	"\nThere are stopped jobs"
#define	_SGI_DMMX_csh_nopipe	":80"
#define	_SGI_MMX_csh_nopipe	"uxsgicsh:80"
#define	_SGI_MMMX_csh_nopipe	"uxsgicsh:80:Can't make pipe"
#define	_SGI_SMMX_csh_nopipe	"Can't make pipe"
#define	_SGI_DMMX_csh_fexists	":81"
#define	_SGI_MMX_csh_fexists	"uxsgicsh:81"
#define	_SGI_MMMX_csh_fexists	"uxsgicsh:81:%s: File exists"
#define	_SGI_SMMX_csh_fexists	"%s: File exists"
#define	_SGI_DMMX_csh_expfull	":82"
#define	_SGI_MMX_csh_expfull	"uxsgicsh:82"
#define	_SGI_MMMX_csh_expfull	"uxsgicsh:82:Expansion buffer overflow"
#define	_SGI_SMMX_csh_expfull	"Expansion buffer overflow"
#define	_SGI_DMMX_csh_badbang	":83"
#define	_SGI_MMX_csh_badbang	"uxsgicsh:83"
#define	_SGI_MMMX_csh_badbang	"uxsgicsh:83:Bad ! form"
#define	_SGI_SMMX_csh_badbang	"Bad ! form"
#define	_SGI_DMMX_csh_noprevs	":84"
#define	_SGI_MMX_csh_noprevs	"uxsgicsh:84"
#define	_SGI_MMMX_csh_noprevs	"uxsgicsh:84:No prev sub"
#define	_SGI_SMMX_csh_noprevs	"No prev sub"
#define	_SGI_DMMX_csh_badsub	":85"
#define	_SGI_MMX_csh_badsub	"uxsgicsh:85"
#define	_SGI_MMMX_csh_badsub	"uxsgicsh:85:Bad substitute"
#define	_SGI_SMMX_csh_badsub	"Bad substitute"
#define	_SGI_DMMX_csh_noplhs	":86"
#define	_SGI_MMX_csh_noplhs	"uxsgicsh:86"
#define	_SGI_MMMX_csh_noplhs	"uxsgicsh:86:No prev lhs"
#define	_SGI_SMMX_csh_noplhs	"No prev lhs"
#define	_SGI_DMMX_csh_rhs2long	":87"
#define	_SGI_MMX_csh_rhs2long	"uxsgicsh:87"
#define	_SGI_MMMX_csh_rhs2long	"uxsgicsh:87:Rhs too long"
#define	_SGI_SMMX_csh_rhs2long	"Rhs too long"
#define	_SGI_DMMX_csh_modfailed	":88"
#define	_SGI_MMX_csh_modfailed	"uxsgicsh:88"
#define	_SGI_MMMX_csh_modfailed	"uxsgicsh:88:Modifier failed"
#define	_SGI_SMMX_csh_modfailed	"Modifier failed"
#define	_SGI_DMMX_csh_sbufov	":89"
#define	_SGI_MMX_csh_sbufov	"uxsgicsh:89"
#define	_SGI_MMMX_csh_sbufov	"uxsgicsh:89:Substitution buffer overflow"
#define	_SGI_SMMX_csh_sbufov	"Substitution buffer overflow"
#define	_SGI_DMMX_csh_badbangsel	":90"
#define	_SGI_MMX_csh_badbangsel	"uxsgicsh:90"
#define	_SGI_MMMX_csh_badbangsel	"uxsgicsh:90:Bad ! arg selector"
#define	_SGI_SMMX_csh_badbangsel	"Bad ! arg selector"
#define	_SGI_DMMX_csh_nopsrch	":91"
#define	_SGI_MMX_csh_nopsrch	"uxsgicsh:91"
#define	_SGI_MMMX_csh_nopsrch	"uxsgicsh:91:No prev search"
#define	_SGI_SMMX_csh_nopsrch	"No prev search"
#define	_SGI_DMMX_csh_evtnotfnd	":92"
#define	_SGI_MMX_csh_evtnotfnd	"uxsgicsh:92"
#define	_SGI_MMMX_csh_evtnotfnd	"uxsgicsh:92:: Event not found"
#define	_SGI_SMMX_csh_evtnotfnd	": Event not found"
#define	_SGI_DMMX_csh_illlocale	":93"
#define	_SGI_MMX_csh_illlocale	"uxsgicsh:93"
#define	_SGI_MMMX_csh_illlocale	"uxsgicsh:93:%s: Invalid locale - csh locale unchanged"
#define	_SGI_SMMX_csh_illlocale	"%s: Invalid locale - csh locale unchanged"
#define	_SGI_DMMX_csh_notlogin	":94"
#define	_SGI_MMX_csh_notlogin	"uxsgicsh:94"
#define	_SGI_MMMX_csh_notlogin	"uxsgicsh:94:Not login shell"
#define	_SGI_SMMX_csh_notlogin	"Not login shell"
#define	_SGI_DMMX_csh_badflag	":95"
#define	_SGI_MMX_csh_badflag	"uxsgicsh:95"
#define	_SGI_MMMX_csh_badflag	"uxsgicsh:95:Unknown flag: -%s\n"
#define	_SGI_SMMX_csh_badflag	"Unknown flag: -%s\n"
#define	_SGI_DMMX_csh_nomem	":96"
#define	_SGI_MMX_csh_nomem	"uxsgicsh:96"
#define	_SGI_MMMX_csh_nomem	"uxsgicsh:96:No memory"
#define	_SGI_SMMX_csh_nomem	"No memory"
#define	_SGI_DMMX_csh_badpllb	":97"
#define	_SGI_MMX_csh_badpllb	"uxsgicsh:97"
#define	_SGI_MMMX_csh_badpllb	"uxsgicsh:97:Badly placed ("
#define	_SGI_SMMX_csh_badpllb	"Badly placed ("
#define	_SGI_DMMX_csh_missnamred	":98"
#define	_SGI_MMX_csh_missnamred	"uxsgicsh:98"
#define	_SGI_MMMX_csh_missnamred	"uxsgicsh:98:Missing name for redirect"
#define	_SGI_SMMX_csh_missnamred	"Missing name for redirect"
#define	_SGI_DMMX_csh_ambored	":99"
#define	_SGI_MMX_csh_ambored	"uxsgicsh:99"
#define	_SGI_MMMX_csh_ambored	"uxsgicsh:99:Ambiguous output redirect"
#define	_SGI_SMMX_csh_ambored	"Ambiguous output redirect"
#define	_SGI_DMMX_csh_ambired	":100"
#define	_SGI_MMX_csh_ambired	"uxsgicsh:100"
#define	_SGI_MMMX_csh_ambired	"uxsgicsh:100:Ambiguous input redirect"
#define	_SGI_SMMX_csh_ambired	"Ambiguous input redirect"
#define	_SGI_DMMX_csh_cantred	":101"
#define	_SGI_MMX_csh_cantred	"uxsgicsh:101"
#define	_SGI_MMMX_csh_cantred	"uxsgicsh:101:Can't << within ()'s"
#define	_SGI_SMMX_csh_cantred	"Can't << within ()'s"
#define	_SGI_DMMX_csh_badplbb	":102"
#define	_SGI_MMX_csh_badplbb	"uxsgicsh:102"
#define	_SGI_MMMX_csh_badplbb	"uxsgicsh:102:Badly placed ()'s"
#define	_SGI_SMMX_csh_badplbb	"Badly placed ()'s"
#define	_SGI_DMMX_csh_inv0cmd	":103"
#define	_SGI_MMX_csh_inv0cmd	"uxsgicsh:103"
#define	_SGI_MMMX_csh_inv0cmd	"uxsgicsh:103:Invalid null command"
#define	_SGI_SMMX_csh_inv0cmd	"Invalid null command"
#define	_SGI_DMMX_csh_badbangmod	":104"
#define	_SGI_MMX_csh_badbangmod	"uxsgicsh:104"
#define	_SGI_MMMX_csh_badbangmod	"uxsgicsh:104:%s: Bad ! modifier"
#define	_SGI_SMMX_csh_badbangmod	"%s: Bad ! modifier"
#define	_SGI_DMMX_csh_2manynames	":105"
#define	_SGI_MMX_csh_2manynames	"uxsgicsh:105"
#define	_SGI_MMMX_csh_2manynames	"uxsgicsh:105:\nYikes! Too many names in passwd!"
#define	_SGI_SMMX_csh_2manynames	"\nYikes! Too many names in passwd!"
#define	_SGI_DMMX_csh_2manyfiles	":106"
#define	_SGI_MMX_csh_2manyfiles	"uxsgicsh:106"
#define	_SGI_MMMX_csh_2manyfiles	"uxsgicsh:106:\nYikes! Too many files!"
#define	_SGI_SMMX_csh_2manyfiles	"\nYikes! Too many files!"
#define	_SGI_DMMX_csh_S_HUP	":107"
#define	_SGI_MMX_csh_S_HUP	"uxsgicsh:107"
#define	_SGI_MMMX_csh_S_HUP	"uxsgicsh:107:Hangup"
#define	_SGI_SMMX_csh_S_HUP	"Hangup"
#define	_SGI_DMMX_csh_S_INT	":108"
#define	_SGI_MMX_csh_S_INT	"uxsgicsh:108"
#define	_SGI_MMMX_csh_S_INT	"uxsgicsh:108:Interrupt"
#define	_SGI_SMMX_csh_S_INT	"Interrupt"
#define	_SGI_DMMX_csh_S_QUIT	":109"
#define	_SGI_MMX_csh_S_QUIT	"uxsgicsh:109"
#define	_SGI_MMMX_csh_S_QUIT	"uxsgicsh:109:Quit"
#define	_SGI_SMMX_csh_S_QUIT	"Quit"
#define	_SGI_DMMX_csh_S_ILL	":110"
#define	_SGI_MMX_csh_S_ILL	"uxsgicsh:110"
#define	_SGI_MMMX_csh_S_ILL	"uxsgicsh:110:Illegal instruction"
#define	_SGI_SMMX_csh_S_ILL	"Illegal instruction"
#define	_SGI_DMMX_csh_S_TRAP	":111"
#define	_SGI_MMX_csh_S_TRAP	"uxsgicsh:111"
#define	_SGI_MMMX_csh_S_TRAP	"uxsgicsh:111:Trace/BPT trap"
#define	_SGI_SMMX_csh_S_TRAP	"Trace/BPT trap"
#define	_SGI_DMMX_csh_S_ABRT	":112"
#define	_SGI_MMX_csh_S_ABRT	"uxsgicsh:112"
#define	_SGI_MMMX_csh_S_ABRT	"uxsgicsh:112:Abort"
#define	_SGI_SMMX_csh_S_ABRT	"Abort"
#define	_SGI_DMMX_csh_S_EMT	":113"
#define	_SGI_MMX_csh_S_EMT	"uxsgicsh:113"
#define	_SGI_MMMX_csh_S_EMT	"uxsgicsh:113:Emulator trap"
#define	_SGI_SMMX_csh_S_EMT	"Emulator trap"
#define	_SGI_DMMX_csh_S_FPE	":114"
#define	_SGI_MMX_csh_S_FPE	"uxsgicsh:114"
#define	_SGI_MMMX_csh_S_FPE	"uxsgicsh:114:Arithmetic exception"
#define	_SGI_SMMX_csh_S_FPE	"Arithmetic exception"
#define	_SGI_DMMX_csh_S_KILL	":115"
#define	_SGI_MMX_csh_S_KILL	"uxsgicsh:115"
#define	_SGI_MMMX_csh_S_KILL	"uxsgicsh:115:Killed"
#define	_SGI_SMMX_csh_S_KILL	"Killed"
#define	_SGI_DMMX_csh_S_BUS	":116"
#define	_SGI_MMX_csh_S_BUS	"uxsgicsh:116"
#define	_SGI_MMMX_csh_S_BUS	"uxsgicsh:116:Bus error"
#define	_SGI_SMMX_csh_S_BUS	"Bus error"
#define	_SGI_DMMX_csh_S_SEGV	":117"
#define	_SGI_MMX_csh_S_SEGV	"uxsgicsh:117"
#define	_SGI_MMMX_csh_S_SEGV	"uxsgicsh:117:Segmentation fault"
#define	_SGI_SMMX_csh_S_SEGV	"Segmentation fault"
#define	_SGI_DMMX_csh_S_SYS	":118"
#define	_SGI_MMX_csh_S_SYS	"uxsgicsh:118"
#define	_SGI_MMMX_csh_S_SYS	"uxsgicsh:118:Bad system call"
#define	_SGI_SMMX_csh_S_SYS	"Bad system call"
#define	_SGI_DMMX_csh_S_PIPE	":119"
#define	_SGI_MMX_csh_S_PIPE	"uxsgicsh:119"
#define	_SGI_MMMX_csh_S_PIPE	"uxsgicsh:119:Broken pipe"
#define	_SGI_SMMX_csh_S_PIPE	"Broken pipe"
#define	_SGI_DMMX_csh_S_ALRM	":120"
#define	_SGI_MMX_csh_S_ALRM	"uxsgicsh:120"
#define	_SGI_MMMX_csh_S_ALRM	"uxsgicsh:120:Alarm clock"
#define	_SGI_SMMX_csh_S_ALRM	"Alarm clock"
#define	_SGI_DMMX_csh_S_TERM	":121"
#define	_SGI_MMX_csh_S_TERM	"uxsgicsh:121"
#define	_SGI_MMMX_csh_S_TERM	"uxsgicsh:121:Terminated"
#define	_SGI_SMMX_csh_S_TERM	"Terminated"
#define	_SGI_DMMX_csh_S_USR1	":122"
#define	_SGI_MMX_csh_S_USR1	"uxsgicsh:122"
#define	_SGI_MMMX_csh_S_USR1	"uxsgicsh:122:User defined signal 1"
#define	_SGI_SMMX_csh_S_USR1	"User defined signal 1"
#define	_SGI_DMMX_csh_S_USR2	":123"
#define	_SGI_MMX_csh_S_USR2	"uxsgicsh:123"
#define	_SGI_MMMX_csh_S_USR2	"uxsgicsh:123:User defined signal 2"
#define	_SGI_SMMX_csh_S_USR2	"User defined signal 2"
#define	_SGI_DMMX_csh_S_CHLD	":124"
#define	_SGI_MMX_csh_S_CHLD	"uxsgicsh:124"
#define	_SGI_MMMX_csh_S_CHLD	"uxsgicsh:124:Child exited"
#define	_SGI_SMMX_csh_S_CHLD	"Child exited"
#define	_SGI_DMMX_csh_S_PWR	":125"
#define	_SGI_MMX_csh_S_PWR	"uxsgicsh:125"
#define	_SGI_MMMX_csh_S_PWR	"uxsgicsh:125:Power failed"
#define	_SGI_SMMX_csh_S_PWR	"Power failed"
#define	_SGI_DMMX_csh_S_WINCH	":126"
#define	_SGI_MMX_csh_S_WINCH	"uxsgicsh:126"
#define	_SGI_MMMX_csh_S_WINCH	"uxsgicsh:126:Window size changed"
#define	_SGI_SMMX_csh_S_WINCH	"Window size changed"
#define	_SGI_DMMX_csh_S_URG	":127"
#define	_SGI_MMX_csh_S_URG	"uxsgicsh:127"
#define	_SGI_MMMX_csh_S_URG	"uxsgicsh:127:Urgent I/O condition"
#define	_SGI_SMMX_csh_S_URG	"Urgent I/O condition"
#define	_SGI_DMMX_csh_S_POLL	":128"
#define	_SGI_MMX_csh_S_POLL	"uxsgicsh:128"
#define	_SGI_MMMX_csh_S_POLL	"uxsgicsh:128:Pollable event occurred"
#define	_SGI_SMMX_csh_S_POLL	"Pollable event occurred"
#define	_SGI_DMMX_csh_S_STOP	":129"
#define	_SGI_MMX_csh_S_STOP	"uxsgicsh:129"
#define	_SGI_MMMX_csh_S_STOP	"uxsgicsh:129:Stopped (signal)"
#define	_SGI_SMMX_csh_S_STOP	"Stopped (signal)"
#define	_SGI_DMMX_csh_S_TSTP	":130"
#define	_SGI_MMX_csh_S_TSTP	"uxsgicsh:130"
#define	_SGI_MMMX_csh_S_TSTP	"uxsgicsh:130:Stopped"
#define	_SGI_SMMX_csh_S_TSTP	"Stopped"
#define	_SGI_DMMX_csh_S_CONT	":131"
#define	_SGI_MMX_csh_S_CONT	"uxsgicsh:131"
#define	_SGI_MMMX_csh_S_CONT	"uxsgicsh:131:Continued"
#define	_SGI_SMMX_csh_S_CONT	"Continued"
#define	_SGI_DMMX_csh_S_TTIN	":132"
#define	_SGI_MMX_csh_S_TTIN	"uxsgicsh:132"
#define	_SGI_MMMX_csh_S_TTIN	"uxsgicsh:132:Stopped (tty input)"
#define	_SGI_SMMX_csh_S_TTIN	"Stopped (tty input)"
#define	_SGI_DMMX_csh_S_TTOU	":133"
#define	_SGI_MMX_csh_S_TTOU	"uxsgicsh:133"
#define	_SGI_MMMX_csh_S_TTOU	"uxsgicsh:133:Stopped (tty output)"
#define	_SGI_SMMX_csh_S_TTOU	"Stopped (tty output)"
#define	_SGI_DMMX_csh_S_VTALRM	":134"
#define	_SGI_MMX_csh_S_VTALRM	"uxsgicsh:134"
#define	_SGI_MMMX_csh_S_VTALRM	"uxsgicsh:134:Virtual timer expired"
#define	_SGI_SMMX_csh_S_VTALRM	"Virtual timer expired"
#define	_SGI_DMMX_csh_S_PROF	":135"
#define	_SGI_MMX_csh_S_PROF	"uxsgicsh:135"
#define	_SGI_MMMX_csh_S_PROF	"uxsgicsh:135:Profiling timer expired"
#define	_SGI_SMMX_csh_S_PROF	"Profiling timer expired"
#define	_SGI_DMMX_csh_S_XCPU	":136"
#define	_SGI_MMX_csh_S_XCPU	"uxsgicsh:136"
#define	_SGI_MMMX_csh_S_XCPU	"uxsgicsh:136:Cputime limit exceeded"
#define	_SGI_SMMX_csh_S_XCPU	"Cputime limit exceeded"
#define	_SGI_DMMX_csh_S_XFSZ	":137"
#define	_SGI_MMX_csh_S_XFSZ	"uxsgicsh:137"
#define	_SGI_MMMX_csh_S_XFSZ	"uxsgicsh:137:Filesize limit exceeded"
#define	_SGI_SMMX_csh_S_XFSZ	"Filesize limit exceeded"
#define	_SGI_DMMX_csh_S_32	":138"
#define	_SGI_MMX_csh_S_32	"uxsgicsh:138"
#define	_SGI_MMMX_csh_S_32	"uxsgicsh:138:Signal 32"
#define	_SGI_SMMX_csh_S_32	"Signal 32"
#define	_SGI_DMMX_csh_S_DEFAULTSTR	":139"
#define	_SGI_MMX_csh_S_DEFAULTSTR	"uxsgicsh:139"
#define	_SGI_MMMX_csh_S_DEFAULTSTR	"uxsgicsh:139:Signal %-14d"
#define	_SGI_SMMX_csh_S_DEFAULTSTR	"Signal %-14d"
#define	_SGI_DMMX_csh_core	":140"
#define	_SGI_MMX_csh_core	"uxsgicsh:140"
#define	_SGI_MMMX_csh_core	"uxsgicsh:140: (core dumped)"
#define	_SGI_SMMX_csh_core	" (core dumped)"
#define	_SGI_DMMX_csh_done	":141"
#define	_SGI_MMX_csh_done	"uxsgicsh:141"
#define	_SGI_MMMX_csh_done	"uxsgicsh:141:Done"
#define	_SGI_SMMX_csh_done	"Done"
#define	_SGI_DMMX_csh_run	":142"
#define	_SGI_MMX_csh_run	"uxsgicsh:142"
#define	_SGI_MMMX_csh_run	"uxsgicsh:142:Running "
#define	_SGI_SMMX_csh_run	"Running "
#define	_SGI_DMMX_csh_exit	":143"
#define	_SGI_MMX_csh_exit	"uxsgicsh:143"
#define	_SGI_MMMX_csh_exit	"uxsgicsh:143:Exit %-16d"
#define	_SGI_SMMX_csh_exit	"Exit %-16d"
#define	_SGI_DMMX_csh_uselogout	":144"
#define	_SGI_MMX_csh_uselogout	"uxsgicsh:144"
#define	_SGI_MMMX_csh_uselogout	"uxsgicsh:144:Use \"logout\" to logout"
#define	_SGI_SMMX_csh_uselogout	"Use \"logout\" to logout"
#define	_SGI_DMMX_csh_useexit	":145"
#define	_SGI_MMX_csh_useexit	"uxsgicsh:145"
#define	_SGI_MMMX_csh_useexit	"uxsgicsh:145:Use \"exit\" to leave csh"
#define	_SGI_SMMX_csh_useexit	"Use \"exit\" to leave csh"
#define	_SGI_DMMX_csh_alrdstp	":146"
#define	_SGI_MMX_csh_alrdstp	"uxsgicsh:146"
#define	_SGI_MMMX_csh_alrdstp	"uxsgicsh:146:%s: Already stopped"
#define	_SGI_SMMX_csh_alrdstp	"%s: Already stopped"
#define	_SGI_DMMX_csh_ridpat	":147"
#define	_SGI_MMX_csh_ridpat	"uxsgicsh:147"
#define	_SGI_MMMX_csh_ridpat	"uxsgicsh:147:Ridiculously long path truncated"
#define	_SGI_SMMX_csh_ridpat	"Ridiculously long path truncated"
#define	_SGI_DMMX_csh_badcurdir	":148"
#define	_SGI_MMX_csh_badcurdir	"uxsgicsh:148"
#define	_SGI_MMMX_csh_badcurdir	"uxsgicsh:148:Cannot determine current working directory"
#define	_SGI_SMMX_csh_badcurdir	"Cannot determine current working directory"
