#define	_SGI_DMMX_e_access	":1"
#define	_SGI_MMX_e_access	"uxsgish:1"
#define	_SGI_MMMX_e_access	"uxsgish:1:permission denied"
#define	_SGI_SMMX_e_access	"permission denied"
#define	_SGI_DMMX_e_alias	":2"
#define	_SGI_MMX_e_alias	"uxsgish:2"
#define	_SGI_MMMX_e_alias	"uxsgish:2: alias not found"
#define	_SGI_SMMX_e_alias	" alias not found"
#define	_SGI_DMMX_e_aliasspc	":3"
#define	_SGI_MMX_e_aliasspc	"uxsgish:3"
#define	_SGI_MMMX_e_aliasspc	"uxsgish:3:alias "
#define	_SGI_SMMX_e_aliasspc	"alias "
#define	_SGI_DMMX_e_aliname	":4"
#define	_SGI_MMX_e_aliname	"uxsgish:4"
#define	_SGI_MMMX_e_aliname	"uxsgish:4:invalid alias name"
#define	_SGI_SMMX_e_aliname	"invalid alias name"
#define	_SGI_DMMX_e_ambiguous	":5"
#define	_SGI_MMX_e_ambiguous	"uxsgish:5"
#define	_SGI_MMMX_e_ambiguous	"uxsgish:5:Ambiguous"
#define	_SGI_SMMX_e_ambiguous	"Ambiguous"
#define	_SGI_DMMX_e_argexp	":6"
#define	_SGI_MMX_e_argexp	"uxsgish:6"
#define	_SGI_MMMX_e_argexp	"uxsgish:6:argument expected"
#define	_SGI_SMMX_e_argexp	"argument expected"
#define	_SGI_DMMX_e_arglist	":7"
#define	_SGI_MMX_e_arglist	"uxsgish:7"
#define	_SGI_MMMX_e_arglist	"uxsgish:7:arg list too long"
#define	_SGI_SMMX_e_arglist	"arg list too long"
#define	_SGI_DMMX_e_atline	":8"
#define	_SGI_MMX_e_atline	"uxsgish:8"
#define	_SGI_MMMX_e_atline	"uxsgish:8: at line "
#define	_SGI_SMMX_e_atline	" at line "
#define	_SGI_DMMX_e_badcolon	":9"
#define	_SGI_MMX_e_badcolon	"uxsgish:9"
#define	_SGI_MMMX_e_badcolon	"uxsgish:9:invalid use of :"
#define	_SGI_SMMX_e_badcolon	"invalid use of :"
#define	_SGI_DMMX_e_badinlib	":10"
#define	_SGI_MMX_e_badinlib	"uxsgish:10"
#define	_SGI_MMMX_e_badinlib	"uxsgish:10:Cannot inlib"
#define	_SGI_SMMX_e_badinlib	"Cannot inlib"
#define	_SGI_DMMX_e_badmagic	":11"
#define	_SGI_MMX_e_badmagic	"uxsgish:11"
#define	_SGI_MMMX_e_badmagic	"uxsgish:11:Program not supported by architecture"
#define	_SGI_SMMX_e_badmagic	"Program not supported by architecture"
#define	_SGI_DMMX_e_badtrap	":12"
#define	_SGI_MMX_e_badtrap	"uxsgish:12"
#define	_SGI_MMMX_e_badtrap	"uxsgish:12:bad trap"
#define	_SGI_SMMX_e_badtrap	"bad trap"
#define	_SGI_DMMX_e_badver	":13"
#define	_SGI_MMX_e_badver	"uxsgish:13"
#define	_SGI_MMMX_e_badver	"uxsgish:13:Unrecognized version"
#define	_SGI_SMMX_e_badver	"Unrecognized version"
#define	_SGI_DMMX_e_bltfn	":14"
#define	_SGI_MMX_e_bltfn	"uxsgish:14"
#define	_SGI_MMMX_e_bltfn	"uxsgish:14:function "
#define	_SGI_SMMX_e_bltfn	"function "
#define	_SGI_DMMX_e_bracket	":15"
#define	_SGI_MMX_e_bracket	"uxsgish:15"
#define	_SGI_MMMX_e_bracket	"uxsgish:15:] missing"
#define	_SGI_SMMX_e_bracket	"] missing"
#define	_SGI_DMMX_e_cmdunknown	":16"
#define	_SGI_MMX_e_cmdunknown	"uxsgish:16"
#define	_SGI_MMMX_e_cmdunknown	"uxsgish:16:<command unknown>"
#define	_SGI_SMMX_e_cmdunknown	"<command unknown>"
#define	_SGI_DMMX_e_combo	":17"
#define	_SGI_MMX_e_combo	"uxsgish:17"
#define	_SGI_MMMX_e_combo	"uxsgish:17:bad option combination"
#define	_SGI_SMMX_e_combo	"bad option combination"
#define	_SGI_DMMX_e_command	":18"
#define	_SGI_MMX_e_command	"uxsgish:18"
#define	_SGI_MMMX_e_command	"uxsgish:18:command"
#define	_SGI_SMMX_e_command	"command"
#define	_SGI_DMMX_e_coredump	":19"
#define	_SGI_MMX_e_coredump	"uxsgish:19"
#define	_SGI_MMMX_e_coredump	"uxsgish:19:(coredump)"
#define	_SGI_SMMX_e_coredump	"(coredump)"
#define	_SGI_DMMX_e_create	":20"
#define	_SGI_MMX_e_create	"uxsgish:20"
#define	_SGI_MMMX_e_create	"uxsgish:20:cannot create"
#define	_SGI_SMMX_e_create	"cannot create"
#define	_SGI_DMMX_e_direct	":21"
#define	_SGI_MMX_e_direct	"uxsgish:21"
#define	_SGI_MMMX_e_direct	"uxsgish:21:bad directory"
#define	_SGI_SMMX_e_direct	"bad directory"
#define	_SGI_DMMX_e_divzero	":22"
#define	_SGI_MMX_e_divzero	"uxsgish:22"
#define	_SGI_MMMX_e_divzero	"uxsgish:22:divide by zero"
#define	_SGI_SMMX_e_divzero	"divide by zero"
#define	_SGI_DMMX_e_done	":23"
#define	_SGI_MMX_e_done	"uxsgish:23"
#define	_SGI_MMMX_e_done	"uxsgish:23: Done"
#define	_SGI_SMMX_e_done	" Done"
#define	_SGI_DMMX_e_endoffile	":24"
#define	_SGI_MMX_e_endoffile	"uxsgish:24"
#define	_SGI_MMMX_e_endoffile	"uxsgish:24:end of file"
#define	_SGI_SMMX_e_endoffile	"end of file"
#define	_SGI_DMMX_e_exec	":25"
#define	_SGI_MMX_e_exec	"uxsgish:25"
#define	_SGI_MMMX_e_exec	"uxsgish:25:cannot execute"
#define	_SGI_SMMX_e_exec	"cannot execute"
#define	_SGI_DMMX_e_export	":26"
#define	_SGI_MMX_e_export	"uxsgish:26"
#define	_SGI_MMMX_e_export	"uxsgish:26:export"
#define	_SGI_SMMX_e_export	"export"
#define	_SGI_DMMX_e_fexists	":27"
#define	_SGI_MMX_e_fexists	"uxsgish:27"
#define	_SGI_MMMX_e_fexists	"uxsgish:27:file already exists"
#define	_SGI_SMMX_e_fexists	"file already exists"
#define	_SGI_DMMX_e_file	":28"
#define	_SGI_MMX_e_file	"uxsgish:28"
#define	_SGI_MMMX_e_file	"uxsgish:28:bad file unit number"
#define	_SGI_SMMX_e_file	"bad file unit number"
#define	_SGI_DMMX_e_flimit	":29"
#define	_SGI_MMX_e_flimit	"uxsgish:29"
#define	_SGI_MMMX_e_flimit	"uxsgish:29:too many open files"
#define	_SGI_SMMX_e_flimit	"too many open files"
#define	_SGI_DMMX_e_fork	":30"
#define	_SGI_MMX_e_fork	"uxsgish:30"
#define	_SGI_MMMX_e_fork	"uxsgish:30:cannot fork: too many processes"
#define	_SGI_SMMX_e_fork	"cannot fork: too many processes"
#define	_SGI_DMMX_e_format	":31"
#define	_SGI_MMX_e_format	"uxsgish:31"
#define	_SGI_MMMX_e_format	"uxsgish:31:bad format"
#define	_SGI_SMMX_e_format	"bad format"
#define	_SGI_DMMX_e_found	":32"
#define	_SGI_MMX_e_found	"uxsgish:32"
#define	_SGI_MMMX_e_found	"uxsgish:32: not found"
#define	_SGI_SMMX_e_found	" not found"
#define	_SGI_DMMX_e_function	":33"
#define	_SGI_MMX_e_function	"uxsgish:33"
#define	_SGI_MMMX_e_function	"uxsgish:33:unknown function"
#define	_SGI_SMMX_e_function	"unknown function"
#define	_SGI_DMMX_e_getmap	":34"
#define	_SGI_MMX_e_getmap	"uxsgish:34"
#define	_SGI_MMMX_e_getmap	"uxsgish:34:cannot get mapping"
#define	_SGI_SMMX_e_getmap	"cannot get mapping"
#define	_SGI_DMMX_e_getvers	":35"
#define	_SGI_MMX_e_getvers	"uxsgish:35"
#define	_SGI_MMMX_e_getvers	"uxsgish:35:cannot get versions"
#define	_SGI_SMMX_e_getvers	"cannot get versions"
#define	_SGI_DMMX_e_heading	":36"
#define	_SGI_MMX_e_heading	"uxsgish:36"
#define	_SGI_MMMX_e_heading	"uxsgish:36:Current option settings"
#define	_SGI_SMMX_e_heading	"Current option settings"
#define	_SGI_DMMX_e_history	":37"
#define	_SGI_MMX_e_history	"uxsgish:37"
#define	_SGI_MMMX_e_history	"uxsgish:37:no history file"
#define	_SGI_SMMX_e_history	"no history file"
#define	_SGI_DMMX_e_ident	":38"
#define	_SGI_MMX_e_ident	"uxsgish:38"
#define	_SGI_MMMX_e_ident	"uxsgish:38:is not an identifier"
#define	_SGI_SMMX_e_ident	"is not an identifier"
#define	_SGI_DMMX_e_incompatible	":39"
#define	_SGI_MMX_e_incompatible	"uxsgish:39"
#define	_SGI_MMMX_e_incompatible	"uxsgish:39:operands have incompatible types"
#define	_SGI_SMMX_e_incompatible	"operands have incompatible types"
#define	_SGI_DMMX_e_intbase	":40"
#define	_SGI_MMX_e_intbase	"uxsgish:40"
#define	_SGI_MMMX_e_intbase	"uxsgish:40:base"
#define	_SGI_SMMX_e_intbase	"base"
#define	_SGI_DMMX_e_invalidnm	":41"
#define	_SGI_MMX_e_invalidnm	"uxsgish:41"
#define	_SGI_MMMX_e_invalidnm	"uxsgish:41:invalid name"
#define	_SGI_SMMX_e_invalidnm	"invalid name"
#define	_SGI_DMMX_e_running	":42"
#define	_SGI_MMX_e_running	"uxsgish:42"
#define	_SGI_MMMX_e_running	"uxsgish:42:You have running jobs"
#define	_SGI_SMMX_e_running	"You have running jobs"
#define	_SGI_DMMX_e_jobusage	":43"
#define	_SGI_MMX_e_jobusage	"uxsgish:43"
#define	_SGI_MMMX_e_jobusage	"uxsgish:43:Arguments must be %job or process ids"
#define	_SGI_SMMX_e_jobusage	"Arguments must be %job or process ids"
#define	_SGI_DMMX_e_kill	":44"
#define	_SGI_MMX_e_kill	"uxsgish:44"
#define	_SGI_MMMX_e_kill	"uxsgish:44:kill"
#define	_SGI_SMMX_e_kill	"kill"
#define	_SGI_DMMX_e_killcolon	":45"
#define	_SGI_MMX_e_killcolon	"uxsgish:45"
#define	_SGI_MMMX_e_killcolon	"uxsgish:45:kill: "
#define	_SGI_SMMX_e_killcolon	"kill: "
#define	_SGI_DMMX_e_libacc	":46"
#define	_SGI_MMX_e_libacc	"uxsgish:46"
#define	_SGI_MMMX_e_libacc	"uxsgish:46:can't access a needed shared library"
#define	_SGI_SMMX_e_libacc	"can't access a needed shared library"
#define	_SGI_DMMX_e_libbad	":47"
#define	_SGI_MMX_e_libbad	"uxsgish:47"
#define	_SGI_MMMX_e_libbad	"uxsgish:47:accessing a corrupted shared library"
#define	_SGI_SMMX_e_libbad	"accessing a corrupted shared library"
#define	_SGI_DMMX_e_libmax	":48"
#define	_SGI_MMX_e_libmax	"uxsgish:48"
#define	_SGI_MMMX_e_libmax	"uxsgish:48:attempting to link in too many libs"
#define	_SGI_SMMX_e_libmax	"attempting to link in too many libs"
#define	_SGI_DMMX_e_libscn	":49"
#define	_SGI_MMX_e_libscn	"uxsgish:49"
#define	_SGI_MMMX_e_libscn	"uxsgish:49:.lib section in a.out corrupted"
#define	_SGI_SMMX_e_libscn	".lib section in a.out corrupted"
#define	_SGI_DMMX_e_link	":50"
#define	_SGI_MMX_e_link	"uxsgish:50"
#define	_SGI_MMMX_e_link	"uxsgish:50:remote link inactive"
#define	_SGI_SMMX_e_link	"remote link inactive"
#define	_SGI_DMMX_e_logout	":51"
#define	_SGI_MMX_e_logout	"uxsgish:51"
#define	_SGI_MMMX_e_logout	"uxsgish:51:Use 'exit' to terminate this shell"
#define	_SGI_SMMX_e_logout	"Use 'exit' to terminate this shell"
#define	_SGI_DMMX_e_longname	":52"
#define	_SGI_MMX_e_longname	"uxsgish:52"
#define	_SGI_MMMX_e_longname	"uxsgish:52:name too long"
#define	_SGI_SMMX_e_longname	"name too long"
#define	_SGI_DMMX_e_mailmsg	":53"
#define	_SGI_MMX_e_mailmsg	"uxsgish:53"
#define	_SGI_MMMX_e_mailmsg	"uxsgish:53:you have mail in $_"
#define	_SGI_SMMX_e_mailmsg	"you have mail in $_"
#define	_SGI_DMMX_e_malloc	":54"
#define	_SGI_MMX_e_malloc	"uxsgish:54"
#define	_SGI_MMMX_e_malloc	"uxsgish:54:malloc failed while growing stack\n"
#define	_SGI_SMMX_e_malloc	"malloc failed while growing stack\n"
#define	_SGI_DMMX_e_moretokens	":55"
#define	_SGI_MMX_e_moretokens	"uxsgish:55"
#define	_SGI_MMMX_e_moretokens	"uxsgish:55:more tokens expected"
#define	_SGI_SMMX_e_moretokens	"more tokens expected"
#define	_SGI_DMMX_e_multihop	":56"
#define	_SGI_MMX_e_multihop	"uxsgish:56"
#define	_SGI_MMMX_e_multihop	"uxsgish:56:multihop attempted"
#define	_SGI_SMMX_e_multihop	"multihop attempted"
#define	_SGI_DMMX_e_nargs	":57"
#define	_SGI_MMX_e_nargs	"uxsgish:57"
#define	_SGI_MMMX_e_nargs	"uxsgish:57:bad argument count"
#define	_SGI_SMMX_e_nargs	"bad argument count"
#define	_SGI_DMMX_e_newtty	":58"
#define	_SGI_MMX_e_newtty	"uxsgish:58"
#define	_SGI_MMMX_e_newtty	"uxsgish:58:Switching to new tty driver..."
#define	_SGI_SMMX_e_newtty	"Switching to new tty driver..."
#define	_SGI_DMMX_e_nlorsemi	":59"
#define	_SGI_MMX_e_nlorsemi	"uxsgish:59"
#define	_SGI_MMMX_e_nlorsemi	"uxsgish:59:newline or ;"
#define	_SGI_SMMX_e_nlorsemi	"newline or ;"
#define	_SGI_DMMX_e_no_jctl	":60"
#define	_SGI_MMX_e_no_jctl	"uxsgish:60"
#define	_SGI_MMMX_e_no_jctl	"uxsgish:60:No job control"
#define	_SGI_SMMX_e_no_jctl	"No job control"
#define	_SGI_DMMX_e_no_job	":61"
#define	_SGI_MMX_e_no_job	"uxsgish:61"
#define	_SGI_MMMX_e_no_job	"uxsgish:61:no such job"
#define	_SGI_SMMX_e_no_job	"no such job"
#define	_SGI_DMMX_e_no_proc	":62"
#define	_SGI_MMX_e_no_proc	"uxsgish:62"
#define	_SGI_MMMX_e_no_proc	"uxsgish:62:no such process"
#define	_SGI_SMMX_e_no_proc	"no such process"
#define	_SGI_DMMX_e_no_start	":63"
#define	_SGI_MMX_e_no_start	"uxsgish:63"
#define	_SGI_MMMX_e_no_start	"uxsgish:63:Cannot start job control"
#define	_SGI_SMMX_e_no_start	"Cannot start job control"
#define	_SGI_DMMX_e_no_access	":64"
#define	_SGI_MMX_e_no_access	"uxsgish:64"
#define	_SGI_MMMX_e_no_access	"uxsgish:64:not accessible"
#define	_SGI_SMMX_e_no_access	"not accessible"
#define	_SGI_DMMX_e_notdir	":65"
#define	_SGI_MMX_e_notdir	"uxsgish:65"
#define	_SGI_MMMX_e_notdir	"uxsgish:65:not a directory"
#define	_SGI_SMMX_e_notdir	"not a directory"
#define	_SGI_DMMX_e_notlvalue	":66"
#define	_SGI_MMX_e_notlvalue	"uxsgish:66"
#define	_SGI_MMMX_e_notlvalue	"uxsgish:66:assignment requires lvalue"
#define	_SGI_SMMX_e_notlvalue	"assignment requires lvalue"
#define	_SGI_DMMX_e_notset	":67"
#define	_SGI_MMX_e_notset	"uxsgish:67"
#define	_SGI_MMMX_e_notset	"uxsgish:67:parameter not set"
#define	_SGI_SMMX_e_notset	"parameter not set"
#define	_SGI_DMMX_e_nover	":68"
#define	_SGI_MMX_e_nover	"uxsgish:68"
#define	_SGI_MMMX_e_nover	"uxsgish:68:Version not defined"
#define	_SGI_SMMX_e_nover	"Version not defined"
#define	_SGI_DMMX_e_nullset	":69"
#define	_SGI_MMX_e_nullset	"uxsgish:69"
#define	_SGI_MMMX_e_nullset	"uxsgish:69:parameter null or not set"
#define	_SGI_SMMX_e_nullset	"parameter null or not set"
#define	_SGI_DMMX_e_number	":70"
#define	_SGI_MMX_e_number	"uxsgish:70"
#define	_SGI_MMMX_e_number	"uxsgish:70:bad number"
#define	_SGI_SMMX_e_number	"bad number"
#define	_SGI_DMMX_e_off	":71"
#define	_SGI_MMX_e_off	"uxsgish:71"
#define	_SGI_MMMX_e_off	"uxsgish:71:off"
#define	_SGI_SMMX_e_off	"off"
#define	_SGI_DMMX_e_oldtty	":72"
#define	_SGI_MMX_e_oldtty	"uxsgish:72"
#define	_SGI_MMMX_e_oldtty	"uxsgish:72:Reverting to old tty driver..."
#define	_SGI_SMMX_e_oldtty	"Reverting to old tty driver..."
#define	_SGI_DMMX_e_on	":73"
#define	_SGI_MMX_e_on	"uxsgish:73"
#define	_SGI_MMMX_e_on	"uxsgish:73:on"
#define	_SGI_SMMX_e_on	"on"
#define	_SGI_DMMX_e_open	":74"
#define	_SGI_MMX_e_open	"uxsgish:74"
#define	_SGI_MMMX_e_open	"uxsgish:74:cannot open"
#define	_SGI_SMMX_e_open	"cannot open"
#define	_SGI_DMMX_e_option	":75"
#define	_SGI_MMX_e_option	"uxsgish:75"
#define	_SGI_MMMX_e_option	"uxsgish:75:bad option(s)"
#define	_SGI_SMMX_e_option	"bad option(s)"
#define	_SGI_DMMX_e_paren	":76"
#define	_SGI_MMX_e_paren	"uxsgish:76"
#define	_SGI_MMMX_e_paren	"uxsgish:76:unbalanced parenthesis"
#define	_SGI_SMMX_e_paren	"unbalanced parenthesis"
#define	_SGI_DMMX_e_pexists	":77"
#define	_SGI_MMX_e_pexists	"uxsgish:77"
#define	_SGI_MMMX_e_pexists	"uxsgish:77:process already exists"
#define	_SGI_SMMX_e_pexists	"process already exists"
#define	_SGI_DMMX_e_pipe	":78"
#define	_SGI_MMX_e_pipe	"uxsgish:78"
#define	_SGI_MMMX_e_pipe	"uxsgish:78:cannot make pipe"
#define	_SGI_SMMX_e_pipe	"cannot make pipe"
#define	_SGI_DMMX_e_precision	":79"
#define	_SGI_MMX_e_precision	"uxsgish:79"
#define	_SGI_MMMX_e_precision	"uxsgish:79:precision"
#define	_SGI_SMMX_e_precision	"precision"
#define	_SGI_DMMX_e_prohibited	":80"
#define	_SGI_MMX_e_prohibited	"uxsgish:80"
#define	_SGI_MMMX_e_prohibited	"uxsgish:80:login setuid/setgid shells prohibited"
#define	_SGI_SMMX_e_prohibited	"login setuid/setgid shells prohibited"
#define	_SGI_DMMX_e_pwd	":81"
#define	_SGI_MMX_e_pwd	"uxsgish:81"
#define	_SGI_MMMX_e_pwd	"uxsgish:81:cannot access parent directories"
#define	_SGI_SMMX_e_pwd	"cannot access parent directories"
#define	_SGI_DMMX_e_query	":82"
#define	_SGI_MMX_e_query	"uxsgish:82"
#define	_SGI_MMMX_e_query	"uxsgish:82:no query process"
#define	_SGI_SMMX_e_query	"no query process"
#define	_SGI_DMMX_e_questcolon	":83"
#define	_SGI_MMX_e_questcolon	"uxsgish:83"
#define	_SGI_MMMX_e_questcolon	"uxsgish:83:: expected for ? operator"
#define	_SGI_SMMX_e_questcolon	": expected for ? operator"
#define	_SGI_DMMX_e_readonly	":84"
#define	_SGI_MMX_e_readonly	"uxsgish:84"
#define	_SGI_MMMX_e_readonly	"uxsgish:84:readonly"
#define	_SGI_SMMX_e_readonly	"readonly"
#define	_SGI_DMMX_e_real	":85"
#define	_SGI_MMX_e_real	"uxsgish:85"
#define	_SGI_MMMX_e_real	"uxsgish:85:\nreal"
#define	_SGI_SMMX_e_real	"\nreal"
#define	_SGI_DMMX_e_recursive	":86"
#define	_SGI_MMX_e_recursive	"uxsgish:86"
#define	_SGI_MMMX_e_recursive	"uxsgish:86:recursion too deep"
#define	_SGI_SMMX_e_recursive	"recursion too deep"
#define	_SGI_DMMX_e_restricted	":87"
#define	_SGI_MMX_e_restricted	"uxsgish:87"
#define	_SGI_MMMX_e_restricted	"uxsgish:87:restricted"
#define	_SGI_SMMX_e_restricted	"restricted"
#define	_SGI_DMMX_e_rootnode	":88"
#define	_SGI_MMX_e_rootnode	"uxsgish:88"
#define	_SGI_MMMX_e_rootnode	"uxsgish:88:Bad root node specification"
#define	_SGI_SMMX_e_rootnode	"Bad root node specification"
#define	_SGI_DMMX_e_Running	":89"
#define	_SGI_MMX_e_Running	"uxsgish:89"
#define	_SGI_MMMX_e_Running	"uxsgish:89: Running"
#define	_SGI_SMMX_e_Running	" Running"
#define	_SGI_DMMX_e_setmap	":90"
#define	_SGI_MMX_e_setmap	"uxsgish:90"
#define	_SGI_MMMX_e_setmap	"uxsgish:90:cannot set mapping"
#define	_SGI_SMMX_e_setmap	"cannot set mapping"
#define	_SGI_DMMX_e_setvpath	":91"
#define	_SGI_MMX_e_setvpath	"uxsgish:91"
#define	_SGI_MMMX_e_setvpath	"uxsgish:91:cannot set vpath"
#define	_SGI_SMMX_e_setvpath	"cannot set vpath"
#define	_SGI_DMMX_e_space	":92"
#define	_SGI_MMX_e_space	"uxsgish:92"
#define	_SGI_MMMX_e_space	"uxsgish:92:no space"
#define	_SGI_SMMX_e_space	"no space"
#define	_SGI_DMMX_e_subscript	":93"
#define	_SGI_MMX_e_subscript	"uxsgish:93"
#define	_SGI_MMMX_e_subscript	"uxsgish:93:subscript out of range"
#define	_SGI_SMMX_e_subscript	"subscript out of range"
#define	_SGI_DMMX_e_subst	":94"
#define	_SGI_MMX_e_subst	"uxsgish:94"
#define	_SGI_MMMX_e_subst	"uxsgish:94:bad substitution"
#define	_SGI_SMMX_e_subst	"bad substitution"
#define	_SGI_DMMX_e_swap	":95"
#define	_SGI_MMX_e_swap	"uxsgish:95"
#define	_SGI_MMMX_e_swap	"uxsgish:95:cannot fork: no swap space"
#define	_SGI_SMMX_e_swap	"cannot fork: no swap space"
#define	_SGI_DMMX_e_synbad	":96"
#define	_SGI_MMX_e_synbad	"uxsgish:96"
#define	_SGI_MMMX_e_synbad	"uxsgish:96:syntax error"
#define	_SGI_SMMX_e_synbad	"syntax error"
#define	_SGI_DMMX_e_sys	":97"
#define	_SGI_MMX_e_sys	"uxsgish:97"
#define	_SGI_MMMX_e_sys	"uxsgish:97:sys"
#define	_SGI_SMMX_e_sys	"sys"
#define	_SGI_DMMX_e_terminate	":98"
#define	_SGI_MMX_e_terminate	"uxsgish:98"
#define	_SGI_MMMX_e_terminate	"uxsgish:98:You have stopped jobs"
#define	_SGI_SMMX_e_terminate	"You have stopped jobs"
#define	_SGI_DMMX_e_test	":99"
#define	_SGI_MMX_e_test	"uxsgish:99"
#define	_SGI_MMMX_e_test	"uxsgish:99:test"
#define	_SGI_SMMX_e_test	"test"
#define	_SGI_DMMX_e_testop	":100"
#define	_SGI_MMX_e_testop	"uxsgish:100"
#define	_SGI_MMMX_e_testop	"uxsgish:100:unknown test operator"
#define	_SGI_SMMX_e_testop	"unknown test operator"
#define	_SGI_DMMX_e_timeout	":101"
#define	_SGI_MMX_e_timeout	"uxsgish:101"
#define	_SGI_MMMX_e_timeout	"uxsgish:101:timed out waiting for input"
#define	_SGI_SMMX_e_timeout	"timed out waiting for input"
#define	_SGI_DMMX_e_timewarn	":102"
#define	_SGI_MMX_e_timewarn	"uxsgish:102"
#define	_SGI_MMMX_e_timewarn	"uxsgish:102:\r\n\007shell will time out in 60 seconds"
#define	_SGI_SMMX_e_timewarn	"\r\n\007shell will time out in 60 seconds"
#define	_SGI_DMMX_e_toobig	":103"
#define	_SGI_MMX_e_toobig	"uxsgish:103"
#define	_SGI_MMMX_e_toobig	"uxsgish:103:too big"
#define	_SGI_SMMX_e_toobig	"too big"
#define	_SGI_DMMX_e_trap	":104"
#define	_SGI_MMX_e_trap	"uxsgish:104"
#define	_SGI_MMMX_e_trap	"uxsgish:104:trap -- "
#define	_SGI_SMMX_e_trap	"trap -- "
#define	_SGI_DMMX_e_txtbsy	":105"
#define	_SGI_MMX_e_txtbsy	"uxsgish:105"
#define	_SGI_MMMX_e_txtbsy	"uxsgish:105:text busy"
#define	_SGI_SMMX_e_txtbsy	"text busy"
#define	_SGI_DMMX_e_ulimit	":106"
#define	_SGI_MMX_e_ulimit	"uxsgish:106"
#define	_SGI_MMMX_e_ulimit	"uxsgish:106:exceeds allowable limit"
#define	_SGI_SMMX_e_ulimit	"exceeds allowable limit"
#define	_SGI_DMMX_e_undefsym	":107"
#define	_SGI_MMX_e_undefsym	"uxsgish:107"
#define	_SGI_MMMX_e_undefsym	"uxsgish:107:undefined symbols"
#define	_SGI_SMMX_e_undefsym	"undefined symbols"
#define	_SGI_DMMX_e_unexpected	":108"
#define	_SGI_MMX_e_unexpected	"uxsgish:108"
#define	_SGI_MMMX_e_unexpected	"uxsgish:108: unexpected"
#define	_SGI_SMMX_e_unexpected	" unexpected"
#define	_SGI_DMMX_e_unknown	":109"
#define	_SGI_MMX_e_unknown	"uxsgish:109"
#define	_SGI_MMMX_e_unknown	"uxsgish:109:unknown"
#define	_SGI_SMMX_e_unknown	"unknown"
#define	_SGI_DMMX_e_unlimited	":110"
#define	_SGI_MMX_e_unlimited	"uxsgish:110"
#define	_SGI_MMMX_e_unlimited	"uxsgish:110:unlimited"
#define	_SGI_SMMX_e_unlimited	"unlimited"
#define	_SGI_DMMX_e_unmatched	":111"
#define	_SGI_MMX_e_unmatched	"uxsgish:111"
#define	_SGI_MMMX_e_unmatched	"uxsgish:111: unmatched"
#define	_SGI_SMMX_e_unmatched	" unmatched"
#define	_SGI_DMMX_e_user	":112"
#define	_SGI_MMX_e_user	"uxsgish:112"
#define	_SGI_MMMX_e_user	"uxsgish:112:user"
#define	_SGI_SMMX_e_user	"user"
#define	_SGI_DMMX_is_	":113"
#define	_SGI_MMX_is_	"uxsgish:113"
#define	_SGI_MMMX_is_	"uxsgish:113: is "
#define	_SGI_SMMX_is_	" is "
#define	_SGI_DMMX_is_alias	":114"
#define	_SGI_MMX_is_alias	"uxsgish:114"
#define	_SGI_MMMX_is_alias	"uxsgish:114: is an alias for "
#define	_SGI_SMMX_is_alias	" is an alias for "
#define	_SGI_DMMX_is_builtin	":115"
#define	_SGI_MMX_is_builtin	"uxsgish:115"
#define	_SGI_MMMX_is_builtin	"uxsgish:115: is a shell builtin"
#define	_SGI_SMMX_is_builtin	" is a shell builtin"
#define	_SGI_DMMX_is_function	":116"
#define	_SGI_MMX_is_function	"uxsgish:116"
#define	_SGI_MMMX_is_function	"uxsgish:116: is a function"
#define	_SGI_SMMX_is_function	" is a function"
#define	_SGI_DMMX_is_pathfound	":117"
#define	_SGI_MMX_is_pathfound	"uxsgish:117"
#define	_SGI_MMMX_is_pathfound	"uxsgish:117: is found in PATH"
#define	_SGI_SMMX_is_pathfound	" is found in PATH"
#define	_SGI_DMMX_is_readonly	":118"
#define	_SGI_MMX_is_readonly	"uxsgish:118"
#define	_SGI_MMMX_is_readonly	"uxsgish:118:is read only"
#define	_SGI_SMMX_is_readonly	"is read only"
#define	_SGI_DMMX_is_reserved	":119"
#define	_SGI_MMX_is_reserved	"uxsgish:119"
#define	_SGI_MMMX_is_reserved	"uxsgish:119: is a reserved keyword"
#define	_SGI_SMMX_is_reserved	" is a reserved keyword"
#define	_SGI_DMMX_is_spc_builtin	":120"
#define	_SGI_MMX_is_spc_builtin	"uxsgish:120"
#define	_SGI_MMMX_is_spc_builtin	"uxsgish:120: is a special shell builtin"
#define	_SGI_SMMX_is_spc_builtin	" is a special shell builtin"
#define	_SGI_DMMX_is_talias	":121"
#define	_SGI_MMX_is_talias	"uxsgish:121"
#define	_SGI_MMMX_is_talias	"uxsgish:121: is a tracked alias for "
#define	_SGI_SMMX_is_talias	" is a tracked alias for "
#define	_SGI_DMMX_is_ufunction	":122"
#define	_SGI_MMX_is_ufunction	"uxsgish:122"
#define	_SGI_MMMX_is_ufunction	"uxsgish:122: is an undefined function"
#define	_SGI_SMMX_is_ufunction	" is an undefined function"
#define	_SGI_DMMX_is_xalias	":123"
#define	_SGI_MMX_is_xalias	"uxsgish:123"
#define	_SGI_MMMX_is_xalias	"uxsgish:123: is an exported alias for "
#define	_SGI_SMMX_is_xalias	" is an exported alias for "
#define	_SGI_DMMX_is_xfunction	":124"
#define	_SGI_MMX_is_xfunction	"uxsgish:124"
#define	_SGI_MMMX_is_xfunction	"uxsgish:124: is an exported function"
#define	_SGI_SMMX_is_xfunction	" is an exported function"
#define	_SGI_DMMX_r_coredump	":125"
#define	_SGI_MMX_r_coredump	"uxsgish:125"
#define	_SGI_MMMX_r_coredump	"uxsgish:125:coredump(blocks)    "
#define	_SGI_SMMX_r_coredump	"coredump(blocks)    "
#define	_SGI_DMMX_r_data	":126"
#define	_SGI_MMX_r_data	"uxsgish:126"
#define	_SGI_MMMX_r_data	"uxsgish:126:data(kbytes)        "
#define	_SGI_SMMX_r_data	"data(kbytes)        "
#define	_SGI_DMMX_r_file	":127"
#define	_SGI_MMX_r_file	"uxsgish:127"
#define	_SGI_MMMX_r_file	"uxsgish:127:file(blocks)        "
#define	_SGI_SMMX_r_file	"file(blocks)        "
#define	_SGI_DMMX_r_memory	":128"
#define	_SGI_MMX_r_memory	"uxsgish:128"
#define	_SGI_MMMX_r_memory	"uxsgish:128:memory(kbytes)      "
#define	_SGI_SMMX_r_memory	"memory(kbytes)      "
#define	_SGI_DMMX_r_nofiles	":129"
#define	_SGI_MMX_r_nofiles	"uxsgish:129"
#define	_SGI_MMMX_r_nofiles	"uxsgish:129:nofiles(descriptors)"
#define	_SGI_SMMX_r_nofiles	"nofiles(descriptors)"
#define	_SGI_DMMX_r_stack	":130"
#define	_SGI_MMX_r_stack	"uxsgish:130"
#define	_SGI_MMMX_r_stack	"uxsgish:130:stack(kbytes)       "
#define	_SGI_SMMX_r_stack	"stack(kbytes)       "
#define	_SGI_DMMX_r_time	":131"
#define	_SGI_MMX_r_time	"uxsgish:131"
#define	_SGI_MMMX_r_time	"uxsgish:131:time(seconds)       "
#define	_SGI_SMMX_r_time	"time(seconds)       "
#define	_SGI_DMMX_r_vmemory	":132"
#define	_SGI_MMX_r_vmemory	"uxsgish:132"
#define	_SGI_MMMX_r_vmemory	"uxsgish:132:vmemory(kbytes)     "
#define	_SGI_SMMX_r_vmemory	"vmemory(kbytes)     "
#define	_SGI_DMMX_s_abort	":133"
#define	_SGI_MMX_s_abort	"uxsgish:133"
#define	_SGI_MMMX_s_abort	"uxsgish:133:Abort"
#define	_SGI_SMMX_s_abort	"Abort"
#define	_SGI_DMMX_s_alarmcall	":134"
#define	_SGI_MMX_s_alarmcall	"uxsgish:134"
#define	_SGI_MMMX_s_alarmcall	"uxsgish:134:Alarm call"
#define	_SGI_SMMX_s_alarmcall	"Alarm call"
#define	_SGI_DMMX_s_badsyscall	":135"
#define	_SGI_MMX_s_badsyscall	"uxsgish:135"
#define	_SGI_MMMX_s_badsyscall	"uxsgish:135:Bad system call"
#define	_SGI_SMMX_s_badsyscall	"Bad system call"
#define	_SGI_DMMX_s_brokenpipe	":136"
#define	_SGI_MMX_s_brokenpipe	"uxsgish:136"
#define	_SGI_MMMX_s_brokenpipe	"uxsgish:136:Broken Pipe"
#define	_SGI_SMMX_s_brokenpipe	"Broken Pipe"
#define	_SGI_DMMX_s_buserror	":137"
#define	_SGI_MMX_s_buserror	"uxsgish:137"
#define	_SGI_MMMX_s_buserror	"uxsgish:137:Bus error"
#define	_SGI_SMMX_s_buserror	"Bus error"
#define	_SGI_DMMX_s_childstop	":138"
#define	_SGI_MMX_s_childstop	"uxsgish:138"
#define	_SGI_MMMX_s_childstop	"uxsgish:138:Child stopped or terminated"
#define	_SGI_SMMX_s_childstop	"Child stopped or terminated"
#define	_SGI_DMMX_s_childdeath	":139"
#define	_SGI_MMX_s_childdeath	"uxsgish:139"
#define	_SGI_MMMX_s_childdeath	"uxsgish:139:Death of Child"
#define	_SGI_SMMX_s_childdeath	"Death of Child"
#define	_SGI_DMMX_s_emttrap	":140"
#define	_SGI_MMX_s_emttrap	"uxsgish:140"
#define	_SGI_MMMX_s_emttrap	"uxsgish:140:EMT trap"
#define	_SGI_SMMX_s_emttrap	"EMT trap"
#define	_SGI_DMMX_s_floatex	":141"
#define	_SGI_MMX_s_floatex	"uxsgish:141"
#define	_SGI_MMMX_s_floatex	"uxsgish:141:Floating exception"
#define	_SGI_SMMX_s_floatex	"Floating exception"
#define	_SGI_DMMX_s_hangup	":142"
#define	_SGI_MMX_s_hangup	"uxsgish:142"
#define	_SGI_MMMX_s_hangup	"uxsgish:142:Hangup"
#define	_SGI_SMMX_s_hangup	"Hangup"
#define	_SGI_DMMX_s_illegal	":143"
#define	_SGI_MMX_s_illegal	"uxsgish:143"
#define	_SGI_MMMX_s_illegal	"uxsgish:143:Illegal instruction"
#define	_SGI_SMMX_s_illegal	"Illegal instruction"
#define	_SGI_DMMX_s_intr	":144"
#define	_SGI_MMX_s_intr	"uxsgish:144"
#define	_SGI_MMMX_s_intr	"uxsgish:144:Interrupt"
#define	_SGI_SMMX_s_intr	"Interrupt"
#define	_SGI_DMMX_s_iosignal	":145"
#define	_SGI_MMX_s_iosignal	"uxsgish:145"
#define	_SGI_MMMX_s_iosignal	"uxsgish:145:IO signal"
#define	_SGI_SMMX_s_iosignal	"IO signal"
#define	_SGI_DMMX_s_killed	":146"
#define	_SGI_MMX_s_killed	"uxsgish:146"
#define	_SGI_MMMX_s_killed	"uxsgish:146:Killed"
#define	_SGI_SMMX_s_killed	"Killed"
#define	_SGI_DMMX_s_memoryfault	":147"
#define	_SGI_MMX_s_memoryfault	"uxsgish:147"
#define	_SGI_MMMX_s_memoryfault	"uxsgish:147:Memory fault"
#define	_SGI_SMMX_s_memoryfault	"Memory fault"
#define	_SGI_DMMX_s_powerfail	":148"
#define	_SGI_MMX_s_powerfail	"uxsgish:148"
#define	_SGI_MMMX_s_powerfail	"uxsgish:148:Power fail"
#define	_SGI_SMMX_s_powerfail	"Power fail"
#define	_SGI_DMMX_s_profalarm	":149"
#define	_SGI_MMX_s_profalarm	"uxsgish:149"
#define	_SGI_MMMX_s_profalarm	"uxsgish:149:Profiling time alarm"
#define	_SGI_SMMX_s_profalarm	"Profiling time alarm"
#define	_SGI_DMMX_s_quit	":150"
#define	_SGI_MMX_s_quit	"uxsgish:150"
#define	_SGI_MMMX_s_quit	"uxsgish:150:Quit"
#define	_SGI_SMMX_s_quit	"Quit"
#define	_SGI_DMMX_s_resource	":151"
#define	_SGI_MMX_s_resource	"uxsgish:151"
#define	_SGI_MMMX_s_resource	"uxsgish:151:Resources lost"
#define	_SGI_SMMX_s_resource	"Resources lost"
#define	_SGI_DMMX_s_securitychg	":152"
#define	_SGI_MMX_s_securitychg	"uxsgish:152"
#define	_SGI_MMMX_s_securitychg	"uxsgish:152:Security label changed"
#define	_SGI_SMMX_s_securitychg	"Security label changed"
#define	_SGI_DMMX_s_sizelimit	":153"
#define	_SGI_MMX_s_sizelimit	"uxsgish:153"
#define	_SGI_MMMX_s_sizelimit	"uxsgish:153:Exceeded file size limit"
#define	_SGI_SMMX_s_sizelimit	"Exceeded file size limit"
#define	_SGI_DMMX_s_sockintr	":154"
#define	_SGI_MMX_s_sockintr	"uxsgish:154"
#define	_SGI_MMMX_s_sockintr	"uxsgish:154:Socket interrupt"
#define	_SGI_SMMX_s_sockintr	"Socket interrupt"
#define	_SGI_DMMX_s_stopcont	":155"
#define	_SGI_MMX_s_stopcont	"uxsgish:155"
#define	_SGI_MMMX_s_stopcont	"uxsgish:155:Stopped process continued"
#define	_SGI_SMMX_s_stopcont	"Stopped process continued"
#define	_SGI_DMMX_s_stopstop	":156"
#define	_SGI_MMX_s_stopstop	"uxsgish:156"
#define	_SGI_MMMX_s_stopstop	"uxsgish:156:Stopped (SIGSTOP)"
#define	_SGI_SMMX_s_stopstop	"Stopped (SIGSTOP)"
#define	_SGI_DMMX_s_stoptstp	":157"
#define	_SGI_MMX_s_stoptstp	"uxsgish:157"
#define	_SGI_MMMX_s_stoptstp	"uxsgish:157:Stopped (SIGTSTP)"
#define	_SGI_SMMX_s_stoptstp	"Stopped (SIGTSTP)"
#define	_SGI_DMMX_s_stopttin	":158"
#define	_SGI_MMX_s_stopttin	"uxsgish:158"
#define	_SGI_MMMX_s_stopttin	"uxsgish:158:Stopped (SIGTTIN)"
#define	_SGI_SMMX_s_stopttin	"Stopped (SIGTTIN)"
#define	_SGI_DMMX_s_stopttou	":159"
#define	_SGI_MMX_s_stopttou	"uxsgish:159"
#define	_SGI_MMMX_s_stopttou	"uxsgish:159:Stopped (SIGTTOU)"
#define	_SGI_SMMX_s_stopttou	"Stopped (SIGTTOU)"
#define	_SGI_DMMX_s_term	":160"
#define	_SGI_MMX_s_term	"uxsgish:160"
#define	_SGI_MMMX_s_term	"uxsgish:160:Terminated"
#define	_SGI_SMMX_s_term	"Terminated"
#define	_SGI_DMMX_s_timelimit	":161"
#define	_SGI_MMX_s_timelimit	"uxsgish:161"
#define	_SGI_MMMX_s_timelimit	"uxsgish:161:Exceeded CPU time limit"
#define	_SGI_SMMX_s_timelimit	"Exceeded CPU time limit"
#define	_SGI_DMMX_s_tracetrap	":162"
#define	_SGI_MMX_s_tracetrap	"uxsgish:162"
#define	_SGI_MMMX_s_tracetrap	"uxsgish:162:Trace/BPT trap"
#define	_SGI_SMMX_s_tracetrap	"Trace/BPT trap"
#define	_SGI_DMMX_s_usrsig1	":163"
#define	_SGI_MMX_s_usrsig1	"uxsgish:163"
#define	_SGI_MMMX_s_usrsig1	"uxsgish:163:User signal 1"
#define	_SGI_SMMX_s_usrsig1	"User signal 1"
#define	_SGI_DMMX_s_usrsig2	":164"
#define	_SGI_MMX_s_usrsig2	"uxsgish:164"
#define	_SGI_MMMX_s_usrsig2	"uxsgish:164:User signal 2"
#define	_SGI_SMMX_s_usrsig2	"User signal 2"
#define	_SGI_DMMX_s_virtalarm	":165"
#define	_SGI_MMX_s_virtalarm	"uxsgish:165"
#define	_SGI_MMMX_s_virtalarm	"uxsgish:165:Virtual time alarm"
#define	_SGI_SMMX_s_virtalarm	"Virtual time alarm"
#define	_SGI_DMMX_s_winsizechg	":166"
#define	_SGI_MMX_s_winsizechg	"uxsgish:166"
#define	_SGI_MMMX_s_winsizechg	"uxsgish:166:Window size change"
#define	_SGI_SMMX_s_winsizechg	"Window size change"
#define	_SGI_DMMX_e_nosuchres	":167"
#define	_SGI_MMX_e_nosuchres	"uxsgish:167"
#define	_SGI_MMMX_e_nosuchres	"uxsgish:167:no such resource"
#define	_SGI_SMMX_e_nosuchres	"no such resource"
#define	_SGI_DMMX_e_badscale	":168"
#define	_SGI_MMX_e_badscale	"uxsgish:168"
#define	_SGI_MMMX_e_badscale	"uxsgish:168:Improper or unknown scale factor"
#define	_SGI_SMMX_e_badscale	"Improper or unknown scale factor"
#define	_SGI_DMMX_l_cputime	":169"
#define	_SGI_MMX_l_cputime	"uxsgish:169"
#define	_SGI_MMMX_l_cputime	"uxsgish:169:cputime      "
#define	_SGI_SMMX_l_cputime	"cputime      "
#define	_SGI_DMMX_l_filesize	":170"
#define	_SGI_MMX_l_filesize	"uxsgish:170"
#define	_SGI_MMMX_l_filesize	"uxsgish:170:filesize     "
#define	_SGI_SMMX_l_filesize	"filesize     "
#define	_SGI_DMMX_l_datasize	":171"
#define	_SGI_MMX_l_datasize	"uxsgish:171"
#define	_SGI_MMMX_l_datasize	"uxsgish:171:datasize     "
#define	_SGI_SMMX_l_datasize	"datasize     "
#define	_SGI_DMMX_l_stacksize	":172"
#define	_SGI_MMX_l_stacksize	"uxsgish:172"
#define	_SGI_MMMX_l_stacksize	"uxsgish:172:stacksize    "
#define	_SGI_SMMX_l_stacksize	"stacksize    "
#define	_SGI_DMMX_l_coredumpsize	":173"
#define	_SGI_MMX_l_coredumpsize	"uxsgish:173"
#define	_SGI_MMMX_l_coredumpsize	"uxsgish:173:coredumpsize "
#define	_SGI_SMMX_l_coredumpsize	"coredumpsize "
#define	_SGI_DMMX_l_memoryuse	":174"
#define	_SGI_MMX_l_memoryuse	"uxsgish:174"
#define	_SGI_MMMX_l_memoryuse	"uxsgish:174:memoryuse    "
#define	_SGI_SMMX_l_memoryuse	"memoryuse    "
#define	_SGI_DMMX_l_descriptors	":175"
#define	_SGI_MMX_l_descriptors	"uxsgish:175"
#define	_SGI_MMMX_l_descriptors	"uxsgish:175:descriptors  "
#define	_SGI_SMMX_l_descriptors	"descriptors  "
#define	_SGI_DMMX_l_vmemory	":176"
#define	_SGI_MMX_l_vmemory	"uxsgish:176"
#define	_SGI_MMMX_l_vmemory	"uxsgish:176:vmemory      "
#define	_SGI_SMMX_l_vmemory	"vmemory      "
#define	_SGI_DMMX_sc_seconds	":177"
#define	_SGI_MMX_sc_seconds	"uxsgish:177"
#define	_SGI_MMMX_sc_seconds	"uxsgish:177:seconds"
#define	_SGI_SMMX_sc_seconds	"seconds"
#define	_SGI_DMMX_sc_kbytes	":178"
#define	_SGI_MMX_sc_kbytes	"uxsgish:178"
#define	_SGI_MMMX_sc_kbytes	"uxsgish:178:kbytes"
#define	_SGI_SMMX_sc_kbytes	"kbytes"
#define	_SGI_DMMX_sc_hours	":179"
#define	_SGI_MMX_sc_hours	"uxsgish:179"
#define	_SGI_MMMX_sc_hours	"uxsgish:179:hours"
#define	_SGI_SMMX_sc_hours	"hours"
#define	_SGI_DMMX_sc_minutes	":180"
#define	_SGI_MMX_sc_minutes	"uxsgish:180"
#define	_SGI_MMMX_sc_minutes	"uxsgish:180:minutes"
#define	_SGI_SMMX_sc_minutes	"minutes"
#define	_SGI_DMMX_sc_megabytes	":181"
#define	_SGI_MMX_sc_megabytes	"uxsgish:181"
#define	_SGI_MMMX_sc_megabytes	"uxsgish:181:megabytes"
#define	_SGI_SMMX_sc_megabytes	"megabytes"
#define	_SGI_DMMX_e_cant	":182"
#define	_SGI_MMX_e_cant	"uxsgish:182"
#define	_SGI_MMMX_e_cant	"uxsgish:182:: Can't "
#define	_SGI_SMMX_e_cant	": Can't "
#define	_SGI_DMMX_e_remove	":183"
#define	_SGI_MMX_e_remove	"uxsgish:183"
#define	_SGI_MMMX_e_remove	"uxsgish:183:remove "
#define	_SGI_SMMX_e_remove	"remove "
#define	_SGI_DMMX_e_set	":184"
#define	_SGI_MMX_e_set	"uxsgish:184"
#define	_SGI_MMMX_e_set	"uxsgish:184:set "
#define	_SGI_SMMX_e_set	"set "
#define	_SGI_DMMX_e_hard	":185"
#define	_SGI_MMX_e_hard	"uxsgish:185"
#define	_SGI_MMMX_e_hard	"uxsgish:185:hard "
#define	_SGI_SMMX_e_hard	"hard "
#define	_SGI_DMMX_e_limit	":186"
#define	_SGI_MMX_e_limit	"uxsgish:186"
#define	_SGI_MMMX_e_limit	"uxsgish:186:limit"
#define	_SGI_SMMX_e_limit	"limit"
#define	_SGI_DMMX_e_write	":187"
#define	_SGI_MMX_e_write	"uxsgish:187"
#define	_SGI_MMMX_e_write	"uxsgish:187:write"
#define	_SGI_SMMX_e_write	"write"
#define	_SGI_DMMX_r_concurrency	":188"
#define	_SGI_MMX_r_concurrency	"uxsgish:188"
#define	_SGI_MMMX_r_concurrency	"uxsgish:188:concurrency(threads)"
#define	_SGI_SMMX_r_concurrency	"concurrency(threads)"
#define	_SGI_DMMX_l_threads	":189"
#define	_SGI_MMX_l_threads	"uxsgish:189"
#define	_SGI_MMMX_l_threads	"uxsgish:189:threads  "
#define	_SGI_SMMX_l_threads	"threads  "
#define	_SGI_DMMX_e_malloc_freejobs	":190"
#define	_SGI_MMX_e_malloc_freejobs	"uxsgish:190"
#define	_SGI_MMMX_e_malloc_freejobs	"uxsgish:190:malloc failed for freejobs list"
#define	_SGI_SMMX_e_malloc_freejobs	"malloc failed for freejobs list"
#define	_SGI_DMMX_e_jobs	":191"
#define	_SGI_MMX_e_jobs	"uxsgish:191"
#define	_SGI_MMMX_e_jobs	"uxsgish:191:too many jobs"
#define	_SGI_SMMX_e_jobs	"too many jobs"
