#! smake
# generate sendmail for SVR3
#
# "$Header: /proj/irix6.5m/isms/eoe/cmd/sendmail/RCS/Makefile,v 1.4 1997/05/09 21:21:45 mende Exp $"

include	$(ROOT)/usr/include/make/commondefs


default clean clobber install:
	cd include; $(MAKE) $@
	cd src; $(MAKE) $@
	cd lib; $(MAKE) $@

exports headers:


