#!smake

DEPTH=../

include $(ROOT)/usr/include/make/commondefs

# This defines CATNAME as the directory name
# and then defines TARGETS as CATNAME
include $(DEPTH)/catalogdefs


# Defines default, install and headers
include $(CATALOGRULES)

include $(COMMONRULES)

