#include <mkmsgs.h>
#define	_MSG_NAWK_UNKNOWN_TYPE_MSG_NUM	1
#define	_MSG_NAWK_UNKNOWN_TYPE_MSG_NUM_STR	":1"
#define	_MSG_NAWK_UNKNOWN_TYPE_CAT_NUM_STR	"uxawk:1"
#define	_MSG_NAWK_UNKNOWN_TYPE_DEF_MSG	"Unknown type %d in %s"
#define	_MSG_NAWK_UNKNOWN_TYPE_CAT_NUM_STR_DEF_MSG	"uxawk:1:Unknown type %d in %s"
#define	_MSG_NAWK_UNKNOWN_TYPE_MSG_NUM_STR_DEF_MSG	":1:Unknown type %d in %s"
#define	_MSG_NAWK_UNKNOWN_TYPE_FILE_CAT_NUM	uxawk:1
#define	_SGI_DNAWK_UNKNOWN_TYPE	":1"
#define	_SGI_NAWK_UNKNOWN_TYPE	"uxawk:1"
#define	_SGI_MNAWK_UNKNOWN_TYPE	"uxawk:1:Unknown type %d in %s"
#define	_SGI_SNAWK_UNKNOWN_TYPE	"Unknown type %d in %s"
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_MSG_NUM	2
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_MSG_NUM_STR	":2"
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_CAT_NUM_STR	"uxawk:2"
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_DEF_MSG	"Character class too big"
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_CAT_NUM_STR_DEF_MSG	"uxawk:2:Character class too big"
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_MSG_NUM_STR_DEF_MSG	":2:Character class too big"
#define	_MSG_NAWK_CHAR_CLASS_TOO_BIG_FILE_CAT_NUM	uxawk:2
#define	_SGI_DNAWK_CHAR_CLASS_TOO_BIG	":2"
#define	_SGI_NAWK_CHAR_CLASS_TOO_BIG	"uxawk:2"
#define	_SGI_MNAWK_CHAR_CLASS_TOO_BIG	"uxawk:2:Character class too big"
#define	_SGI_SNAWK_CHAR_CLASS_TOO_BIG	"Character class too big"
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_MSG_NUM	3
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_MSG_NUM_STR	":3"
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_CAT_NUM_STR	"uxawk:3"
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_DEF_MSG	"Syntax error in regular expression %s at %s"
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_CAT_NUM_STR_DEF_MSG	"uxawk:3:Syntax error in regular expression %s at %s"
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_MSG_NUM_STR_DEF_MSG	":3:Syntax error in regular expression %s at %s"
#define	_MSG_NAWK_SYNTAX_ERR_IN_REG_EXPSN_FILE_CAT_NUM	uxawk:3
#define	_SGI_DNAWK_SYNTAX_ERR_IN_REG_EXPSN	":3"
#define	_SGI_NAWK_SYNTAX_ERR_IN_REG_EXPSN	"uxawk:3"
#define	_SGI_MNAWK_SYNTAX_ERR_IN_REG_EXPSN	"uxawk:3:Syntax error in regular expression %s at %s"
#define	_SGI_SNAWK_SYNTAX_ERR_IN_REG_EXPSN	"Syntax error in regular expression %s at %s"
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_MSG_NUM	4
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_MSG_NUM_STR	":4"
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_CAT_NUM_STR	"uxawk:4"
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_DEF_MSG	"Nonterminated character class %s"
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_CAT_NUM_STR_DEF_MSG	"uxawk:4:Nonterminated character class %s"
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_MSG_NUM_STR_DEF_MSG	":4:Nonterminated character class %s"
#define	_MSG_NAWK_NON_TERMINATED_CHAR_CLASS_FILE_CAT_NUM	uxawk:4
#define	_SGI_DNAWK_NON_TERMINATED_CHAR_CLASS	":4"
#define	_SGI_NAWK_NON_TERMINATED_CHAR_CLASS	"uxawk:4"
#define	_SGI_MNAWK_NON_TERMINATED_CHAR_CLASS	"uxawk:4:Nonterminated character class %s"
#define	_SGI_SNAWK_NON_TERMINATED_CHAR_CLASS	"Nonterminated character class %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_MSG_NUM	5
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_MSG_NUM_STR	":5"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_CAT_NUM_STR	"uxawk:5"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_DEF_MSG	"Regular expression too big: out of space in %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_CAT_NUM_STR_DEF_MSG	"uxawk:5:Regular expression too big: out of space in %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_MSG_NUM_STR_DEF_MSG	":5:Regular expression too big: out of space in %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR_FILE_CAT_NUM	uxawk:5
#define	_SGI_DNAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR	":5"
#define	_SGI_NAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR	"uxawk:5"
#define	_SGI_MNAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR	"uxawk:5:Regular expression too big: out of space in %s"
#define	_SGI_SNAWK_REG_EXP_TOO_BIG_OUT_OF_SPACE_IN_STR	"Regular expression too big: out of space in %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_MSG_NUM	6
#define	_MSG_NAWK_REG_EXP_TOO_BIG_MSG_NUM_STR	":6"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_CAT_NUM_STR	"uxawk:6"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_DEF_MSG	"Regular expression too big: %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_CAT_NUM_STR_DEF_MSG	"uxawk:6:Regular expression too big: %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_MSG_NUM_STR_DEF_MSG	":6:Regular expression too big: %s"
#define	_MSG_NAWK_REG_EXP_TOO_BIG_FILE_CAT_NUM	uxawk:6
#define	_SGI_DNAWK_REG_EXP_TOO_BIG	":6"
#define	_SGI_NAWK_REG_EXP_TOO_BIG	"uxawk:6"
#define	_SGI_MNAWK_REG_EXP_TOO_BIG	"uxawk:6:Regular expression too big: %s"
#define	_SGI_SNAWK_REG_EXP_TOO_BIG	"Regular expression too big: %s"
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_MSG_NUM	7
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_MSG_NUM_STR	":7"
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_CAT_NUM_STR	"uxawk:7"
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_DEF_MSG	"Follow set overflow"
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_CAT_NUM_STR_DEF_MSG	"uxawk:7:Follow set overflow"
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_MSG_NUM_STR_DEF_MSG	":7:Follow set overflow"
#define	_MSG_NAWK_FOLLOW_SET_OVERFLOW_FILE_CAT_NUM	uxawk:7
#define	_SGI_DNAWK_FOLLOW_SET_OVERFLOW	":7"
#define	_SGI_NAWK_FOLLOW_SET_OVERFLOW	"uxawk:7"
#define	_SGI_MNAWK_FOLLOW_SET_OVERFLOW	"uxawk:7:Follow set overflow"
#define	_SGI_SNAWK_FOLLOW_SET_OVERFLOW	"Follow set overflow"
#define	_MSG_NAWK_EMPTY_REG_EXP_MSG_NUM	8
#define	_MSG_NAWK_EMPTY_REG_EXP_MSG_NUM_STR	":8"
#define	_MSG_NAWK_EMPTY_REG_EXP_CAT_NUM_STR	"uxawk:8"
#define	_MSG_NAWK_EMPTY_REG_EXP_DEF_MSG	"Empty regular expression"
#define	_MSG_NAWK_EMPTY_REG_EXP_CAT_NUM_STR_DEF_MSG	"uxawk:8:Empty regular expression"
#define	_MSG_NAWK_EMPTY_REG_EXP_MSG_NUM_STR_DEF_MSG	":8:Empty regular expression"
#define	_MSG_NAWK_EMPTY_REG_EXP_FILE_CAT_NUM	uxawk:8
#define	_SGI_DNAWK_EMPTY_REG_EXP	":8"
#define	_SGI_NAWK_EMPTY_REG_EXP	"uxawk:8"
#define	_SGI_MNAWK_EMPTY_REG_EXP	"uxawk:8:Empty regular expression"
#define	_SGI_SNAWK_EMPTY_REG_EXP	"Empty regular expression"
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_MSG_NUM	9
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_MSG_NUM_STR	":9"
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_CAT_NUM_STR	"uxawk:9"
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_DEF_MSG	"Illegal primary in regular expression %s at %s"
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_CAT_NUM_STR_DEF_MSG	"uxawk:9:Illegal primary in regular expression %s at %s"
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_MSG_NUM_STR_DEF_MSG	":9:Illegal primary in regular expression %s at %s"
#define	_MSG_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP_FILE_CAT_NUM	uxawk:9
#define	_SGI_DNAWK_ILLEGAL_PRIMARY_IN_REG_EXP	":9"
#define	_SGI_NAWK_ILLEGAL_PRIMARY_IN_REG_EXP	"uxawk:9"
#define	_SGI_MNAWK_ILLEGAL_PRIMARY_IN_REG_EXP	"uxawk:9:Illegal primary in regular expression %s at %s"
#define	_SGI_SNAWK_ILLEGAL_PRIMARY_IN_REG_EXP	"Illegal primary in regular expression %s at %s"
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_MSG_NUM	10
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_MSG_NUM_STR	":10"
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_CAT_NUM_STR	"uxawk:10"
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_DEF_MSG	"Newline in character class %s..."
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_CAT_NUM_STR_DEF_MSG	"uxawk:10:Newline in character class %s..."
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_MSG_NUM_STR_DEF_MSG	":10:Newline in character class %s..."
#define	_MSG_NAWK_NL_IN_CHAR_CLASS_FILE_CAT_NUM	uxawk:10
#define	_SGI_DNAWK_NL_IN_CHAR_CLASS	":10"
#define	_SGI_NAWK_NL_IN_CHAR_CLASS	"uxawk:10"
#define	_SGI_MNAWK_NL_IN_CHAR_CLASS	"uxawk:10:Newline in character class %s..."
#define	_SGI_SNAWK_NL_IN_CHAR_CLASS	"Newline in character class %s..."
#define	_MSG_NAWK_CANNOT_OPEN_MSG_NUM	11
#define	_MSG_NAWK_CANNOT_OPEN_MSG_NUM_STR	":11"
#define	_MSG_NAWK_CANNOT_OPEN_CAT_NUM_STR	"uxawk:11"
#define	_MSG_NAWK_CANNOT_OPEN_DEF_MSG	"Cannot open %s: %s"
#define	_MSG_NAWK_CANNOT_OPEN_CAT_NUM_STR_DEF_MSG	"uxawk:11:Cannot open %s: %s"
#define	_MSG_NAWK_CANNOT_OPEN_MSG_NUM_STR_DEF_MSG	":11:Cannot open %s: %s"
#define	_MSG_NAWK_CANNOT_OPEN_FILE_CAT_NUM	uxawk:11
#define	_SGI_DNAWK_CANNOT_OPEN	":11"
#define	_SGI_NAWK_CANNOT_OPEN	"uxawk:11"
#define	_SGI_MNAWK_CANNOT_OPEN	"uxawk:11:Cannot open %s: %s"
#define	_SGI_SNAWK_CANNOT_OPEN	"Cannot open %s: %s"
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_MSG_NUM	12
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_MSG_NUM_STR	":12"
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_CAT_NUM_STR	"uxawk:12"
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_DEF_MSG	"Input record `%.20s...' too long"
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_CAT_NUM_STR_DEF_MSG	"uxawk:12:Input record `%.20s...' too long"
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_MSG_NUM_STR_DEF_MSG	":12:Input record `%.20s...' too long"
#define	_MSG_NAWK_INPUT_REC_TOO_LONG_FILE_CAT_NUM	uxawk:12
#define	_SGI_DNAWK_INPUT_REC_TOO_LONG	":12"
#define	_SGI_NAWK_INPUT_REC_TOO_LONG	"uxawk:12"
#define	_SGI_MNAWK_INPUT_REC_TOO_LONG	"uxawk:12:Input record `%.20s...' too long"
#define	_SGI_SNAWK_INPUT_REC_TOO_LONG	"Input record `%.20s...' too long"
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_MSG_NUM	13
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_MSG_NUM_STR	":13"
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_CAT_NUM_STR	"uxawk:13"
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_DEF_MSG	"Record `%.20s...' has too many fields"
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_CAT_NUM_STR_DEF_MSG	"uxawk:13:Record `%.20s...' has too many fields"
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_MSG_NUM_STR_DEF_MSG	":13:Record `%.20s...' has too many fields"
#define	_MSG_NAWK_REC_HAS_TOO_MANY_FLDS_FILE_CAT_NUM	uxawk:13
#define	_SGI_DNAWK_REC_HAS_TOO_MANY_FLDS	":13"
#define	_SGI_NAWK_REC_HAS_TOO_MANY_FLDS	"uxawk:13"
#define	_SGI_MNAWK_REC_HAS_TOO_MANY_FLDS	"uxawk:13:Record `%.20s...' has too many fields"
#define	_SGI_SNAWK_REC_HAS_TOO_MANY_FLDS	"Record `%.20s...' has too many fields"
#define	_MSG_NAWK_FIELD_IS_MSG_NUM	14
#define	_MSG_NAWK_FIELD_IS_MSG_NUM_STR	":14"
#define	_MSG_NAWK_FIELD_IS_CAT_NUM_STR	"uxawk:14"
#define	_MSG_NAWK_FIELD_IS_DEF_MSG	"field %d: |%s|\n"
#define	_MSG_NAWK_FIELD_IS_CAT_NUM_STR_DEF_MSG	"uxawk:14:field %d: |%s|\n"
#define	_MSG_NAWK_FIELD_IS_MSG_NUM_STR_DEF_MSG	":14:field %d: |%s|\n"
#define	_MSG_NAWK_FIELD_IS_FILE_CAT_NUM	uxawk:14
#define	_SGI_DNAWK_FIELD_IS	":14"
#define	_SGI_NAWK_FIELD_IS	"uxawk:14"
#define	_SGI_MNAWK_FIELD_IS	"uxawk:14:field %d: |%s|\n"
#define	_SGI_SNAWK_FIELD_IS	"field %d: |%s|\n"
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_MSG_NUM	15
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_MSG_NUM_STR	":15"
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_CAT_NUM_STR	"uxawk:15"
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_DEF_MSG	"Creating too many fields"
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_CAT_NUM_STR_DEF_MSG	"uxawk:15:Creating too many fields"
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_MSG_NUM_STR_DEF_MSG	":15:Creating too many fields"
#define	_MSG_NAWK_CREATING_TOO_MANY_FLDS_FILE_CAT_NUM	uxawk:15
#define	_SGI_DNAWK_CREATING_TOO_MANY_FLDS	":15"
#define	_SGI_NAWK_CREATING_TOO_MANY_FLDS	"uxawk:15"
#define	_SGI_MNAWK_CREATING_TOO_MANY_FLDS	"uxawk:15:Creating too many fields"
#define	_SGI_SNAWK_CREATING_TOO_MANY_FLDS	"Creating too many fields"
#define	_MSG_NAWK_BUILD_GIANT_REC_MSG_NUM	16
#define	_MSG_NAWK_BUILD_GIANT_REC_MSG_NUM_STR	":16"
#define	_MSG_NAWK_BUILD_GIANT_REC_CAT_NUM_STR	"uxawk:16"
#define	_MSG_NAWK_BUILD_GIANT_REC_DEF_MSG	"Built giant record `%.20s...'"
#define	_MSG_NAWK_BUILD_GIANT_REC_CAT_NUM_STR_DEF_MSG	"uxawk:16:Built giant record `%.20s...'"
#define	_MSG_NAWK_BUILD_GIANT_REC_MSG_NUM_STR_DEF_MSG	":16:Built giant record `%.20s...'"
#define	_MSG_NAWK_BUILD_GIANT_REC_FILE_CAT_NUM	uxawk:16
#define	_SGI_DNAWK_BUILD_GIANT_REC	":16"
#define	_SGI_NAWK_BUILD_GIANT_REC	"uxawk:16"
#define	_SGI_MNAWK_BUILD_GIANT_REC	"uxawk:16:Built giant record `%.20s...'"
#define	_SGI_SNAWK_BUILD_GIANT_REC	"Built giant record `%.20s...'"
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_MSG_NUM	17
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_MSG_NUM_STR	":17"
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_CAT_NUM_STR	"uxawk:17"
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_DEF_MSG	"Trying to access field %d"
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_CAT_NUM_STR_DEF_MSG	"uxawk:17:Trying to access field %d"
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_MSG_NUM_STR_DEF_MSG	":17:Trying to access field %d"
#define	_MSG_NAWK_TRYING_TO_ACCESS_FLD_FILE_CAT_NUM	uxawk:17
#define	_SGI_DNAWK_TRYING_TO_ACCESS_FLD	":17"
#define	_SGI_NAWK_TRYING_TO_ACCESS_FLD	"uxawk:17"
#define	_SGI_MNAWK_TRYING_TO_ACCESS_FLD	"uxawk:17:Trying to access field %d"
#define	_SGI_SNAWK_TRYING_TO_ACCESS_FLD	"Trying to access field %d"
#define	_MSG_NAWK_AT_SOURCE_LINE_MSG_NUM	18
#define	_MSG_NAWK_AT_SOURCE_LINE_MSG_NUM_STR	":18"
#define	_MSG_NAWK_AT_SOURCE_LINE_CAT_NUM_STR	"uxawk:18"
#define	_MSG_NAWK_AT_SOURCE_LINE_DEF_MSG	" at source line %d"
#define	_MSG_NAWK_AT_SOURCE_LINE_CAT_NUM_STR_DEF_MSG	"uxawk:18: at source line %d"
#define	_MSG_NAWK_AT_SOURCE_LINE_MSG_NUM_STR_DEF_MSG	":18: at source line %d"
#define	_MSG_NAWK_AT_SOURCE_LINE_FILE_CAT_NUM	uxawk:18
#define	_SGI_DNAWK_AT_SOURCE_LINE	":18"
#define	_SGI_NAWK_AT_SOURCE_LINE	"uxawk:18"
#define	_SGI_MNAWK_AT_SOURCE_LINE	"uxawk:18: at source line %d"
#define	_SGI_SNAWK_AT_SOURCE_LINE	" at source line %d"
#define	_MSG_NAWK_IN_FUNCTION_MSG_NUM	19
#define	_MSG_NAWK_IN_FUNCTION_MSG_NUM_STR	":19"
#define	_MSG_NAWK_IN_FUNCTION_CAT_NUM_STR	"uxawk:19"
#define	_MSG_NAWK_IN_FUNCTION_DEF_MSG	" in function %s"
#define	_MSG_NAWK_IN_FUNCTION_CAT_NUM_STR_DEF_MSG	"uxawk:19: in function %s"
#define	_MSG_NAWK_IN_FUNCTION_MSG_NUM_STR_DEF_MSG	":19: in function %s"
#define	_MSG_NAWK_IN_FUNCTION_FILE_CAT_NUM	uxawk:19
#define	_SGI_DNAWK_IN_FUNCTION	":19"
#define	_SGI_NAWK_IN_FUNCTION	"uxawk:19"
#define	_SGI_MNAWK_IN_FUNCTION	"uxawk:19: in function %s"
#define	_SGI_SNAWK_IN_FUNCTION	" in function %s"
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_MSG_NUM	20
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_MSG_NUM_STR	":20"
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_CAT_NUM_STR	"uxawk:20"
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_DEF_MSG	"Floating point exception"
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_CAT_NUM_STR_DEF_MSG	"uxawk:20:Floating point exception"
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_MSG_NUM_STR_DEF_MSG	":20:Floating point exception"
#define	_MSG_NAWK_FLOATING_PT_EXCEPTION_FILE_CAT_NUM	uxawk:20
#define	_SGI_DNAWK_FLOATING_PT_EXCEPTION	":20"
#define	_SGI_NAWK_FLOATING_PT_EXCEPTION	"uxawk:20"
#define	_SGI_MNAWK_FLOATING_PT_EXCEPTION	"uxawk:20:Floating point exception"
#define	_SGI_SNAWK_FLOATING_PT_EXCEPTION	"Floating point exception"
#define	_MSG_NAWK_MISSING_CHAR_MSG_NUM	21
#define	_MSG_NAWK_MISSING_CHAR_MSG_NUM_STR	":21"
#define	_MSG_NAWK_MISSING_CHAR_CAT_NUM_STR	"uxawk:21"
#define	_MSG_NAWK_MISSING_CHAR_DEF_MSG	"Missing %c\n"
#define	_MSG_NAWK_MISSING_CHAR_CAT_NUM_STR_DEF_MSG	"uxawk:21:Missing %c\n"
#define	_MSG_NAWK_MISSING_CHAR_MSG_NUM_STR_DEF_MSG	":21:Missing %c\n"
#define	_MSG_NAWK_MISSING_CHAR_FILE_CAT_NUM	uxawk:21
#define	_SGI_DNAWK_MISSING_CHAR	":21"
#define	_SGI_NAWK_MISSING_CHAR	"uxawk:21"
#define	_SGI_MNAWK_MISSING_CHAR	"uxawk:21:Missing %c\n"
#define	_SGI_SNAWK_MISSING_CHAR	"Missing %c\n"
#define	_MSG_NAWK_MISSING_NCHARS_MSG_NUM	22
#define	_MSG_NAWK_MISSING_NCHARS_MSG_NUM_STR	":22"
#define	_MSG_NAWK_MISSING_NCHARS_CAT_NUM_STR	"uxawk:22"
#define	_MSG_NAWK_MISSING_NCHARS_DEF_MSG	"%d missing %c's\n"
#define	_MSG_NAWK_MISSING_NCHARS_CAT_NUM_STR_DEF_MSG	"uxawk:22:%d missing %c's\n"
#define	_MSG_NAWK_MISSING_NCHARS_MSG_NUM_STR_DEF_MSG	":22:%d missing %c's\n"
#define	_MSG_NAWK_MISSING_NCHARS_FILE_CAT_NUM	uxawk:22
#define	_SGI_DNAWK_MISSING_NCHARS	":22"
#define	_SGI_NAWK_MISSING_NCHARS	"uxawk:22"
#define	_SGI_MNAWK_MISSING_NCHARS	"uxawk:22:%d missing %c's\n"
#define	_SGI_SNAWK_MISSING_NCHARS	"%d missing %c's\n"
#define	_MSG_NAWK_EXTRA_CHAR_NL_MSG_NUM	23
#define	_MSG_NAWK_EXTRA_CHAR_NL_MSG_NUM_STR	":23"
#define	_MSG_NAWK_EXTRA_CHAR_NL_CAT_NUM_STR	"uxawk:23"
#define	_MSG_NAWK_EXTRA_CHAR_NL_DEF_MSG	"Extra %c\n"
#define	_MSG_NAWK_EXTRA_CHAR_NL_CAT_NUM_STR_DEF_MSG	"uxawk:23:Extra %c\n"
#define	_MSG_NAWK_EXTRA_CHAR_NL_MSG_NUM_STR_DEF_MSG	":23:Extra %c\n"
#define	_MSG_NAWK_EXTRA_CHAR_NL_FILE_CAT_NUM	uxawk:23
#define	_SGI_DNAWK_EXTRA_CHAR_NL	":23"
#define	_SGI_NAWK_EXTRA_CHAR_NL	"uxawk:23"
#define	_SGI_MNAWK_EXTRA_CHAR_NL	"uxawk:23:Extra %c\n"
#define	_SGI_SNAWK_EXTRA_CHAR_NL	"Extra %c\n"
#define	_MSG_NAWK_EXTRA_NCHARS_MSG_NUM	24
#define	_MSG_NAWK_EXTRA_NCHARS_MSG_NUM_STR	":24"
#define	_MSG_NAWK_EXTRA_NCHARS_CAT_NUM_STR	"uxawk:24"
#define	_MSG_NAWK_EXTRA_NCHARS_DEF_MSG	"%d extra %c's\n"
#define	_MSG_NAWK_EXTRA_NCHARS_CAT_NUM_STR_DEF_MSG	"uxawk:24:%d extra %c's\n"
#define	_MSG_NAWK_EXTRA_NCHARS_MSG_NUM_STR_DEF_MSG	":24:%d extra %c's\n"
#define	_MSG_NAWK_EXTRA_NCHARS_FILE_CAT_NUM	uxawk:24
#define	_SGI_DNAWK_EXTRA_NCHARS	":24"
#define	_SGI_NAWK_EXTRA_NCHARS	"uxawk:24"
#define	_SGI_MNAWK_EXTRA_NCHARS	"uxawk:24:%d extra %c's\n"
#define	_SGI_SNAWK_EXTRA_NCHARS	"%d extra %c's\n"
#define	_MSG_NAWK_INPUT_REC_NO_MSG_NUM	25
#define	_MSG_NAWK_INPUT_REC_NO_MSG_NUM_STR	":25"
#define	_MSG_NAWK_INPUT_REC_NO_CAT_NUM_STR	"uxawk:25"
#define	_MSG_NAWK_INPUT_REC_NO_DEF_MSG	"Input record number %g"
#define	_MSG_NAWK_INPUT_REC_NO_CAT_NUM_STR_DEF_MSG	"uxawk:25:Input record number %g"
#define	_MSG_NAWK_INPUT_REC_NO_MSG_NUM_STR_DEF_MSG	":25:Input record number %g"
#define	_MSG_NAWK_INPUT_REC_NO_FILE_CAT_NUM	uxawk:25
#define	_SGI_DNAWK_INPUT_REC_NO	":25"
#define	_SGI_NAWK_INPUT_REC_NO	"uxawk:25"
#define	_SGI_MNAWK_INPUT_REC_NO	"uxawk:25:Input record number %g"
#define	_SGI_SNAWK_INPUT_REC_NO	"Input record number %g"
#define	_MSG_NAWK_FILE_NAME_MSG_NUM	26
#define	_MSG_NAWK_FILE_NAME_MSG_NUM_STR	":26"
#define	_MSG_NAWK_FILE_NAME_CAT_NUM_STR	"uxawk:26"
#define	_MSG_NAWK_FILE_NAME_DEF_MSG	", file %s"
#define	_MSG_NAWK_FILE_NAME_CAT_NUM_STR_DEF_MSG	"uxawk:26:, file %s"
#define	_MSG_NAWK_FILE_NAME_MSG_NUM_STR_DEF_MSG	":26:, file %s"
#define	_MSG_NAWK_FILE_NAME_FILE_CAT_NUM	uxawk:26
#define	_SGI_DNAWK_FILE_NAME	":26"
#define	_SGI_NAWK_FILE_NAME	"uxawk:26"
#define	_SGI_MNAWK_FILE_NAME	"uxawk:26:, file %s"
#define	_SGI_SNAWK_FILE_NAME	", file %s"
#define	_MSG_NAWK_SOURCE_LINE_NO_MSG_NUM	27
#define	_MSG_NAWK_SOURCE_LINE_NO_MSG_NUM_STR	":27"
#define	_MSG_NAWK_SOURCE_LINE_NO_CAT_NUM_STR	"uxawk:27"
#define	_MSG_NAWK_SOURCE_LINE_NO_DEF_MSG	"Source line number %d\n"
#define	_MSG_NAWK_SOURCE_LINE_NO_CAT_NUM_STR_DEF_MSG	"uxawk:27:Source line number %d\n"
#define	_MSG_NAWK_SOURCE_LINE_NO_MSG_NUM_STR_DEF_MSG	":27:Source line number %d\n"
#define	_MSG_NAWK_SOURCE_LINE_NO_FILE_CAT_NUM	uxawk:27
#define	_SGI_DNAWK_SOURCE_LINE_NO	":27"
#define	_SGI_NAWK_SOURCE_LINE_NO	"uxawk:27"
#define	_SGI_MNAWK_SOURCE_LINE_NO	"uxawk:27:Source line number %d\n"
#define	_SGI_SNAWK_SOURCE_LINE_NO	"Source line number %d\n"
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_MSG_NUM	28
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_MSG_NUM_STR	":28"
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_CAT_NUM_STR	"uxawk:28"
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_DEF_MSG	"Context is\n\t"
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_CAT_NUM_STR_DEF_MSG	"uxawk:28:Context is\n\t"
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_MSG_NUM_STR_DEF_MSG	":28:Context is\n\t"
#define	_MSG_NAWK_CONTEXT_IS_NL_TAB_FILE_CAT_NUM	uxawk:28
#define	_SGI_DNAWK_CONTEXT_IS_NL_TAB	":28"
#define	_SGI_NAWK_CONTEXT_IS_NL_TAB	"uxawk:28"
#define	_SGI_MNAWK_CONTEXT_IS_NL_TAB	"uxawk:28:Context is\n\t"
#define	_SGI_SNAWK_CONTEXT_IS_NL_TAB	"Context is\n\t"
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_MSG_NUM	29
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_MSG_NUM_STR	":29"
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_CAT_NUM_STR	"uxawk:29"
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_DEF_MSG	"%s argument out of domain"
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_CAT_NUM_STR_DEF_MSG	"uxawk:29:%s argument out of domain"
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_MSG_NUM_STR_DEF_MSG	":29:%s argument out of domain"
#define	_MSG_NAWK_ARG_OUT_OF_DOMAIN_FILE_CAT_NUM	uxawk:29
#define	_SGI_DNAWK_ARG_OUT_OF_DOMAIN	":29"
#define	_SGI_NAWK_ARG_OUT_OF_DOMAIN	"uxawk:29"
#define	_SGI_MNAWK_ARG_OUT_OF_DOMAIN	"uxawk:29:%s argument out of domain"
#define	_SGI_SNAWK_ARG_OUT_OF_DOMAIN	"%s argument out of domain"
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_MSG_NUM	30
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_MSG_NUM_STR	":30"
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_CAT_NUM_STR	"uxawk:30"
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_DEF_MSG	"%s result out of range"
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_CAT_NUM_STR_DEF_MSG	"uxawk:30:%s result out of range"
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_MSG_NUM_STR_DEF_MSG	":30:%s result out of range"
#define	_MSG_NAWK_RESULT_OUT_OF_RANGE_FILE_CAT_NUM	uxawk:30
#define	_SGI_DNAWK_RESULT_OUT_OF_RANGE	":30"
#define	_SGI_NAWK_RESULT_OUT_OF_RANGE	"uxawk:30"
#define	_SGI_MNAWK_RESULT_OUT_OF_RANGE	"uxawk:30:%s result out of range"
#define	_SGI_SNAWK_RESULT_OUT_OF_RANGE	"%s result out of range"
#define	_MSG_NAWK_VER_OCT_11_1989_MSG_NUM	31
#define	_MSG_NAWK_VER_OCT_11_1989_MSG_NUM_STR	":31"
#define	_MSG_NAWK_VER_OCT_11_1989_CAT_NUM_STR	"uxawk:31"
#define	_MSG_NAWK_VER_OCT_11_1989_DEF_MSG	"version Oct 11, 1989"
#define	_MSG_NAWK_VER_OCT_11_1989_CAT_NUM_STR_DEF_MSG	"uxawk:31:version Oct 11, 1989"
#define	_MSG_NAWK_VER_OCT_11_1989_MSG_NUM_STR_DEF_MSG	":31:version Oct 11, 1989"
#define	_MSG_NAWK_VER_OCT_11_1989_FILE_CAT_NUM	uxawk:31
#define	_SGI_DNAWK_VER_OCT_11_1989	":31"
#define	_SGI_NAWK_VER_OCT_11_1989	"uxawk:31"
#define	_SGI_MNAWK_VER_OCT_11_1989	"uxawk:31:version Oct 11, 1989"
#define	_SGI_SNAWK_VER_OCT_11_1989	"version Oct 11, 1989"
#define	_MSG_NAWK_INCORRECT_USAGE_MSG_NUM	32
#define	_MSG_NAWK_INCORRECT_USAGE_MSG_NUM_STR	":32"
#define	_MSG_NAWK_INCORRECT_USAGE_CAT_NUM_STR	"uxawk:32"
#define	_MSG_NAWK_INCORRECT_USAGE_DEF_MSG	"Incorrect usage\n"
#define	_MSG_NAWK_INCORRECT_USAGE_CAT_NUM_STR_DEF_MSG	"uxawk:32:Incorrect usage\n"
#define	_MSG_NAWK_INCORRECT_USAGE_MSG_NUM_STR_DEF_MSG	":32:Incorrect usage\n"
#define	_MSG_NAWK_INCORRECT_USAGE_FILE_CAT_NUM	uxawk:32
#define	_SGI_DNAWK_INCORRECT_USAGE	":32"
#define	_SGI_NAWK_INCORRECT_USAGE	"uxawk:32"
#define	_SGI_MNAWK_INCORRECT_USAGE	"uxawk:32:Incorrect usage\n"
#define	_SGI_SNAWK_INCORRECT_USAGE	"Incorrect usage\n"
#define	_MSG_NAWK_USAGE_MSG_MSG_NUM	33
#define	_MSG_NAWK_USAGE_MSG_MSG_NUM_STR	":33"
#define	_MSG_NAWK_USAGE_MSG_CAT_NUM_STR	"uxawk:33"
#define	_MSG_NAWK_USAGE_MSG_DEF_MSG	"Usage: %s [-f programfile | 'program'] [-Ffieldsep] [-v var=value] [files]\n"
#define	_MSG_NAWK_USAGE_MSG_CAT_NUM_STR_DEF_MSG	"uxawk:33:Usage: %s [-f programfile | 'program'] [-Ffieldsep] [-v var=value] [files]\n"
#define	_MSG_NAWK_USAGE_MSG_MSG_NUM_STR_DEF_MSG	":33:Usage: %s [-f programfile | 'program'] [-Ffieldsep] [-v var=value] [files]\n"
#define	_MSG_NAWK_USAGE_MSG_FILE_CAT_NUM	uxawk:33
#define	_SGI_DNAWK_USAGE_MSG	":33"
#define	_SGI_NAWK_USAGE_MSG	"uxawk:33"
#define	_SGI_MNAWK_USAGE_MSG	"uxawk:33:Usage: %s [-f programfile | 'program'] [-Ffieldsep] [-v var=value] [files]\n"
#define	_SGI_SNAWK_USAGE_MSG	"Usage: %s [-f programfile | 'program'] [-Ffieldsep] [-v var=value] [files]\n"
#define	_MSG_NAWK_NO_PROG_FILE_NAME_MSG_NUM	34
#define	_MSG_NAWK_NO_PROG_FILE_NAME_MSG_NUM_STR	":34"
#define	_MSG_NAWK_NO_PROG_FILE_NAME_CAT_NUM_STR	"uxawk:34"
#define	_MSG_NAWK_NO_PROG_FILE_NAME_DEF_MSG	"No program filename"
#define	_MSG_NAWK_NO_PROG_FILE_NAME_CAT_NUM_STR_DEF_MSG	"uxawk:34:No program filename"
#define	_MSG_NAWK_NO_PROG_FILE_NAME_MSG_NUM_STR_DEF_MSG	":34:No program filename"
#define	_MSG_NAWK_NO_PROG_FILE_NAME_FILE_CAT_NUM	uxawk:34
#define	_SGI_DNAWK_NO_PROG_FILE_NAME	":34"
#define	_SGI_NAWK_NO_PROG_FILE_NAME	"uxawk:34"
#define	_SGI_MNAWK_NO_PROG_FILE_NAME	"uxawk:34:No program filename"
#define	_SGI_SNAWK_NO_PROG_FILE_NAME	"No program filename"
#define	_MSG_NAWK_FS_EMPTY_MSG_NUM	35
#define	_MSG_NAWK_FS_EMPTY_MSG_NUM_STR	":35"
#define	_MSG_NAWK_FS_EMPTY_CAT_NUM_STR	"uxawk:35"
#define	_MSG_NAWK_FS_EMPTY_DEF_MSG	"Field separator FS is empty"
#define	_MSG_NAWK_FS_EMPTY_CAT_NUM_STR_DEF_MSG	"uxawk:35:Field separator FS is empty"
#define	_MSG_NAWK_FS_EMPTY_MSG_NUM_STR_DEF_MSG	":35:Field separator FS is empty"
#define	_MSG_NAWK_FS_EMPTY_FILE_CAT_NUM	uxawk:35
#define	_SGI_DNAWK_FS_EMPTY	":35"
#define	_SGI_NAWK_FS_EMPTY	"uxawk:35"
#define	_SGI_MNAWK_FS_EMPTY	"uxawk:35:Field separator FS is empty"
#define	_SGI_SNAWK_FS_EMPTY	"Field separator FS is empty"
#define	_MSG_NAWK_UNKNOWN_OPTION_MSG_NUM	36
#define	_MSG_NAWK_UNKNOWN_OPTION_MSG_NUM_STR	":36"
#define	_MSG_NAWK_UNKNOWN_OPTION_CAT_NUM_STR	"uxawk:36"
#define	_MSG_NAWK_UNKNOWN_OPTION_DEF_MSG	"Unknown option %s ignored\n"
#define	_MSG_NAWK_UNKNOWN_OPTION_CAT_NUM_STR_DEF_MSG	"uxawk:36:Unknown option %s ignored\n"
#define	_MSG_NAWK_UNKNOWN_OPTION_MSG_NUM_STR_DEF_MSG	":36:Unknown option %s ignored\n"
#define	_MSG_NAWK_UNKNOWN_OPTION_FILE_CAT_NUM	uxawk:36
#define	_SGI_DNAWK_UNKNOWN_OPTION	":36"
#define	_SGI_NAWK_UNKNOWN_OPTION	"uxawk:36"
#define	_SGI_MNAWK_UNKNOWN_OPTION	"uxawk:36:Unknown option %s ignored\n"
#define	_SGI_SNAWK_UNKNOWN_OPTION	"Unknown option %s ignored\n"
#define	_MSG_NAWK_NO_PROG_GIVEN_MSG_NUM	37
#define	_MSG_NAWK_NO_PROG_GIVEN_MSG_NUM_STR	":37"
#define	_MSG_NAWK_NO_PROG_GIVEN_CAT_NUM_STR	"uxawk:37"
#define	_MSG_NAWK_NO_PROG_GIVEN_DEF_MSG	"No program given"
#define	_MSG_NAWK_NO_PROG_GIVEN_CAT_NUM_STR_DEF_MSG	"uxawk:37:No program given"
#define	_MSG_NAWK_NO_PROG_GIVEN_MSG_NUM_STR_DEF_MSG	":37:No program given"
#define	_MSG_NAWK_NO_PROG_GIVEN_FILE_CAT_NUM	uxawk:37
#define	_SGI_DNAWK_NO_PROG_GIVEN	":37"
#define	_SGI_NAWK_NO_PROG_GIVEN	"uxawk:37"
#define	_SGI_MNAWK_NO_PROG_GIVEN	"uxawk:37:No program given"
#define	_SGI_SNAWK_NO_PROG_GIVEN	"No program given"
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_MSG_NUM	38
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_MSG_NUM_STR	":38"
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_CAT_NUM_STR	"uxawk:38"
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_DEF_MSG	"%s is a function, not an array"
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_CAT_NUM_STR_DEF_MSG	"uxawk:38:%s is a function, not an array"
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_MSG_NUM_STR_DEF_MSG	":38:%s is a function, not an array"
#define	_MSG_NAWK_NOT_FUNC_AN_ARRAY_FILE_CAT_NUM	uxawk:38
#define	_SGI_DNAWK_NOT_FUNC_AN_ARRAY	":38"
#define	_SGI_NAWK_NOT_FUNC_AN_ARRAY	"uxawk:38"
#define	_SGI_MNAWK_NOT_FUNC_AN_ARRAY	"uxawk:38:%s is a function, not an array"
#define	_SGI_SNAWK_NOT_FUNC_AN_ARRAY	"%s is a function, not an array"
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_MSG_NUM	39
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_MSG_NUM_STR	":39"
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_CAT_NUM_STR	"uxawk:39"
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_DEF_MSG	"`%s' is an array name and a function name"
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_CAT_NUM_STR_DEF_MSG	"uxawk:39:`%s' is an array name and a function name"
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_MSG_NUM_STR_DEF_MSG	":39:`%s' is an array name and a function name"
#define	_MSG_NAWK_ARRAY_AND_FUNC_NAME_FILE_CAT_NUM	uxawk:39
#define	_SGI_DNAWK_ARRAY_AND_FUNC_NAME	":39"
#define	_SGI_NAWK_ARRAY_AND_FUNC_NAME	"uxawk:39"
#define	_SGI_MNAWK_ARRAY_AND_FUNC_NAME	"uxawk:39:`%s' is an array name and a function name"
#define	_SGI_SNAWK_ARRAY_AND_FUNC_NAME	"`%s' is an array name and a function name"
#define	_MSG_NAWK_RESULT_TOO_BIG_MSG_NUM	40
#define	_MSG_NAWK_RESULT_TOO_BIG_MSG_NUM_STR	":40"
#define	_MSG_NAWK_RESULT_TOO_BIG_CAT_NUM_STR	"uxawk:40"
#define	_MSG_NAWK_RESULT_TOO_BIG_DEF_MSG	"%s() result %.20s too big"
#define	_MSG_NAWK_RESULT_TOO_BIG_CAT_NUM_STR_DEF_MSG	"uxawk:40:%s() result %.20s too big"
#define	_MSG_NAWK_RESULT_TOO_BIG_MSG_NUM_STR_DEF_MSG	":40:%s() result %.20s too big"
#define	_MSG_NAWK_RESULT_TOO_BIG_FILE_CAT_NUM	uxawk:40
#define	_SGI_DNAWK_RESULT_TOO_BIG	":40"
#define	_SGI_NAWK_RESULT_TOO_BIG	"uxawk:40"
#define	_SGI_MNAWK_RESULT_TOO_BIG	"uxawk:40:%s() result %.20s too big"
#define	_SGI_SNAWK_RESULT_TOO_BIG	"%s() result %.20s too big"
#define	_MSG_NAWK_NOT_AN_ARRAY_MSG_NUM	41
#define	_MSG_NAWK_NOT_AN_ARRAY_MSG_NUM_STR	":41"
#define	_MSG_NAWK_NOT_AN_ARRAY_CAT_NUM_STR	"uxawk:41"
#define	_MSG_NAWK_NOT_AN_ARRAY_DEF_MSG	"%s is not an array"
#define	_MSG_NAWK_NOT_AN_ARRAY_CAT_NUM_STR_DEF_MSG	"uxawk:41:%s is not an array"
#define	_MSG_NAWK_NOT_AN_ARRAY_MSG_NUM_STR_DEF_MSG	":41:%s is not an array"
#define	_MSG_NAWK_NOT_AN_ARRAY_FILE_CAT_NUM	uxawk:41
#define	_SGI_DNAWK_NOT_AN_ARRAY	":41"
#define	_SGI_NAWK_NOT_AN_ARRAY	"uxawk:41"
#define	_SGI_MNAWK_NOT_AN_ARRAY	"uxawk:41:%s is not an array"
#define	_SGI_SNAWK_NOT_AN_ARRAY	"%s is not an array"
#define	_MSG_NAWK_IO_ERR_OCCURRED_MSG_NUM	42
#define	_MSG_NAWK_IO_ERR_OCCURRED_MSG_NUM_STR	":42"
#define	_MSG_NAWK_IO_ERR_OCCURRED_CAT_NUM_STR	"uxawk:42"
#define	_MSG_NAWK_IO_ERR_OCCURRED_DEF_MSG	"I/O error occurred on %s"
#define	_MSG_NAWK_IO_ERR_OCCURRED_CAT_NUM_STR_DEF_MSG	"uxawk:42:I/O error occurred on %s"
#define	_MSG_NAWK_IO_ERR_OCCURRED_MSG_NUM_STR_DEF_MSG	":42:I/O error occurred on %s"
#define	_MSG_NAWK_IO_ERR_OCCURRED_FILE_CAT_NUM	uxawk:42
#define	_SGI_DNAWK_IO_ERR_OCCURRED	":42"
#define	_SGI_NAWK_IO_ERR_OCCURRED	"uxawk:42"
#define	_SGI_MNAWK_IO_ERR_OCCURRED	"uxawk:42:I/O error occurred on %s"
#define	_SGI_SNAWK_IO_ERR_OCCURRED	"I/O error occurred on %s"
#define	_MSG_NAWK_ILLEGAL_STMT_MSG_NUM	43
#define	_MSG_NAWK_ILLEGAL_STMT_MSG_NUM_STR	":43"
#define	_MSG_NAWK_ILLEGAL_STMT_CAT_NUM_STR	"uxawk:43"
#define	_MSG_NAWK_ILLEGAL_STMT_DEF_MSG	"Illegal statement"
#define	_MSG_NAWK_ILLEGAL_STMT_CAT_NUM_STR_DEF_MSG	"uxawk:43:Illegal statement"
#define	_MSG_NAWK_ILLEGAL_STMT_MSG_NUM_STR_DEF_MSG	":43:Illegal statement"
#define	_MSG_NAWK_ILLEGAL_STMT_FILE_CAT_NUM	uxawk:43
#define	_SGI_DNAWK_ILLEGAL_STMT	":43"
#define	_SGI_NAWK_ILLEGAL_STMT	"uxawk:43"
#define	_SGI_MNAWK_ILLEGAL_STMT	"uxawk:43:Illegal statement"
#define	_SGI_SNAWK_ILLEGAL_STMT	"Illegal statement"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_MSG_NUM	44
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_MSG_NUM_STR	":44"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_CAT_NUM_STR	"uxawk:44"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_DEF_MSG	"Illegal break, continue or next from BEGIN"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_CAT_NUM_STR_DEF_MSG	"uxawk:44:Illegal break, continue or next from BEGIN"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_MSG_NUM_STR_DEF_MSG	":44:Illegal break, continue or next from BEGIN"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN_FILE_CAT_NUM	uxawk:44
#define	_SGI_DNAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN	":44"
#define	_SGI_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN	"uxawk:44"
#define	_SGI_MNAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN	"uxawk:44:Illegal break, continue or next from BEGIN"
#define	_SGI_SNAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_BEGIN	"Illegal break, continue or next from BEGIN"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_MSG_NUM	45
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_MSG_NUM_STR	":45"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_CAT_NUM_STR	"uxawk:45"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_DEF_MSG	"Illegal break or next from END"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_CAT_NUM_STR_DEF_MSG	"uxawk:45:Illegal break or next from END"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_MSG_NUM_STR_DEF_MSG	":45:Illegal break or next from END"
#define	_MSG_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END_FILE_CAT_NUM	uxawk:45
#define	_SGI_DNAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END	":45"
#define	_SGI_NAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END	"uxawk:45"
#define	_SGI_MNAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END	"uxawk:45:Illegal break or next from END"
#define	_SGI_SNAWK_ILL_BREAK_CONTINUE_OR_NEXT_FROM_END	"Illegal break or next from END"
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_MSG_NUM	46
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_MSG_NUM_STR	":46"
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_CAT_NUM_STR	"uxawk:46"
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_DEF_MSG	"Calling undefined function %s"
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_CAT_NUM_STR_DEF_MSG	"uxawk:46:Calling undefined function %s"
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_MSG_NUM_STR_DEF_MSG	":46:Calling undefined function %s"
#define	_MSG_NAWK_CALLING_UNDEFINED_FUNC_FILE_CAT_NUM	uxawk:46
#define	_SGI_DNAWK_CALLING_UNDEFINED_FUNC	":46"
#define	_SGI_NAWK_CALLING_UNDEFINED_FUNC	"uxawk:46"
#define	_SGI_MNAWK_CALLING_UNDEFINED_FUNC	"uxawk:46:Calling undefined function %s"
#define	_SGI_SNAWK_CALLING_UNDEFINED_FUNC	"Calling undefined function %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_MSG_NUM	47
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_MSG_NUM_STR	":47"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_CAT_NUM_STR	"uxawk:47"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_DEF_MSG	"Out of space for stack frames calling %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_CAT_NUM_STR_DEF_MSG	"uxawk:47:Out of space for stack frames calling %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_MSG_NUM_STR_DEF_MSG	":47:Out of space for stack frames calling %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL_FILE_CAT_NUM	uxawk:47
#define	_SGI_DNAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL	":47"
#define	_SGI_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL	"uxawk:47"
#define	_SGI_MNAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL	"uxawk:47:Out of space for stack frames calling %s"
#define	_SGI_SNAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CALL	"Out of space for stack frames calling %s"
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_MSG_NUM	48
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_MSG_NUM_STR	":48"
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_CAT_NUM_STR	"uxawk:48"
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_DEF_MSG	"Function %s called with 1 arg, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_CAT_NUM_STR_DEF_MSG	"uxawk:48:Function %s called with 1 arg, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_MSG_NUM_STR_DEF_MSG	":48:Function %s called with 1 arg, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_1ARG_FILE_CAT_NUM	uxawk:48
#define	_SGI_DNAWK_FUNC_CALLED_WITH_1ARG	":48"
#define	_SGI_NAWK_FUNC_CALLED_WITH_1ARG	"uxawk:48"
#define	_SGI_MNAWK_FUNC_CALLED_WITH_1ARG	"uxawk:48:Function %s called with 1 arg, uses only %d"
#define	_SGI_SNAWK_FUNC_CALLED_WITH_1ARG	"Function %s called with 1 arg, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_MSG_NUM	49
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_MSG_NUM_STR	":49"
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_CAT_NUM_STR	"uxawk:49"
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_DEF_MSG	"Function %s called with %d args, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_CAT_NUM_STR_DEF_MSG	"uxawk:49:Function %s called with %d args, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_MSG_NUM_STR_DEF_MSG	":49:Function %s called with %d args, uses only %d"
#define	_MSG_NAWK_FUNC_CALLED_WITH_NARGS_FILE_CAT_NUM	uxawk:49
#define	_SGI_DNAWK_FUNC_CALLED_WITH_NARGS	":49"
#define	_SGI_NAWK_FUNC_CALLED_WITH_NARGS	"uxawk:49"
#define	_SGI_MNAWK_FUNC_CALLED_WITH_NARGS	"uxawk:49:Function %s called with %d args, uses only %d"
#define	_SGI_SNAWK_FUNC_CALLED_WITH_NARGS	"Function %s called with %d args, uses only %d"
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_MSG_NUM	50
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_MSG_NUM_STR	":50"
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_CAT_NUM_STR	"uxawk:50"
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_DEF_MSG	"Function %s has %d arguments, limit %d"
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_CAT_NUM_STR_DEF_MSG	"uxawk:50:Function %s has %d arguments, limit %d"
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_MSG_NUM_STR_DEF_MSG	":50:Function %s has %d arguments, limit %d"
#define	_MSG_NAWK_FUNC_HAS_NARGS_LIMIT_FILE_CAT_NUM	uxawk:50
#define	_SGI_DNAWK_FUNC_HAS_NARGS_LIMIT	":50"
#define	_SGI_NAWK_FUNC_HAS_NARGS_LIMIT	"uxawk:50"
#define	_SGI_MNAWK_FUNC_HAS_NARGS_LIMIT	"uxawk:50:Function %s has %d arguments, limit %d"
#define	_SGI_SNAWK_FUNC_HAS_NARGS_LIMIT	"Function %s has %d arguments, limit %d"
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_MSG_NUM	51
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_MSG_NUM_STR	":51"
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_CAT_NUM_STR	"uxawk:51"
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_DEF_MSG	"Cannot use function %s as argument in %s"
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_CAT_NUM_STR_DEF_MSG	"uxawk:51:Cannot use function %s as argument in %s"
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_MSG_NUM_STR_DEF_MSG	":51:Cannot use function %s as argument in %s"
#define	_MSG_NAWK_CANNOT_USE_FUNC_AS_ARG_FILE_CAT_NUM	uxawk:51
#define	_SGI_DNAWK_CANNOT_USE_FUNC_AS_ARG	":51"
#define	_SGI_NAWK_CANNOT_USE_FUNC_AS_ARG	"uxawk:51"
#define	_SGI_MNAWK_CANNOT_USE_FUNC_AS_ARG	"uxawk:51:Cannot use function %s as argument in %s"
#define	_SGI_SNAWK_CANNOT_USE_FUNC_AS_ARG	"Cannot use function %s as argument in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_MSG_NUM	52
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_MSG_NUM_STR	":52"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CAT_NUM_STR	"uxawk:52"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_DEF_MSG	"Out of space for stack frames in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_CAT_NUM_STR_DEF_MSG	"uxawk:52:Out of space for stack frames in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_MSG_NUM_STR_DEF_MSG	":52:Out of space for stack frames in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC_FILE_CAT_NUM	uxawk:52
#define	_SGI_DNAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC	":52"
#define	_SGI_NAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC	"uxawk:52"
#define	_SGI_MNAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC	"uxawk:52:Out of space for stack frames in %s"
#define	_SGI_SNAWK_OUT_OF_SPACE_FOR_STACK_IN_FUNC	"Out of space for stack frames in %s"
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_MSG_NUM	53
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_MSG_NUM_STR	":53"
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_CAT_NUM_STR	"uxawk:53"
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_DEF_MSG	"Argument #%d of function %s was not supplied"
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_CAT_NUM_STR_DEF_MSG	"uxawk:53:Argument #%d of function %s was not supplied"
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_MSG_NUM_STR_DEF_MSG	":53:Argument #%d of function %s was not supplied"
#define	_MSG_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED_FILE_CAT_NUM	uxawk:53
#define	_SGI_DNAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED	":53"
#define	_SGI_NAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED	"uxawk:53"
#define	_SGI_MNAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED	"uxawk:53:Argument #%d of function %s was not supplied"
#define	_SGI_SNAWK_NTH_ARG_OF_FUNC_NOT_SUPPLIED	"Argument #%d of function %s was not supplied"
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_MSG_NUM	54
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_MSG_NUM_STR	":54"
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_CAT_NUM_STR	"uxawk:54"
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_DEF_MSG	"Illegal jump type %d"
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_CAT_NUM_STR_DEF_MSG	"uxawk:54:Illegal jump type %d"
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_MSG_NUM_STR_DEF_MSG	":54:Illegal jump type %d"
#define	_MSG_NAWK_ILLEGAL_JUMP_TYPE_FILE_CAT_NUM	uxawk:54
#define	_SGI_DNAWK_ILLEGAL_JUMP_TYPE	":54"
#define	_SGI_NAWK_ILLEGAL_JUMP_TYPE	"uxawk:54"
#define	_SGI_MNAWK_ILLEGAL_JUMP_TYPE	"uxawk:54:Illegal jump type %d"
#define	_SGI_SNAWK_ILLEGAL_JUMP_TYPE	"Illegal jump type %d"
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_MSG_NUM	55
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_MSG_NUM_STR	":55"
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_CAT_NUM_STR	"uxawk:55"
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_DEF_MSG	"Unknown boolean operator %d"
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_CAT_NUM_STR_DEF_MSG	"uxawk:55:Unknown boolean operator %d"
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_MSG_NUM_STR_DEF_MSG	":55:Unknown boolean operator %d"
#define	_MSG_NAWK_UNKNOWN_BOOLEAN_OPERATOR_FILE_CAT_NUM	uxawk:55
#define	_SGI_DNAWK_UNKNOWN_BOOLEAN_OPERATOR	":55"
#define	_SGI_NAWK_UNKNOWN_BOOLEAN_OPERATOR	"uxawk:55"
#define	_SGI_MNAWK_UNKNOWN_BOOLEAN_OPERATOR	"uxawk:55:Unknown boolean operator %d"
#define	_SGI_SNAWK_UNKNOWN_BOOLEAN_OPERATOR	"Unknown boolean operator %d"
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_MSG_NUM	56
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_MSG_NUM_STR	":56"
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_CAT_NUM_STR	"uxawk:56"
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_DEF_MSG	"Unknown relational operator %d"
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_CAT_NUM_STR_DEF_MSG	"uxawk:56:Unknown relational operator %d"
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_MSG_NUM_STR_DEF_MSG	":56:Unknown relational operator %d"
#define	_MSG_NAWK_UNKNOWN_RELATIONAL_OPERATOR_FILE_CAT_NUM	uxawk:56
#define	_SGI_DNAWK_UNKNOWN_RELATIONAL_OPERATOR	":56"
#define	_SGI_NAWK_UNKNOWN_RELATIONAL_OPERATOR	"uxawk:56"
#define	_SGI_MNAWK_UNKNOWN_RELATIONAL_OPERATOR	"uxawk:56:Unknown relational operator %d"
#define	_SGI_SNAWK_UNKNOWN_RELATIONAL_OPERATOR	"Unknown relational operator %d"
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_MSG_NUM	57
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_MSG_NUM_STR	":57"
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_CAT_NUM_STR	"uxawk:57"
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_DEF_MSG	"Tempcell list is curdled"
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_CAT_NUM_STR_DEF_MSG	"uxawk:57:Tempcell list is curdled"
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_MSG_NUM_STR_DEF_MSG	":57:Tempcell list is curdled"
#define	_MSG_NAWK_TEMPCELL_LIST_CURDLED_FILE_CAT_NUM	uxawk:57
#define	_SGI_DNAWK_TEMPCELL_LIST_CURDLED	":57"
#define	_SGI_NAWK_TEMPCELL_LIST_CURDLED	"uxawk:57"
#define	_SGI_MNAWK_TEMPCELL_LIST_CURDLED	"uxawk:57:Tempcell list is curdled"
#define	_SGI_SNAWK_TEMPCELL_LIST_CURDLED	"Tempcell list is curdled"
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_MSG_NUM	58
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_MSG_NUM_STR	":58"
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_CAT_NUM_STR	"uxawk:58"
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_DEF_MSG	"No space for temporaries"
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_CAT_NUM_STR_DEF_MSG	"uxawk:58:No space for temporaries"
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_MSG_NUM_STR_DEF_MSG	":58:No space for temporaries"
#define	_MSG_NAWK_NO_SPACE_FOR_TEMPORARIES_FILE_CAT_NUM	uxawk:58
#define	_SGI_DNAWK_NO_SPACE_FOR_TEMPORARIES	":58"
#define	_SGI_NAWK_NO_SPACE_FOR_TEMPORARIES	"uxawk:58"
#define	_SGI_MNAWK_NO_SPACE_FOR_TEMPORARIES	"uxawk:58:No space for temporaries"
#define	_SGI_SNAWK_NO_SPACE_FOR_TEMPORARIES	"No space for temporaries"
#define	_MSG_NAWK_ILLEGAL_FIELD_MSG_NUM	59
#define	_MSG_NAWK_ILLEGAL_FIELD_MSG_NUM_STR	":59"
#define	_MSG_NAWK_ILLEGAL_FIELD_CAT_NUM_STR	"uxawk:59"
#define	_MSG_NAWK_ILLEGAL_FIELD_DEF_MSG	"Illegal field $(%s)"
#define	_MSG_NAWK_ILLEGAL_FIELD_CAT_NUM_STR_DEF_MSG	"uxawk:59:Illegal field $(%s)"
#define	_MSG_NAWK_ILLEGAL_FIELD_MSG_NUM_STR_DEF_MSG	":59:Illegal field $(%s)"
#define	_MSG_NAWK_ILLEGAL_FIELD_FILE_CAT_NUM	uxawk:59
#define	_SGI_DNAWK_ILLEGAL_FIELD	":59"
#define	_SGI_NAWK_ILLEGAL_FIELD	"uxawk:59"
#define	_SGI_MNAWK_ILLEGAL_FIELD	"uxawk:59:Illegal field $(%s)"
#define	_SGI_SNAWK_ILLEGAL_FIELD	"Illegal field $(%s)"
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_MSG_NUM	60
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_MSG_NUM_STR	":60"
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_CAT_NUM_STR	"uxawk:60"
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_DEF_MSG	"Format item %.20s... too long"
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_CAT_NUM_STR_DEF_MSG	"uxawk:60:Format item %.20s... too long"
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_MSG_NUM_STR_DEF_MSG	":60:Format item %.20s... too long"
#define	_MSG_NAWK_FORMAT_ITEM_TOO_BIG_FILE_CAT_NUM	uxawk:60
#define	_SGI_DNAWK_FORMAT_ITEM_TOO_BIG	":60"
#define	_SGI_NAWK_FORMAT_ITEM_TOO_BIG	"uxawk:60"
#define	_SGI_MNAWK_FORMAT_ITEM_TOO_BIG	"uxawk:60:Format item %.20s... too long"
#define	_SGI_SNAWK_FORMAT_ITEM_TOO_BIG	"Format item %.20s... too long"
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_MSG_NUM	61
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_MSG_NUM_STR	":61"
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_CAT_NUM_STR	"uxawk:61"
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_DEF_MSG	"Not enough args in printf(%s)"
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_CAT_NUM_STR_DEF_MSG	"uxawk:61:Not enough args in printf(%s)"
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_MSG_NUM_STR_DEF_MSG	":61:Not enough args in printf(%s)"
#define	_MSG_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF_FILE_CAT_NUM	uxawk:61
#define	_SGI_DNAWK_NOT_ENOUGH_ARGS_IN_PRINTF	":61"
#define	_SGI_NAWK_NOT_ENOUGH_ARGS_IN_PRINTF	"uxawk:61"
#define	_SGI_MNAWK_NOT_ENOUGH_ARGS_IN_PRINTF	"uxawk:61:Not enough args in printf(%s)"
#define	_SGI_SNAWK_NOT_ENOUGH_ARGS_IN_PRINTF	"Not enough args in printf(%s)"
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_MSG_NUM	62
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_MSG_NUM_STR	":62"
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_CAT_NUM_STR	"uxawk:62"
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_DEF_MSG	"sprintf string %.40s ... too long"
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_CAT_NUM_STR_DEF_MSG	"uxawk:62:sprintf string %.40s ... too long"
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_MSG_NUM_STR_DEF_MSG	":62:sprintf string %.40s ... too long"
#define	_MSG_NAWK_SPRINTF_STRING_TOO_BIG_FILE_CAT_NUM	uxawk:62
#define	_SGI_DNAWK_SPRINTF_STRING_TOO_BIG	":62"
#define	_SGI_NAWK_SPRINTF_STRING_TOO_BIG	"uxawk:62"
#define	_SGI_MNAWK_SPRINTF_STRING_TOO_BIG	"uxawk:62:sprintf string %.40s ... too long"
#define	_SGI_SNAWK_SPRINTF_STRING_TOO_BIG	"sprintf string %.40s ... too long"
#define	_MSG_UXAWK_63_MSG_NUM	63
#define	_MSG_UXAWK_63_MSG_NUM_STR	":63"
#define	_MSG_UXAWK_63_CAT_NUM_STR	"uxawk:63"
#define	_MSG_UXAWK_63_DEF_MSG	"printf string %.40s ... too long"
#define	_MSG_UXAWK_63_CAT_NUM_STR_DEF_MSG	"uxawk:63:printf string %.40s ... too long"
#define	_MSG_UXAWK_63_MSG_NUM_STR_DEF_MSG	":63:printf string %.40s ... too long"
#define	_MSG_UXAWK_63_FILE_CAT_NUM	uxawk:63
#define	_SGI_DUXAWK_63	":63"
#define	_SGI_UXAWK_63	"uxawk:63"
#define	_SGI_MUXAWK_63	"uxawk:63:printf string %.40s ... too long"
#define	_SGI_SUXAWK_63	"printf string %.40s ... too long"
#define	_MSG_NAWK_DIVISION_BY_ZERO_MSG_NUM	64
#define	_MSG_NAWK_DIVISION_BY_ZERO_MSG_NUM_STR	":64"
#define	_MSG_NAWK_DIVISION_BY_ZERO_CAT_NUM_STR	"uxawk:64"
#define	_MSG_NAWK_DIVISION_BY_ZERO_DEF_MSG	"Division by zero"
#define	_MSG_NAWK_DIVISION_BY_ZERO_CAT_NUM_STR_DEF_MSG	"uxawk:64:Division by zero"
#define	_MSG_NAWK_DIVISION_BY_ZERO_MSG_NUM_STR_DEF_MSG	":64:Division by zero"
#define	_MSG_NAWK_DIVISION_BY_ZERO_FILE_CAT_NUM	uxawk:64
#define	_SGI_DNAWK_DIVISION_BY_ZERO	":64"
#define	_SGI_NAWK_DIVISION_BY_ZERO	"uxawk:64"
#define	_SGI_MNAWK_DIVISION_BY_ZERO	"uxawk:64:Division by zero"
#define	_SGI_SNAWK_DIVISION_BY_ZERO	"Division by zero"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_MSG_NUM	65
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_MSG_NUM_STR	":65"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_CAT_NUM_STR	"uxawk:65"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_DEF_MSG	"Division by zero in mod"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_CAT_NUM_STR_DEF_MSG	"uxawk:65:Division by zero in mod"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_MSG_NUM_STR_DEF_MSG	":65:Division by zero in mod"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_FILE_CAT_NUM	uxawk:65
#define	_SGI_DNAWK_DIVISION_BY_ZERO_IN_MOD	":65"
#define	_SGI_NAWK_DIVISION_BY_ZERO_IN_MOD	"uxawk:65"
#define	_SGI_MNAWK_DIVISION_BY_ZERO_IN_MOD	"uxawk:65:Division by zero in mod"
#define	_SGI_SNAWK_DIVISION_BY_ZERO_IN_MOD	"Division by zero in mod"
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_MSG_NUM	66
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_MSG_NUM_STR	":66"
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_CAT_NUM_STR	"uxawk:66"
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_DEF_MSG	"Illegal arithmetic operator %d"
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_CAT_NUM_STR_DEF_MSG	"uxawk:66:Illegal arithmetic operator %d"
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_MSG_NUM_STR_DEF_MSG	":66:Illegal arithmetic operator %d"
#define	_MSG_NAWK_ILLEGAL_ARITHMETIC_OPERATOR_FILE_CAT_NUM	uxawk:66
#define	_SGI_DNAWK_ILLEGAL_ARITHMETIC_OPERATOR	":66"
#define	_SGI_NAWK_ILLEGAL_ARITHMETIC_OPERATOR	"uxawk:66"
#define	_SGI_MNAWK_ILLEGAL_ARITHMETIC_OPERATOR	"uxawk:66:Illegal arithmetic operator %d"
#define	_SGI_SNAWK_ILLEGAL_ARITHMETIC_OPERATOR	"Illegal arithmetic operator %d"
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_MSG_NUM	67
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_MSG_NUM_STR	":67"
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_CAT_NUM_STR	"uxawk:67"
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_DEF_MSG	"Division by zero in /="
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_CAT_NUM_STR_DEF_MSG	"uxawk:67:Division by zero in /="
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_MSG_NUM_STR_DEF_MSG	":67:Division by zero in /="
#define	_MSG_NAWK_DIVISION_BY_ZERO_EQ_FILE_CAT_NUM	uxawk:67
#define	_SGI_DNAWK_DIVISION_BY_ZERO_EQ	":67"
#define	_SGI_NAWK_DIVISION_BY_ZERO_EQ	"uxawk:67"
#define	_SGI_MNAWK_DIVISION_BY_ZERO_EQ	"uxawk:67:Division by zero in /="
#define	_SGI_SNAWK_DIVISION_BY_ZERO_EQ	"Division by zero in /="
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_MSG_NUM	68
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_MSG_NUM_STR	":68"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_CAT_NUM_STR	"uxawk:68"
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_DEF_MSG	"Division by zero in %%="
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_CAT_NUM_STR_DEF_MSG	"uxawk:68:Division by zero in %%="
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_MSG_NUM_STR_DEF_MSG	":68:Division by zero in %%="
#define	_MSG_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ_FILE_CAT_NUM	uxawk:68
#define	_SGI_DNAWK_DIVISION_BY_ZERO_IN_MOD_EQ	":68"
#define	_SGI_NAWK_DIVISION_BY_ZERO_IN_MOD_EQ	"uxawk:68"
#define	_SGI_MNAWK_DIVISION_BY_ZERO_IN_MOD_EQ	"uxawk:68:Division by zero in %%="
#define	_SGI_SNAWK_DIVISION_BY_ZERO_IN_MOD_EQ	"Division by zero in %%="
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_MSG_NUM	69
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_MSG_NUM_STR	":69"
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_CAT_NUM_STR	"uxawk:69"
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_DEF_MSG	"Illegal assignment operator %d"
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_CAT_NUM_STR_DEF_MSG	"uxawk:69:Illegal assignment operator %d"
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_MSG_NUM_STR_DEF_MSG	":69:Illegal assignment operator %d"
#define	_MSG_NAWK_ILLEGAL_ASSGNMNT_OP_FILE_CAT_NUM	uxawk:69
#define	_SGI_DNAWK_ILLEGAL_ASSGNMNT_OP	":69"
#define	_SGI_NAWK_ILLEGAL_ASSGNMNT_OP	"uxawk:69"
#define	_SGI_MNAWK_ILLEGAL_ASSGNMNT_OP	"uxawk:69:Illegal assignment operator %d"
#define	_SGI_SNAWK_ILLEGAL_ASSGNMNT_OP	"Illegal assignment operator %d"
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_MSG_NUM	70
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_MSG_NUM_STR	":70"
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_CAT_NUM_STR	"uxawk:70"
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_DEF_MSG	"Out of space concatenating %.15s and %.15s"
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_CAT_NUM_STR_DEF_MSG	"uxawk:70:Out of space concatenating %.15s and %.15s"
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_MSG_NUM_STR_DEF_MSG	":70:Out of space concatenating %.15s and %.15s"
#define	_MSG_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS_FILE_CAT_NUM	uxawk:70
#define	_SGI_DNAWK_OUT_OF_SPACE_CONCATING_TWO_STRS	":70"
#define	_SGI_NAWK_OUT_OF_SPACE_CONCATING_TWO_STRS	"uxawk:70"
#define	_SGI_MNAWK_OUT_OF_SPACE_CONCATING_TWO_STRS	"uxawk:70:Out of space concatenating %.15s and %.15s"
#define	_SGI_SNAWK_OUT_OF_SPACE_CONCATING_TWO_STRS	"Out of space concatenating %.15s and %.15s"
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_MSG_NUM	71
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_MSG_NUM_STR	":71"
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_CAT_NUM_STR	"uxawk:71"
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_DEF_MSG	"Illegal type of split()"
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_CAT_NUM_STR_DEF_MSG	"uxawk:71:Illegal type of split()"
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_MSG_NUM_STR_DEF_MSG	":71:Illegal type of split()"
#define	_MSG_NAWK_ILLEGAL_TYPE_OF_SPLIT_FILE_CAT_NUM	uxawk:71
#define	_SGI_DNAWK_ILLEGAL_TYPE_OF_SPLIT	":71"
#define	_SGI_NAWK_ILLEGAL_TYPE_OF_SPLIT	"uxawk:71"
#define	_SGI_MNAWK_ILLEGAL_TYPE_OF_SPLIT	"uxawk:71:Illegal type of split()"
#define	_SGI_SNAWK_ILLEGAL_TYPE_OF_SPLIT	"Illegal type of split()"
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_MSG_NUM	72
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_MSG_NUM_STR	":72"
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_CAT_NUM_STR	"uxawk:72"
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_DEF_MSG	"atan2 requires two arguments; returning 1.0"
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_CAT_NUM_STR_DEF_MSG	"uxawk:72:atan2 requires two arguments; returning 1.0"
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_MSG_NUM_STR_DEF_MSG	":72:atan2 requires two arguments; returning 1.0"
#define	_MSG_NAWK_ATAN2_REQUIRES_TWO_ARGS_FILE_CAT_NUM	uxawk:72
#define	_SGI_DNAWK_ATAN2_REQUIRES_TWO_ARGS	":72"
#define	_SGI_NAWK_ATAN2_REQUIRES_TWO_ARGS	"uxawk:72"
#define	_SGI_MNAWK_ATAN2_REQUIRES_TWO_ARGS	"uxawk:72:atan2 requires two arguments; returning 1.0"
#define	_SGI_SNAWK_ATAN2_REQUIRES_TWO_ARGS	"atan2 requires two arguments; returning 1.0"
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_MSG_NUM	73
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_MSG_NUM_STR	":73"
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_CAT_NUM_STR	"uxawk:73"
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_DEF_MSG	"Illegal function type %d"
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_CAT_NUM_STR_DEF_MSG	"uxawk:73:Illegal function type %d"
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_MSG_NUM_STR_DEF_MSG	":73:Illegal function type %d"
#define	_MSG_NAWK_ILLEGAL_FUNC_TYPE_FILE_CAT_NUM	uxawk:73
#define	_SGI_DNAWK_ILLEGAL_FUNC_TYPE	":73"
#define	_SGI_NAWK_ILLEGAL_FUNC_TYPE	"uxawk:73"
#define	_SGI_MNAWK_ILLEGAL_FUNC_TYPE	"uxawk:73:Illegal function type %d"
#define	_SGI_SNAWK_ILLEGAL_FUNC_TYPE	"Illegal function type %d"
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_MSG_NUM	74
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_MSG_NUM_STR	":74"
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_CAT_NUM_STR	"uxawk:74"
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_DEF_MSG	"Function has too many arguments"
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_CAT_NUM_STR_DEF_MSG	"uxawk:74:Function has too many arguments"
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_MSG_NUM_STR_DEF_MSG	":74:Function has too many arguments"
#define	_MSG_NAWK_FUNC_HAS_MANY_ARGS_FILE_CAT_NUM	uxawk:74
#define	_SGI_DNAWK_FUNC_HAS_MANY_ARGS	":74"
#define	_SGI_NAWK_FUNC_HAS_MANY_ARGS	"uxawk:74"
#define	_SGI_MNAWK_FUNC_HAS_MANY_ARGS	"uxawk:74:Function has too many arguments"
#define	_SGI_SNAWK_FUNC_HAS_MANY_ARGS	"Function has too many arguments"
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_MSG_NUM	75
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_MSG_NUM_STR	":75"
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_CAT_NUM_STR	"uxawk:75"
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_DEF_MSG	"Null file name in print or getline"
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_CAT_NUM_STR_DEF_MSG	"uxawk:75:Null file name in print or getline"
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_MSG_NUM_STR_DEF_MSG	":75:Null file name in print or getline"
#define	_MSG_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE_FILE_CAT_NUM	uxawk:75
#define	_SGI_DNAWK_NULL_FNAME_IN_PRINT_OR_GETLINE	":75"
#define	_SGI_NAWK_NULL_FNAME_IN_PRINT_OR_GETLINE	"uxawk:75"
#define	_SGI_MNAWK_NULL_FNAME_IN_PRINT_OR_GETLINE	"uxawk:75:Null file name in print or getline"
#define	_SGI_SNAWK_NULL_FNAME_IN_PRINT_OR_GETLINE	"Null file name in print or getline"
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_MSG_NUM	76
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_MSG_NUM_STR	":76"
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_CAT_NUM_STR	"uxawk:76"
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_DEF_MSG	"%s makes too many open files"
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_CAT_NUM_STR_DEF_MSG	"uxawk:76:%s makes too many open files"
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_MSG_NUM_STR_DEF_MSG	":76:%s makes too many open files"
#define	_MSG_NAWK_STR_MAKES_MANY_OPEN_FILES_FILE_CAT_NUM	uxawk:76
#define	_SGI_DNAWK_STR_MAKES_MANY_OPEN_FILES	":76"
#define	_SGI_NAWK_STR_MAKES_MANY_OPEN_FILES	"uxawk:76"
#define	_SGI_MNAWK_STR_MAKES_MANY_OPEN_FILES	"uxawk:76:%s makes too many open files"
#define	_SGI_SNAWK_STR_MAKES_MANY_OPEN_FILES	"%s makes too many open files"
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_MSG_NUM	77
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_MSG_NUM_STR	":77"
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_CAT_NUM_STR	"uxawk:77"
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_DEF_MSG	"Illegal redirection"
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_CAT_NUM_STR_DEF_MSG	"uxawk:77:Illegal redirection"
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_MSG_NUM_STR_DEF_MSG	":77:Illegal redirection"
#define	_MSG_NAWK_ILLEGAL_REDIRECTION_FILE_CAT_NUM	uxawk:77
#define	_SGI_DNAWK_ILLEGAL_REDIRECTION	":77"
#define	_SGI_NAWK_ILLEGAL_REDIRECTION	"uxawk:77"
#define	_SGI_MNAWK_ILLEGAL_REDIRECTION	"uxawk:77:Illegal redirection"
#define	_SGI_SNAWK_ILLEGAL_REDIRECTION	"Illegal redirection"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_MSG_NUM	78
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_MSG_NUM_STR	":78"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_CAT_NUM_STR	"uxawk:78"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_DEF_MSG	"I/O error occurred closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_CAT_NUM_STR_DEF_MSG	"uxawk:78:I/O error occurred closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_MSG_NUM_STR_DEF_MSG	":78:I/O error occurred closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE_FILE_CAT_NUM	uxawk:78
#define	_SGI_DNAWK_IO_ERROR_OCCURRED_CLOSING_FILE	":78"
#define	_SGI_NAWK_IO_ERROR_OCCURRED_CLOSING_FILE	"uxawk:78"
#define	_SGI_MNAWK_IO_ERROR_OCCURRED_CLOSING_FILE	"uxawk:78:I/O error occurred closing %s"
#define	_SGI_SNAWK_IO_ERROR_OCCURRED_CLOSING_FILE	"I/O error occurred closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_MSG_NUM	79
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_MSG_NUM_STR	":79"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_CAT_NUM_STR	"uxawk:79"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_DEF_MSG	"I/O error occurred while closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_CAT_NUM_STR_DEF_MSG	"uxawk:79:I/O error occurred while closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_MSG_NUM_STR_DEF_MSG	":79:I/O error occurred while closing %s"
#define	_MSG_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE_FILE_CAT_NUM	uxawk:79
#define	_SGI_DNAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE	":79"
#define	_SGI_NAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE	"uxawk:79"
#define	_SGI_MNAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE	"uxawk:79:I/O error occurred while closing %s"
#define	_SGI_SNAWK_IO_ERROR_OCCURRED_WHILE_CLOSING_FILE	"I/O error occurred while closing %s"
#define	_MSG_NAWK_ASSIGN_TO_MSG_NUM	80
#define	_MSG_NAWK_ASSIGN_TO_MSG_NUM_STR	":80"
#define	_MSG_NAWK_ASSIGN_TO_CAT_NUM_STR	"uxawk:80"
#define	_MSG_NAWK_ASSIGN_TO_DEF_MSG	"assign to"
#define	_MSG_NAWK_ASSIGN_TO_CAT_NUM_STR_DEF_MSG	"uxawk:80:assign to"
#define	_MSG_NAWK_ASSIGN_TO_MSG_NUM_STR_DEF_MSG	":80:assign to"
#define	_MSG_NAWK_ASSIGN_TO_FILE_CAT_NUM	uxawk:80
#define	_SGI_DNAWK_ASSIGN_TO	":80"
#define	_SGI_NAWK_ASSIGN_TO	"uxawk:80"
#define	_SGI_MNAWK_ASSIGN_TO	"uxawk:80:assign to"
#define	_SGI_SNAWK_ASSIGN_TO	"assign to"
#define	_MSG_NAWK_READ_VALUE_OF_MSG_NUM	81
#define	_MSG_NAWK_READ_VALUE_OF_MSG_NUM_STR	":81"
#define	_MSG_NAWK_READ_VALUE_OF_CAT_NUM_STR	"uxawk:81"
#define	_MSG_NAWK_READ_VALUE_OF_DEF_MSG	"read value of"
#define	_MSG_NAWK_READ_VALUE_OF_CAT_NUM_STR_DEF_MSG	"uxawk:81:read value of"
#define	_MSG_NAWK_READ_VALUE_OF_MSG_NUM_STR_DEF_MSG	":81:read value of"
#define	_MSG_NAWK_READ_VALUE_OF_FILE_CAT_NUM	uxawk:81
#define	_SGI_DNAWK_READ_VALUE_OF	":81"
#define	_SGI_NAWK_READ_VALUE_OF	"uxawk:81"
#define	_SGI_MNAWK_READ_VALUE_OF	"uxawk:81:read value of"
#define	_SGI_SNAWK_READ_VALUE_OF	"read value of"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_MSG_NUM	82
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_MSG_NUM_STR	":82"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_CAT_NUM_STR	"uxawk:82"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_DEF_MSG	"Out of space in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_CAT_NUM_STR_DEF_MSG	"uxawk:82:Out of space in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_MSG_NUM_STR_DEF_MSG	":82:Out of space in %s"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_STR_FILE_CAT_NUM	uxawk:82
#define	_SGI_DNAWK_OUT_OF_SPACE_IN_STR	":82"
#define	_SGI_NAWK_OUT_OF_SPACE_IN_STR	"uxawk:82"
#define	_SGI_MNAWK_OUT_OF_SPACE_IN_STR	"uxawk:82:Out of space in %s"
#define	_SGI_SNAWK_OUT_OF_SPACE_IN_STR	"Out of space in %s"
#define	_MSG_NAWK_NL_IN_STRING_MSG_NUM	83
#define	_MSG_NAWK_NL_IN_STRING_MSG_NUM_STR	":83"
#define	_MSG_NAWK_NL_IN_STRING_CAT_NUM_STR	"uxawk:83"
#define	_MSG_NAWK_NL_IN_STRING_DEF_MSG	"Newline in string %.10s ..."
#define	_MSG_NAWK_NL_IN_STRING_CAT_NUM_STR_DEF_MSG	"uxawk:83:Newline in string %.10s ..."
#define	_MSG_NAWK_NL_IN_STRING_MSG_NUM_STR_DEF_MSG	":83:Newline in string %.10s ..."
#define	_MSG_NAWK_NL_IN_STRING_FILE_CAT_NUM	uxawk:83
#define	_SGI_DNAWK_NL_IN_STRING	":83"
#define	_SGI_NAWK_NL_IN_STRING	"uxawk:83"
#define	_SGI_MNAWK_NL_IN_STRING	"uxawk:83:Newline in string %.10s ..."
#define	_SGI_SNAWK_NL_IN_STRING	"Newline in string %.10s ..."
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_MSG_NUM	84
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_MSG_NUM_STR	":84"
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_CAT_NUM_STR	"uxawk:84"
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_DEF_MSG	"Symbol table overflow at %s"
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_CAT_NUM_STR_DEF_MSG	"uxawk:84:Symbol table overflow at %s"
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_MSG_NUM_STR_DEF_MSG	":84:Symbol table overflow at %s"
#define	_MSG_NAWK_SYMBOL_TABLE_OVERFLOW_FILE_CAT_NUM	uxawk:84
#define	_SGI_DNAWK_SYMBOL_TABLE_OVERFLOW	":84"
#define	_SGI_NAWK_SYMBOL_TABLE_OVERFLOW	"uxawk:84"
#define	_SGI_MNAWK_SYMBOL_TABLE_OVERFLOW	"uxawk:84:Symbol table overflow at %s"
#define	_SGI_SNAWK_SYMBOL_TABLE_OVERFLOW	"Symbol table overflow at %s"
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_MSG_NUM	85
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_MSG_NUM_STR	":85"
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_CAT_NUM_STR	"uxawk:85"
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_DEF_MSG	"Cannot %s %s; it's an array name."
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_CAT_NUM_STR_DEF_MSG	"uxawk:85:Cannot %s %s; it's an array name."
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_MSG_NUM_STR_DEF_MSG	":85:Cannot %s %s; it's an array name."
#define	_MSG_NAWK_CANNOT_ITS_AN_ARRAY_NAME_FILE_CAT_NUM	uxawk:85
#define	_SGI_DNAWK_CANNOT_ITS_AN_ARRAY_NAME	":85"
#define	_SGI_NAWK_CANNOT_ITS_AN_ARRAY_NAME	"uxawk:85"
#define	_SGI_MNAWK_CANNOT_ITS_AN_ARRAY_NAME	"uxawk:85:Cannot %s %s; it's an array name."
#define	_SGI_SNAWK_CANNOT_ITS_AN_ARRAY_NAME	"Cannot %s %s; it's an array name."
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_MSG_NUM	86
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_MSG_NUM_STR	":86"
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_CAT_NUM_STR	"uxawk:86"
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_DEF_MSG	"Cannot %s %s; it's a function."
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_CAT_NUM_STR_DEF_MSG	"uxawk:86:Cannot %s %s; it's a function."
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_MSG_NUM_STR_DEF_MSG	":86:Cannot %s %s; it's a function."
#define	_MSG_NAWK_CANNOT_ITS_A_FUNC_FILE_CAT_NUM	uxawk:86
#define	_SGI_DNAWK_CANNOT_ITS_A_FUNC	":86"
#define	_SGI_NAWK_CANNOT_ITS_A_FUNC	"uxawk:86"
#define	_SGI_MNAWK_CANNOT_ITS_A_FUNC	"uxawk:86:Cannot %s %s; it's a function."
#define	_SGI_SNAWK_CANNOT_ITS_A_FUNC	"Cannot %s %s; it's a function."
#define	_MSG_NAWK_FUNNY_VAR_MSG_NUM	87
#define	_MSG_NAWK_FUNNY_VAR_MSG_NUM_STR	":87"
#define	_MSG_NAWK_FUNNY_VAR_CAT_NUM_STR	"uxawk:87"
#define	_MSG_NAWK_FUNNY_VAR_DEF_MSG	"Funny variable %o: n=%s s=\"%s\" f=%g t=%o"
#define	_MSG_NAWK_FUNNY_VAR_CAT_NUM_STR_DEF_MSG	"uxawk:87:Funny variable %o: n=%s s=\"%s\" f=%g t=%o"
#define	_MSG_NAWK_FUNNY_VAR_MSG_NUM_STR_DEF_MSG	":87:Funny variable %o: n=%s s=\"%s\" f=%g t=%o"
#define	_MSG_NAWK_FUNNY_VAR_FILE_CAT_NUM	uxawk:87
#define	_SGI_DNAWK_FUNNY_VAR	":87"
#define	_SGI_NAWK_FUNNY_VAR	"uxawk:87"
#define	_SGI_MNAWK_FUNNY_VAR	"uxawk:87:Funny variable %o: n=%s s=\"%s\" f=%g t=%o"
#define	_SGI_SNAWK_FUNNY_VAR	"Funny variable %o: n=%s s=\"%s\" f=%g t=%o"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_MSG_NUM	88
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_MSG_NUM_STR	":88"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_CAT_NUM_STR	"uxawk:88"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_DEF_MSG	"Out of space in tostring on %s"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_CAT_NUM_STR_DEF_MSG	"uxawk:88:Out of space in tostring on %s"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_MSG_NUM_STR_DEF_MSG	":88:Out of space in tostring on %s"
#define	_MSG_NAWK_OUT_OF_SPACE_IN_TOSTRING_FILE_CAT_NUM	uxawk:88
#define	_SGI_DNAWK_OUT_OF_SPACE_IN_TOSTRING	":88"
#define	_SGI_NAWK_OUT_OF_SPACE_IN_TOSTRING	"uxawk:88"
#define	_SGI_MNAWK_OUT_OF_SPACE_IN_TOSTRING	"uxawk:88:Out of space in tostring on %s"
#define	_SGI_SNAWK_OUT_OF_SPACE_IN_TOSTRING	"Out of space in tostring on %s"
#define	_MSG_NAWK_STRING_TOO_LONG_MSG_NUM	89
#define	_MSG_NAWK_STRING_TOO_LONG_MSG_NUM_STR	":89"
#define	_MSG_NAWK_STRING_TOO_LONG_CAT_NUM_STR	"uxawk:89"
#define	_MSG_NAWK_STRING_TOO_LONG_DEF_MSG	"String %.10s ... too long"
#define	_MSG_NAWK_STRING_TOO_LONG_CAT_NUM_STR_DEF_MSG	"uxawk:89:String %.10s ... too long"
#define	_MSG_NAWK_STRING_TOO_LONG_MSG_NUM_STR_DEF_MSG	":89:String %.10s ... too long"
#define	_MSG_NAWK_STRING_TOO_LONG_FILE_CAT_NUM	uxawk:89
#define	_SGI_DNAWK_STRING_TOO_LONG	":89"
#define	_SGI_NAWK_STRING_TOO_LONG	"uxawk:89"
#define	_SGI_MNAWK_STRING_TOO_LONG	"uxawk:89:String %.10s ... too long"
#define	_SGI_SNAWK_STRING_TOO_LONG	"String %.10s ... too long"
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_MSG_NUM	90
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_MSG_NUM_STR	":90"
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_CAT_NUM_STR	"uxawk:90"
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_DEF_MSG	"String/reg expr %.10s ... too long"
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_CAT_NUM_STR_DEF_MSG	"uxawk:90:String/reg expr %.10s ... too long"
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_MSG_NUM_STR_DEF_MSG	":90:String/reg expr %.10s ... too long"
#define	_MSG_NAWK_STR_OR_REG_EXP_TOO_LONG_FILE_CAT_NUM	uxawk:90
#define	_SGI_DNAWK_STR_OR_REG_EXP_TOO_LONG	":90"
#define	_SGI_NAWK_STR_OR_REG_EXP_TOO_LONG	"uxawk:90"
#define	_SGI_MNAWK_STR_OR_REG_EXP_TOO_LONG	"uxawk:90:String/reg expr %.10s ... too long"
#define	_SGI_SNAWK_STR_OR_REG_EXP_TOO_LONG	"String/reg expr %.10s ... too long"
#define	_MSG_NAWK_EXTRA_CHAR_MSG_NUM	91
#define	_MSG_NAWK_EXTRA_CHAR_MSG_NUM_STR	":91"
#define	_MSG_NAWK_EXTRA_CHAR_CAT_NUM_STR	"uxawk:91"
#define	_MSG_NAWK_EXTRA_CHAR_DEF_MSG	"Extra %c"
#define	_MSG_NAWK_EXTRA_CHAR_CAT_NUM_STR_DEF_MSG	"uxawk:91:Extra %c"
#define	_MSG_NAWK_EXTRA_CHAR_MSG_NUM_STR_DEF_MSG	":91:Extra %c"
#define	_MSG_NAWK_EXTRA_CHAR_FILE_CAT_NUM	uxawk:91
#define	_SGI_DNAWK_EXTRA_CHAR	":91"
#define	_SGI_NAWK_EXTRA_CHAR	"uxawk:91"
#define	_SGI_MNAWK_EXTRA_CHAR	"uxawk:91:Extra %c"
#define	_SGI_SNAWK_EXTRA_CHAR	"Extra %c"
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_MSG_NUM	92
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_MSG_NUM_STR	":92"
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_CAT_NUM_STR	"uxawk:92"
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_DEF_MSG	"Illegal nested function"
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_CAT_NUM_STR_DEF_MSG	"uxawk:92:Illegal nested function"
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_MSG_NUM_STR_DEF_MSG	":92:Illegal nested function"
#define	_MSG_NAWK_ILLEGAL_NESTED_FUNCTION_FILE_CAT_NUM	uxawk:92
#define	_SGI_DNAWK_ILLEGAL_NESTED_FUNCTION	":92"
#define	_SGI_NAWK_ILLEGAL_NESTED_FUNCTION	"uxawk:92"
#define	_SGI_MNAWK_ILLEGAL_NESTED_FUNCTION	"uxawk:92:Illegal nested function"
#define	_SGI_SNAWK_ILLEGAL_NESTED_FUNCTION	"Illegal nested function"
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_MSG_NUM	93
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_MSG_NUM_STR	":93"
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_CAT_NUM_STR	"uxawk:93"
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_DEF_MSG	"Return not in function"
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_CAT_NUM_STR_DEF_MSG	"uxawk:93:Return not in function"
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_MSG_NUM_STR_DEF_MSG	":93:Return not in function"
#define	_MSG_NAWK_RETURN_NOT_IN_FUNC_FILE_CAT_NUM	uxawk:93
#define	_SGI_DNAWK_RETURN_NOT_IN_FUNC	":93"
#define	_SGI_NAWK_RETURN_NOT_IN_FUNC	"uxawk:93"
#define	_SGI_MNAWK_RETURN_NOT_IN_FUNC	"uxawk:93:Return not in function"
#define	_SGI_SNAWK_RETURN_NOT_IN_FUNC	"Return not in function"
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_MSG_NUM	94
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_MSG_NUM_STR	":94"
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_CAT_NUM_STR	"uxawk:94"
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_DEF_MSG	"Newline in regular expression %.10s ..."
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_CAT_NUM_STR_DEF_MSG	"uxawk:94:Newline in regular expression %.10s ..."
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_MSG_NUM_STR_DEF_MSG	":94:Newline in regular expression %.10s ..."
#define	_MSG_NAWK_NEWLINE_IN_REG_EXP_FILE_CAT_NUM	uxawk:94
#define	_SGI_DNAWK_NEWLINE_IN_REG_EXP	":94"
#define	_SGI_NAWK_NEWLINE_IN_REG_EXP	"uxawk:94"
#define	_SGI_MNAWK_NEWLINE_IN_REG_EXP	"uxawk:94:Newline in regular expression %.10s ..."
#define	_SGI_SNAWK_NEWLINE_IN_REG_EXP	"Newline in regular expression %.10s ..."
#define	_MSG_NAWK_BAILING_OUT_MSG_NUM	95
#define	_MSG_NAWK_BAILING_OUT_MSG_NUM_STR	":95"
#define	_MSG_NAWK_BAILING_OUT_CAT_NUM_STR	"uxawk:95"
#define	_MSG_NAWK_BAILING_OUT_DEF_MSG	"Bailing out"
#define	_MSG_NAWK_BAILING_OUT_CAT_NUM_STR_DEF_MSG	"uxawk:95:Bailing out"
#define	_MSG_NAWK_BAILING_OUT_MSG_NUM_STR_DEF_MSG	":95:Bailing out"
#define	_MSG_NAWK_BAILING_OUT_FILE_CAT_NUM	uxawk:95
#define	_SGI_DNAWK_BAILING_OUT	":95"
#define	_SGI_NAWK_BAILING_OUT	"uxawk:95"
#define	_SGI_MNAWK_BAILING_OUT	"uxawk:95:Bailing out"
#define	_SGI_SNAWK_BAILING_OUT	"Bailing out"
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_MSG_NUM	96
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_MSG_NUM_STR	":96"
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_CAT_NUM_STR	"uxawk:96"
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_DEF_MSG	"You can only delete array[element]"
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_CAT_NUM_STR_DEF_MSG	"uxawk:96:You can only delete array[element]"
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_MSG_NUM_STR_DEF_MSG	":96:You can only delete array[element]"
#define	_MSG_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT_FILE_CAT_NUM	uxawk:96
#define	_SGI_DNAWK_U_CAN_ONLY_DEL_ARR_ELEMENT	":96"
#define	_SGI_NAWK_U_CAN_ONLY_DEL_ARR_ELEMENT	"uxawk:96"
#define	_SGI_MNAWK_U_CAN_ONLY_DEL_ARR_ELEMENT	"uxawk:96:You can only delete array[element]"
#define	_SGI_SNAWK_U_CAN_ONLY_DEL_ARR_ELEMENT	"You can only delete array[element]"
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_MSG_NUM	97
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_MSG_NUM_STR	":97"
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_CAT_NUM_STR	"uxawk:97"
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_DEF_MSG	"Next is illegal inside a function"
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_CAT_NUM_STR_DEF_MSG	"uxawk:97:Next is illegal inside a function"
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_MSG_NUM_STR_DEF_MSG	":97:Next is illegal inside a function"
#define	_MSG_NAWK_NEXT_IN_FUNC_IS_ILLEGAL_FILE_CAT_NUM	uxawk:97
#define	_SGI_DNAWK_NEXT_IN_FUNC_IS_ILLEGAL	":97"
#define	_SGI_NAWK_NEXT_IN_FUNC_IS_ILLEGAL	"uxawk:97"
#define	_SGI_MNAWK_NEXT_IN_FUNC_IS_ILLEGAL	"uxawk:97:Next is illegal inside a function"
#define	_SGI_SNAWK_NEXT_IN_FUNC_IS_ILLEGAL	"Next is illegal inside a function"
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_MSG_NUM	98
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_MSG_NUM_STR	":98"
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_CAT_NUM_STR	"uxawk:98"
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_DEF_MSG	"Index() doesn't permit regular expressions"
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_CAT_NUM_STR_DEF_MSG	"uxawk:98:Index() doesn't permit regular expressions"
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_MSG_NUM_STR_DEF_MSG	":98:Index() doesn't permit regular expressions"
#define	_MSG_NAWK_INDEX_NOT_PERMIT_REG_EXP_FILE_CAT_NUM	uxawk:98
#define	_SGI_DNAWK_INDEX_NOT_PERMIT_REG_EXP	":98"
#define	_SGI_NAWK_INDEX_NOT_PERMIT_REG_EXP	"uxawk:98"
#define	_SGI_MNAWK_INDEX_NOT_PERMIT_REG_EXP	"uxawk:98:Index() doesn't permit regular expressions"
#define	_SGI_SNAWK_INDEX_NOT_PERMIT_REG_EXP	"Index() doesn't permit regular expressions"
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_MSG_NUM	99
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_MSG_NUM_STR	":99"
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_CAT_NUM_STR	"uxawk:99"
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_DEF_MSG	"%s is an array, not a function"
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_CAT_NUM_STR_DEF_MSG	"uxawk:99:%s is an array, not a function"
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_MSG_NUM_STR_DEF_MSG	":99:%s is an array, not a function"
#define	_MSG_NAWK_STR_IS_AN_ARR_NOT_A_FUNC_FILE_CAT_NUM	uxawk:99
#define	_SGI_DNAWK_STR_IS_AN_ARR_NOT_A_FUNC	":99"
#define	_SGI_NAWK_STR_IS_AN_ARR_NOT_A_FUNC	"uxawk:99"
#define	_SGI_MNAWK_STR_IS_AN_ARR_NOT_A_FUNC	"uxawk:99:%s is an array, not a function"
#define	_SGI_SNAWK_STR_IS_AN_ARR_NOT_A_FUNC	"%s is an array, not a function"
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_MSG_NUM	100
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_MSG_NUM_STR	":100"
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_CAT_NUM_STR	"uxawk:100"
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_DEF_MSG	"You cannot define function %s more than once"
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_CAT_NUM_STR_DEF_MSG	"uxawk:100:You cannot define function %s more than once"
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_MSG_NUM_STR_DEF_MSG	":100:You cannot define function %s more than once"
#define	_MSG_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE_FILE_CAT_NUM	uxawk:100
#define	_SGI_DNAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE	":100"
#define	_SGI_NAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE	"uxawk:100"
#define	_SGI_MNAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE	"uxawk:100:You cannot define function %s more than once"
#define	_SGI_SNAWK_CANNOT_DEFN_FUNC_MORE_THAN_ONCE	"You cannot define function %s more than once"
#define	_MSG_NAWK_GOTXPG_MSG_NUM	101
#define	_MSG_NAWK_GOTXPG_MSG_NUM_STR	":101"
#define	_MSG_NAWK_GOTXPG_CAT_NUM_STR	"uxawk:101"
#define	_MSG_NAWK_GOTXPG_DEF_MSG	"awk:Cannot exec /usr/bin/pawk"
#define	_MSG_NAWK_GOTXPG_CAT_NUM_STR_DEF_MSG	"uxawk:101:awk:Cannot exec /usr/bin/pawk"
#define	_MSG_NAWK_GOTXPG_MSG_NUM_STR_DEF_MSG	":101:awk:Cannot exec /usr/bin/pawk"
#define	_MSG_NAWK_GOTXPG_FILE_CAT_NUM	uxawk:101
#define	_SGI_DNAWK_GOTXPG	":101"
#define	_SGI_NAWK_GOTXPG	"uxawk:101"
#define	_SGI_MNAWK_GOTXPG	"uxawk:101:awk:Cannot exec /usr/bin/pawk"
#define	_SGI_SNAWK_GOTXPG	"awk:Cannot exec /usr/bin/pawk"
#define	_MSG_NAWK_QSTRING_MSG_NUM	102
#define	_MSG_NAWK_QSTRING_MSG_NUM_STR	":102"
#define	_MSG_NAWK_QSTRING_CAT_NUM_STR	"uxawk:102"
#define	_MSG_NAWK_QSTRING_DEF_MSG	"mbtowc failed in qstring"
#define	_MSG_NAWK_QSTRING_CAT_NUM_STR_DEF_MSG	"uxawk:102:mbtowc failed in qstring"
#define	_MSG_NAWK_QSTRING_MSG_NUM_STR_DEF_MSG	":102:mbtowc failed in qstring"
#define	_MSG_NAWK_QSTRING_FILE_CAT_NUM	uxawk:102
#define	_SGI_DNAWK_QSTRING	":102"
#define	_SGI_NAWK_QSTRING	"uxawk:102"
#define	_SGI_MNAWK_QSTRING	"uxawk:102:mbtowc failed in qstring"
#define	_SGI_SNAWK_QSTRING	"mbtowc failed in qstring"
#define	_MSG_NAWK_SFORMAT1_MSG_NUM	103
#define	_MSG_NAWK_SFORMAT1_MSG_NUM_STR	":103"
#define	_MSG_NAWK_SFORMAT1_CAT_NUM_STR	"uxawk:103"
#define	_MSG_NAWK_SFORMAT1_DEF_MSG	"mblen failed in sformat"
#define	_MSG_NAWK_SFORMAT1_CAT_NUM_STR_DEF_MSG	"uxawk:103:mblen failed in sformat"
#define	_MSG_NAWK_SFORMAT1_MSG_NUM_STR_DEF_MSG	":103:mblen failed in sformat"
#define	_MSG_NAWK_SFORMAT1_FILE_CAT_NUM	uxawk:103
#define	_SGI_DNAWK_SFORMAT1	":103"
#define	_SGI_NAWK_SFORMAT1	"uxawk:103"
#define	_SGI_MNAWK_SFORMAT1	"uxawk:103:mblen failed in sformat"
#define	_SGI_SNAWK_SFORMAT1	"mblen failed in sformat"
#define	_MSG_NAWK_SFORMAT2_MSG_NUM	104
#define	_MSG_NAWK_SFORMAT2_MSG_NUM_STR	":104"
#define	_MSG_NAWK_SFORMAT2_CAT_NUM_STR	"uxawk:104"
#define	_MSG_NAWK_SFORMAT2_DEF_MSG	"mbstowcs failed in sformat"
#define	_MSG_NAWK_SFORMAT2_CAT_NUM_STR_DEF_MSG	"uxawk:104:mbstowcs failed in sformat"
#define	_MSG_NAWK_SFORMAT2_MSG_NUM_STR_DEF_MSG	":104:mbstowcs failed in sformat"
#define	_MSG_NAWK_SFORMAT2_FILE_CAT_NUM	uxawk:104
#define	_SGI_DNAWK_SFORMAT2	":104"
#define	_SGI_NAWK_SFORMAT2	"uxawk:104"
#define	_SGI_MNAWK_SFORMAT2	"uxawk:104:mbstowcs failed in sformat"
#define	_SGI_SNAWK_SFORMAT2	"mbstowcs failed in sformat"
#define	_MSG_NAWK_SFORMAT3_MSG_NUM	105
#define	_MSG_NAWK_SFORMAT3_MSG_NUM_STR	":105"
#define	_MSG_NAWK_SFORMAT3_CAT_NUM_STR	"uxawk:105"
#define	_MSG_NAWK_SFORMAT3_DEF_MSG	"mbtowc failed in sformat"
#define	_MSG_NAWK_SFORMAT3_CAT_NUM_STR_DEF_MSG	"uxawk:105:mbtowc failed in sformat"
#define	_MSG_NAWK_SFORMAT3_MSG_NUM_STR_DEF_MSG	":105:mbtowc failed in sformat"
#define	_MSG_NAWK_SFORMAT3_FILE_CAT_NUM	uxawk:105
#define	_SGI_DNAWK_SFORMAT3	":105"
#define	_SGI_NAWK_SFORMAT3	"uxawk:105"
#define	_SGI_MNAWK_SFORMAT3	"uxawk:105:mbtowc failed in sformat"
#define	_SGI_SNAWK_SFORMAT3	"mbtowc failed in sformat"
#define	_MSG_NAWK_FFORMAT1_MSG_NUM	106
#define	_MSG_NAWK_FFORMAT1_MSG_NUM_STR	":106"
#define	_MSG_NAWK_FFORMAT1_CAT_NUM_STR	"uxawk:106"
#define	_MSG_NAWK_FFORMAT1_DEF_MSG	"mblen failed in sformat"
#define	_MSG_NAWK_FFORMAT1_CAT_NUM_STR_DEF_MSG	"uxawk:106:mblen failed in sformat"
#define	_MSG_NAWK_FFORMAT1_MSG_NUM_STR_DEF_MSG	":106:mblen failed in sformat"
#define	_MSG_NAWK_FFORMAT1_FILE_CAT_NUM	uxawk:106
#define	_SGI_DNAWK_FFORMAT1	":106"
#define	_SGI_NAWK_FFORMAT1	"uxawk:106"
#define	_SGI_MNAWK_FFORMAT1	"uxawk:106:mblen failed in sformat"
#define	_SGI_SNAWK_FFORMAT1	"mblen failed in sformat"
#define	_MSG_NAWK_FFORMAT2_MSG_NUM	107
#define	_MSG_NAWK_FFORMAT2_MSG_NUM_STR	":107"
#define	_MSG_NAWK_FFORMAT2_CAT_NUM_STR	"uxawk:107"
#define	_MSG_NAWK_FFORMAT2_DEF_MSG	"mbstowcs failed in sformat"
#define	_MSG_NAWK_FFORMAT2_CAT_NUM_STR_DEF_MSG	"uxawk:107:mbstowcs failed in sformat"
#define	_MSG_NAWK_FFORMAT2_MSG_NUM_STR_DEF_MSG	":107:mbstowcs failed in sformat"
#define	_MSG_NAWK_FFORMAT2_FILE_CAT_NUM	uxawk:107
#define	_SGI_DNAWK_FFORMAT2	":107"
#define	_SGI_NAWK_FFORMAT2	"uxawk:107"
#define	_SGI_MNAWK_FFORMAT2	"uxawk:107:mbstowcs failed in sformat"
#define	_SGI_SNAWK_FFORMAT2	"mbstowcs failed in sformat"
#define	_MSG_NAWK_FFORMAT3_MSG_NUM	108
#define	_MSG_NAWK_FFORMAT3_MSG_NUM_STR	":108"
#define	_MSG_NAWK_FFORMAT3_CAT_NUM_STR	"uxawk:108"
#define	_MSG_NAWK_FFORMAT3_DEF_MSG	"mbtowc failed in sformat"
#define	_MSG_NAWK_FFORMAT3_CAT_NUM_STR_DEF_MSG	"uxawk:108:mbtowc failed in sformat"
#define	_MSG_NAWK_FFORMAT3_MSG_NUM_STR_DEF_MSG	":108:mbtowc failed in sformat"
#define	_MSG_NAWK_FFORMAT3_FILE_CAT_NUM	uxawk:108
#define	_SGI_DNAWK_FFORMAT3	":108"
#define	_SGI_NAWK_FFORMAT3	"uxawk:108"
#define	_SGI_MNAWK_FFORMAT3	"uxawk:108:mbtowc failed in sformat"
#define	_SGI_SNAWK_FFORMAT3	"mbtowc failed in sformat"
#define	_MSG_NAWK_FLDBLD_MSG_NUM	109
#define	_MSG_NAWK_FLDBLD_MSG_NUM_STR	":109"
#define	_MSG_NAWK_FLDBLD_CAT_NUM_STR	"uxawk:109"
#define	_MSG_NAWK_FLDBLD_DEF_MSG	"mbtowc failed for field separator in fldbld"
#define	_MSG_NAWK_FLDBLD_CAT_NUM_STR_DEF_MSG	"uxawk:109:mbtowc failed for field separator in fldbld"
#define	_MSG_NAWK_FLDBLD_MSG_NUM_STR_DEF_MSG	":109:mbtowc failed for field separator in fldbld"
#define	_MSG_NAWK_FLDBLD_FILE_CAT_NUM	uxawk:109
#define	_SGI_DNAWK_FLDBLD	":109"
#define	_SGI_NAWK_FLDBLD	"uxawk:109"
#define	_SGI_MNAWK_FLDBLD	"uxawk:109:mbtowc failed for field separator in fldbld"
#define	_SGI_SNAWK_FLDBLD	"mbtowc failed for field separator in fldbld"
#define	_MSG_NAWK_ISCHAR_MSG_NUM	110
#define	_MSG_NAWK_ISCHAR_MSG_NUM_STR	":110"
#define	_MSG_NAWK_ISCHAR_CAT_NUM_STR	"uxawk:110"
#define	_MSG_NAWK_ISCHAR_DEF_MSG	"mblen failed in IsCharBoundary"
#define	_MSG_NAWK_ISCHAR_CAT_NUM_STR_DEF_MSG	"uxawk:110:mblen failed in IsCharBoundary"
#define	_MSG_NAWK_ISCHAR_MSG_NUM_STR_DEF_MSG	":110:mblen failed in IsCharBoundary"
#define	_MSG_NAWK_ISCHAR_FILE_CAT_NUM	uxawk:110
#define	_SGI_DNAWK_ISCHAR	":110"
#define	_SGI_NAWK_ISCHAR	"uxawk:110"
#define	_SGI_MNAWK_ISCHAR	"uxawk:110:mblen failed in IsCharBoundary"
#define	_SGI_SNAWK_ISCHAR	"mblen failed in IsCharBoundary"
#define	_MSG_NAWK_READREC_MSG_NUM	111
#define	_MSG_NAWK_READREC_MSG_NUM_STR	":111"
#define	_MSG_NAWK_READREC_CAT_NUM_STR	"uxawk:111"
#define	_MSG_NAWK_READREC_DEF_MSG	"mbtowc failed in readrec"
#define	_MSG_NAWK_READREC_CAT_NUM_STR_DEF_MSG	"uxawk:111:mbtowc failed in readrec"
#define	_MSG_NAWK_READREC_MSG_NUM_STR_DEF_MSG	":111:mbtowc failed in readrec"
#define	_MSG_NAWK_READREC_FILE_CAT_NUM	uxawk:111
#define	_SGI_DNAWK_READREC	":111"
#define	_SGI_NAWK_READREC	"uxawk:111"
#define	_SGI_MNAWK_READREC	"uxawk:111:mbtowc failed in readrec"
#define	_SGI_SNAWK_READREC	"mbtowc failed in readrec"
#define	_MSG_NAWK_BLTIN_MSG_NUM	112
#define	_MSG_NAWK_BLTIN_MSG_NUM_STR	":112"
#define	_MSG_NAWK_BLTIN_CAT_NUM_STR	"uxawk:112"
#define	_MSG_NAWK_BLTIN_DEF_MSG	"mbstowcs failed in bltin"
#define	_MSG_NAWK_BLTIN_CAT_NUM_STR_DEF_MSG	"uxawk:112:mbstowcs failed in bltin"
#define	_MSG_NAWK_BLTIN_MSG_NUM_STR_DEF_MSG	":112:mbstowcs failed in bltin"
#define	_MSG_NAWK_BLTIN_FILE_CAT_NUM	uxawk:112
#define	_SGI_DNAWK_BLTIN	":112"
#define	_SGI_NAWK_BLTIN	"uxawk:112"
#define	_SGI_MNAWK_BLTIN	"uxawk:112:mbstowcs failed in bltin"
#define	_SGI_SNAWK_BLTIN	"mbstowcs failed in bltin"
#define	_MSG_NAWK_MATCHOP_MSG_NUM	113
#define	_MSG_NAWK_MATCHOP_MSG_NUM_STR	":113"
#define	_MSG_NAWK_MATCHOP_CAT_NUM_STR	"uxawk:113"
#define	_MSG_NAWK_MATCHOP_DEF_MSG	"mbstowcs failed in matchop "
#define	_MSG_NAWK_MATCHOP_CAT_NUM_STR_DEF_MSG	"uxawk:113:mbstowcs failed in matchop "
#define	_MSG_NAWK_MATCHOP_MSG_NUM_STR_DEF_MSG	":113:mbstowcs failed in matchop "
#define	_MSG_NAWK_MATCHOP_FILE_CAT_NUM	uxawk:113
#define	_SGI_DNAWK_MATCHOP	":113"
#define	_SGI_NAWK_MATCHOP	"uxawk:113"
#define	_SGI_MNAWK_MATCHOP	"uxawk:113:mbstowcs failed in matchop "
#define	_SGI_SNAWK_MATCHOP	"mbstowcs failed in matchop "
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_MSG_NUM	114
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_MSG_NUM_STR	":114"
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_CAT_NUM_STR	"uxawk:114"
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_DEF_MSG	"Regular expression too big"
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_CAT_NUM_STR_DEF_MSG	"uxawk:114:Regular expression too big"
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_MSG_NUM_STR_DEF_MSG	":114:Regular expression too big"
#define	_MSG_NAWK_REGULAR_EXP_TOO_BIG_FILE_CAT_NUM	uxawk:114
#define	_SGI_DNAWK_REGULAR_EXP_TOO_BIG	":114"
#define	_SGI_NAWK_REGULAR_EXP_TOO_BIG	"uxawk:114"
#define	_SGI_MNAWK_REGULAR_EXP_TOO_BIG	"uxawk:114:Regular expression too big"
#define	_SGI_SNAWK_REGULAR_EXP_TOO_BIG	"Regular expression too big"
#define	_MSG_NAWK_VARIABLE_EMPTY_MSG_NUM	115
#define	_MSG_NAWK_VARIABLE_EMPTY_MSG_NUM_STR	":115"
#define	_MSG_NAWK_VARIABLE_EMPTY_CAT_NUM_STR	"uxawk:115"
#define	_MSG_NAWK_VARIABLE_EMPTY_DEF_MSG	"No variable specified after -v switch"
#define	_MSG_NAWK_VARIABLE_EMPTY_CAT_NUM_STR_DEF_MSG	"uxawk:115:No variable specified after -v switch"
#define	_MSG_NAWK_VARIABLE_EMPTY_MSG_NUM_STR_DEF_MSG	":115:No variable specified after -v switch"
#define	_MSG_NAWK_VARIABLE_EMPTY_FILE_CAT_NUM	uxawk:115
#define	_SGI_DNAWK_VARIABLE_EMPTY	":115"
#define	_SGI_NAWK_VARIABLE_EMPTY	"uxawk:115"
#define	_SGI_MNAWK_VARIABLE_EMPTY	"uxawk:115:No variable specified after -v switch"
#define	_SGI_SNAWK_VARIABLE_EMPTY	"No variable specified after -v switch"
