#include <mkmsgs.h>
#define	_MSG_t_strerror_0_MSG_NUM	1
#define	_MSG_t_strerror_0_MSG_NUM_STR	":1"
#define	_MSG_t_strerror_0_CAT_NUM_STR	"uxlibxnet:1"
#define	_MSG_t_strerror_0_DEF_MSG	"No Error"
#define	_MSG_t_strerror_0_CAT_NUM_STR_DEF_MSG	"uxlibxnet:1:No Error"
#define	_MSG_t_strerror_0_MSG_NUM_STR_DEF_MSG	":1:No Error"
#define	_MSG_t_strerror_0_FILE_CAT_NUM	uxlibxnet:1
#define	_SGI_Dt_strerror_0	":1"
#define	_SGI_t_strerror_0	"uxlibxnet:1"
#define	_SGI_Mt_strerror_0	"uxlibxnet:1:No Error"
#define	_SGI_St_strerror_0	"No Error"
#define	_MSG_t_strerror_TBADADDR_MSG_NUM	2
#define	_MSG_t_strerror_TBADADDR_MSG_NUM_STR	":2"
#define	_MSG_t_strerror_TBADADDR_CAT_NUM_STR	"uxlibxnet:2"
#define	_MSG_t_strerror_TBADADDR_DEF_MSG	"incorrect addr format"
#define	_MSG_t_strerror_TBADADDR_CAT_NUM_STR_DEF_MSG	"uxlibxnet:2:incorrect addr format"
#define	_MSG_t_strerror_TBADADDR_MSG_NUM_STR_DEF_MSG	":2:incorrect addr format"
#define	_MSG_t_strerror_TBADADDR_FILE_CAT_NUM	uxlibxnet:2
#define	_SGI_Dt_strerror_TBADADDR	":2"
#define	_SGI_t_strerror_TBADADDR	"uxlibxnet:2"
#define	_SGI_Mt_strerror_TBADADDR	"uxlibxnet:2:incorrect addr format"
#define	_SGI_St_strerror_TBADADDR	"incorrect addr format"
#define	_MSG_t_strerror_TBADOPT_MSG_NUM	3
#define	_MSG_t_strerror_TBADOPT_MSG_NUM_STR	":3"
#define	_MSG_t_strerror_TBADOPT_CAT_NUM_STR	"uxlibxnet:3"
#define	_MSG_t_strerror_TBADOPT_DEF_MSG	"incorrect option format"
#define	_MSG_t_strerror_TBADOPT_CAT_NUM_STR_DEF_MSG	"uxlibxnet:3:incorrect option format"
#define	_MSG_t_strerror_TBADOPT_MSG_NUM_STR_DEF_MSG	":3:incorrect option format"
#define	_MSG_t_strerror_TBADOPT_FILE_CAT_NUM	uxlibxnet:3
#define	_SGI_Dt_strerror_TBADOPT	":3"
#define	_SGI_t_strerror_TBADOPT	"uxlibxnet:3"
#define	_SGI_Mt_strerror_TBADOPT	"uxlibxnet:3:incorrect option format"
#define	_SGI_St_strerror_TBADOPT	"incorrect option format"
#define	_MSG_t_strerror_TACCES_MSG_NUM	4
#define	_MSG_t_strerror_TACCES_MSG_NUM_STR	":4"
#define	_MSG_t_strerror_TACCES_CAT_NUM_STR	"uxlibxnet:4"
#define	_MSG_t_strerror_TACCES_DEF_MSG	"incorrect permissions"
#define	_MSG_t_strerror_TACCES_CAT_NUM_STR_DEF_MSG	"uxlibxnet:4:incorrect permissions"
#define	_MSG_t_strerror_TACCES_MSG_NUM_STR_DEF_MSG	":4:incorrect permissions"
#define	_MSG_t_strerror_TACCES_FILE_CAT_NUM	uxlibxnet:4
#define	_SGI_Dt_strerror_TACCES	":4"
#define	_SGI_t_strerror_TACCES	"uxlibxnet:4"
#define	_SGI_Mt_strerror_TACCES	"uxlibxnet:4:incorrect permissions"
#define	_SGI_St_strerror_TACCES	"incorrect permissions"
#define	_MSG_t_strerror_TBADF_MSG_NUM	5
#define	_MSG_t_strerror_TBADF_MSG_NUM_STR	":5"
#define	_MSG_t_strerror_TBADF_CAT_NUM_STR	"uxlibxnet:5"
#define	_MSG_t_strerror_TBADF_DEF_MSG	"illegal transport fd"
#define	_MSG_t_strerror_TBADF_CAT_NUM_STR_DEF_MSG	"uxlibxnet:5:illegal transport fd"
#define	_MSG_t_strerror_TBADF_MSG_NUM_STR_DEF_MSG	":5:illegal transport fd"
#define	_MSG_t_strerror_TBADF_FILE_CAT_NUM	uxlibxnet:5
#define	_SGI_Dt_strerror_TBADF	":5"
#define	_SGI_t_strerror_TBADF	"uxlibxnet:5"
#define	_SGI_Mt_strerror_TBADF	"uxlibxnet:5:illegal transport fd"
#define	_SGI_St_strerror_TBADF	"illegal transport fd"
#define	_MSG_t_strerror_TNOADDR_MSG_NUM	6
#define	_MSG_t_strerror_TNOADDR_MSG_NUM_STR	":6"
#define	_MSG_t_strerror_TNOADDR_CAT_NUM_STR	"uxlibxnet:6"
#define	_MSG_t_strerror_TNOADDR_DEF_MSG	"couldn't allocate addr"
#define	_MSG_t_strerror_TNOADDR_CAT_NUM_STR_DEF_MSG	"uxlibxnet:6:couldn't allocate addr"
#define	_MSG_t_strerror_TNOADDR_MSG_NUM_STR_DEF_MSG	":6:couldn't allocate addr"
#define	_MSG_t_strerror_TNOADDR_FILE_CAT_NUM	uxlibxnet:6
#define	_SGI_Dt_strerror_TNOADDR	":6"
#define	_SGI_t_strerror_TNOADDR	"uxlibxnet:6"
#define	_SGI_Mt_strerror_TNOADDR	"uxlibxnet:6:couldn't allocate addr"
#define	_SGI_St_strerror_TNOADDR	"couldn't allocate addr"
#define	_MSG_t_strerror_TOUTSTAT_MSG_NUM	7
#define	_MSG_t_strerror_TOUTSTAT_MSG_NUM_STR	":7"
#define	_MSG_t_strerror_TOUTSTAT_CAT_NUM_STR	"uxlibxnet:7"
#define	_MSG_t_strerror_TOUTSTAT_DEF_MSG	"out of state"
#define	_MSG_t_strerror_TOUTSTAT_CAT_NUM_STR_DEF_MSG	"uxlibxnet:7:out of state"
#define	_MSG_t_strerror_TOUTSTAT_MSG_NUM_STR_DEF_MSG	":7:out of state"
#define	_MSG_t_strerror_TOUTSTAT_FILE_CAT_NUM	uxlibxnet:7
#define	_SGI_Dt_strerror_TOUTSTAT	":7"
#define	_SGI_t_strerror_TOUTSTAT	"uxlibxnet:7"
#define	_SGI_Mt_strerror_TOUTSTAT	"uxlibxnet:7:out of state"
#define	_SGI_St_strerror_TOUTSTAT	"out of state"
#define	_MSG_t_strerror_TBADSEQ_MSG_NUM	8
#define	_MSG_t_strerror_TBADSEQ_MSG_NUM_STR	":8"
#define	_MSG_t_strerror_TBADSEQ_CAT_NUM_STR	"uxlibxnet:8"
#define	_MSG_t_strerror_TBADSEQ_DEF_MSG	"bad call sequence number"
#define	_MSG_t_strerror_TBADSEQ_CAT_NUM_STR_DEF_MSG	"uxlibxnet:8:bad call sequence number"
#define	_MSG_t_strerror_TBADSEQ_MSG_NUM_STR_DEF_MSG	":8:bad call sequence number"
#define	_MSG_t_strerror_TBADSEQ_FILE_CAT_NUM	uxlibxnet:8
#define	_SGI_Dt_strerror_TBADSEQ	":8"
#define	_SGI_t_strerror_TBADSEQ	"uxlibxnet:8"
#define	_SGI_Mt_strerror_TBADSEQ	"uxlibxnet:8:bad call sequence number"
#define	_SGI_St_strerror_TBADSEQ	"bad call sequence number"
#define	_MSG_t_strerror_TSYSERR_MSG_NUM	9
#define	_MSG_t_strerror_TSYSERR_MSG_NUM_STR	":9"
#define	_MSG_t_strerror_TSYSERR_CAT_NUM_STR	"uxlibxnet:9"
#define	_MSG_t_strerror_TSYSERR_DEF_MSG	"system error"
#define	_MSG_t_strerror_TSYSERR_CAT_NUM_STR_DEF_MSG	"uxlibxnet:9:system error"
#define	_MSG_t_strerror_TSYSERR_MSG_NUM_STR_DEF_MSG	":9:system error"
#define	_MSG_t_strerror_TSYSERR_FILE_CAT_NUM	uxlibxnet:9
#define	_SGI_Dt_strerror_TSYSERR	":9"
#define	_SGI_t_strerror_TSYSERR	"uxlibxnet:9"
#define	_SGI_Mt_strerror_TSYSERR	"uxlibxnet:9:system error"
#define	_SGI_St_strerror_TSYSERR	"system error"
#define	_MSG_t_strerror_TLOOK_MSG_NUM	10
#define	_MSG_t_strerror_TLOOK_MSG_NUM_STR	":10"
#define	_MSG_t_strerror_TLOOK_CAT_NUM_STR	"uxlibxnet:10"
#define	_MSG_t_strerror_TLOOK_DEF_MSG	"event requires attention"
#define	_MSG_t_strerror_TLOOK_CAT_NUM_STR_DEF_MSG	"uxlibxnet:10:event requires attention"
#define	_MSG_t_strerror_TLOOK_MSG_NUM_STR_DEF_MSG	":10:event requires attention"
#define	_MSG_t_strerror_TLOOK_FILE_CAT_NUM	uxlibxnet:10
#define	_SGI_Dt_strerror_TLOOK	":10"
#define	_SGI_t_strerror_TLOOK	"uxlibxnet:10"
#define	_SGI_Mt_strerror_TLOOK	"uxlibxnet:10:event requires attention"
#define	_SGI_St_strerror_TLOOK	"event requires attention"
#define	_MSG_t_strerror_TBADDATA_MSG_NUM	11
#define	_MSG_t_strerror_TBADDATA_MSG_NUM_STR	":11"
#define	_MSG_t_strerror_TBADDATA_CAT_NUM_STR	"uxlibxnet:11"
#define	_MSG_t_strerror_TBADDATA_DEF_MSG	"illegal amount of data"
#define	_MSG_t_strerror_TBADDATA_CAT_NUM_STR_DEF_MSG	"uxlibxnet:11:illegal amount of data"
#define	_MSG_t_strerror_TBADDATA_MSG_NUM_STR_DEF_MSG	":11:illegal amount of data"
#define	_MSG_t_strerror_TBADDATA_FILE_CAT_NUM	uxlibxnet:11
#define	_SGI_Dt_strerror_TBADDATA	":11"
#define	_SGI_t_strerror_TBADDATA	"uxlibxnet:11"
#define	_SGI_Mt_strerror_TBADDATA	"uxlibxnet:11:illegal amount of data"
#define	_SGI_St_strerror_TBADDATA	"illegal amount of data"
#define	_MSG_t_strerror_TBUFOVFLW_MSG_NUM	12
#define	_MSG_t_strerror_TBUFOVFLW_MSG_NUM_STR	":12"
#define	_MSG_t_strerror_TBUFOVFLW_CAT_NUM_STR	"uxlibxnet:12"
#define	_MSG_t_strerror_TBUFOVFLW_DEF_MSG	"buffer not large enough"
#define	_MSG_t_strerror_TBUFOVFLW_CAT_NUM_STR_DEF_MSG	"uxlibxnet:12:buffer not large enough"
#define	_MSG_t_strerror_TBUFOVFLW_MSG_NUM_STR_DEF_MSG	":12:buffer not large enough"
#define	_MSG_t_strerror_TBUFOVFLW_FILE_CAT_NUM	uxlibxnet:12
#define	_SGI_Dt_strerror_TBUFOVFLW	":12"
#define	_SGI_t_strerror_TBUFOVFLW	"uxlibxnet:12"
#define	_SGI_Mt_strerror_TBUFOVFLW	"uxlibxnet:12:buffer not large enough"
#define	_SGI_St_strerror_TBUFOVFLW	"buffer not large enough"
#define	_MSG_t_strerror_TFLOW_MSG_NUM	13
#define	_MSG_t_strerror_TFLOW_MSG_NUM_STR	":13"
#define	_MSG_t_strerror_TFLOW_CAT_NUM_STR	"uxlibxnet:13"
#define	_MSG_t_strerror_TFLOW_DEF_MSG	"flow control"
#define	_MSG_t_strerror_TFLOW_CAT_NUM_STR_DEF_MSG	"uxlibxnet:13:flow control"
#define	_MSG_t_strerror_TFLOW_MSG_NUM_STR_DEF_MSG	":13:flow control"
#define	_MSG_t_strerror_TFLOW_FILE_CAT_NUM	uxlibxnet:13
#define	_SGI_Dt_strerror_TFLOW	":13"
#define	_SGI_t_strerror_TFLOW	"uxlibxnet:13"
#define	_SGI_Mt_strerror_TFLOW	"uxlibxnet:13:flow control"
#define	_SGI_St_strerror_TFLOW	"flow control"
#define	_MSG_t_strerror_TNODATA_MSG_NUM	14
#define	_MSG_t_strerror_TNODATA_MSG_NUM_STR	":14"
#define	_MSG_t_strerror_TNODATA_CAT_NUM_STR	"uxlibxnet:14"
#define	_MSG_t_strerror_TNODATA_DEF_MSG	"no data"
#define	_MSG_t_strerror_TNODATA_CAT_NUM_STR_DEF_MSG	"uxlibxnet:14:no data"
#define	_MSG_t_strerror_TNODATA_MSG_NUM_STR_DEF_MSG	":14:no data"
#define	_MSG_t_strerror_TNODATA_FILE_CAT_NUM	uxlibxnet:14
#define	_SGI_Dt_strerror_TNODATA	":14"
#define	_SGI_t_strerror_TNODATA	"uxlibxnet:14"
#define	_SGI_Mt_strerror_TNODATA	"uxlibxnet:14:no data"
#define	_SGI_St_strerror_TNODATA	"no data"
#define	_MSG_t_strerror_TNODIS_MSG_NUM	15
#define	_MSG_t_strerror_TNODIS_MSG_NUM_STR	":15"
#define	_MSG_t_strerror_TNODIS_CAT_NUM_STR	"uxlibxnet:15"
#define	_MSG_t_strerror_TNODIS_DEF_MSG	"discon_ind not found on queue"
#define	_MSG_t_strerror_TNODIS_CAT_NUM_STR_DEF_MSG	"uxlibxnet:15:discon_ind not found on queue"
#define	_MSG_t_strerror_TNODIS_MSG_NUM_STR_DEF_MSG	":15:discon_ind not found on queue"
#define	_MSG_t_strerror_TNODIS_FILE_CAT_NUM	uxlibxnet:15
#define	_SGI_Dt_strerror_TNODIS	":15"
#define	_SGI_t_strerror_TNODIS	"uxlibxnet:15"
#define	_SGI_Mt_strerror_TNODIS	"uxlibxnet:15:discon_ind not found on queue"
#define	_SGI_St_strerror_TNODIS	"discon_ind not found on queue"
#define	_MSG_t_strerror_TNOUDERR_MSG_NUM	16
#define	_MSG_t_strerror_TNOUDERR_MSG_NUM_STR	":16"
#define	_MSG_t_strerror_TNOUDERR_CAT_NUM_STR	"uxlibxnet:16"
#define	_MSG_t_strerror_TNOUDERR_DEF_MSG	"unitdata error not found"
#define	_MSG_t_strerror_TNOUDERR_CAT_NUM_STR_DEF_MSG	"uxlibxnet:16:unitdata error not found"
#define	_MSG_t_strerror_TNOUDERR_MSG_NUM_STR_DEF_MSG	":16:unitdata error not found"
#define	_MSG_t_strerror_TNOUDERR_FILE_CAT_NUM	uxlibxnet:16
#define	_SGI_Dt_strerror_TNOUDERR	":16"
#define	_SGI_t_strerror_TNOUDERR	"uxlibxnet:16"
#define	_SGI_Mt_strerror_TNOUDERR	"uxlibxnet:16:unitdata error not found"
#define	_SGI_St_strerror_TNOUDERR	"unitdata error not found"
#define	_MSG_t_strerror_TBADFLAG_MSG_NUM	17
#define	_MSG_t_strerror_TBADFLAG_MSG_NUM_STR	":17"
#define	_MSG_t_strerror_TBADFLAG_CAT_NUM_STR	"uxlibxnet:17"
#define	_MSG_t_strerror_TBADFLAG_DEF_MSG	"bad flags"
#define	_MSG_t_strerror_TBADFLAG_CAT_NUM_STR_DEF_MSG	"uxlibxnet:17:bad flags"
#define	_MSG_t_strerror_TBADFLAG_MSG_NUM_STR_DEF_MSG	":17:bad flags"
#define	_MSG_t_strerror_TBADFLAG_FILE_CAT_NUM	uxlibxnet:17
#define	_SGI_Dt_strerror_TBADFLAG	":17"
#define	_SGI_t_strerror_TBADFLAG	"uxlibxnet:17"
#define	_SGI_Mt_strerror_TBADFLAG	"uxlibxnet:17:bad flags"
#define	_SGI_St_strerror_TBADFLAG	"bad flags"
#define	_MSG_t_strerror_TNOREL_MSG_NUM	18
#define	_MSG_t_strerror_TNOREL_MSG_NUM_STR	":18"
#define	_MSG_t_strerror_TNOREL_CAT_NUM_STR	"uxlibxnet:18"
#define	_MSG_t_strerror_TNOREL_DEF_MSG	"no ord rel found on queue"
#define	_MSG_t_strerror_TNOREL_CAT_NUM_STR_DEF_MSG	"uxlibxnet:18:no ord rel found on queue"
#define	_MSG_t_strerror_TNOREL_MSG_NUM_STR_DEF_MSG	":18:no ord rel found on queue"
#define	_MSG_t_strerror_TNOREL_FILE_CAT_NUM	uxlibxnet:18
#define	_SGI_Dt_strerror_TNOREL	":18"
#define	_SGI_t_strerror_TNOREL	"uxlibxnet:18"
#define	_SGI_Mt_strerror_TNOREL	"uxlibxnet:18:no ord rel found on queue"
#define	_SGI_St_strerror_TNOREL	"no ord rel found on queue"
#define	_MSG_t_strerror_TNOTSUPPORT_MSG_NUM	19
#define	_MSG_t_strerror_TNOTSUPPORT_MSG_NUM_STR	":19"
#define	_MSG_t_strerror_TNOTSUPPORT_CAT_NUM_STR	"uxlibxnet:19"
#define	_MSG_t_strerror_TNOTSUPPORT_DEF_MSG	"primitive/action not supported"
#define	_MSG_t_strerror_TNOTSUPPORT_CAT_NUM_STR_DEF_MSG	"uxlibxnet:19:primitive/action not supported"
#define	_MSG_t_strerror_TNOTSUPPORT_MSG_NUM_STR_DEF_MSG	":19:primitive/action not supported"
#define	_MSG_t_strerror_TNOTSUPPORT_FILE_CAT_NUM	uxlibxnet:19
#define	_SGI_Dt_strerror_TNOTSUPPORT	":19"
#define	_SGI_t_strerror_TNOTSUPPORT	"uxlibxnet:19"
#define	_SGI_Mt_strerror_TNOTSUPPORT	"uxlibxnet:19:primitive/action not supported"
#define	_SGI_St_strerror_TNOTSUPPORT	"primitive/action not supported"
#define	_MSG_t_strerror_TSTATECHNG_MSG_NUM	20
#define	_MSG_t_strerror_TSTATECHNG_MSG_NUM_STR	":20"
#define	_MSG_t_strerror_TSTATECHNG_CAT_NUM_STR	"uxlibxnet:20"
#define	_MSG_t_strerror_TSTATECHNG_DEF_MSG	"state is in process of changing"
#define	_MSG_t_strerror_TSTATECHNG_CAT_NUM_STR_DEF_MSG	"uxlibxnet:20:state is in process of changing"
#define	_MSG_t_strerror_TSTATECHNG_MSG_NUM_STR_DEF_MSG	":20:state is in process of changing"
#define	_MSG_t_strerror_TSTATECHNG_FILE_CAT_NUM	uxlibxnet:20
#define	_SGI_Dt_strerror_TSTATECHNG	":20"
#define	_SGI_t_strerror_TSTATECHNG	"uxlibxnet:20"
#define	_SGI_Mt_strerror_TSTATECHNG	"uxlibxnet:20:state is in process of changing"
#define	_SGI_St_strerror_TSTATECHNG	"state is in process of changing"
#define	_MSG_t_strerror_TNOSTRUCTYPE_MSG_NUM	21
#define	_MSG_t_strerror_TNOSTRUCTYPE_MSG_NUM_STR	":21"
#define	_MSG_t_strerror_TNOSTRUCTYPE_CAT_NUM_STR	"uxlibxnet:21"
#define	_MSG_t_strerror_TNOSTRUCTYPE_DEF_MSG	"unsupported struct-type requested"
#define	_MSG_t_strerror_TNOSTRUCTYPE_CAT_NUM_STR_DEF_MSG	"uxlibxnet:21:unsupported struct-type requested"
#define	_MSG_t_strerror_TNOSTRUCTYPE_MSG_NUM_STR_DEF_MSG	":21:unsupported struct-type requested"
#define	_MSG_t_strerror_TNOSTRUCTYPE_FILE_CAT_NUM	uxlibxnet:21
#define	_SGI_Dt_strerror_TNOSTRUCTYPE	":21"
#define	_SGI_t_strerror_TNOSTRUCTYPE	"uxlibxnet:21"
#define	_SGI_Mt_strerror_TNOSTRUCTYPE	"uxlibxnet:21:unsupported struct-type requested"
#define	_SGI_St_strerror_TNOSTRUCTYPE	"unsupported struct-type requested"
#define	_MSG_t_strerror_TBADNAME_MSG_NUM	22
#define	_MSG_t_strerror_TBADNAME_MSG_NUM_STR	":22"
#define	_MSG_t_strerror_TBADNAME_CAT_NUM_STR	"uxlibxnet:22"
#define	_MSG_t_strerror_TBADNAME_DEF_MSG	"invalid transport provider name"
#define	_MSG_t_strerror_TBADNAME_CAT_NUM_STR_DEF_MSG	"uxlibxnet:22:invalid transport provider name"
#define	_MSG_t_strerror_TBADNAME_MSG_NUM_STR_DEF_MSG	":22:invalid transport provider name"
#define	_MSG_t_strerror_TBADNAME_FILE_CAT_NUM	uxlibxnet:22
#define	_SGI_Dt_strerror_TBADNAME	":22"
#define	_SGI_t_strerror_TBADNAME	"uxlibxnet:22"
#define	_SGI_Mt_strerror_TBADNAME	"uxlibxnet:22:invalid transport provider name"
#define	_SGI_St_strerror_TBADNAME	"invalid transport provider name"
#define	_MSG_t_strerror_TBADQLEN_MSG_NUM	23
#define	_MSG_t_strerror_TBADQLEN_MSG_NUM_STR	":23"
#define	_MSG_t_strerror_TBADQLEN_CAT_NUM_STR	"uxlibxnet:23"
#define	_MSG_t_strerror_TBADQLEN_DEF_MSG	"qlen is zero"
#define	_MSG_t_strerror_TBADQLEN_CAT_NUM_STR_DEF_MSG	"uxlibxnet:23:qlen is zero"
#define	_MSG_t_strerror_TBADQLEN_MSG_NUM_STR_DEF_MSG	":23:qlen is zero"
#define	_MSG_t_strerror_TBADQLEN_FILE_CAT_NUM	uxlibxnet:23
#define	_SGI_Dt_strerror_TBADQLEN	":23"
#define	_SGI_t_strerror_TBADQLEN	"uxlibxnet:23"
#define	_SGI_Mt_strerror_TBADQLEN	"uxlibxnet:23:qlen is zero"
#define	_SGI_St_strerror_TBADQLEN	"qlen is zero"
#define	_MSG_t_strerror_TADDRBUSY_MSG_NUM	24
#define	_MSG_t_strerror_TADDRBUSY_MSG_NUM_STR	":24"
#define	_MSG_t_strerror_TADDRBUSY_CAT_NUM_STR	"uxlibxnet:24"
#define	_MSG_t_strerror_TADDRBUSY_DEF_MSG	"address in use"
#define	_MSG_t_strerror_TADDRBUSY_CAT_NUM_STR_DEF_MSG	"uxlibxnet:24:address in use"
#define	_MSG_t_strerror_TADDRBUSY_MSG_NUM_STR_DEF_MSG	":24:address in use"
#define	_MSG_t_strerror_TADDRBUSY_FILE_CAT_NUM	uxlibxnet:24
#define	_SGI_Dt_strerror_TADDRBUSY	":24"
#define	_SGI_t_strerror_TADDRBUSY	"uxlibxnet:24"
#define	_SGI_Mt_strerror_TADDRBUSY	"uxlibxnet:24:address in use"
#define	_SGI_St_strerror_TADDRBUSY	"address in use"
#define	_MSG_t_strerror_TINDOUT_MSG_NUM	25
#define	_MSG_t_strerror_TINDOUT_MSG_NUM_STR	":25"
#define	_MSG_t_strerror_TINDOUT_CAT_NUM_STR	"uxlibxnet:25"
#define	_MSG_t_strerror_TINDOUT_DEF_MSG	"outstanding connection indications"
#define	_MSG_t_strerror_TINDOUT_CAT_NUM_STR_DEF_MSG	"uxlibxnet:25:outstanding connection indications"
#define	_MSG_t_strerror_TINDOUT_MSG_NUM_STR_DEF_MSG	":25:outstanding connection indications"
#define	_MSG_t_strerror_TINDOUT_FILE_CAT_NUM	uxlibxnet:25
#define	_SGI_Dt_strerror_TINDOUT	":25"
#define	_SGI_t_strerror_TINDOUT	"uxlibxnet:25"
#define	_SGI_Mt_strerror_TINDOUT	"uxlibxnet:25:outstanding connection indications"
#define	_SGI_St_strerror_TINDOUT	"outstanding connection indications"
#define	_MSG_t_strerror_TPROVMISMATCH_MSG_NUM	26
#define	_MSG_t_strerror_TPROVMISMATCH_MSG_NUM_STR	":26"
#define	_MSG_t_strerror_TPROVMISMATCH_CAT_NUM_STR	"uxlibxnet:26"
#define	_MSG_t_strerror_TPROVMISMATCH_DEF_MSG	"transport provider mismatch"
#define	_MSG_t_strerror_TPROVMISMATCH_CAT_NUM_STR_DEF_MSG	"uxlibxnet:26:transport provider mismatch"
#define	_MSG_t_strerror_TPROVMISMATCH_MSG_NUM_STR_DEF_MSG	":26:transport provider mismatch"
#define	_MSG_t_strerror_TPROVMISMATCH_FILE_CAT_NUM	uxlibxnet:26
#define	_SGI_Dt_strerror_TPROVMISMATCH	":26"
#define	_SGI_t_strerror_TPROVMISMATCH	"uxlibxnet:26"
#define	_SGI_Mt_strerror_TPROVMISMATCH	"uxlibxnet:26:transport provider mismatch"
#define	_SGI_St_strerror_TPROVMISMATCH	"transport provider mismatch"
#define	_MSG_t_strerror_TRESADDR_A_MSG_NUM	27
#define	_MSG_t_strerror_TRESADDR_A_MSG_NUM_STR	":27"
#define	_MSG_t_strerror_TRESADDR_A_CAT_NUM_STR	"uxlibxnet:27"
#define	_MSG_t_strerror_TRESADDR_A_DEF_MSG	"resfd specified to accept w/qlen >0"
#define	_MSG_t_strerror_TRESADDR_A_CAT_NUM_STR_DEF_MSG	"uxlibxnet:27:resfd specified to accept w/qlen >0"
#define	_MSG_t_strerror_TRESADDR_A_MSG_NUM_STR_DEF_MSG	":27:resfd specified to accept w/qlen >0"
#define	_MSG_t_strerror_TRESADDR_A_FILE_CAT_NUM	uxlibxnet:27
#define	_SGI_Dt_strerror_TRESADDR_A	":27"
#define	_SGI_t_strerror_TRESADDR_A	"uxlibxnet:27"
#define	_SGI_Mt_strerror_TRESADDR_A	"uxlibxnet:27:resfd specified to accept w/qlen >0"
#define	_SGI_St_strerror_TRESADDR_A	"resfd specified to accept w/qlen >0"
#define	_MSG_t_strerror_TRESADDR_B_MSG_NUM	28
#define	_MSG_t_strerror_TRESADDR_B_MSG_NUM_STR	":28"
#define	_MSG_t_strerror_TRESADDR_B_CAT_NUM_STR	"uxlibxnet:28"
#define	_MSG_t_strerror_TRESADDR_B_DEF_MSG	"resfd not bound to same addr as fd"
#define	_MSG_t_strerror_TRESADDR_B_CAT_NUM_STR_DEF_MSG	"uxlibxnet:28:resfd not bound to same addr as fd"
#define	_MSG_t_strerror_TRESADDR_B_MSG_NUM_STR_DEF_MSG	":28:resfd not bound to same addr as fd"
#define	_MSG_t_strerror_TRESADDR_B_FILE_CAT_NUM	uxlibxnet:28
#define	_SGI_Dt_strerror_TRESADDR_B	":28"
#define	_SGI_t_strerror_TRESADDR_B	"uxlibxnet:28"
#define	_SGI_Mt_strerror_TRESADDR_B	"uxlibxnet:28:resfd not bound to same addr as fd"
#define	_SGI_St_strerror_TRESADDR_B	"resfd not bound to same addr as fd"
#define	_MSG_t_strerror_TQFULL_MSG_NUM	29
#define	_MSG_t_strerror_TQFULL_MSG_NUM_STR	":29"
#define	_MSG_t_strerror_TQFULL_CAT_NUM_STR	"uxlibxnet:29"
#define	_MSG_t_strerror_TQFULL_DEF_MSG	"incoming connection queue full"
#define	_MSG_t_strerror_TQFULL_CAT_NUM_STR_DEF_MSG	"uxlibxnet:29:incoming connection queue full"
#define	_MSG_t_strerror_TQFULL_MSG_NUM_STR_DEF_MSG	":29:incoming connection queue full"
#define	_MSG_t_strerror_TQFULL_FILE_CAT_NUM	uxlibxnet:29
#define	_SGI_Dt_strerror_TQFULL	":29"
#define	_SGI_t_strerror_TQFULL	"uxlibxnet:29"
#define	_SGI_Mt_strerror_TQFULL	"uxlibxnet:29:incoming connection queue full"
#define	_SGI_St_strerror_TQFULL	"incoming connection queue full"
#define	_MSG_t_strerror_TPROTO_MSG_NUM	30
#define	_MSG_t_strerror_TPROTO_MSG_NUM_STR	":30"
#define	_MSG_t_strerror_TPROTO_CAT_NUM_STR	"uxlibxnet:30"
#define	_MSG_t_strerror_TPROTO_DEF_MSG	"XTI protocol error"
#define	_MSG_t_strerror_TPROTO_CAT_NUM_STR_DEF_MSG	"uxlibxnet:30:XTI protocol error"
#define	_MSG_t_strerror_TPROTO_MSG_NUM_STR_DEF_MSG	":30:XTI protocol error"
#define	_MSG_t_strerror_TPROTO_FILE_CAT_NUM	uxlibxnet:30
#define	_SGI_Dt_strerror_TPROTO	":30"
#define	_SGI_t_strerror_TPROTO	"uxlibxnet:30"
#define	_SGI_Mt_strerror_TPROTO	"uxlibxnet:30:XTI protocol error"
#define	_SGI_St_strerror_TPROTO	"XTI protocol error"
#define	_MSG_t_strerror_unknown_MSG_NUM	31
#define	_MSG_t_strerror_unknown_MSG_NUM_STR	":31"
#define	_MSG_t_strerror_unknown_CAT_NUM_STR	"uxlibxnet:31"
#define	_MSG_t_strerror_unknown_DEF_MSG	"%d: error unknown"
#define	_MSG_t_strerror_unknown_CAT_NUM_STR_DEF_MSG	"uxlibxnet:31:%d: error unknown"
#define	_MSG_t_strerror_unknown_MSG_NUM_STR_DEF_MSG	":31:%d: error unknown"
#define	_MSG_t_strerror_unknown_FILE_CAT_NUM	uxlibxnet:31
#define	_SGI_Dt_strerror_unknown	":31"
#define	_SGI_t_strerror_unknown	"uxlibxnet:31"
#define	_SGI_Mt_strerror_unknown	"uxlibxnet:31:%d: error unknown"
#define	_SGI_St_strerror_unknown	"%d: error unknown"
