#include <mkmsgs.h>
#define	_MSG_GETOPT_ILLOPT_MSG_NUM	1
#define	_MSG_GETOPT_ILLOPT_MSG_NUM_STR	":1"
#define	_MSG_GETOPT_ILLOPT_CAT_NUM_STR	"uxlibc:1"
#define	_MSG_GETOPT_ILLOPT_DEF_MSG	"Illegal option -- %c\n"
#define	_MSG_GETOPT_ILLOPT_CAT_NUM_STR_DEF_MSG	"uxlibc:1:Illegal option -- %c\n"
#define	_MSG_GETOPT_ILLOPT_MSG_NUM_STR_DEF_MSG	":1:Illegal option -- %c\n"
#define	_MSG_GETOPT_ILLOPT_FILE_CAT_NUM	uxlibc:1
#define	_SGI_DGETOPT_ILLOPT	":1"
#define	_SGI_GETOPT_ILLOPT	"uxlibc:1"
#define	_SGI_MGETOPT_ILLOPT	"uxlibc:1:Illegal option -- %c\n"
#define	_SGI_SGETOPT_ILLOPT	"Illegal option -- %c\n"
#define	_MSG_GETOPT_NO_ARG_MSG_NUM	2
#define	_MSG_GETOPT_NO_ARG_MSG_NUM_STR	":2"
#define	_MSG_GETOPT_NO_ARG_CAT_NUM_STR	"uxlibc:2"
#define	_MSG_GETOPT_NO_ARG_DEF_MSG	"Option requires an argument -- %c\n"
#define	_MSG_GETOPT_NO_ARG_CAT_NUM_STR_DEF_MSG	"uxlibc:2:Option requires an argument -- %c\n"
#define	_MSG_GETOPT_NO_ARG_MSG_NUM_STR_DEF_MSG	":2:Option requires an argument -- %c\n"
#define	_MSG_GETOPT_NO_ARG_FILE_CAT_NUM	uxlibc:2
#define	_SGI_DGETOPT_NO_ARG	":2"
#define	_SGI_GETOPT_NO_ARG	"uxlibc:2"
#define	_SGI_MGETOPT_NO_ARG	"uxlibc:2:Option requires an argument -- %c\n"
#define	_SGI_SGETOPT_NO_ARG	"Option requires an argument -- %c\n"
#define	_MSG_PFMT_DEF_COLON_MSG_NUM	3
#define	_MSG_PFMT_DEF_COLON_MSG_NUM_STR	":3"
#define	_MSG_PFMT_DEF_COLON_CAT_NUM_STR	"uxlibc:3"
#define	_MSG_PFMT_DEF_COLON_DEF_MSG	": "
#define	_MSG_PFMT_DEF_COLON_CAT_NUM_STR_DEF_MSG	"uxlibc:3:: "
#define	_MSG_PFMT_DEF_COLON_MSG_NUM_STR_DEF_MSG	":3:: "
#define	_MSG_PFMT_DEF_COLON_FILE_CAT_NUM	uxlibc:3
#define	_SGI_DPFMT_DEF_COLON	":3"
#define	_SGI_PFMT_DEF_COLON	"uxlibc:3"
#define	_SGI_MPFMT_DEF_COLON	"uxlibc:3:: "
#define	_SGI_SPFMT_DEF_COLON	": "
#define	_MSG_SIGNAL_0_MSG_NUM	4
#define	_MSG_SIGNAL_0_MSG_NUM_STR	":4"
#define	_MSG_SIGNAL_0_CAT_NUM_STR	"uxlibc:4"
#define	_MSG_SIGNAL_0_DEF_MSG	"Signal 0"
#define	_MSG_SIGNAL_0_CAT_NUM_STR_DEF_MSG	"uxlibc:4:Signal 0"
#define	_MSG_SIGNAL_0_MSG_NUM_STR_DEF_MSG	":4:Signal 0"
#define	_MSG_SIGNAL_0_FILE_CAT_NUM	uxlibc:4
#define	_SGI_DSIGNAL_0	":4"
#define	_SGI_SIGNAL_0	"uxlibc:4"
#define	_SGI_MSIGNAL_0	"uxlibc:4:Signal 0"
#define	_SGI_SSIGNAL_0	"Signal 0"
#define	_MSG_SIGNAL_1_MSG_NUM	5
#define	_MSG_SIGNAL_1_MSG_NUM_STR	":5"
#define	_MSG_SIGNAL_1_CAT_NUM_STR	"uxlibc:5"
#define	_MSG_SIGNAL_1_DEF_MSG	"Hangup"
#define	_MSG_SIGNAL_1_CAT_NUM_STR_DEF_MSG	"uxlibc:5:Hangup"
#define	_MSG_SIGNAL_1_MSG_NUM_STR_DEF_MSG	":5:Hangup"
#define	_MSG_SIGNAL_1_FILE_CAT_NUM	uxlibc:5
#define	_SGI_DSIGNAL_1	":5"
#define	_SGI_SIGNAL_1	"uxlibc:5"
#define	_SGI_MSIGNAL_1	"uxlibc:5:Hangup"
#define	_SGI_SSIGNAL_1	"Hangup"
#define	_MSG_SIGNAL_2_MSG_NUM	6
#define	_MSG_SIGNAL_2_MSG_NUM_STR	":6"
#define	_MSG_SIGNAL_2_CAT_NUM_STR	"uxlibc:6"
#define	_MSG_SIGNAL_2_DEF_MSG	"Interrupt"
#define	_MSG_SIGNAL_2_CAT_NUM_STR_DEF_MSG	"uxlibc:6:Interrupt"
#define	_MSG_SIGNAL_2_MSG_NUM_STR_DEF_MSG	":6:Interrupt"
#define	_MSG_SIGNAL_2_FILE_CAT_NUM	uxlibc:6
#define	_SGI_DSIGNAL_2	":6"
#define	_SGI_SIGNAL_2	"uxlibc:6"
#define	_SGI_MSIGNAL_2	"uxlibc:6:Interrupt"
#define	_SGI_SSIGNAL_2	"Interrupt"
#define	_MSG_SIGNAL_3_MSG_NUM	7
#define	_MSG_SIGNAL_3_MSG_NUM_STR	":7"
#define	_MSG_SIGNAL_3_CAT_NUM_STR	"uxlibc:7"
#define	_MSG_SIGNAL_3_DEF_MSG	"Quit"
#define	_MSG_SIGNAL_3_CAT_NUM_STR_DEF_MSG	"uxlibc:7:Quit"
#define	_MSG_SIGNAL_3_MSG_NUM_STR_DEF_MSG	":7:Quit"
#define	_MSG_SIGNAL_3_FILE_CAT_NUM	uxlibc:7
#define	_SGI_DSIGNAL_3	":7"
#define	_SGI_SIGNAL_3	"uxlibc:7"
#define	_SGI_MSIGNAL_3	"uxlibc:7:Quit"
#define	_SGI_SSIGNAL_3	"Quit"
#define	_MSG_SIGNAL_4_MSG_NUM	8
#define	_MSG_SIGNAL_4_MSG_NUM_STR	":8"
#define	_MSG_SIGNAL_4_CAT_NUM_STR	"uxlibc:8"
#define	_MSG_SIGNAL_4_DEF_MSG	"Illegal instruction"
#define	_MSG_SIGNAL_4_CAT_NUM_STR_DEF_MSG	"uxlibc:8:Illegal instruction"
#define	_MSG_SIGNAL_4_MSG_NUM_STR_DEF_MSG	":8:Illegal instruction"
#define	_MSG_SIGNAL_4_FILE_CAT_NUM	uxlibc:8
#define	_SGI_DSIGNAL_4	":8"
#define	_SGI_SIGNAL_4	"uxlibc:8"
#define	_SGI_MSIGNAL_4	"uxlibc:8:Illegal instruction"
#define	_SGI_SSIGNAL_4	"Illegal instruction"
#define	_MSG_SIGNAL_5_MSG_NUM	9
#define	_MSG_SIGNAL_5_MSG_NUM_STR	":9"
#define	_MSG_SIGNAL_5_CAT_NUM_STR	"uxlibc:9"
#define	_MSG_SIGNAL_5_DEF_MSG	"Trace/BPT trap"
#define	_MSG_SIGNAL_5_CAT_NUM_STR_DEF_MSG	"uxlibc:9:Trace/BPT trap"
#define	_MSG_SIGNAL_5_MSG_NUM_STR_DEF_MSG	":9:Trace/BPT trap"
#define	_MSG_SIGNAL_5_FILE_CAT_NUM	uxlibc:9
#define	_SGI_DSIGNAL_5	":9"
#define	_SGI_SIGNAL_5	"uxlibc:9"
#define	_SGI_MSIGNAL_5	"uxlibc:9:Trace/BPT trap"
#define	_SGI_SSIGNAL_5	"Trace/BPT trap"
#define	_MSG_SIGNAL_6_MSG_NUM	10
#define	_MSG_SIGNAL_6_MSG_NUM_STR	":10"
#define	_MSG_SIGNAL_6_CAT_NUM_STR	"uxlibc:10"
#define	_MSG_SIGNAL_6_DEF_MSG	"Abort"
#define	_MSG_SIGNAL_6_CAT_NUM_STR_DEF_MSG	"uxlibc:10:Abort"
#define	_MSG_SIGNAL_6_MSG_NUM_STR_DEF_MSG	":10:Abort"
#define	_MSG_SIGNAL_6_FILE_CAT_NUM	uxlibc:10
#define	_SGI_DSIGNAL_6	":10"
#define	_SGI_SIGNAL_6	"uxlibc:10"
#define	_SGI_MSIGNAL_6	"uxlibc:10:Abort"
#define	_SGI_SSIGNAL_6	"Abort"
#define	_MSG_SIGNAL_7_MSG_NUM	11
#define	_MSG_SIGNAL_7_MSG_NUM_STR	":11"
#define	_MSG_SIGNAL_7_CAT_NUM_STR	"uxlibc:11"
#define	_MSG_SIGNAL_7_DEF_MSG	"EMT trap"
#define	_MSG_SIGNAL_7_CAT_NUM_STR_DEF_MSG	"uxlibc:11:EMT trap"
#define	_MSG_SIGNAL_7_MSG_NUM_STR_DEF_MSG	":11:EMT trap"
#define	_MSG_SIGNAL_7_FILE_CAT_NUM	uxlibc:11
#define	_SGI_DSIGNAL_7	":11"
#define	_SGI_SIGNAL_7	"uxlibc:11"
#define	_SGI_MSIGNAL_7	"uxlibc:11:EMT trap"
#define	_SGI_SSIGNAL_7	"EMT trap"
#define	_MSG_SIGNAL_8_MSG_NUM	12
#define	_MSG_SIGNAL_8_MSG_NUM_STR	":12"
#define	_MSG_SIGNAL_8_CAT_NUM_STR	"uxlibc:12"
#define	_MSG_SIGNAL_8_DEF_MSG	"Floating point exception"
#define	_MSG_SIGNAL_8_CAT_NUM_STR_DEF_MSG	"uxlibc:12:Floating point exception"
#define	_MSG_SIGNAL_8_MSG_NUM_STR_DEF_MSG	":12:Floating point exception"
#define	_MSG_SIGNAL_8_FILE_CAT_NUM	uxlibc:12
#define	_SGI_DSIGNAL_8	":12"
#define	_SGI_SIGNAL_8	"uxlibc:12"
#define	_SGI_MSIGNAL_8	"uxlibc:12:Floating point exception"
#define	_SGI_SSIGNAL_8	"Floating point exception"
#define	_MSG_SIGNAL_9_MSG_NUM	13
#define	_MSG_SIGNAL_9_MSG_NUM_STR	":13"
#define	_MSG_SIGNAL_9_CAT_NUM_STR	"uxlibc:13"
#define	_MSG_SIGNAL_9_DEF_MSG	"Killed"
#define	_MSG_SIGNAL_9_CAT_NUM_STR_DEF_MSG	"uxlibc:13:Killed"
#define	_MSG_SIGNAL_9_MSG_NUM_STR_DEF_MSG	":13:Killed"
#define	_MSG_SIGNAL_9_FILE_CAT_NUM	uxlibc:13
#define	_SGI_DSIGNAL_9	":13"
#define	_SGI_SIGNAL_9	"uxlibc:13"
#define	_SGI_MSIGNAL_9	"uxlibc:13:Killed"
#define	_SGI_SSIGNAL_9	"Killed"
#define	_MSG_SIGNAL_10_MSG_NUM	14
#define	_MSG_SIGNAL_10_MSG_NUM_STR	":14"
#define	_MSG_SIGNAL_10_CAT_NUM_STR	"uxlibc:14"
#define	_MSG_SIGNAL_10_DEF_MSG	"Bus error"
#define	_MSG_SIGNAL_10_CAT_NUM_STR_DEF_MSG	"uxlibc:14:Bus error"
#define	_MSG_SIGNAL_10_MSG_NUM_STR_DEF_MSG	":14:Bus error"
#define	_MSG_SIGNAL_10_FILE_CAT_NUM	uxlibc:14
#define	_SGI_DSIGNAL_10	":14"
#define	_SGI_SIGNAL_10	"uxlibc:14"
#define	_SGI_MSIGNAL_10	"uxlibc:14:Bus error"
#define	_SGI_SSIGNAL_10	"Bus error"
#define	_MSG_SIGNAL_11_MSG_NUM	15
#define	_MSG_SIGNAL_11_MSG_NUM_STR	":15"
#define	_MSG_SIGNAL_11_CAT_NUM_STR	"uxlibc:15"
#define	_MSG_SIGNAL_11_DEF_MSG	"Segmentation fault"
#define	_MSG_SIGNAL_11_CAT_NUM_STR_DEF_MSG	"uxlibc:15:Segmentation fault"
#define	_MSG_SIGNAL_11_MSG_NUM_STR_DEF_MSG	":15:Segmentation fault"
#define	_MSG_SIGNAL_11_FILE_CAT_NUM	uxlibc:15
#define	_SGI_DSIGNAL_11	":15"
#define	_SGI_SIGNAL_11	"uxlibc:15"
#define	_SGI_MSIGNAL_11	"uxlibc:15:Segmentation fault"
#define	_SGI_SSIGNAL_11	"Segmentation fault"
#define	_MSG_SIGNAL_12_MSG_NUM	16
#define	_MSG_SIGNAL_12_MSG_NUM_STR	":16"
#define	_MSG_SIGNAL_12_CAT_NUM_STR	"uxlibc:16"
#define	_MSG_SIGNAL_12_DEF_MSG	"Bad system call"
#define	_MSG_SIGNAL_12_CAT_NUM_STR_DEF_MSG	"uxlibc:16:Bad system call"
#define	_MSG_SIGNAL_12_MSG_NUM_STR_DEF_MSG	":16:Bad system call"
#define	_MSG_SIGNAL_12_FILE_CAT_NUM	uxlibc:16
#define	_SGI_DSIGNAL_12	":16"
#define	_SGI_SIGNAL_12	"uxlibc:16"
#define	_SGI_MSIGNAL_12	"uxlibc:16:Bad system call"
#define	_SGI_SSIGNAL_12	"Bad system call"
#define	_MSG_SIGNAL_13_MSG_NUM	17
#define	_MSG_SIGNAL_13_MSG_NUM_STR	":17"
#define	_MSG_SIGNAL_13_CAT_NUM_STR	"uxlibc:17"
#define	_MSG_SIGNAL_13_DEF_MSG	"Broken pipe"
#define	_MSG_SIGNAL_13_CAT_NUM_STR_DEF_MSG	"uxlibc:17:Broken pipe"
#define	_MSG_SIGNAL_13_MSG_NUM_STR_DEF_MSG	":17:Broken pipe"
#define	_MSG_SIGNAL_13_FILE_CAT_NUM	uxlibc:17
#define	_SGI_DSIGNAL_13	":17"
#define	_SGI_SIGNAL_13	"uxlibc:17"
#define	_SGI_MSIGNAL_13	"uxlibc:17:Broken pipe"
#define	_SGI_SSIGNAL_13	"Broken pipe"
#define	_MSG_SIGNAL_14_MSG_NUM	18
#define	_MSG_SIGNAL_14_MSG_NUM_STR	":18"
#define	_MSG_SIGNAL_14_CAT_NUM_STR	"uxlibc:18"
#define	_MSG_SIGNAL_14_DEF_MSG	"Alarm clock"
#define	_MSG_SIGNAL_14_CAT_NUM_STR_DEF_MSG	"uxlibc:18:Alarm clock"
#define	_MSG_SIGNAL_14_MSG_NUM_STR_DEF_MSG	":18:Alarm clock"
#define	_MSG_SIGNAL_14_FILE_CAT_NUM	uxlibc:18
#define	_SGI_DSIGNAL_14	":18"
#define	_SGI_SIGNAL_14	"uxlibc:18"
#define	_SGI_MSIGNAL_14	"uxlibc:18:Alarm clock"
#define	_SGI_SSIGNAL_14	"Alarm clock"
#define	_MSG_SIGNAL_15_MSG_NUM	19
#define	_MSG_SIGNAL_15_MSG_NUM_STR	":19"
#define	_MSG_SIGNAL_15_CAT_NUM_STR	"uxlibc:19"
#define	_MSG_SIGNAL_15_DEF_MSG	"Terminated"
#define	_MSG_SIGNAL_15_CAT_NUM_STR_DEF_MSG	"uxlibc:19:Terminated"
#define	_MSG_SIGNAL_15_MSG_NUM_STR_DEF_MSG	":19:Terminated"
#define	_MSG_SIGNAL_15_FILE_CAT_NUM	uxlibc:19
#define	_SGI_DSIGNAL_15	":19"
#define	_SGI_SIGNAL_15	"uxlibc:19"
#define	_SGI_MSIGNAL_15	"uxlibc:19:Terminated"
#define	_SGI_SSIGNAL_15	"Terminated"
#define	_MSG_SIGNAL_16_MSG_NUM	20
#define	_MSG_SIGNAL_16_MSG_NUM_STR	":20"
#define	_MSG_SIGNAL_16_CAT_NUM_STR	"uxlibc:20"
#define	_MSG_SIGNAL_16_DEF_MSG	"User defined signal 1"
#define	_MSG_SIGNAL_16_CAT_NUM_STR_DEF_MSG	"uxlibc:20:User defined signal 1"
#define	_MSG_SIGNAL_16_MSG_NUM_STR_DEF_MSG	":20:User defined signal 1"
#define	_MSG_SIGNAL_16_FILE_CAT_NUM	uxlibc:20
#define	_SGI_DSIGNAL_16	":20"
#define	_SGI_SIGNAL_16	"uxlibc:20"
#define	_SGI_MSIGNAL_16	"uxlibc:20:User defined signal 1"
#define	_SGI_SSIGNAL_16	"User defined signal 1"
#define	_MSG_SIGNAL_17_MSG_NUM	21
#define	_MSG_SIGNAL_17_MSG_NUM_STR	":21"
#define	_MSG_SIGNAL_17_CAT_NUM_STR	"uxlibc:21"
#define	_MSG_SIGNAL_17_DEF_MSG	"User defined signal 2"
#define	_MSG_SIGNAL_17_CAT_NUM_STR_DEF_MSG	"uxlibc:21:User defined signal 2"
#define	_MSG_SIGNAL_17_MSG_NUM_STR_DEF_MSG	":21:User defined signal 2"
#define	_MSG_SIGNAL_17_FILE_CAT_NUM	uxlibc:21
#define	_SGI_DSIGNAL_17	":21"
#define	_SGI_SIGNAL_17	"uxlibc:21"
#define	_SGI_MSIGNAL_17	"uxlibc:21:User defined signal 2"
#define	_SGI_SSIGNAL_17	"User defined signal 2"
#define	_MSG_SIGNAL_18_MSG_NUM	22
#define	_MSG_SIGNAL_18_MSG_NUM_STR	":22"
#define	_MSG_SIGNAL_18_CAT_NUM_STR	"uxlibc:22"
#define	_MSG_SIGNAL_18_DEF_MSG	"Child exited"
#define	_MSG_SIGNAL_18_CAT_NUM_STR_DEF_MSG	"uxlibc:22:Child exited"
#define	_MSG_SIGNAL_18_MSG_NUM_STR_DEF_MSG	":22:Child exited"
#define	_MSG_SIGNAL_18_FILE_CAT_NUM	uxlibc:22
#define	_SGI_DSIGNAL_18	":22"
#define	_SGI_SIGNAL_18	"uxlibc:22"
#define	_SGI_MSIGNAL_18	"uxlibc:22:Child exited"
#define	_SGI_SSIGNAL_18	"Child exited"
#define	_MSG_SIGNAL_19_MSG_NUM	23
#define	_MSG_SIGNAL_19_MSG_NUM_STR	":23"
#define	_MSG_SIGNAL_19_CAT_NUM_STR	"uxlibc:23"
#define	_MSG_SIGNAL_19_DEF_MSG	"Power-fail restart"
#define	_MSG_SIGNAL_19_CAT_NUM_STR_DEF_MSG	"uxlibc:23:Power-fail restart"
#define	_MSG_SIGNAL_19_MSG_NUM_STR_DEF_MSG	":23:Power-fail restart"
#define	_MSG_SIGNAL_19_FILE_CAT_NUM	uxlibc:23
#define	_SGI_DSIGNAL_19	":23"
#define	_SGI_SIGNAL_19	"uxlibc:23"
#define	_SGI_MSIGNAL_19	"uxlibc:23:Power-fail restart"
#define	_SGI_SSIGNAL_19	"Power-fail restart"
#define	_MSG_SIGNAL_20_MSG_NUM	24
#define	_MSG_SIGNAL_20_MSG_NUM_STR	":24"
#define	_MSG_SIGNAL_20_CAT_NUM_STR	"uxlibc:24"
#define	_MSG_SIGNAL_20_DEF_MSG	"Window size changes"
#define	_MSG_SIGNAL_20_CAT_NUM_STR_DEF_MSG	"uxlibc:24:Window size changes"
#define	_MSG_SIGNAL_20_MSG_NUM_STR_DEF_MSG	":24:Window size changes"
#define	_MSG_SIGNAL_20_FILE_CAT_NUM	uxlibc:24
#define	_SGI_DSIGNAL_20	":24"
#define	_SGI_SIGNAL_20	"uxlibc:24"
#define	_SGI_MSIGNAL_20	"uxlibc:24:Window size changes"
#define	_SGI_SSIGNAL_20	"Window size changes"
#define	_MSG_SIGNAL_21_MSG_NUM	25
#define	_MSG_SIGNAL_21_MSG_NUM_STR	":25"
#define	_MSG_SIGNAL_21_CAT_NUM_STR	"uxlibc:25"
#define	_MSG_SIGNAL_21_DEF_MSG	"Urgent I/O condition"
#define	_MSG_SIGNAL_21_CAT_NUM_STR_DEF_MSG	"uxlibc:25:Urgent I/O condition"
#define	_MSG_SIGNAL_21_MSG_NUM_STR_DEF_MSG	":25:Urgent I/O condition"
#define	_MSG_SIGNAL_21_FILE_CAT_NUM	uxlibc:25
#define	_SGI_DSIGNAL_21	":25"
#define	_SGI_SIGNAL_21	"uxlibc:25"
#define	_SGI_MSIGNAL_21	"uxlibc:25:Urgent I/O condition"
#define	_SGI_SSIGNAL_21	"Urgent I/O condition"
#define	_MSG_SIGNAL_22_MSG_NUM	26
#define	_MSG_SIGNAL_22_MSG_NUM_STR	":26"
#define	_MSG_SIGNAL_22_CAT_NUM_STR	"uxlibc:26"
#define	_MSG_SIGNAL_22_DEF_MSG	"Pollable event occured"
#define	_MSG_SIGNAL_22_CAT_NUM_STR_DEF_MSG	"uxlibc:26:Pollable event occured"
#define	_MSG_SIGNAL_22_MSG_NUM_STR_DEF_MSG	":26:Pollable event occured"
#define	_MSG_SIGNAL_22_FILE_CAT_NUM	uxlibc:26
#define	_SGI_DSIGNAL_22	":26"
#define	_SGI_SIGNAL_22	"uxlibc:26"
#define	_SGI_MSIGNAL_22	"uxlibc:26:Pollable event occured"
#define	_SGI_SSIGNAL_22	"Pollable event occured"
#define	_MSG_SIGNAL_23_MSG_NUM	27
#define	_MSG_SIGNAL_23_MSG_NUM_STR	":27"
#define	_MSG_SIGNAL_23_CAT_NUM_STR	"uxlibc:27"
#define	_MSG_SIGNAL_23_DEF_MSG	"Stop signal (not from tty)"
#define	_MSG_SIGNAL_23_CAT_NUM_STR_DEF_MSG	"uxlibc:27:Stop signal (not from tty)"
#define	_MSG_SIGNAL_23_MSG_NUM_STR_DEF_MSG	":27:Stop signal (not from tty)"
#define	_MSG_SIGNAL_23_FILE_CAT_NUM	uxlibc:27
#define	_SGI_DSIGNAL_23	":27"
#define	_SGI_SIGNAL_23	"uxlibc:27"
#define	_SGI_MSIGNAL_23	"uxlibc:27:Stop signal (not from tty)"
#define	_SGI_SSIGNAL_23	"Stop signal (not from tty)"
#define	_MSG_SIGNAL_24_MSG_NUM	28
#define	_MSG_SIGNAL_24_MSG_NUM_STR	":28"
#define	_MSG_SIGNAL_24_CAT_NUM_STR	"uxlibc:28"
#define	_MSG_SIGNAL_24_DEF_MSG	"Stop signal from tty"
#define	_MSG_SIGNAL_24_CAT_NUM_STR_DEF_MSG	"uxlibc:28:Stop signal from tty"
#define	_MSG_SIGNAL_24_MSG_NUM_STR_DEF_MSG	":28:Stop signal from tty"
#define	_MSG_SIGNAL_24_FILE_CAT_NUM	uxlibc:28
#define	_SGI_DSIGNAL_24	":28"
#define	_SGI_SIGNAL_24	"uxlibc:28"
#define	_SGI_MSIGNAL_24	"uxlibc:28:Stop signal from tty"
#define	_SGI_SSIGNAL_24	"Stop signal from tty"
#define	_MSG_SIGNAL_25_MSG_NUM	29
#define	_MSG_SIGNAL_25_MSG_NUM_STR	":29"
#define	_MSG_SIGNAL_25_CAT_NUM_STR	"uxlibc:29"
#define	_MSG_SIGNAL_25_DEF_MSG	"Continued"
#define	_MSG_SIGNAL_25_CAT_NUM_STR_DEF_MSG	"uxlibc:29:Continued"
#define	_MSG_SIGNAL_25_MSG_NUM_STR_DEF_MSG	":29:Continued"
#define	_MSG_SIGNAL_25_FILE_CAT_NUM	uxlibc:29
#define	_SGI_DSIGNAL_25	":29"
#define	_SGI_SIGNAL_25	"uxlibc:29"
#define	_SGI_MSIGNAL_25	"uxlibc:29:Continued"
#define	_SGI_SSIGNAL_25	"Continued"
#define	_MSG_SIGNAL_26_MSG_NUM	30
#define	_MSG_SIGNAL_26_MSG_NUM_STR	":30"
#define	_MSG_SIGNAL_26_CAT_NUM_STR	"uxlibc:30"
#define	_MSG_SIGNAL_26_DEF_MSG	"Stopped (tty input)"
#define	_MSG_SIGNAL_26_CAT_NUM_STR_DEF_MSG	"uxlibc:30:Stopped (tty input)"
#define	_MSG_SIGNAL_26_MSG_NUM_STR_DEF_MSG	":30:Stopped (tty input)"
#define	_MSG_SIGNAL_26_FILE_CAT_NUM	uxlibc:30
#define	_SGI_DSIGNAL_26	":30"
#define	_SGI_SIGNAL_26	"uxlibc:30"
#define	_SGI_MSIGNAL_26	"uxlibc:30:Stopped (tty input)"
#define	_SGI_SSIGNAL_26	"Stopped (tty input)"
#define	_MSG_SIGNAL_27_MSG_NUM	31
#define	_MSG_SIGNAL_27_MSG_NUM_STR	":31"
#define	_MSG_SIGNAL_27_CAT_NUM_STR	"uxlibc:31"
#define	_MSG_SIGNAL_27_DEF_MSG	"Stopped (tty output)"
#define	_MSG_SIGNAL_27_CAT_NUM_STR_DEF_MSG	"uxlibc:31:Stopped (tty output)"
#define	_MSG_SIGNAL_27_MSG_NUM_STR_DEF_MSG	":31:Stopped (tty output)"
#define	_MSG_SIGNAL_27_FILE_CAT_NUM	uxlibc:31
#define	_SGI_DSIGNAL_27	":31"
#define	_SGI_SIGNAL_27	"uxlibc:31"
#define	_SGI_MSIGNAL_27	"uxlibc:31:Stopped (tty output)"
#define	_SGI_SSIGNAL_27	"Stopped (tty output)"
#define	_MSG_SIGNAL_28_MSG_NUM	32
#define	_MSG_SIGNAL_28_MSG_NUM_STR	":32"
#define	_MSG_SIGNAL_28_CAT_NUM_STR	"uxlibc:32"
#define	_MSG_SIGNAL_28_DEF_MSG	"Virtual time alarm"
#define	_MSG_SIGNAL_28_CAT_NUM_STR_DEF_MSG	"uxlibc:32:Virtual time alarm"
#define	_MSG_SIGNAL_28_MSG_NUM_STR_DEF_MSG	":32:Virtual time alarm"
#define	_MSG_SIGNAL_28_FILE_CAT_NUM	uxlibc:32
#define	_SGI_DSIGNAL_28	":32"
#define	_SGI_SIGNAL_28	"uxlibc:32"
#define	_SGI_MSIGNAL_28	"uxlibc:32:Virtual time alarm"
#define	_SGI_SSIGNAL_28	"Virtual time alarm"
#define	_MSG_SIGNAL_29_MSG_NUM	33
#define	_MSG_SIGNAL_29_MSG_NUM_STR	":33"
#define	_MSG_SIGNAL_29_CAT_NUM_STR	"uxlibc:33"
#define	_MSG_SIGNAL_29_DEF_MSG	"Profiling alarm"
#define	_MSG_SIGNAL_29_CAT_NUM_STR_DEF_MSG	"uxlibc:33:Profiling alarm"
#define	_MSG_SIGNAL_29_MSG_NUM_STR_DEF_MSG	":33:Profiling alarm"
#define	_MSG_SIGNAL_29_FILE_CAT_NUM	uxlibc:33
#define	_SGI_DSIGNAL_29	":33"
#define	_SGI_SIGNAL_29	"uxlibc:33"
#define	_SGI_MSIGNAL_29	"uxlibc:33:Profiling alarm"
#define	_SGI_SSIGNAL_29	"Profiling alarm"
#define	_MSG_SIGNAL_30_MSG_NUM	34
#define	_MSG_SIGNAL_30_MSG_NUM_STR	":34"
#define	_MSG_SIGNAL_30_CAT_NUM_STR	"uxlibc:34"
#define	_MSG_SIGNAL_30_DEF_MSG	"Cputime limit exceeded"
#define	_MSG_SIGNAL_30_CAT_NUM_STR_DEF_MSG	"uxlibc:34:Cputime limit exceeded"
#define	_MSG_SIGNAL_30_MSG_NUM_STR_DEF_MSG	":34:Cputime limit exceeded"
#define	_MSG_SIGNAL_30_FILE_CAT_NUM	uxlibc:34
#define	_SGI_DSIGNAL_30	":34"
#define	_SGI_SIGNAL_30	"uxlibc:34"
#define	_SGI_MSIGNAL_30	"uxlibc:34:Cputime limit exceeded"
#define	_SGI_SSIGNAL_30	"Cputime limit exceeded"
#define	_MSG_SIGNAL_31_MSG_NUM	35
#define	_MSG_SIGNAL_31_MSG_NUM_STR	":35"
#define	_MSG_SIGNAL_31_CAT_NUM_STR	"uxlibc:35"
#define	_MSG_SIGNAL_31_DEF_MSG	"Filesize limit exceeded"
#define	_MSG_SIGNAL_31_CAT_NUM_STR_DEF_MSG	"uxlibc:35:Filesize limit exceeded"
#define	_MSG_SIGNAL_31_MSG_NUM_STR_DEF_MSG	":35:Filesize limit exceeded"
#define	_MSG_SIGNAL_31_FILE_CAT_NUM	uxlibc:35
#define	_SGI_DSIGNAL_31	":35"
#define	_SGI_SIGNAL_31	"uxlibc:35"
#define	_SGI_MSIGNAL_31	"uxlibc:35:Filesize limit exceeded"
#define	_SGI_SSIGNAL_31	"Filesize limit exceeded"
#define	_MSG_SIGNAL_32_MSG_NUM	36
#define	_MSG_SIGNAL_32_MSG_NUM_STR	":36"
#define	_MSG_SIGNAL_32_CAT_NUM_STR	"uxlibc:36"
#define	_MSG_SIGNAL_32_DEF_MSG	"Signal 32"
#define	_MSG_SIGNAL_32_CAT_NUM_STR_DEF_MSG	"uxlibc:36:Signal 32"
#define	_MSG_SIGNAL_32_MSG_NUM_STR_DEF_MSG	":36:Signal 32"
#define	_MSG_SIGNAL_32_FILE_CAT_NUM	uxlibc:36
#define	_SGI_DSIGNAL_32	":36"
#define	_SGI_SIGNAL_32	"uxlibc:36"
#define	_SGI_MSIGNAL_32	"uxlibc:36:Signal 32"
#define	_SGI_SSIGNAL_32	"Signal 32"
#define	_MSG_SIGNAL_33_MSG_NUM	37
#define	_MSG_SIGNAL_33_MSG_NUM_STR	":37"
#define	_MSG_SIGNAL_33_CAT_NUM_STR	"uxlibc:37"
#define	_MSG_SIGNAL_33_DEF_MSG	"System reserved signal 33"
#define	_MSG_SIGNAL_33_CAT_NUM_STR_DEF_MSG	"uxlibc:37:System reserved signal 33"
#define	_MSG_SIGNAL_33_MSG_NUM_STR_DEF_MSG	":37:System reserved signal 33"
#define	_MSG_SIGNAL_33_FILE_CAT_NUM	uxlibc:37
#define	_SGI_DSIGNAL_33	":37"
#define	_SGI_SIGNAL_33	"uxlibc:37"
#define	_SGI_MSIGNAL_33	"uxlibc:37:System reserved signal 33"
#define	_SGI_SSIGNAL_33	"System reserved signal 33"
#define	_MSG_SIGNAL_34_MSG_NUM	38
#define	_MSG_SIGNAL_34_MSG_NUM_STR	":38"
#define	_MSG_SIGNAL_34_CAT_NUM_STR	"uxlibc:38"
#define	_MSG_SIGNAL_34_DEF_MSG	"System reserved signal 34"
#define	_MSG_SIGNAL_34_CAT_NUM_STR_DEF_MSG	"uxlibc:38:System reserved signal 34"
#define	_MSG_SIGNAL_34_MSG_NUM_STR_DEF_MSG	":38:System reserved signal 34"
#define	_MSG_SIGNAL_34_FILE_CAT_NUM	uxlibc:38
#define	_SGI_DSIGNAL_34	":38"
#define	_SGI_SIGNAL_34	"uxlibc:38"
#define	_SGI_MSIGNAL_34	"uxlibc:38:System reserved signal 34"
#define	_SGI_SSIGNAL_34	"System reserved signal 34"
#define	_MSG_SIGNAL_35_MSG_NUM	39
#define	_MSG_SIGNAL_35_MSG_NUM_STR	":39"
#define	_MSG_SIGNAL_35_CAT_NUM_STR	"uxlibc:39"
#define	_MSG_SIGNAL_35_DEF_MSG	"System reserved signal 35"
#define	_MSG_SIGNAL_35_CAT_NUM_STR_DEF_MSG	"uxlibc:39:System reserved signal 35"
#define	_MSG_SIGNAL_35_MSG_NUM_STR_DEF_MSG	":39:System reserved signal 35"
#define	_MSG_SIGNAL_35_FILE_CAT_NUM	uxlibc:39
#define	_SGI_DSIGNAL_35	":39"
#define	_SGI_SIGNAL_35	"uxlibc:39"
#define	_SGI_MSIGNAL_35	"uxlibc:39:System reserved signal 35"
#define	_SGI_SSIGNAL_35	"System reserved signal 35"
#define	_MSG_SIGNAL_36_MSG_NUM	40
#define	_MSG_SIGNAL_36_MSG_NUM_STR	":40"
#define	_MSG_SIGNAL_36_CAT_NUM_STR	"uxlibc:40"
#define	_MSG_SIGNAL_36_DEF_MSG	"System reserved signal 36"
#define	_MSG_SIGNAL_36_CAT_NUM_STR_DEF_MSG	"uxlibc:40:System reserved signal 36"
#define	_MSG_SIGNAL_36_MSG_NUM_STR_DEF_MSG	":40:System reserved signal 36"
#define	_MSG_SIGNAL_36_FILE_CAT_NUM	uxlibc:40
#define	_SGI_DSIGNAL_36	":40"
#define	_SGI_SIGNAL_36	"uxlibc:40"
#define	_SGI_MSIGNAL_36	"uxlibc:40:System reserved signal 36"
#define	_SGI_SSIGNAL_36	"System reserved signal 36"
#define	_MSG_SIGNAL_37_MSG_NUM	41
#define	_MSG_SIGNAL_37_MSG_NUM_STR	":41"
#define	_MSG_SIGNAL_37_CAT_NUM_STR	"uxlibc:41"
#define	_MSG_SIGNAL_37_DEF_MSG	"System reserved signal 37"
#define	_MSG_SIGNAL_37_CAT_NUM_STR_DEF_MSG	"uxlibc:41:System reserved signal 37"
#define	_MSG_SIGNAL_37_MSG_NUM_STR_DEF_MSG	":41:System reserved signal 37"
#define	_MSG_SIGNAL_37_FILE_CAT_NUM	uxlibc:41
#define	_SGI_DSIGNAL_37	":41"
#define	_SGI_SIGNAL_37	"uxlibc:41"
#define	_SGI_MSIGNAL_37	"uxlibc:41:System reserved signal 37"
#define	_SGI_SSIGNAL_37	"System reserved signal 37"
#define	_MSG_SIGNAL_38_MSG_NUM	42
#define	_MSG_SIGNAL_38_MSG_NUM_STR	":42"
#define	_MSG_SIGNAL_38_CAT_NUM_STR	"uxlibc:42"
#define	_MSG_SIGNAL_38_DEF_MSG	"System reserved signal 38"
#define	_MSG_SIGNAL_38_CAT_NUM_STR_DEF_MSG	"uxlibc:42:System reserved signal 38"
#define	_MSG_SIGNAL_38_MSG_NUM_STR_DEF_MSG	":42:System reserved signal 38"
#define	_MSG_SIGNAL_38_FILE_CAT_NUM	uxlibc:42
#define	_SGI_DSIGNAL_38	":42"
#define	_SGI_SIGNAL_38	"uxlibc:42"
#define	_SGI_MSIGNAL_38	"uxlibc:42:System reserved signal 38"
#define	_SGI_SSIGNAL_38	"System reserved signal 38"
#define	_MSG_SIGNAL_39_MSG_NUM	43
#define	_MSG_SIGNAL_39_MSG_NUM_STR	":43"
#define	_MSG_SIGNAL_39_CAT_NUM_STR	"uxlibc:43"
#define	_MSG_SIGNAL_39_DEF_MSG	"System reserved signal 39"
#define	_MSG_SIGNAL_39_CAT_NUM_STR_DEF_MSG	"uxlibc:43:System reserved signal 39"
#define	_MSG_SIGNAL_39_MSG_NUM_STR_DEF_MSG	":43:System reserved signal 39"
#define	_MSG_SIGNAL_39_FILE_CAT_NUM	uxlibc:43
#define	_SGI_DSIGNAL_39	":43"
#define	_SGI_SIGNAL_39	"uxlibc:43"
#define	_SGI_MSIGNAL_39	"uxlibc:43:System reserved signal 39"
#define	_SGI_SSIGNAL_39	"System reserved signal 39"
#define	_MSG_SIGNAL_40_MSG_NUM	44
#define	_MSG_SIGNAL_40_MSG_NUM_STR	":44"
#define	_MSG_SIGNAL_40_CAT_NUM_STR	"uxlibc:44"
#define	_MSG_SIGNAL_40_DEF_MSG	"System reserved signal 40"
#define	_MSG_SIGNAL_40_CAT_NUM_STR_DEF_MSG	"uxlibc:44:System reserved signal 40"
#define	_MSG_SIGNAL_40_MSG_NUM_STR_DEF_MSG	":44:System reserved signal 40"
#define	_MSG_SIGNAL_40_FILE_CAT_NUM	uxlibc:44
#define	_SGI_DSIGNAL_40	":44"
#define	_SGI_SIGNAL_40	"uxlibc:44"
#define	_SGI_MSIGNAL_40	"uxlibc:44:System reserved signal 40"
#define	_SGI_SSIGNAL_40	"System reserved signal 40"
#define	_MSG_SIGNAL_41_MSG_NUM	45
#define	_MSG_SIGNAL_41_MSG_NUM_STR	":45"
#define	_MSG_SIGNAL_41_CAT_NUM_STR	"uxlibc:45"
#define	_MSG_SIGNAL_41_DEF_MSG	"System reserved signal 41"
#define	_MSG_SIGNAL_41_CAT_NUM_STR_DEF_MSG	"uxlibc:45:System reserved signal 41"
#define	_MSG_SIGNAL_41_MSG_NUM_STR_DEF_MSG	":45:System reserved signal 41"
#define	_MSG_SIGNAL_41_FILE_CAT_NUM	uxlibc:45
#define	_SGI_DSIGNAL_41	":45"
#define	_SGI_SIGNAL_41	"uxlibc:45"
#define	_SGI_MSIGNAL_41	"uxlibc:45:System reserved signal 41"
#define	_SGI_SSIGNAL_41	"System reserved signal 41"
#define	_MSG_SIGNAL_42_MSG_NUM	46
#define	_MSG_SIGNAL_42_MSG_NUM_STR	":46"
#define	_MSG_SIGNAL_42_CAT_NUM_STR	"uxlibc:46"
#define	_MSG_SIGNAL_42_DEF_MSG	"System reserved signal 42"
#define	_MSG_SIGNAL_42_CAT_NUM_STR_DEF_MSG	"uxlibc:46:System reserved signal 42"
#define	_MSG_SIGNAL_42_MSG_NUM_STR_DEF_MSG	":46:System reserved signal 42"
#define	_MSG_SIGNAL_42_FILE_CAT_NUM	uxlibc:46
#define	_SGI_DSIGNAL_42	":46"
#define	_SGI_SIGNAL_42	"uxlibc:46"
#define	_SGI_MSIGNAL_42	"uxlibc:46:System reserved signal 42"
#define	_SGI_SSIGNAL_42	"System reserved signal 42"
#define	_MSG_SIGNAL_43_MSG_NUM	47
#define	_MSG_SIGNAL_43_MSG_NUM_STR	":47"
#define	_MSG_SIGNAL_43_CAT_NUM_STR	"uxlibc:47"
#define	_MSG_SIGNAL_43_DEF_MSG	"System reserved signal 43"
#define	_MSG_SIGNAL_43_CAT_NUM_STR_DEF_MSG	"uxlibc:47:System reserved signal 43"
#define	_MSG_SIGNAL_43_MSG_NUM_STR_DEF_MSG	":47:System reserved signal 43"
#define	_MSG_SIGNAL_43_FILE_CAT_NUM	uxlibc:47
#define	_SGI_DSIGNAL_43	":47"
#define	_SGI_SIGNAL_43	"uxlibc:47"
#define	_SGI_MSIGNAL_43	"uxlibc:47:System reserved signal 43"
#define	_SGI_SSIGNAL_43	"System reserved signal 43"
#define	_MSG_SIGNAL_44_MSG_NUM	48
#define	_MSG_SIGNAL_44_MSG_NUM_STR	":48"
#define	_MSG_SIGNAL_44_CAT_NUM_STR	"uxlibc:48"
#define	_MSG_SIGNAL_44_DEF_MSG	"System reserved signal 44"
#define	_MSG_SIGNAL_44_CAT_NUM_STR_DEF_MSG	"uxlibc:48:System reserved signal 44"
#define	_MSG_SIGNAL_44_MSG_NUM_STR_DEF_MSG	":48:System reserved signal 44"
#define	_MSG_SIGNAL_44_FILE_CAT_NUM	uxlibc:48
#define	_SGI_DSIGNAL_44	":48"
#define	_SGI_SIGNAL_44	"uxlibc:48"
#define	_SGI_MSIGNAL_44	"uxlibc:48:System reserved signal 44"
#define	_SGI_SSIGNAL_44	"System reserved signal 44"
#define	_MSG_SIGNAL_45_MSG_NUM	49
#define	_MSG_SIGNAL_45_MSG_NUM_STR	":49"
#define	_MSG_SIGNAL_45_CAT_NUM_STR	"uxlibc:49"
#define	_MSG_SIGNAL_45_DEF_MSG	"System reserved signal 45"
#define	_MSG_SIGNAL_45_CAT_NUM_STR_DEF_MSG	"uxlibc:49:System reserved signal 45"
#define	_MSG_SIGNAL_45_MSG_NUM_STR_DEF_MSG	":49:System reserved signal 45"
#define	_MSG_SIGNAL_45_FILE_CAT_NUM	uxlibc:49
#define	_SGI_DSIGNAL_45	":49"
#define	_SGI_SIGNAL_45	"uxlibc:49"
#define	_SGI_MSIGNAL_45	"uxlibc:49:System reserved signal 45"
#define	_SGI_SSIGNAL_45	"System reserved signal 45"
#define	_MSG_SIGNAL_46_MSG_NUM	50
#define	_MSG_SIGNAL_46_MSG_NUM_STR	":50"
#define	_MSG_SIGNAL_46_CAT_NUM_STR	"uxlibc:50"
#define	_MSG_SIGNAL_46_DEF_MSG	"System reserved signal 46"
#define	_MSG_SIGNAL_46_CAT_NUM_STR_DEF_MSG	"uxlibc:50:System reserved signal 46"
#define	_MSG_SIGNAL_46_MSG_NUM_STR_DEF_MSG	":50:System reserved signal 46"
#define	_MSG_SIGNAL_46_FILE_CAT_NUM	uxlibc:50
#define	_SGI_DSIGNAL_46	":50"
#define	_SGI_SIGNAL_46	"uxlibc:50"
#define	_SGI_MSIGNAL_46	"uxlibc:50:System reserved signal 46"
#define	_SGI_SSIGNAL_46	"System reserved signal 46"
#define	_MSG_SIGNAL_47_MSG_NUM	51
#define	_MSG_SIGNAL_47_MSG_NUM_STR	":51"
#define	_MSG_SIGNAL_47_CAT_NUM_STR	"uxlibc:51"
#define	_MSG_SIGNAL_47_DEF_MSG	"System reserved signal 47"
#define	_MSG_SIGNAL_47_CAT_NUM_STR_DEF_MSG	"uxlibc:51:System reserved signal 47"
#define	_MSG_SIGNAL_47_MSG_NUM_STR_DEF_MSG	":51:System reserved signal 47"
#define	_MSG_SIGNAL_47_FILE_CAT_NUM	uxlibc:51
#define	_SGI_DSIGNAL_47	":51"
#define	_SGI_SIGNAL_47	"uxlibc:51"
#define	_SGI_MSIGNAL_47	"uxlibc:51:System reserved signal 47"
#define	_SGI_SSIGNAL_47	"System reserved signal 47"
#define	_MSG_SIGNAL_48_MSG_NUM	52
#define	_MSG_SIGNAL_48_MSG_NUM_STR	":52"
#define	_MSG_SIGNAL_48_CAT_NUM_STR	"uxlibc:52"
#define	_MSG_SIGNAL_48_DEF_MSG	"System reserved signal 48"
#define	_MSG_SIGNAL_48_CAT_NUM_STR_DEF_MSG	"uxlibc:52:System reserved signal 48"
#define	_MSG_SIGNAL_48_MSG_NUM_STR_DEF_MSG	":52:System reserved signal 48"
#define	_MSG_SIGNAL_48_FILE_CAT_NUM	uxlibc:52
#define	_SGI_DSIGNAL_48	":52"
#define	_SGI_SIGNAL_48	"uxlibc:52"
#define	_SGI_MSIGNAL_48	"uxlibc:52:System reserved signal 48"
#define	_SGI_SSIGNAL_48	"System reserved signal 48"
#define	_MSG_SIGNAL_49_MSG_NUM	53
#define	_MSG_SIGNAL_49_MSG_NUM_STR	":53"
#define	_MSG_SIGNAL_49_CAT_NUM_STR	"uxlibc:53"
#define	_MSG_SIGNAL_49_DEF_MSG	"Real-time signal RTMIN"
#define	_MSG_SIGNAL_49_CAT_NUM_STR_DEF_MSG	"uxlibc:53:Real-time signal RTMIN"
#define	_MSG_SIGNAL_49_MSG_NUM_STR_DEF_MSG	":53:Real-time signal RTMIN"
#define	_MSG_SIGNAL_49_FILE_CAT_NUM	uxlibc:53
#define	_SGI_DSIGNAL_49	":53"
#define	_SGI_SIGNAL_49	"uxlibc:53"
#define	_SGI_MSIGNAL_49	"uxlibc:53:Real-time signal RTMIN"
#define	_SGI_SSIGNAL_49	"Real-time signal RTMIN"
#define	_MSG_SIGNAL_50_MSG_NUM	54
#define	_MSG_SIGNAL_50_MSG_NUM_STR	":54"
#define	_MSG_SIGNAL_50_CAT_NUM_STR	"uxlibc:54"
#define	_MSG_SIGNAL_50_DEF_MSG	"Real-time signal RTMIN+1"
#define	_MSG_SIGNAL_50_CAT_NUM_STR_DEF_MSG	"uxlibc:54:Real-time signal RTMIN+1"
#define	_MSG_SIGNAL_50_MSG_NUM_STR_DEF_MSG	":54:Real-time signal RTMIN+1"
#define	_MSG_SIGNAL_50_FILE_CAT_NUM	uxlibc:54
#define	_SGI_DSIGNAL_50	":54"
#define	_SGI_SIGNAL_50	"uxlibc:54"
#define	_SGI_MSIGNAL_50	"uxlibc:54:Real-time signal RTMIN+1"
#define	_SGI_SSIGNAL_50	"Real-time signal RTMIN+1"
#define	_MSG_SIGNAL_51_MSG_NUM	55
#define	_MSG_SIGNAL_51_MSG_NUM_STR	":55"
#define	_MSG_SIGNAL_51_CAT_NUM_STR	"uxlibc:55"
#define	_MSG_SIGNAL_51_DEF_MSG	"Real-time signal RTMIN+2"
#define	_MSG_SIGNAL_51_CAT_NUM_STR_DEF_MSG	"uxlibc:55:Real-time signal RTMIN+2"
#define	_MSG_SIGNAL_51_MSG_NUM_STR_DEF_MSG	":55:Real-time signal RTMIN+2"
#define	_MSG_SIGNAL_51_FILE_CAT_NUM	uxlibc:55
#define	_SGI_DSIGNAL_51	":55"
#define	_SGI_SIGNAL_51	"uxlibc:55"
#define	_SGI_MSIGNAL_51	"uxlibc:55:Real-time signal RTMIN+2"
#define	_SGI_SSIGNAL_51	"Real-time signal RTMIN+2"
#define	_MSG_SIGNAL_52_MSG_NUM	56
#define	_MSG_SIGNAL_52_MSG_NUM_STR	":56"
#define	_MSG_SIGNAL_52_CAT_NUM_STR	"uxlibc:56"
#define	_MSG_SIGNAL_52_DEF_MSG	"Real-time signal RTMIN+3"
#define	_MSG_SIGNAL_52_CAT_NUM_STR_DEF_MSG	"uxlibc:56:Real-time signal RTMIN+3"
#define	_MSG_SIGNAL_52_MSG_NUM_STR_DEF_MSG	":56:Real-time signal RTMIN+3"
#define	_MSG_SIGNAL_52_FILE_CAT_NUM	uxlibc:56
#define	_SGI_DSIGNAL_52	":56"
#define	_SGI_SIGNAL_52	"uxlibc:56"
#define	_SGI_MSIGNAL_52	"uxlibc:56:Real-time signal RTMIN+3"
#define	_SGI_SSIGNAL_52	"Real-time signal RTMIN+3"
#define	_MSG_SIGNAL_53_MSG_NUM	57
#define	_MSG_SIGNAL_53_MSG_NUM_STR	":57"
#define	_MSG_SIGNAL_53_CAT_NUM_STR	"uxlibc:57"
#define	_MSG_SIGNAL_53_DEF_MSG	"Real-time signal RTMIN+4"
#define	_MSG_SIGNAL_53_CAT_NUM_STR_DEF_MSG	"uxlibc:57:Real-time signal RTMIN+4"
#define	_MSG_SIGNAL_53_MSG_NUM_STR_DEF_MSG	":57:Real-time signal RTMIN+4"
#define	_MSG_SIGNAL_53_FILE_CAT_NUM	uxlibc:57
#define	_SGI_DSIGNAL_53	":57"
#define	_SGI_SIGNAL_53	"uxlibc:57"
#define	_SGI_MSIGNAL_53	"uxlibc:57:Real-time signal RTMIN+4"
#define	_SGI_SSIGNAL_53	"Real-time signal RTMIN+4"
#define	_MSG_SIGNAL_54_MSG_NUM	58
#define	_MSG_SIGNAL_54_MSG_NUM_STR	":58"
#define	_MSG_SIGNAL_54_CAT_NUM_STR	"uxlibc:58"
#define	_MSG_SIGNAL_54_DEF_MSG	"Real-time signal RTMIN+5"
#define	_MSG_SIGNAL_54_CAT_NUM_STR_DEF_MSG	"uxlibc:58:Real-time signal RTMIN+5"
#define	_MSG_SIGNAL_54_MSG_NUM_STR_DEF_MSG	":58:Real-time signal RTMIN+5"
#define	_MSG_SIGNAL_54_FILE_CAT_NUM	uxlibc:58
#define	_SGI_DSIGNAL_54	":58"
#define	_SGI_SIGNAL_54	"uxlibc:58"
#define	_SGI_MSIGNAL_54	"uxlibc:58:Real-time signal RTMIN+5"
#define	_SGI_SSIGNAL_54	"Real-time signal RTMIN+5"
#define	_MSG_SIGNAL_55_MSG_NUM	59
#define	_MSG_SIGNAL_55_MSG_NUM_STR	":59"
#define	_MSG_SIGNAL_55_CAT_NUM_STR	"uxlibc:59"
#define	_MSG_SIGNAL_55_DEF_MSG	"Real-time signal RTMIN+6"
#define	_MSG_SIGNAL_55_CAT_NUM_STR_DEF_MSG	"uxlibc:59:Real-time signal RTMIN+6"
#define	_MSG_SIGNAL_55_MSG_NUM_STR_DEF_MSG	":59:Real-time signal RTMIN+6"
#define	_MSG_SIGNAL_55_FILE_CAT_NUM	uxlibc:59
#define	_SGI_DSIGNAL_55	":59"
#define	_SGI_SIGNAL_55	"uxlibc:59"
#define	_SGI_MSIGNAL_55	"uxlibc:59:Real-time signal RTMIN+6"
#define	_SGI_SSIGNAL_55	"Real-time signal RTMIN+6"
#define	_MSG_SIGNAL_56_MSG_NUM	60
#define	_MSG_SIGNAL_56_MSG_NUM_STR	":60"
#define	_MSG_SIGNAL_56_CAT_NUM_STR	"uxlibc:60"
#define	_MSG_SIGNAL_56_DEF_MSG	"Real-time signal RTMIN+7"
#define	_MSG_SIGNAL_56_CAT_NUM_STR_DEF_MSG	"uxlibc:60:Real-time signal RTMIN+7"
#define	_MSG_SIGNAL_56_MSG_NUM_STR_DEF_MSG	":60:Real-time signal RTMIN+7"
#define	_MSG_SIGNAL_56_FILE_CAT_NUM	uxlibc:60
#define	_SGI_DSIGNAL_56	":60"
#define	_SGI_SIGNAL_56	"uxlibc:60"
#define	_SGI_MSIGNAL_56	"uxlibc:60:Real-time signal RTMIN+7"
#define	_SGI_SSIGNAL_56	"Real-time signal RTMIN+7"
#define	_MSG_SIGNAL_57_MSG_NUM	61
#define	_MSG_SIGNAL_57_MSG_NUM_STR	":61"
#define	_MSG_SIGNAL_57_CAT_NUM_STR	"uxlibc:61"
#define	_MSG_SIGNAL_57_DEF_MSG	"Real-time signal RTMIN+8"
#define	_MSG_SIGNAL_57_CAT_NUM_STR_DEF_MSG	"uxlibc:61:Real-time signal RTMIN+8"
#define	_MSG_SIGNAL_57_MSG_NUM_STR_DEF_MSG	":61:Real-time signal RTMIN+8"
#define	_MSG_SIGNAL_57_FILE_CAT_NUM	uxlibc:61
#define	_SGI_DSIGNAL_57	":61"
#define	_SGI_SIGNAL_57	"uxlibc:61"
#define	_SGI_MSIGNAL_57	"uxlibc:61:Real-time signal RTMIN+8"
#define	_SGI_SSIGNAL_57	"Real-time signal RTMIN+8"
#define	_MSG_SIGNAL_58_MSG_NUM	62
#define	_MSG_SIGNAL_58_MSG_NUM_STR	":62"
#define	_MSG_SIGNAL_58_CAT_NUM_STR	"uxlibc:62"
#define	_MSG_SIGNAL_58_DEF_MSG	"Real-time signal RTMIN+9"
#define	_MSG_SIGNAL_58_CAT_NUM_STR_DEF_MSG	"uxlibc:62:Real-time signal RTMIN+9"
#define	_MSG_SIGNAL_58_MSG_NUM_STR_DEF_MSG	":62:Real-time signal RTMIN+9"
#define	_MSG_SIGNAL_58_FILE_CAT_NUM	uxlibc:62
#define	_SGI_DSIGNAL_58	":62"
#define	_SGI_SIGNAL_58	"uxlibc:62"
#define	_SGI_MSIGNAL_58	"uxlibc:62:Real-time signal RTMIN+9"
#define	_SGI_SSIGNAL_58	"Real-time signal RTMIN+9"
#define	_MSG_SIGNAL_59_MSG_NUM	63
#define	_MSG_SIGNAL_59_MSG_NUM_STR	":63"
#define	_MSG_SIGNAL_59_CAT_NUM_STR	"uxlibc:63"
#define	_MSG_SIGNAL_59_DEF_MSG	"Real-time signal RTMIN+10"
#define	_MSG_SIGNAL_59_CAT_NUM_STR_DEF_MSG	"uxlibc:63:Real-time signal RTMIN+10"
#define	_MSG_SIGNAL_59_MSG_NUM_STR_DEF_MSG	":63:Real-time signal RTMIN+10"
#define	_MSG_SIGNAL_59_FILE_CAT_NUM	uxlibc:63
#define	_SGI_DSIGNAL_59	":63"
#define	_SGI_SIGNAL_59	"uxlibc:63"
#define	_SGI_MSIGNAL_59	"uxlibc:63:Real-time signal RTMIN+10"
#define	_SGI_SSIGNAL_59	"Real-time signal RTMIN+10"
#define	_MSG_SIGNAL_60_MSG_NUM	64
#define	_MSG_SIGNAL_60_MSG_NUM_STR	":64"
#define	_MSG_SIGNAL_60_CAT_NUM_STR	"uxlibc:64"
#define	_MSG_SIGNAL_60_DEF_MSG	"Real-time signal RTMIN+11"
#define	_MSG_SIGNAL_60_CAT_NUM_STR_DEF_MSG	"uxlibc:64:Real-time signal RTMIN+11"
#define	_MSG_SIGNAL_60_MSG_NUM_STR_DEF_MSG	":64:Real-time signal RTMIN+11"
#define	_MSG_SIGNAL_60_FILE_CAT_NUM	uxlibc:64
#define	_SGI_DSIGNAL_60	":64"
#define	_SGI_SIGNAL_60	"uxlibc:64"
#define	_SGI_MSIGNAL_60	"uxlibc:64:Real-time signal RTMIN+11"
#define	_SGI_SSIGNAL_60	"Real-time signal RTMIN+11"
#define	_MSG_SIGNAL_61_MSG_NUM	65
#define	_MSG_SIGNAL_61_MSG_NUM_STR	":65"
#define	_MSG_SIGNAL_61_CAT_NUM_STR	"uxlibc:65"
#define	_MSG_SIGNAL_61_DEF_MSG	"Real-time signal RTMIN+12"
#define	_MSG_SIGNAL_61_CAT_NUM_STR_DEF_MSG	"uxlibc:65:Real-time signal RTMIN+12"
#define	_MSG_SIGNAL_61_MSG_NUM_STR_DEF_MSG	":65:Real-time signal RTMIN+12"
#define	_MSG_SIGNAL_61_FILE_CAT_NUM	uxlibc:65
#define	_SGI_DSIGNAL_61	":65"
#define	_SGI_SIGNAL_61	"uxlibc:65"
#define	_SGI_MSIGNAL_61	"uxlibc:65:Real-time signal RTMIN+12"
#define	_SGI_SSIGNAL_61	"Real-time signal RTMIN+12"
#define	_MSG_SIGNAL_62_MSG_NUM	66
#define	_MSG_SIGNAL_62_MSG_NUM_STR	":66"
#define	_MSG_SIGNAL_62_CAT_NUM_STR	"uxlibc:66"
#define	_MSG_SIGNAL_62_DEF_MSG	"Real-time signal RTMIN+13"
#define	_MSG_SIGNAL_62_CAT_NUM_STR_DEF_MSG	"uxlibc:66:Real-time signal RTMIN+13"
#define	_MSG_SIGNAL_62_MSG_NUM_STR_DEF_MSG	":66:Real-time signal RTMIN+13"
#define	_MSG_SIGNAL_62_FILE_CAT_NUM	uxlibc:66
#define	_SGI_DSIGNAL_62	":66"
#define	_SGI_SIGNAL_62	"uxlibc:66"
#define	_SGI_MSIGNAL_62	"uxlibc:66:Real-time signal RTMIN+13"
#define	_SGI_SSIGNAL_62	"Real-time signal RTMIN+13"
#define	_MSG_SIGNAL_63_MSG_NUM	67
#define	_MSG_SIGNAL_63_MSG_NUM_STR	":67"
#define	_MSG_SIGNAL_63_CAT_NUM_STR	"uxlibc:67"
#define	_MSG_SIGNAL_63_DEF_MSG	"Real-time signal RTMIN+14"
#define	_MSG_SIGNAL_63_CAT_NUM_STR_DEF_MSG	"uxlibc:67:Real-time signal RTMIN+14"
#define	_MSG_SIGNAL_63_MSG_NUM_STR_DEF_MSG	":67:Real-time signal RTMIN+14"
#define	_MSG_SIGNAL_63_FILE_CAT_NUM	uxlibc:67
#define	_SGI_DSIGNAL_63	":67"
#define	_SGI_SIGNAL_63	"uxlibc:67"
#define	_SGI_MSIGNAL_63	"uxlibc:67:Real-time signal RTMIN+14"
#define	_SGI_SSIGNAL_63	"Real-time signal RTMIN+14"
#define	_MSG_SIGNAL_64_MSG_NUM	68
#define	_MSG_SIGNAL_64_MSG_NUM_STR	":68"
#define	_MSG_SIGNAL_64_CAT_NUM_STR	"uxlibc:68"
#define	_MSG_SIGNAL_64_DEF_MSG	"Real-time signal RTMAX"
#define	_MSG_SIGNAL_64_CAT_NUM_STR_DEF_MSG	"uxlibc:68:Real-time signal RTMAX"
#define	_MSG_SIGNAL_64_MSG_NUM_STR_DEF_MSG	":68:Real-time signal RTMAX"
#define	_MSG_SIGNAL_64_FILE_CAT_NUM	uxlibc:68
#define	_SGI_DSIGNAL_64	":68"
#define	_SGI_SIGNAL_64	"uxlibc:68"
#define	_SGI_MSIGNAL_64	"uxlibc:68:Real-time signal RTMAX"
#define	_SGI_SSIGNAL_64	"Real-time signal RTMAX"
#define	_MSG_UXLIBC_69_MSG_NUM	69
#define	_MSG_UXLIBC_69_MSG_NUM_STR	":69"
#define	_MSG_UXLIBC_69_CAT_NUM_STR	"uxlibc:69"
#define	_MSG_UXLIBC_69_DEF_MSG	"high priority input available"
#define	_MSG_UXLIBC_69_CAT_NUM_STR_DEF_MSG	"uxlibc:69:high priority input available"
#define	_MSG_UXLIBC_69_MSG_NUM_STR_DEF_MSG	":69:high priority input available"
#define	_MSG_UXLIBC_69_FILE_CAT_NUM	uxlibc:69
#define	_SGI_DUXLIBC_69	":69"
#define	_SGI_UXLIBC_69	"uxlibc:69"
#define	_SGI_MUXLIBC_69	"uxlibc:69:high priority input available"
#define	_SGI_SUXLIBC_69	"high priority input available"
#define	_MSG_UXLIBC_70_MSG_NUM	70
#define	_MSG_UXLIBC_70_MSG_NUM_STR	":70"
#define	_MSG_UXLIBC_70_CAT_NUM_STR	"uxlibc:70"
#define	_MSG_UXLIBC_70_DEF_MSG	"disconnected device"
#define	_MSG_UXLIBC_70_CAT_NUM_STR_DEF_MSG	"uxlibc:70:disconnected device"
#define	_MSG_UXLIBC_70_MSG_NUM_STR_DEF_MSG	":70:disconnected device"
#define	_MSG_UXLIBC_70_FILE_CAT_NUM	uxlibc:70
#define	_SGI_DUXLIBC_70	":70"
#define	_SGI_UXLIBC_70	"uxlibc:70"
#define	_SGI_MUXLIBC_70	"uxlibc:70:disconnected device"
#define	_SGI_SUXLIBC_70	"disconnected device"
#define	_MSG_UXLIBC_71_MSG_NUM	71
#define	_MSG_UXLIBC_71_MSG_NUM_STR	":71"
#define	_MSG_UXLIBC_71_CAT_NUM_STR	"uxlibc:71"
#define	_MSG_UXLIBC_71_DEF_MSG	" ( from process %d )"
#define	_MSG_UXLIBC_71_CAT_NUM_STR_DEF_MSG	"uxlibc:71: ( from process %d )"
#define	_MSG_UXLIBC_71_MSG_NUM_STR_DEF_MSG	":71: ( from process %d )"
#define	_MSG_UXLIBC_71_FILE_CAT_NUM	uxlibc:71
#define	_SGI_DUXLIBC_71	":71"
#define	_SGI_UXLIBC_71	"uxlibc:71"
#define	_SGI_MUXLIBC_71	"uxlibc:71: ( from process %d )"
#define	_SGI_SUXLIBC_71	" ( from process %d )"
#define	_MSG_PFMT_SEV_MSG_NUM	72
#define	_MSG_PFMT_SEV_MSG_NUM_STR	":72"
#define	_MSG_PFMT_SEV_CAT_NUM_STR	"uxlibc:72"
#define	_MSG_PFMT_SEV_DEF_MSG	"SEV = %d"
#define	_MSG_PFMT_SEV_CAT_NUM_STR_DEF_MSG	"uxlibc:72:SEV = %d"
#define	_MSG_PFMT_SEV_MSG_NUM_STR_DEF_MSG	":72:SEV = %d"
#define	_MSG_PFMT_SEV_FILE_CAT_NUM	uxlibc:72
#define	_SGI_DPFMT_SEV	":72"
#define	_SGI_PFMT_SEV	"uxlibc:72"
#define	_SGI_MPFMT_SEV	"uxlibc:72:SEV = %d"
#define	_SGI_SPFMT_SEV	"SEV = %d"
#define	_MSG_PFMT_TO_FIX_MSG_NUM	73
#define	_MSG_PFMT_TO_FIX_MSG_NUM_STR	":73"
#define	_MSG_PFMT_TO_FIX_CAT_NUM_STR	"uxlibc:73"
#define	_MSG_PFMT_TO_FIX_DEF_MSG	"TO FIX"
#define	_MSG_PFMT_TO_FIX_CAT_NUM_STR_DEF_MSG	"uxlibc:73:TO FIX"
#define	_MSG_PFMT_TO_FIX_MSG_NUM_STR_DEF_MSG	":73:TO FIX"
#define	_MSG_PFMT_TO_FIX_FILE_CAT_NUM	uxlibc:73
#define	_SGI_DPFMT_TO_FIX	":73"
#define	_SGI_PFMT_TO_FIX	"uxlibc:73"
#define	_SGI_MPFMT_TO_FIX	"uxlibc:73:TO FIX"
#define	_SGI_SPFMT_TO_FIX	"TO FIX"
#define	_MSG_PFMT_ERROR_MSG_NUM	74
#define	_MSG_PFMT_ERROR_MSG_NUM_STR	":74"
#define	_MSG_PFMT_ERROR_CAT_NUM_STR	"uxlibc:74"
#define	_MSG_PFMT_ERROR_DEF_MSG	"ERROR"
#define	_MSG_PFMT_ERROR_CAT_NUM_STR_DEF_MSG	"uxlibc:74:ERROR"
#define	_MSG_PFMT_ERROR_MSG_NUM_STR_DEF_MSG	":74:ERROR"
#define	_MSG_PFMT_ERROR_FILE_CAT_NUM	uxlibc:74
#define	_SGI_DPFMT_ERROR	":74"
#define	_SGI_PFMT_ERROR	"uxlibc:74"
#define	_SGI_MPFMT_ERROR	"uxlibc:74:ERROR"
#define	_SGI_SPFMT_ERROR	"ERROR"
#define	_MSG_PFMT_HALT_MSG_NUM	75
#define	_MSG_PFMT_HALT_MSG_NUM_STR	":75"
#define	_MSG_PFMT_HALT_CAT_NUM_STR	"uxlibc:75"
#define	_MSG_PFMT_HALT_DEF_MSG	"HALT"
#define	_MSG_PFMT_HALT_CAT_NUM_STR_DEF_MSG	"uxlibc:75:HALT"
#define	_MSG_PFMT_HALT_MSG_NUM_STR_DEF_MSG	":75:HALT"
#define	_MSG_PFMT_HALT_FILE_CAT_NUM	uxlibc:75
#define	_SGI_DPFMT_HALT	":75"
#define	_SGI_PFMT_HALT	"uxlibc:75"
#define	_SGI_MPFMT_HALT	"uxlibc:75:HALT"
#define	_SGI_SPFMT_HALT	"HALT"
#define	_MSG_PFMT_WARNING_MSG_NUM	76
#define	_MSG_PFMT_WARNING_MSG_NUM_STR	":76"
#define	_MSG_PFMT_WARNING_CAT_NUM_STR	"uxlibc:76"
#define	_MSG_PFMT_WARNING_DEF_MSG	"WARNING"
#define	_MSG_PFMT_WARNING_CAT_NUM_STR_DEF_MSG	"uxlibc:76:WARNING"
#define	_MSG_PFMT_WARNING_MSG_NUM_STR_DEF_MSG	":76:WARNING"
#define	_MSG_PFMT_WARNING_FILE_CAT_NUM	uxlibc:76
#define	_SGI_DPFMT_WARNING	":76"
#define	_SGI_PFMT_WARNING	"uxlibc:76"
#define	_SGI_MPFMT_WARNING	"uxlibc:76:WARNING"
#define	_SGI_SPFMT_WARNING	"WARNING"
#define	_MSG_PFMT_INFO_MSG_NUM	77
#define	_MSG_PFMT_INFO_MSG_NUM_STR	":77"
#define	_MSG_PFMT_INFO_CAT_NUM_STR	"uxlibc:77"
#define	_MSG_PFMT_INFO_DEF_MSG	"INFO"
#define	_MSG_PFMT_INFO_CAT_NUM_STR_DEF_MSG	"uxlibc:77:INFO"
#define	_MSG_PFMT_INFO_MSG_NUM_STR_DEF_MSG	":77:INFO"
#define	_MSG_PFMT_INFO_FILE_CAT_NUM	uxlibc:77
#define	_SGI_DPFMT_INFO	":77"
#define	_SGI_PFMT_INFO	"uxlibc:77"
#define	_SGI_MPFMT_INFO	"uxlibc:77:INFO"
#define	_SGI_SPFMT_INFO	"INFO"
#define	_MSG_YACCPAR_SYNTAX_MSG_NUM	78
#define	_MSG_YACCPAR_SYNTAX_MSG_NUM_STR	":78"
#define	_MSG_YACCPAR_SYNTAX_CAT_NUM_STR	"uxlibc:78"
#define	_MSG_YACCPAR_SYNTAX_DEF_MSG	"Syntax error - cannot backup"
#define	_MSG_YACCPAR_SYNTAX_CAT_NUM_STR_DEF_MSG	"uxlibc:78:Syntax error - cannot backup"
#define	_MSG_YACCPAR_SYNTAX_MSG_NUM_STR_DEF_MSG	":78:Syntax error - cannot backup"
#define	_MSG_YACCPAR_SYNTAX_FILE_CAT_NUM	uxlibc:78
#define	_SGI_DYACCPAR_SYNTAX	":78"
#define	_SGI_YACCPAR_SYNTAX	"uxlibc:78"
#define	_SGI_MYACCPAR_SYNTAX	"uxlibc:78:Syntax error - cannot backup"
#define	_SGI_SYACCPAR_SYNTAX	"Syntax error - cannot backup"
#define	_MSG_YACCPAR_INITERR_MSG_NUM	79
#define	_MSG_YACCPAR_INITERR_MSG_NUM_STR	":79"
#define	_MSG_YACCPAR_INITERR_CAT_NUM_STR	"uxlibc:79"
#define	_MSG_YACCPAR_INITERR_DEF_MSG	"Yacc initialization error"
#define	_MSG_YACCPAR_INITERR_CAT_NUM_STR_DEF_MSG	"uxlibc:79:Yacc initialization error"
#define	_MSG_YACCPAR_INITERR_MSG_NUM_STR_DEF_MSG	":79:Yacc initialization error"
#define	_MSG_YACCPAR_INITERR_FILE_CAT_NUM	uxlibc:79
#define	_SGI_DYACCPAR_INITERR	":79"
#define	_SGI_YACCPAR_INITERR	"uxlibc:79"
#define	_SGI_MYACCPAR_INITERR	"uxlibc:79:Yacc initialization error"
#define	_SGI_SYACCPAR_INITERR	"Yacc initialization error"
#define	_MSG_YACCPAR_STACK_MSG_NUM	80
#define	_MSG_YACCPAR_STACK_MSG_NUM_STR	":80"
#define	_MSG_YACCPAR_STACK_CAT_NUM_STR	"uxlibc:80"
#define	_MSG_YACCPAR_STACK_DEF_MSG	"Yacc stack overflow"
#define	_MSG_YACCPAR_STACK_CAT_NUM_STR_DEF_MSG	"uxlibc:80:Yacc stack overflow"
#define	_MSG_YACCPAR_STACK_MSG_NUM_STR_DEF_MSG	":80:Yacc stack overflow"
#define	_MSG_YACCPAR_STACK_FILE_CAT_NUM	uxlibc:80
#define	_SGI_DYACCPAR_STACK	":80"
#define	_SGI_YACCPAR_STACK	"uxlibc:80"
#define	_SGI_MYACCPAR_STACK	"uxlibc:80:Yacc stack overflow"
#define	_SGI_SYACCPAR_STACK	"Yacc stack overflow"
#define	_MSG_SYNTAX_ERROR_MSG_NUM	81
#define	_MSG_SYNTAX_ERROR_MSG_NUM_STR	":81"
#define	_MSG_SYNTAX_ERROR_CAT_NUM_STR	"uxlibc:81"
#define	_MSG_SYNTAX_ERROR_DEF_MSG	"Syntax error"
#define	_MSG_SYNTAX_ERROR_CAT_NUM_STR_DEF_MSG	"uxlibc:81:Syntax error"
#define	_MSG_SYNTAX_ERROR_MSG_NUM_STR_DEF_MSG	":81:Syntax error"
#define	_MSG_SYNTAX_ERROR_FILE_CAT_NUM	uxlibc:81
#define	_SGI_DSYNTAX_ERROR	":81"
#define	_SGI_SYNTAX_ERROR	"uxlibc:81"
#define	_SGI_MSYNTAX_ERROR	"uxlibc:81:Syntax error"
#define	_SGI_SSYNTAX_ERROR	"Syntax error"
#define	_MSG_UXLIBC_82_MSG_NUM	82
#define	_MSG_UXLIBC_82_MSG_NUM_STR	":82"
#define	_MSG_UXLIBC_82_CAT_NUM_STR	"uxlibc:82"
#define	_MSG_UXLIBC_82_DEF_MSG	"Format error, no tabs after %s at line %d\n"
#define	_MSG_UXLIBC_82_CAT_NUM_STR_DEF_MSG	"uxlibc:82:Format error, no tabs after %s at line %d\n"
#define	_MSG_UXLIBC_82_MSG_NUM_STR_DEF_MSG	":82:Format error, no tabs after %s at line %d\n"
#define	_MSG_UXLIBC_82_FILE_CAT_NUM	uxlibc:82
#define	_SGI_DUXLIBC_82	":82"
#define	_SGI_UXLIBC_82	"uxlibc:82"
#define	_SGI_MUXLIBC_82	"uxlibc:82:Format error, no tabs after %s at line %d\n"
#define	_SGI_SUXLIBC_82	"Format error, no tabs after %s at line %d\n"
#define	_MSG_UXLIBC_83_MSG_NUM	83
#define	_MSG_UXLIBC_83_MSG_NUM_STR	":83"
#define	_MSG_UXLIBC_83_CAT_NUM_STR	"uxlibc:83"
#define	_MSG_UXLIBC_83_DEF_MSG	"Not enough memory for the magic table"
#define	_MSG_UXLIBC_83_CAT_NUM_STR_DEF_MSG	"uxlibc:83:Not enough memory for the magic table"
#define	_MSG_UXLIBC_83_MSG_NUM_STR_DEF_MSG	":83:Not enough memory for the magic table"
#define	_MSG_UXLIBC_83_FILE_CAT_NUM	uxlibc:83
#define	_SGI_DUXLIBC_83	":83"
#define	_SGI_UXLIBC_83	"uxlibc:83"
#define	_SGI_MUXLIBC_83	"uxlibc:83:Not enough memory for the magic table"
#define	_SGI_SUXLIBC_83	"Not enough memory for the magic table"
#define	_MSG_FILE_84_MSG_NUM	84
#define	_MSG_FILE_84_MSG_NUM_STR	":84"
#define	_MSG_FILE_84_CAT_NUM_STR	"uxlibc:84"
#define	_MSG_FILE_84_DEF_MSG	"%s:\t"
#define	_MSG_FILE_84_CAT_NUM_STR_DEF_MSG	"uxlibc:84:%s:\t"
#define	_MSG_FILE_84_MSG_NUM_STR_DEF_MSG	":84:%s:\t"
#define	_MSG_FILE_84_FILE_CAT_NUM	uxlibc:84
#define	_SGI_DFILE_84	":84"
#define	_SGI_FILE_84	"uxlibc:84"
#define	_SGI_MFILE_84	"uxlibc:84:%s:\t"
#define	_SGI_SFILE_84	"%s:\t"
#define	_MSG_UXLIBC_85_MSG_NUM	85
#define	_MSG_UXLIBC_85_MSG_NUM_STR	":85"
#define	_MSG_UXLIBC_85_CAT_NUM_STR	"uxlibc:85"
#define	_MSG_UXLIBC_85_DEF_MSG	"Can't open the magic file <%s>: %s\n"
#define	_MSG_UXLIBC_85_CAT_NUM_STR_DEF_MSG	"uxlibc:85:Can't open the magic file <%s>: %s\n"
#define	_MSG_UXLIBC_85_MSG_NUM_STR_DEF_MSG	":85:Can't open the magic file <%s>: %s\n"
#define	_MSG_UXLIBC_85_FILE_CAT_NUM	uxlibc:85
#define	_SGI_DUXLIBC_85	":85"
#define	_SGI_UXLIBC_85	"uxlibc:85"
#define	_SGI_MUXLIBC_85	"uxlibc:85:Can't open the magic file <%s>: %s\n"
#define	_SGI_SUXLIBC_85	"Can't open the magic file <%s>: %s\n"
#define	_MSG_UXLIBC_86_MSG_NUM	86
#define	_MSG_UXLIBC_86_MSG_NUM_STR	":86"
#define	_MSG_UXLIBC_86_CAT_NUM_STR	"uxlibc:86"
#define	_MSG_UXLIBC_86_DEF_MSG	"Can't close %s: %s\n"
#define	_MSG_UXLIBC_86_CAT_NUM_STR_DEF_MSG	"uxlibc:86:Can't close %s: %s\n"
#define	_MSG_UXLIBC_86_MSG_NUM_STR_DEF_MSG	":86:Can't close %s: %s\n"
#define	_MSG_UXLIBC_86_FILE_CAT_NUM	uxlibc:86
#define	_SGI_DUXLIBC_86	":86"
#define	_SGI_UXLIBC_86	"uxlibc:86"
#define	_SGI_MUXLIBC_86	"uxlibc:86:Can't close %s: %s\n"
#define	_SGI_SUXLIBC_86	"Can't close %s: %s\n"
#define	_MSG_UXLIBC_87_MSG_NUM	87
#define	_MSG_UXLIBC_87_MSG_NUM_STR	":87"
#define	_MSG_UXLIBC_87_CAT_NUM_STR	"uxlibc:87"
#define	_MSG_UXLIBC_87_DEF_MSG	"level	off	type	opcode	value	string\n"
#define	_MSG_UXLIBC_87_CAT_NUM_STR_DEF_MSG	"uxlibc:87:level	off	type	opcode	value	string\n"
#define	_MSG_UXLIBC_87_MSG_NUM_STR_DEF_MSG	":87:level	off	type	opcode	value	string\n"
#define	_MSG_UXLIBC_87_FILE_CAT_NUM	uxlibc:87
#define	_SGI_DUXLIBC_87	":87"
#define	_SGI_UXLIBC_87	"uxlibc:87"
#define	_SGI_MUXLIBC_87	"uxlibc:87:level	off	type	opcode	value	string\n"
#define	_SGI_SUXLIBC_87	"level	off	type	opcode	value	string\n"
#define	_MSG_regcomp_REG_NOMATCH_MSG_NUM	88
#define	_MSG_regcomp_REG_NOMATCH_MSG_NUM_STR	":88"
#define	_MSG_regcomp_REG_NOMATCH_CAT_NUM_STR	"uxlibc:88"
#define	_MSG_regcomp_REG_NOMATCH_DEF_MSG	"regexec() failed to match"
#define	_MSG_regcomp_REG_NOMATCH_CAT_NUM_STR_DEF_MSG	"uxlibc:88:regexec() failed to match"
#define	_MSG_regcomp_REG_NOMATCH_MSG_NUM_STR_DEF_MSG	":88:regexec() failed to match"
#define	_MSG_regcomp_REG_NOMATCH_FILE_CAT_NUM	uxlibc:88
#define	_SGI_Dregcomp_REG_NOMATCH	":88"
#define	_SGI_regcomp_REG_NOMATCH	"uxlibc:88"
#define	_SGI_Mregcomp_REG_NOMATCH	"uxlibc:88:regexec() failed to match"
#define	_SGI_Sregcomp_REG_NOMATCH	"regexec() failed to match"
#define	_MSG_regcomp_REG_BADPAT_MSG_NUM	89
#define	_MSG_regcomp_REG_BADPAT_MSG_NUM_STR	":89"
#define	_MSG_regcomp_REG_BADPAT_CAT_NUM_STR	"uxlibc:89"
#define	_MSG_regcomp_REG_BADPAT_DEF_MSG	"invalid regular expression"
#define	_MSG_regcomp_REG_BADPAT_CAT_NUM_STR_DEF_MSG	"uxlibc:89:invalid regular expression"
#define	_MSG_regcomp_REG_BADPAT_MSG_NUM_STR_DEF_MSG	":89:invalid regular expression"
#define	_MSG_regcomp_REG_BADPAT_FILE_CAT_NUM	uxlibc:89
#define	_SGI_Dregcomp_REG_BADPAT	":89"
#define	_SGI_regcomp_REG_BADPAT	"uxlibc:89"
#define	_SGI_Mregcomp_REG_BADPAT	"uxlibc:89:invalid regular expression"
#define	_SGI_Sregcomp_REG_BADPAT	"invalid regular expression"
#define	_MSG_regcomp_REG_ECOLLATE_MSG_NUM	90
#define	_MSG_regcomp_REG_ECOLLATE_MSG_NUM_STR	":90"
#define	_MSG_regcomp_REG_ECOLLATE_CAT_NUM_STR	"uxlibc:90"
#define	_MSG_regcomp_REG_ECOLLATE_DEF_MSG	"invalid collating element"
#define	_MSG_regcomp_REG_ECOLLATE_CAT_NUM_STR_DEF_MSG	"uxlibc:90:invalid collating element"
#define	_MSG_regcomp_REG_ECOLLATE_MSG_NUM_STR_DEF_MSG	":90:invalid collating element"
#define	_MSG_regcomp_REG_ECOLLATE_FILE_CAT_NUM	uxlibc:90
#define	_SGI_Dregcomp_REG_ECOLLATE	":90"
#define	_SGI_regcomp_REG_ECOLLATE	"uxlibc:90"
#define	_SGI_Mregcomp_REG_ECOLLATE	"uxlibc:90:invalid collating element"
#define	_SGI_Sregcomp_REG_ECOLLATE	"invalid collating element"
#define	_MSG_regcomp_REG_ECTYPE_MSG_NUM	91
#define	_MSG_regcomp_REG_ECTYPE_MSG_NUM_STR	":91"
#define	_MSG_regcomp_REG_ECTYPE_CAT_NUM_STR	"uxlibc:91"
#define	_MSG_regcomp_REG_ECTYPE_DEF_MSG	"invalid character class"
#define	_MSG_regcomp_REG_ECTYPE_CAT_NUM_STR_DEF_MSG	"uxlibc:91:invalid character class"
#define	_MSG_regcomp_REG_ECTYPE_MSG_NUM_STR_DEF_MSG	":91:invalid character class"
#define	_MSG_regcomp_REG_ECTYPE_FILE_CAT_NUM	uxlibc:91
#define	_SGI_Dregcomp_REG_ECTYPE	":91"
#define	_SGI_regcomp_REG_ECTYPE	"uxlibc:91"
#define	_SGI_Mregcomp_REG_ECTYPE	"uxlibc:91:invalid character class"
#define	_SGI_Sregcomp_REG_ECTYPE	"invalid character class"
#define	_MSG_regcomp_REG_EESCAPE_MSG_NUM	92
#define	_MSG_regcomp_REG_EESCAPE_MSG_NUM_STR	":92"
#define	_MSG_regcomp_REG_EESCAPE_CAT_NUM_STR	"uxlibc:92"
#define	_MSG_regcomp_REG_EESCAPE_DEF_MSG	"trailing backslash (\\)"
#define	_MSG_regcomp_REG_EESCAPE_CAT_NUM_STR_DEF_MSG	"uxlibc:92:trailing backslash (\\)"
#define	_MSG_regcomp_REG_EESCAPE_MSG_NUM_STR_DEF_MSG	":92:trailing backslash (\\)"
#define	_MSG_regcomp_REG_EESCAPE_FILE_CAT_NUM	uxlibc:92
#define	_SGI_Dregcomp_REG_EESCAPE	":92"
#define	_SGI_regcomp_REG_EESCAPE	"uxlibc:92"
#define	_SGI_Mregcomp_REG_EESCAPE	"uxlibc:92:trailing backslash (\\)"
#define	_SGI_Sregcomp_REG_EESCAPE	"trailing backslash (\\)"
#define	_MSG_regcomp_REG_ESUBREG_MSG_NUM	93
#define	_MSG_regcomp_REG_ESUBREG_MSG_NUM_STR	":93"
#define	_MSG_regcomp_REG_ESUBREG_CAT_NUM_STR	"uxlibc:93"
#define	_MSG_regcomp_REG_ESUBREG_DEF_MSG	"invalid backreference number"
#define	_MSG_regcomp_REG_ESUBREG_CAT_NUM_STR_DEF_MSG	"uxlibc:93:invalid backreference number"
#define	_MSG_regcomp_REG_ESUBREG_MSG_NUM_STR_DEF_MSG	":93:invalid backreference number"
#define	_MSG_regcomp_REG_ESUBREG_FILE_CAT_NUM	uxlibc:93
#define	_SGI_Dregcomp_REG_ESUBREG	":93"
#define	_SGI_regcomp_REG_ESUBREG	"uxlibc:93"
#define	_SGI_Mregcomp_REG_ESUBREG	"uxlibc:93:invalid backreference number"
#define	_SGI_Sregcomp_REG_ESUBREG	"invalid backreference number"
#define	_MSG_regcomp_REG_EBRACK_MSG_NUM	94
#define	_MSG_regcomp_REG_EBRACK_MSG_NUM_STR	":94"
#define	_MSG_regcomp_REG_EBRACK_CAT_NUM_STR	"uxlibc:94"
#define	_MSG_regcomp_REG_EBRACK_DEF_MSG	"brackets ([ ]) not balanced"
#define	_MSG_regcomp_REG_EBRACK_CAT_NUM_STR_DEF_MSG	"uxlibc:94:brackets ([ ]) not balanced"
#define	_MSG_regcomp_REG_EBRACK_MSG_NUM_STR_DEF_MSG	":94:brackets ([ ]) not balanced"
#define	_MSG_regcomp_REG_EBRACK_FILE_CAT_NUM	uxlibc:94
#define	_SGI_Dregcomp_REG_EBRACK	":94"
#define	_SGI_regcomp_REG_EBRACK	"uxlibc:94"
#define	_SGI_Mregcomp_REG_EBRACK	"uxlibc:94:brackets ([ ]) not balanced"
#define	_SGI_Sregcomp_REG_EBRACK	"brackets ([ ]) not balanced"
#define	_MSG_regcomp_REG_EPAREN_MSG_NUM	95
#define	_MSG_regcomp_REG_EPAREN_MSG_NUM_STR	":95"
#define	_MSG_regcomp_REG_EPAREN_CAT_NUM_STR	"uxlibc:95"
#define	_MSG_regcomp_REG_EPAREN_DEF_MSG	"parentheses not balanced"
#define	_MSG_regcomp_REG_EPAREN_CAT_NUM_STR_DEF_MSG	"uxlibc:95:parentheses not balanced"
#define	_MSG_regcomp_REG_EPAREN_MSG_NUM_STR_DEF_MSG	":95:parentheses not balanced"
#define	_MSG_regcomp_REG_EPAREN_FILE_CAT_NUM	uxlibc:95
#define	_SGI_Dregcomp_REG_EPAREN	":95"
#define	_SGI_regcomp_REG_EPAREN	"uxlibc:95"
#define	_SGI_Mregcomp_REG_EPAREN	"uxlibc:95:parentheses not balanced"
#define	_SGI_Sregcomp_REG_EPAREN	"parentheses not balanced"
#define	_MSG_regcomp_REG_EBRACE_MSG_NUM	96
#define	_MSG_regcomp_REG_EBRACE_MSG_NUM_STR	":96"
#define	_MSG_regcomp_REG_EBRACE_CAT_NUM_STR	"uxlibc:96"
#define	_MSG_regcomp_REG_EBRACE_DEF_MSG	"braces not balanced"
#define	_MSG_regcomp_REG_EBRACE_CAT_NUM_STR_DEF_MSG	"uxlibc:96:braces not balanced"
#define	_MSG_regcomp_REG_EBRACE_MSG_NUM_STR_DEF_MSG	":96:braces not balanced"
#define	_MSG_regcomp_REG_EBRACE_FILE_CAT_NUM	uxlibc:96
#define	_SGI_Dregcomp_REG_EBRACE	":96"
#define	_SGI_regcomp_REG_EBRACE	"uxlibc:96"
#define	_SGI_Mregcomp_REG_EBRACE	"uxlibc:96:braces not balanced"
#define	_SGI_Sregcomp_REG_EBRACE	"braces not balanced"
#define	_MSG_regcomp_REG_BADBR_MSG_NUM	97
#define	_MSG_regcomp_REG_BADBR_MSG_NUM_STR	":97"
#define	_MSG_regcomp_REG_BADBR_CAT_NUM_STR	"uxlibc:97"
#define	_MSG_regcomp_REG_BADBR_DEF_MSG	"invalid repetition count(s)"
#define	_MSG_regcomp_REG_BADBR_CAT_NUM_STR_DEF_MSG	"uxlibc:97:invalid repetition count(s)"
#define	_MSG_regcomp_REG_BADBR_MSG_NUM_STR_DEF_MSG	":97:invalid repetition count(s)"
#define	_MSG_regcomp_REG_BADBR_FILE_CAT_NUM	uxlibc:97
#define	_SGI_Dregcomp_REG_BADBR	":97"
#define	_SGI_regcomp_REG_BADBR	"uxlibc:97"
#define	_SGI_Mregcomp_REG_BADBR	"uxlibc:97:invalid repetition count(s)"
#define	_SGI_Sregcomp_REG_BADBR	"invalid repetition count(s)"
#define	_MSG_regcomp_REG_ERANGE_MSG_NUM	98
#define	_MSG_regcomp_REG_ERANGE_MSG_NUM_STR	":98"
#define	_MSG_regcomp_REG_ERANGE_CAT_NUM_STR	"uxlibc:98"
#define	_MSG_regcomp_REG_ERANGE_DEF_MSG	"invalid character range"
#define	_MSG_regcomp_REG_ERANGE_CAT_NUM_STR_DEF_MSG	"uxlibc:98:invalid character range"
#define	_MSG_regcomp_REG_ERANGE_MSG_NUM_STR_DEF_MSG	":98:invalid character range"
#define	_MSG_regcomp_REG_ERANGE_FILE_CAT_NUM	uxlibc:98
#define	_SGI_Dregcomp_REG_ERANGE	":98"
#define	_SGI_regcomp_REG_ERANGE	"uxlibc:98"
#define	_SGI_Mregcomp_REG_ERANGE	"uxlibc:98:invalid character range"
#define	_SGI_Sregcomp_REG_ERANGE	"invalid character range"
#define	_MSG_regcomp_REG_ESPACE_MSG_NUM	99
#define	_MSG_regcomp_REG_ESPACE_MSG_NUM_STR	":99"
#define	_MSG_regcomp_REG_ESPACE_CAT_NUM_STR	"uxlibc:99"
#define	_MSG_regcomp_REG_ESPACE_DEF_MSG	"out of memory"
#define	_MSG_regcomp_REG_ESPACE_CAT_NUM_STR_DEF_MSG	"uxlibc:99:out of memory"
#define	_MSG_regcomp_REG_ESPACE_MSG_NUM_STR_DEF_MSG	":99:out of memory"
#define	_MSG_regcomp_REG_ESPACE_FILE_CAT_NUM	uxlibc:99
#define	_SGI_Dregcomp_REG_ESPACE	":99"
#define	_SGI_regcomp_REG_ESPACE	"uxlibc:99"
#define	_SGI_Mregcomp_REG_ESPACE	"uxlibc:99:out of memory"
#define	_SGI_Sregcomp_REG_ESPACE	"out of memory"
#define	_MSG_regcomp_REG_BADRPT_MSG_NUM	100
#define	_MSG_regcomp_REG_BADRPT_MSG_NUM_STR	":100"
#define	_MSG_regcomp_REG_BADRPT_CAT_NUM_STR	"uxlibc:100"
#define	_MSG_regcomp_REG_BADRPT_DEF_MSG	"repetition-operator operand invalid"
#define	_MSG_regcomp_REG_BADRPT_CAT_NUM_STR_DEF_MSG	"uxlibc:100:repetition-operator operand invalid"
#define	_MSG_regcomp_REG_BADRPT_MSG_NUM_STR_DEF_MSG	":100:repetition-operator operand invalid"
#define	_MSG_regcomp_REG_BADRPT_FILE_CAT_NUM	uxlibc:100
#define	_SGI_Dregcomp_REG_BADRPT	":100"
#define	_SGI_regcomp_REG_BADRPT	"uxlibc:100"
#define	_SGI_Mregcomp_REG_BADRPT	"uxlibc:100:repetition-operator operand invalid"
#define	_SGI_Sregcomp_REG_BADRPT	"repetition-operator operand invalid"
#define	_MSG_regcomp_REG_EMPTY_MSG_NUM	101
#define	_MSG_regcomp_REG_EMPTY_MSG_NUM_STR	":101"
#define	_MSG_regcomp_REG_EMPTY_CAT_NUM_STR	"uxlibc:101"
#define	_MSG_regcomp_REG_EMPTY_DEF_MSG	"empty (sub)expression"
#define	_MSG_regcomp_REG_EMPTY_CAT_NUM_STR_DEF_MSG	"uxlibc:101:empty (sub)expression"
#define	_MSG_regcomp_REG_EMPTY_MSG_NUM_STR_DEF_MSG	":101:empty (sub)expression"
#define	_MSG_regcomp_REG_EMPTY_FILE_CAT_NUM	uxlibc:101
#define	_SGI_Dregcomp_REG_EMPTY	":101"
#define	_SGI_regcomp_REG_EMPTY	"uxlibc:101"
#define	_SGI_Mregcomp_REG_EMPTY	"uxlibc:101:empty (sub)expression"
#define	_SGI_Sregcomp_REG_EMPTY	"empty (sub)expression"
#define	_MSG_regcomp_REG_ASSERT_MSG_NUM	102
#define	_MSG_regcomp_REG_ASSERT_MSG_NUM_STR	":102"
#define	_MSG_regcomp_REG_ASSERT_CAT_NUM_STR	"uxlibc:102"
#define	_MSG_regcomp_REG_ASSERT_DEF_MSG	"\"can't happen\" -- you found a bug"
#define	_MSG_regcomp_REG_ASSERT_CAT_NUM_STR_DEF_MSG	"uxlibc:102:\"can't happen\" -- you found a bug"
#define	_MSG_regcomp_REG_ASSERT_MSG_NUM_STR_DEF_MSG	":102:\"can't happen\" -- you found a bug"
#define	_MSG_regcomp_REG_ASSERT_FILE_CAT_NUM	uxlibc:102
#define	_SGI_Dregcomp_REG_ASSERT	":102"
#define	_SGI_regcomp_REG_ASSERT	"uxlibc:102"
#define	_SGI_Mregcomp_REG_ASSERT	"uxlibc:102:\"can't happen\" -- you found a bug"
#define	_SGI_Sregcomp_REG_ASSERT	"\"can't happen\" -- you found a bug"
#define	_MSG_regcomp_REG_INVARG_MSG_NUM	103
#define	_MSG_regcomp_REG_INVARG_MSG_NUM_STR	":103"
#define	_MSG_regcomp_REG_INVARG_CAT_NUM_STR	"uxlibc:103"
#define	_MSG_regcomp_REG_INVARG_DEF_MSG	"invalid argument to regex routine"
#define	_MSG_regcomp_REG_INVARG_CAT_NUM_STR_DEF_MSG	"uxlibc:103:invalid argument to regex routine"
#define	_MSG_regcomp_REG_INVARG_MSG_NUM_STR_DEF_MSG	":103:invalid argument to regex routine"
#define	_MSG_regcomp_REG_INVARG_FILE_CAT_NUM	uxlibc:103
#define	_SGI_Dregcomp_REG_INVARG	":103"
#define	_SGI_regcomp_REG_INVARG	"uxlibc:103"
#define	_SGI_Mregcomp_REG_INVARG	"uxlibc:103:invalid argument to regex routine"
#define	_SGI_Sregcomp_REG_INVARG	"invalid argument to regex routine"
#define	_MSG_regcomp_unknown_MSG_NUM	104
#define	_MSG_regcomp_unknown_MSG_NUM_STR	":104"
#define	_MSG_regcomp_unknown_CAT_NUM_STR	"uxlibc:104"
#define	_MSG_regcomp_unknown_DEF_MSG	"*** unknown regexp error code ***"
#define	_MSG_regcomp_unknown_CAT_NUM_STR_DEF_MSG	"uxlibc:104:*** unknown regexp error code ***"
#define	_MSG_regcomp_unknown_MSG_NUM_STR_DEF_MSG	":104:*** unknown regexp error code ***"
#define	_MSG_regcomp_unknown_FILE_CAT_NUM	uxlibc:104
#define	_SGI_Dregcomp_unknown	":104"
#define	_SGI_regcomp_unknown	"uxlibc:104"
#define	_SGI_Mregcomp_unknown	"uxlibc:104:*** unknown regexp error code ***"
#define	_SGI_Sregcomp_unknown	"*** unknown regexp error code ***"
