#include <mkmsgs.h>
#define	_MSG_MMX_csh_Interrupted_MSG_NUM	1
#define	_MSG_MMX_csh_Interrupted_MSG_NUM_STR	":1"
#define	_MSG_MMX_csh_Interrupted_CAT_NUM_STR	"uxsgicsh:1"
#define	_MSG_MMX_csh_Interrupted_DEF_MSG	"Interrupted"
#define	_MSG_MMX_csh_Interrupted_CAT_NUM_STR_DEF_MSG	"uxsgicsh:1:Interrupted"
#define	_MSG_MMX_csh_Interrupted_MSG_NUM_STR_DEF_MSG	":1:Interrupted"
#define	_MSG_MMX_csh_Interrupted_FILE_CAT_NUM	uxsgicsh:1
#define	_SGI_DMMX_csh_Interrupted	":1"
#define	_SGI_MMX_csh_Interrupted	"uxsgicsh:1"
#define	_SGI_MMMX_csh_Interrupted	"uxsgicsh:1:Interrupted"
#define	_SGI_SMMX_csh_Interrupted	"Interrupted"
#define	_MSG_MMX_csh_2fewargs_MSG_NUM	2
#define	_MSG_MMX_csh_2fewargs_MSG_NUM_STR	":2"
#define	_MSG_MMX_csh_2fewargs_CAT_NUM_STR	"uxsgicsh:2"
#define	_MSG_MMX_csh_2fewargs_DEF_MSG	"Too few arguments"
#define	_MSG_MMX_csh_2fewargs_CAT_NUM_STR_DEF_MSG	"uxsgicsh:2:Too few arguments"
#define	_MSG_MMX_csh_2fewargs_MSG_NUM_STR_DEF_MSG	":2:Too few arguments"
#define	_MSG_MMX_csh_2fewargs_FILE_CAT_NUM	uxsgicsh:2
#define	_SGI_DMMX_csh_2fewargs	":2"
#define	_SGI_MMX_csh_2fewargs	"uxsgicsh:2"
#define	_SGI_MMMX_csh_2fewargs	"uxsgicsh:2:Too few arguments"
#define	_SGI_SMMX_csh_2fewargs	"Too few arguments"
#define	_MSG_MMX_csh_2manyargs_MSG_NUM	3
#define	_MSG_MMX_csh_2manyargs_MSG_NUM_STR	":3"
#define	_MSG_MMX_csh_2manyargs_CAT_NUM_STR	"uxsgicsh:3"
#define	_MSG_MMX_csh_2manyargs_DEF_MSG	"Too many arguments"
#define	_MSG_MMX_csh_2manyargs_CAT_NUM_STR_DEF_MSG	"uxsgicsh:3:Too many arguments"
#define	_MSG_MMX_csh_2manyargs_MSG_NUM_STR_DEF_MSG	":3:Too many arguments"
#define	_MSG_MMX_csh_2manyargs_FILE_CAT_NUM	uxsgicsh:3
#define	_SGI_DMMX_csh_2manyargs	":3"
#define	_SGI_MMX_csh_2manyargs	"uxsgicsh:3"
#define	_SGI_MMMX_csh_2manyargs	"uxsgicsh:3:Too many arguments"
#define	_SGI_SMMX_csh_2manyargs	"Too many arguments"
#define	_MSG_MMX_csh_nohome_MSG_NUM	4
#define	_MSG_MMX_csh_nohome_MSG_NUM_STR	":4"
#define	_MSG_MMX_csh_nohome_CAT_NUM_STR	"uxsgicsh:4"
#define	_MSG_MMX_csh_nohome_DEF_MSG	"No home directory"
#define	_MSG_MMX_csh_nohome_CAT_NUM_STR_DEF_MSG	"uxsgicsh:4:No home directory"
#define	_MSG_MMX_csh_nohome_MSG_NUM_STR_DEF_MSG	":4:No home directory"
#define	_MSG_MMX_csh_nohome_FILE_CAT_NUM	uxsgicsh:4
#define	_SGI_DMMX_csh_nohome	":4"
#define	_SGI_MMX_csh_nohome	"uxsgicsh:4"
#define	_SGI_MMMX_csh_nohome	"uxsgicsh:4:No home directory"
#define	_SGI_SMMX_csh_nohome	"No home directory"
#define	_MSG_MMX_csh_cannothome_MSG_NUM	5
#define	_MSG_MMX_csh_cannothome_MSG_NUM_STR	":5"
#define	_MSG_MMX_csh_cannothome_CAT_NUM_STR	"uxsgicsh:5"
#define	_MSG_MMX_csh_cannothome_DEF_MSG	"Can't change to home directory"
#define	_MSG_MMX_csh_cannothome_CAT_NUM_STR_DEF_MSG	"uxsgicsh:5:Can't change to home directory"
#define	_MSG_MMX_csh_cannothome_MSG_NUM_STR_DEF_MSG	":5:Can't change to home directory"
#define	_MSG_MMX_csh_cannothome_FILE_CAT_NUM	uxsgicsh:5
#define	_SGI_DMMX_csh_cannothome	":5"
#define	_SGI_MMX_csh_cannothome	"uxsgicsh:5"
#define	_SGI_MMMX_csh_cannothome	"uxsgicsh:5:Can't change to home directory"
#define	_SGI_SMMX_csh_cannothome	"Can't change to home directory"
#define	_MSG_MMX_csh_noodir_MSG_NUM	6
#define	_MSG_MMX_csh_noodir_MSG_NUM_STR	":6"
#define	_MSG_MMX_csh_noodir_CAT_NUM_STR	"uxsgicsh:6"
#define	_MSG_MMX_csh_noodir_DEF_MSG	"No other directory"
#define	_MSG_MMX_csh_noodir_CAT_NUM_STR_DEF_MSG	"uxsgicsh:6:No other directory"
#define	_MSG_MMX_csh_noodir_MSG_NUM_STR_DEF_MSG	":6:No other directory"
#define	_MSG_MMX_csh_noodir_FILE_CAT_NUM	uxsgicsh:6
#define	_SGI_DMMX_csh_noodir	":6"
#define	_SGI_MMX_csh_noodir	"uxsgicsh:6"
#define	_SGI_MMMX_csh_noodir	"uxsgicsh:6:No other directory"
#define	_SGI_SMMX_csh_noodir	"No other directory"
#define	_MSG_MMX_csh_dsnotdeep_MSG_NUM	7
#define	_MSG_MMX_csh_dsnotdeep_MSG_NUM_STR	":7"
#define	_MSG_MMX_csh_dsnotdeep_CAT_NUM_STR	"uxsgicsh:7"
#define	_MSG_MMX_csh_dsnotdeep_DEF_MSG	"Directory stack not that deep"
#define	_MSG_MMX_csh_dsnotdeep_CAT_NUM_STR_DEF_MSG	"uxsgicsh:7:Directory stack not that deep"
#define	_MSG_MMX_csh_dsnotdeep_MSG_NUM_STR_DEF_MSG	":7:Directory stack not that deep"
#define	_MSG_MMX_csh_dsnotdeep_FILE_CAT_NUM	uxsgicsh:7
#define	_SGI_DMMX_csh_dsnotdeep	":7"
#define	_SGI_MMX_csh_dsnotdeep	"uxsgicsh:7"
#define	_SGI_MMMX_csh_dsnotdeep	"uxsgicsh:7:Directory stack not that deep"
#define	_SGI_SMMX_csh_dsnotdeep	"Directory stack not that deep"
#define	_MSG_MMX_csh_invarg_MSG_NUM	8
#define	_MSG_MMX_csh_invarg_MSG_NUM_STR	":8"
#define	_MSG_MMX_csh_invarg_CAT_NUM_STR	"uxsgicsh:8"
#define	_MSG_MMX_csh_invarg_DEF_MSG	"'%s' - Invalid argument"
#define	_MSG_MMX_csh_invarg_CAT_NUM_STR_DEF_MSG	"uxsgicsh:8:'%s' - Invalid argument"
#define	_MSG_MMX_csh_invarg_MSG_NUM_STR_DEF_MSG	":8:'%s' - Invalid argument"
#define	_MSG_MMX_csh_invarg_FILE_CAT_NUM	uxsgicsh:8
#define	_SGI_DMMX_csh_invarg	":8"
#define	_SGI_MMX_csh_invarg	"uxsgicsh:8"
#define	_SGI_MMMX_csh_invarg	"uxsgicsh:8:'%s' - Invalid argument"
#define	_SGI_SMMX_csh_invarg	"'%s' - Invalid argument"
#define	_MSG_MMX_csh_dsempty_MSG_NUM	9
#define	_MSG_MMX_csh_dsempty_MSG_NUM_STR	":9"
#define	_MSG_MMX_csh_dsempty_CAT_NUM_STR	"uxsgicsh:9"
#define	_MSG_MMX_csh_dsempty_DEF_MSG	"Directory stack empty"
#define	_MSG_MMX_csh_dsempty_CAT_NUM_STR_DEF_MSG	"uxsgicsh:9:Directory stack empty"
#define	_MSG_MMX_csh_dsempty_MSG_NUM_STR_DEF_MSG	":9:Directory stack empty"
#define	_MSG_MMX_csh_dsempty_FILE_CAT_NUM	uxsgicsh:9
#define	_SGI_DMMX_csh_dsempty	":9"
#define	_SGI_MMX_csh_dsempty	"uxsgicsh:9"
#define	_SGI_MMMX_csh_dsempty	"uxsgicsh:9:Directory stack empty"
#define	_SGI_SMMX_csh_dsempty	"Directory stack empty"
#define	_MSG_MMX_csh_Ambiguous_MSG_NUM	10
#define	_MSG_MMX_csh_Ambiguous_MSG_NUM_STR	":10"
#define	_MSG_MMX_csh_Ambiguous_CAT_NUM_STR	"uxsgicsh:10"
#define	_MSG_MMX_csh_Ambiguous_DEF_MSG	"Ambiguous"
#define	_MSG_MMX_csh_Ambiguous_CAT_NUM_STR_DEF_MSG	"uxsgicsh:10:Ambiguous"
#define	_MSG_MMX_csh_Ambiguous_MSG_NUM_STR_DEF_MSG	":10:Ambiguous"
#define	_MSG_MMX_csh_Ambiguous_FILE_CAT_NUM	uxsgicsh:10
#define	_SGI_DMMX_csh_Ambiguous	":10"
#define	_SGI_MMX_csh_Ambiguous	"uxsgicsh:10"
#define	_SGI_MMMX_csh_Ambiguous	"uxsgicsh:10:Ambiguous"
#define	_SGI_SMMX_csh_Ambiguous	"Ambiguous"
#define	_MSG_MMX_csh_notermin_MSG_NUM	11
#define	_MSG_MMX_csh_notermin_MSG_NUM_STR	":11"
#define	_MSG_MMX_csh_notermin_CAT_NUM_STR	"uxsgicsh:11"
#define	_MSG_MMX_csh_notermin_DEF_MSG	"<< terminator not found"
#define	_MSG_MMX_csh_notermin_CAT_NUM_STR_DEF_MSG	"uxsgicsh:11:<< terminator not found"
#define	_MSG_MMX_csh_notermin_MSG_NUM_STR_DEF_MSG	":11:<< terminator not found"
#define	_MSG_MMX_csh_notermin_FILE_CAT_NUM	uxsgicsh:11
#define	_SGI_DMMX_csh_notermin	":11"
#define	_SGI_MMX_csh_notermin	"uxsgicsh:11"
#define	_SGI_MMMX_csh_notermin	"uxsgicsh:11:<< terminator not found"
#define	_SGI_SMMX_csh_notermin	"<< terminator not found"
#define	_MSG_MMX_csh_lineov_MSG_NUM	12
#define	_MSG_MMX_csh_lineov_MSG_NUM_STR	":12"
#define	_MSG_MMX_csh_lineov_CAT_NUM_STR	"uxsgicsh:12"
#define	_MSG_MMX_csh_lineov_DEF_MSG	"Line overflow"
#define	_MSG_MMX_csh_lineov_CAT_NUM_STR_DEF_MSG	"uxsgicsh:12:Line overflow"
#define	_MSG_MMX_csh_lineov_MSG_NUM_STR_DEF_MSG	":12:Line overflow"
#define	_MSG_MMX_csh_lineov_FILE_CAT_NUM	uxsgicsh:12
#define	_SGI_DMMX_csh_lineov	":12"
#define	_SGI_MMX_csh_lineov	"uxsgicsh:12"
#define	_SGI_MMMX_csh_lineov	"uxsgicsh:12:Line overflow"
#define	_SGI_SMMX_csh_lineov	"Line overflow"
#define	_MSG_MMX_csh_cmdnotfnd_MSG_NUM	13
#define	_MSG_MMX_csh_cmdnotfnd_MSG_NUM_STR	":13"
#define	_MSG_MMX_csh_cmdnotfnd_CAT_NUM_STR	"uxsgicsh:13"
#define	_MSG_MMX_csh_cmdnotfnd_DEF_MSG	"Command not found"
#define	_MSG_MMX_csh_cmdnotfnd_CAT_NUM_STR_DEF_MSG	"uxsgicsh:13:Command not found"
#define	_MSG_MMX_csh_cmdnotfnd_MSG_NUM_STR_DEF_MSG	":13:Command not found"
#define	_MSG_MMX_csh_cmdnotfnd_FILE_CAT_NUM	uxsgicsh:13
#define	_SGI_DMMX_csh_cmdnotfnd	":13"
#define	_SGI_MMX_csh_cmdnotfnd	"uxsgicsh:13"
#define	_SGI_MMMX_csh_cmdnotfnd	"uxsgicsh:13:Command not found"
#define	_SGI_SMMX_csh_cmdnotfnd	"Command not found"
#define	_MSG_MMX_csh_expsyntax_MSG_NUM	14
#define	_MSG_MMX_csh_expsyntax_MSG_NUM_STR	":14"
#define	_MSG_MMX_csh_expsyntax_CAT_NUM_STR	"uxsgicsh:14"
#define	_MSG_MMX_csh_expsyntax_DEF_MSG	"Expression syntax"
#define	_MSG_MMX_csh_expsyntax_CAT_NUM_STR_DEF_MSG	"uxsgicsh:14:Expression syntax"
#define	_MSG_MMX_csh_expsyntax_MSG_NUM_STR_DEF_MSG	":14:Expression syntax"
#define	_MSG_MMX_csh_expsyntax_FILE_CAT_NUM	uxsgicsh:14
#define	_SGI_DMMX_csh_expsyntax	":14"
#define	_SGI_MMX_csh_expsyntax	"uxsgicsh:14"
#define	_SGI_MMMX_csh_expsyntax	"uxsgicsh:14:Expression syntax"
#define	_SGI_SMMX_csh_expsyntax	"Expression syntax"
#define	_MSG_MMX_csh_mfinqu_MSG_NUM	15
#define	_MSG_MMX_csh_mfinqu_MSG_NUM_STR	":15"
#define	_MSG_MMX_csh_mfinqu_CAT_NUM_STR	"uxsgicsh:15"
#define	_MSG_MMX_csh_mfinqu_DEF_MSG	"Malformed file inquiry"
#define	_MSG_MMX_csh_mfinqu_CAT_NUM_STR_DEF_MSG	"uxsgicsh:15:Malformed file inquiry"
#define	_MSG_MMX_csh_mfinqu_MSG_NUM_STR_DEF_MSG	":15:Malformed file inquiry"
#define	_MSG_MMX_csh_mfinqu_FILE_CAT_NUM	uxsgicsh:15
#define	_SGI_DMMX_csh_mfinqu	":15"
#define	_SGI_MMX_csh_mfinqu	"uxsgicsh:15"
#define	_SGI_MMMX_csh_mfinqu	"uxsgicsh:15:Malformed file inquiry"
#define	_SGI_SMMX_csh_mfinqu	"Malformed file inquiry"
#define	_MSG_MMX_csh_missfilnam_MSG_NUM	16
#define	_MSG_MMX_csh_missfilnam_MSG_NUM_STR	":16"
#define	_MSG_MMX_csh_missfilnam_CAT_NUM_STR	"uxsgicsh:16"
#define	_MSG_MMX_csh_missfilnam_DEF_MSG	"Missing file name"
#define	_MSG_MMX_csh_missfilnam_CAT_NUM_STR_DEF_MSG	"uxsgicsh:16:Missing file name"
#define	_MSG_MMX_csh_missfilnam_MSG_NUM_STR_DEF_MSG	":16:Missing file name"
#define	_MSG_MMX_csh_missfilnam_FILE_CAT_NUM	uxsgicsh:16
#define	_SGI_DMMX_csh_missfilnam	":16"
#define	_SGI_MMX_csh_missfilnam	"uxsgicsh:16"
#define	_SGI_MMMX_csh_missfilnam	"uxsgicsh:16:Missing file name"
#define	_SGI_SMMX_csh_missfilnam	"Missing file name"
#define	_MSG_MMX_csh_notfromtty_MSG_NUM	17
#define	_MSG_MMX_csh_notfromtty_MSG_NUM_STR	":17"
#define	_MSG_MMX_csh_notfromtty_CAT_NUM_STR	"uxsgicsh:17"
#define	_MSG_MMX_csh_notfromtty_DEF_MSG	"Can't from terminal"
#define	_MSG_MMX_csh_notfromtty_CAT_NUM_STR_DEF_MSG	"uxsgicsh:17:Can't from terminal"
#define	_MSG_MMX_csh_notfromtty_MSG_NUM_STR_DEF_MSG	":17:Can't from terminal"
#define	_MSG_MMX_csh_notfromtty_FILE_CAT_NUM	uxsgicsh:17
#define	_SGI_DMMX_csh_notfromtty	":17"
#define	_SGI_MMX_csh_notfromtty	"uxsgicsh:17"
#define	_SGI_MMMX_csh_notfromtty	"uxsgicsh:17:Can't from terminal"
#define	_SGI_SMMX_csh_notfromtty	"Can't from terminal"
#define	_MSG_MMX_csh_xalias_MSG_NUM	18
#define	_MSG_MMX_csh_xalias_MSG_NUM_STR	":18"
#define	_MSG_MMX_csh_xalias_CAT_NUM_STR	"uxsgicsh:18"
#define	_MSG_MMX_csh_xalias_DEF_MSG	"Too dangerous to alias that"
#define	_MSG_MMX_csh_xalias_CAT_NUM_STR_DEF_MSG	"uxsgicsh:18:Too dangerous to alias that"
#define	_MSG_MMX_csh_xalias_MSG_NUM_STR_DEF_MSG	":18:Too dangerous to alias that"
#define	_MSG_MMX_csh_xalias_FILE_CAT_NUM	uxsgicsh:18
#define	_SGI_DMMX_csh_xalias	":18"
#define	_SGI_MMX_csh_xalias	"uxsgicsh:18"
#define	_SGI_MMMX_csh_xalias	"uxsgicsh:18:Too dangerous to alias that"
#define	_SGI_SMMX_csh_xalias	"Too dangerous to alias that"
#define	_MSG_MMX_csh_emptyIF_MSG_NUM	19
#define	_MSG_MMX_csh_emptyIF_MSG_NUM_STR	":19"
#define	_MSG_MMX_csh_emptyIF_CAT_NUM_STR	"uxsgicsh:19"
#define	_MSG_MMX_csh_emptyIF_DEF_MSG	"Empty if"
#define	_MSG_MMX_csh_emptyIF_CAT_NUM_STR_DEF_MSG	"uxsgicsh:19:Empty if"
#define	_MSG_MMX_csh_emptyIF_MSG_NUM_STR_DEF_MSG	":19:Empty if"
#define	_MSG_MMX_csh_emptyIF_FILE_CAT_NUM	uxsgicsh:19
#define	_SGI_DMMX_csh_emptyIF	":19"
#define	_SGI_MMX_csh_emptyIF	"uxsgicsh:19"
#define	_SGI_MMMX_csh_emptyIF	"uxsgicsh:19:Empty if"
#define	_SGI_SMMX_csh_emptyIF	"Empty if"
#define	_MSG_MMX_csh_ImprTHEN_MSG_NUM	20
#define	_MSG_MMX_csh_ImprTHEN_MSG_NUM_STR	":20"
#define	_MSG_MMX_csh_ImprTHEN_CAT_NUM_STR	"uxsgicsh:20"
#define	_MSG_MMX_csh_ImprTHEN_DEF_MSG	"Improper then"
#define	_MSG_MMX_csh_ImprTHEN_CAT_NUM_STR_DEF_MSG	"uxsgicsh:20:Improper then"
#define	_MSG_MMX_csh_ImprTHEN_MSG_NUM_STR_DEF_MSG	":20:Improper then"
#define	_MSG_MMX_csh_ImprTHEN_FILE_CAT_NUM	uxsgicsh:20
#define	_SGI_DMMX_csh_ImprTHEN	":20"
#define	_SGI_MMX_csh_ImprTHEN	"uxsgicsh:20"
#define	_SGI_MMMX_csh_ImprTHEN	"uxsgicsh:20:Improper then"
#define	_SGI_SMMX_csh_ImprTHEN	"Improper then"
#define	_MSG_MMX_csh_notinwf_MSG_NUM	21
#define	_MSG_MMX_csh_notinwf_MSG_NUM_STR	":21"
#define	_MSG_MMX_csh_notinwf_CAT_NUM_STR	"uxsgicsh:21"
#define	_MSG_MMX_csh_notinwf_DEF_MSG	"Not in while/foreach"
#define	_MSG_MMX_csh_notinwf_CAT_NUM_STR_DEF_MSG	"uxsgicsh:21:Not in while/foreach"
#define	_MSG_MMX_csh_notinwf_MSG_NUM_STR_DEF_MSG	":21:Not in while/foreach"
#define	_MSG_MMX_csh_notinwf_FILE_CAT_NUM	uxsgicsh:21
#define	_SGI_DMMX_csh_notinwf	":21"
#define	_SGI_MMX_csh_notinwf	"uxsgicsh:21"
#define	_SGI_MMMX_csh_notinwf	"uxsgicsh:21:Not in while/foreach"
#define	_SGI_SMMX_csh_notinwf	"Not in while/foreach"
#define	_MSG_MMX_csh_invvar_MSG_NUM	22
#define	_MSG_MMX_csh_invvar_MSG_NUM_STR	":22"
#define	_MSG_MMX_csh_invvar_CAT_NUM_STR	"uxsgicsh:22"
#define	_MSG_MMX_csh_invvar_DEF_MSG	"Invalid variable"
#define	_MSG_MMX_csh_invvar_CAT_NUM_STR_DEF_MSG	"uxsgicsh:22:Invalid variable"
#define	_MSG_MMX_csh_invvar_MSG_NUM_STR_DEF_MSG	":22:Invalid variable"
#define	_MSG_MMX_csh_invvar_FILE_CAT_NUM	uxsgicsh:22
#define	_SGI_DMMX_csh_invvar	":22"
#define	_SGI_MMX_csh_invvar	"uxsgicsh:22"
#define	_SGI_MMMX_csh_invvar	"uxsgicsh:22:Invalid variable"
#define	_SGI_SMMX_csh_invvar	"Invalid variable"
#define	_MSG_MMX_csh_wordsned_MSG_NUM	23
#define	_MSG_MMX_csh_wordsned_MSG_NUM_STR	":23"
#define	_MSG_MMX_csh_wordsned_CAT_NUM_STR	"uxsgicsh:23"
#define	_MSG_MMX_csh_wordsned_DEF_MSG	"Words not ()'ed"
#define	_MSG_MMX_csh_wordsned_CAT_NUM_STR_DEF_MSG	"uxsgicsh:23:Words not ()'ed"
#define	_MSG_MMX_csh_wordsned_MSG_NUM_STR_DEF_MSG	":23:Words not ()'ed"
#define	_MSG_MMX_csh_wordsned_FILE_CAT_NUM	uxsgicsh:23
#define	_SGI_DMMX_csh_wordsned	":23"
#define	_SGI_MMX_csh_wordsned	"uxsgicsh:23"
#define	_SGI_MMMX_csh_wordsned	"uxsgicsh:23:Words not ()'ed"
#define	_SGI_SMMX_csh_wordsned	"Words not ()'ed"
#define	_MSG_MMX_csh_nomatch_MSG_NUM	24
#define	_MSG_MMX_csh_nomatch_MSG_NUM_STR	":24"
#define	_MSG_MMX_csh_nomatch_CAT_NUM_STR	"uxsgicsh:24"
#define	_MSG_MMX_csh_nomatch_DEF_MSG	"No match"
#define	_MSG_MMX_csh_nomatch_CAT_NUM_STR_DEF_MSG	"uxsgicsh:24:No match"
#define	_MSG_MMX_csh_nomatch_MSG_NUM_STR_DEF_MSG	":24:No match"
#define	_MSG_MMX_csh_nomatch_FILE_CAT_NUM	uxsgicsh:24
#define	_SGI_DMMX_csh_nomatch	":24"
#define	_SGI_MMX_csh_nomatch	"uxsgicsh:24"
#define	_SGI_MMMX_csh_nomatch	"uxsgicsh:24:No match"
#define	_SGI_SMMX_csh_nomatch	"No match"
#define	_MSG_MMX_csh_tenotfnd_MSG_NUM	25
#define	_MSG_MMX_csh_tenotfnd_MSG_NUM_STR	":25"
#define	_MSG_MMX_csh_tenotfnd_CAT_NUM_STR	"uxsgicsh:25"
#define	_MSG_MMX_csh_tenotfnd_DEF_MSG	"then/endif not found"
#define	_MSG_MMX_csh_tenotfnd_CAT_NUM_STR_DEF_MSG	"uxsgicsh:25:then/endif not found"
#define	_MSG_MMX_csh_tenotfnd_MSG_NUM_STR_DEF_MSG	":25:then/endif not found"
#define	_MSG_MMX_csh_tenotfnd_FILE_CAT_NUM	uxsgicsh:25
#define	_SGI_DMMX_csh_tenotfnd	":25"
#define	_SGI_MMX_csh_tenotfnd	"uxsgicsh:25"
#define	_SGI_MMMX_csh_tenotfnd	"uxsgicsh:25:then/endif not found"
#define	_SGI_SMMX_csh_tenotfnd	"then/endif not found"
#define	_MSG_MMX_csh_endif_MSG_NUM	26
#define	_MSG_MMX_csh_endif_MSG_NUM_STR	":26"
#define	_MSG_MMX_csh_endif_CAT_NUM_STR	"uxsgicsh:26"
#define	_MSG_MMX_csh_endif_DEF_MSG	"endif not found"
#define	_MSG_MMX_csh_endif_CAT_NUM_STR_DEF_MSG	"uxsgicsh:26:endif not found"
#define	_MSG_MMX_csh_endif_MSG_NUM_STR_DEF_MSG	":26:endif not found"
#define	_MSG_MMX_csh_endif_FILE_CAT_NUM	uxsgicsh:26
#define	_SGI_DMMX_csh_endif	":26"
#define	_SGI_MMX_csh_endif	"uxsgicsh:26"
#define	_SGI_MMMX_csh_endif	"uxsgicsh:26:endif not found"
#define	_SGI_SMMX_csh_endif	"endif not found"
#define	_MSG_MMX_csh_endsw_MSG_NUM	27
#define	_MSG_MMX_csh_endsw_MSG_NUM_STR	":27"
#define	_MSG_MMX_csh_endsw_CAT_NUM_STR	"uxsgicsh:27"
#define	_MSG_MMX_csh_endsw_DEF_MSG	"endsw not found"
#define	_MSG_MMX_csh_endsw_CAT_NUM_STR_DEF_MSG	"uxsgicsh:27:endsw not found"
#define	_MSG_MMX_csh_endsw_MSG_NUM_STR_DEF_MSG	":27:endsw not found"
#define	_MSG_MMX_csh_endsw_FILE_CAT_NUM	uxsgicsh:27
#define	_SGI_DMMX_csh_endsw	":27"
#define	_SGI_MMX_csh_endsw	"uxsgicsh:27"
#define	_SGI_MMMX_csh_endsw	"uxsgicsh:27:endsw not found"
#define	_SGI_SMMX_csh_endsw	"endsw not found"
#define	_MSG_MMX_csh_end_MSG_NUM	28
#define	_MSG_MMX_csh_end_MSG_NUM_STR	":28"
#define	_MSG_MMX_csh_end_CAT_NUM_STR	"uxsgicsh:28"
#define	_MSG_MMX_csh_end_DEF_MSG	"end not found"
#define	_MSG_MMX_csh_end_CAT_NUM_STR_DEF_MSG	"uxsgicsh:28:end not found"
#define	_MSG_MMX_csh_end_MSG_NUM_STR_DEF_MSG	":28:end not found"
#define	_MSG_MMX_csh_end_FILE_CAT_NUM	uxsgicsh:28
#define	_SGI_DMMX_csh_end	":28"
#define	_SGI_MMX_csh_end	"uxsgicsh:28"
#define	_SGI_MMMX_csh_end	"uxsgicsh:28:end not found"
#define	_SGI_SMMX_csh_end	"end not found"
#define	_MSG_MMX_csh_label_MSG_NUM	29
#define	_MSG_MMX_csh_label_MSG_NUM_STR	":29"
#define	_MSG_MMX_csh_label_CAT_NUM_STR	"uxsgicsh:29"
#define	_MSG_MMX_csh_label_DEF_MSG	"label not found"
#define	_MSG_MMX_csh_label_CAT_NUM_STR_DEF_MSG	"uxsgicsh:29:label not found"
#define	_MSG_MMX_csh_label_MSG_NUM_STR_DEF_MSG	":29:label not found"
#define	_MSG_MMX_csh_label_FILE_CAT_NUM	uxsgicsh:29
#define	_SGI_DMMX_csh_label	":29"
#define	_SGI_MMX_csh_label	"uxsgicsh:29"
#define	_SGI_MMMX_csh_label	"uxsgicsh:29:label not found"
#define	_SGI_SMMX_csh_label	"label not found"
#define	_MSG_MMX_csh_imprmask_MSG_NUM	30
#define	_MSG_MMX_csh_imprmask_MSG_NUM_STR	":30"
#define	_MSG_MMX_csh_imprmask_CAT_NUM_STR	"uxsgicsh:30"
#define	_MSG_MMX_csh_imprmask_DEF_MSG	"Improper mask"
#define	_MSG_MMX_csh_imprmask_CAT_NUM_STR_DEF_MSG	"uxsgicsh:30:Improper mask"
#define	_MSG_MMX_csh_imprmask_MSG_NUM_STR_DEF_MSG	":30:Improper mask"
#define	_MSG_MMX_csh_imprmask_FILE_CAT_NUM	uxsgicsh:30
#define	_SGI_DMMX_csh_imprmask	":30"
#define	_SGI_MMX_csh_imprmask	"uxsgicsh:30"
#define	_SGI_MMMX_csh_imprmask	"uxsgicsh:30:Improper mask"
#define	_SGI_SMMX_csh_imprmask	"Improper mask"
#define	_MSG_MMX_csh_nolimit_MSG_NUM	31
#define	_MSG_MMX_csh_nolimit_MSG_NUM_STR	":31"
#define	_MSG_MMX_csh_nolimit_CAT_NUM_STR	"uxsgicsh:31"
#define	_MSG_MMX_csh_nolimit_DEF_MSG	"No such limit"
#define	_MSG_MMX_csh_nolimit_CAT_NUM_STR_DEF_MSG	"uxsgicsh:31:No such limit"
#define	_MSG_MMX_csh_nolimit_MSG_NUM_STR_DEF_MSG	":31:No such limit"
#define	_MSG_MMX_csh_nolimit_FILE_CAT_NUM	uxsgicsh:31
#define	_SGI_DMMX_csh_nolimit	":31"
#define	_SGI_MMX_csh_nolimit	"uxsgicsh:31"
#define	_SGI_MMMX_csh_nolimit	"uxsgicsh:31:No such limit"
#define	_SGI_SMMX_csh_nolimit	"No such limit"
#define	_MSG_MMX_csh_illscale_MSG_NUM	32
#define	_MSG_MMX_csh_illscale_MSG_NUM_STR	":32"
#define	_MSG_MMX_csh_illscale_CAT_NUM_STR	"uxsgicsh:32"
#define	_MSG_MMX_csh_illscale_DEF_MSG	"Improper or unknown scale factor"
#define	_MSG_MMX_csh_illscale_CAT_NUM_STR_DEF_MSG	"uxsgicsh:32:Improper or unknown scale factor"
#define	_MSG_MMX_csh_illscale_MSG_NUM_STR_DEF_MSG	":32:Improper or unknown scale factor"
#define	_MSG_MMX_csh_illscale_FILE_CAT_NUM	uxsgicsh:32
#define	_SGI_DMMX_csh_illscale	":32"
#define	_SGI_MMX_csh_illscale	"uxsgicsh:32"
#define	_SGI_MMMX_csh_illscale	"uxsgicsh:32:Improper or unknown scale factor"
#define	_SGI_SMMX_csh_illscale	"Improper or unknown scale factor"
#define	_MSG_MMX_csh_miss_MSG_NUM	33
#define	_MSG_MMX_csh_miss_MSG_NUM_STR	":33"
#define	_MSG_MMX_csh_miss_CAT_NUM_STR	"uxsgicsh:33"
#define	_MSG_MMX_csh_miss_DEF_MSG	"Missing %s"
#define	_MSG_MMX_csh_miss_CAT_NUM_STR_DEF_MSG	"uxsgicsh:33:Missing %s"
#define	_MSG_MMX_csh_miss_MSG_NUM_STR_DEF_MSG	":33:Missing %s"
#define	_MSG_MMX_csh_miss_FILE_CAT_NUM	uxsgicsh:33
#define	_SGI_DMMX_csh_miss	":33"
#define	_SGI_MMX_csh_miss	"uxsgicsh:33"
#define	_SGI_MMMX_csh_miss	"uxsgicsh:33:Missing %s"
#define	_SGI_SMMX_csh_miss	"Missing %s"
#define	_MSG_MMX_csh_nooutput_MSG_NUM	34
#define	_MSG_MMX_csh_nooutput_MSG_NUM_STR	":34"
#define	_MSG_MMX_csh_nooutput_CAT_NUM_STR	"uxsgicsh:34"
#define	_MSG_MMX_csh_nooutput_DEF_MSG	"No output"
#define	_MSG_MMX_csh_nooutput_CAT_NUM_STR_DEF_MSG	"uxsgicsh:34:No output"
#define	_MSG_MMX_csh_nooutput_MSG_NUM_STR_DEF_MSG	":34:No output"
#define	_MSG_MMX_csh_nooutput_FILE_CAT_NUM	uxsgicsh:34
#define	_SGI_DMMX_csh_nooutput	":34"
#define	_SGI_MMX_csh_nooutput	"uxsgicsh:34"
#define	_SGI_MMMX_csh_nooutput	"uxsgicsh:34:No output"
#define	_SGI_SMMX_csh_nooutput	"No output"
#define	_MSG_MMX_csh_undefvar_MSG_NUM	35
#define	_MSG_MMX_csh_undefvar_MSG_NUM_STR	":35"
#define	_MSG_MMX_csh_undefvar_CAT_NUM_STR	"uxsgicsh:35"
#define	_MSG_MMX_csh_undefvar_DEF_MSG	"Undefined variable"
#define	_MSG_MMX_csh_undefvar_CAT_NUM_STR_DEF_MSG	"uxsgicsh:35:Undefined variable"
#define	_MSG_MMX_csh_undefvar_MSG_NUM_STR_DEF_MSG	":35:Undefined variable"
#define	_MSG_MMX_csh_undefvar_FILE_CAT_NUM	uxsgicsh:35
#define	_SGI_DMMX_csh_undefvar	":35"
#define	_SGI_MMX_csh_undefvar	"uxsgicsh:35"
#define	_SGI_MMMX_csh_undefvar	"uxsgicsh:35:Undefined variable"
#define	_SGI_SMMX_csh_undefvar	"Undefined variable"
#define	_MSG_MMX_csh_badsig_MSG_NUM	36
#define	_MSG_MMX_csh_badsig_MSG_NUM_STR	":36"
#define	_MSG_MMX_csh_badsig_CAT_NUM_STR	"uxsgicsh:36"
#define	_MSG_MMX_csh_badsig_DEF_MSG	"Bad signal number"
#define	_MSG_MMX_csh_badsig_CAT_NUM_STR_DEF_MSG	"uxsgicsh:36:Bad signal number"
#define	_MSG_MMX_csh_badsig_MSG_NUM_STR_DEF_MSG	":36:Bad signal number"
#define	_MSG_MMX_csh_badsig_FILE_CAT_NUM	uxsgicsh:36
#define	_SGI_DMMX_csh_badsig	":36"
#define	_SGI_MMX_csh_badsig	"uxsgicsh:36"
#define	_SGI_MMMX_csh_badsig	"uxsgicsh:36:Bad signal number"
#define	_SGI_SMMX_csh_badsig	"Bad signal number"
#define	_MSG_MMX_csh_unknownsig_MSG_NUM	37
#define	_MSG_MMX_csh_unknownsig_MSG_NUM_STR	":37"
#define	_MSG_MMX_csh_unknownsig_CAT_NUM_STR	"uxsgicsh:37"
#define	_MSG_MMX_csh_unknownsig_DEF_MSG	"Unknown signal; kill -l lists signals"
#define	_MSG_MMX_csh_unknownsig_CAT_NUM_STR_DEF_MSG	"uxsgicsh:37:Unknown signal; kill -l lists signals"
#define	_MSG_MMX_csh_unknownsig_MSG_NUM_STR_DEF_MSG	":37:Unknown signal; kill -l lists signals"
#define	_MSG_MMX_csh_unknownsig_FILE_CAT_NUM	uxsgicsh:37
#define	_SGI_DMMX_csh_unknownsig	":37"
#define	_SGI_MMX_csh_unknownsig	"uxsgicsh:37"
#define	_SGI_MMMX_csh_unknownsig	"uxsgicsh:37:Unknown signal; kill -l lists signals"
#define	_SGI_SMMX_csh_unknownsig	"Unknown signal; kill -l lists signals"
#define	_MSG_MMX_csh_jobproc_MSG_NUM	38
#define	_MSG_MMX_csh_jobproc_MSG_NUM_STR	":38"
#define	_MSG_MMX_csh_jobproc_CAT_NUM_STR	"uxsgicsh:38"
#define	_MSG_MMX_csh_jobproc_DEF_MSG	"Arguments should be jobs or process id's"
#define	_MSG_MMX_csh_jobproc_CAT_NUM_STR_DEF_MSG	"uxsgicsh:38:Arguments should be jobs or process id's"
#define	_MSG_MMX_csh_jobproc_MSG_NUM_STR_DEF_MSG	":38:Arguments should be jobs or process id's"
#define	_MSG_MMX_csh_jobproc_FILE_CAT_NUM	uxsgicsh:38
#define	_SGI_DMMX_csh_jobproc	":38"
#define	_SGI_MMX_csh_jobproc	"uxsgicsh:38"
#define	_SGI_MMMX_csh_jobproc	"uxsgicsh:38:Arguments should be jobs or process id's"
#define	_SGI_SMMX_csh_jobproc	"Arguments should be jobs or process id's"
#define	_MSG_MMX_csh_nocjob_MSG_NUM	39
#define	_MSG_MMX_csh_nocjob_MSG_NUM_STR	":39"
#define	_MSG_MMX_csh_nocjob_CAT_NUM_STR	"uxsgicsh:39"
#define	_MSG_MMX_csh_nocjob_DEF_MSG	"No current job"
#define	_MSG_MMX_csh_nocjob_CAT_NUM_STR_DEF_MSG	"uxsgicsh:39:No current job"
#define	_MSG_MMX_csh_nocjob_MSG_NUM_STR_DEF_MSG	":39:No current job"
#define	_MSG_MMX_csh_nocjob_FILE_CAT_NUM	uxsgicsh:39
#define	_SGI_DMMX_csh_nocjob	":39"
#define	_SGI_MMX_csh_nocjob	"uxsgicsh:39"
#define	_SGI_MMMX_csh_nocjob	"uxsgicsh:39:No current job"
#define	_SGI_SMMX_csh_nocjob	"No current job"
#define	_MSG_MMX_csh_nopjob_MSG_NUM	40
#define	_MSG_MMX_csh_nopjob_MSG_NUM_STR	":40"
#define	_MSG_MMX_csh_nopjob_CAT_NUM_STR	"uxsgicsh:40"
#define	_MSG_MMX_csh_nopjob_DEF_MSG	"No previous job"
#define	_MSG_MMX_csh_nopjob_CAT_NUM_STR_DEF_MSG	"uxsgicsh:40:No previous job"
#define	_MSG_MMX_csh_nopjob_MSG_NUM_STR_DEF_MSG	":40:No previous job"
#define	_MSG_MMX_csh_nopjob_FILE_CAT_NUM	uxsgicsh:40
#define	_SGI_DMMX_csh_nopjob	":40"
#define	_SGI_MMX_csh_nopjob	"uxsgicsh:40"
#define	_SGI_MMMX_csh_nopjob	"uxsgicsh:40:No previous job"
#define	_SGI_SMMX_csh_nopjob	"No previous job"
#define	_MSG_MMX_csh_nojob_MSG_NUM	41
#define	_MSG_MMX_csh_nojob_MSG_NUM_STR	":41"
#define	_MSG_MMX_csh_nojob_CAT_NUM_STR	"uxsgicsh:41"
#define	_MSG_MMX_csh_nojob_DEF_MSG	"No such job"
#define	_MSG_MMX_csh_nojob_CAT_NUM_STR_DEF_MSG	"uxsgicsh:41:No such job"
#define	_MSG_MMX_csh_nojob_MSG_NUM_STR_DEF_MSG	":41:No such job"
#define	_MSG_MMX_csh_nojob_FILE_CAT_NUM	uxsgicsh:41
#define	_SGI_DMMX_csh_nojob	":41"
#define	_SGI_MMX_csh_nojob	"uxsgicsh:41"
#define	_SGI_MMMX_csh_nojob	"uxsgicsh:41:No such job"
#define	_SGI_SMMX_csh_nojob	"No such job"
#define	_MSG_MMX_csh_jobmatch_MSG_NUM	42
#define	_MSG_MMX_csh_jobmatch_MSG_NUM_STR	":42"
#define	_MSG_MMX_csh_jobmatch_CAT_NUM_STR	"uxsgicsh:42"
#define	_MSG_MMX_csh_jobmatch_DEF_MSG	"No job matches pattern"
#define	_MSG_MMX_csh_jobmatch_CAT_NUM_STR_DEF_MSG	"uxsgicsh:42:No job matches pattern"
#define	_MSG_MMX_csh_jobmatch_MSG_NUM_STR_DEF_MSG	":42:No job matches pattern"
#define	_MSG_MMX_csh_jobmatch_FILE_CAT_NUM	uxsgicsh:42
#define	_SGI_DMMX_csh_jobmatch	":42"
#define	_SGI_MMX_csh_jobmatch	"uxsgicsh:42"
#define	_SGI_MMMX_csh_jobmatch	"uxsgicsh:42:No job matches pattern"
#define	_SGI_SMMX_csh_jobmatch	"No job matches pattern"
#define	_MSG_MMX_csh_subserr_MSG_NUM	43
#define	_MSG_MMX_csh_subserr_MSG_NUM_STR	":43"
#define	_MSG_MMX_csh_subserr_CAT_NUM_STR	"uxsgicsh:43"
#define	_MSG_MMX_csh_subserr_DEF_MSG	"Subscript error"
#define	_MSG_MMX_csh_subserr_CAT_NUM_STR_DEF_MSG	"uxsgicsh:43:Subscript error"
#define	_MSG_MMX_csh_subserr_MSG_NUM_STR_DEF_MSG	":43:Subscript error"
#define	_MSG_MMX_csh_subserr_FILE_CAT_NUM	uxsgicsh:43
#define	_SGI_DMMX_csh_subserr	":43"
#define	_SGI_MMX_csh_subserr	"uxsgicsh:43"
#define	_SGI_MMMX_csh_subserr	"uxsgicsh:43:Subscript error"
#define	_SGI_SMMX_csh_subserr	"Subscript error"
#define	_MSG_MMX_csh_subsout_MSG_NUM	44
#define	_MSG_MMX_csh_subsout_MSG_NUM_STR	":44"
#define	_MSG_MMX_csh_subsout_CAT_NUM_STR	"uxsgicsh:44"
#define	_MSG_MMX_csh_subsout_DEF_MSG	"Subscript out of range"
#define	_MSG_MMX_csh_subsout_CAT_NUM_STR_DEF_MSG	"uxsgicsh:44:Subscript out of range"
#define	_MSG_MMX_csh_subsout_MSG_NUM_STR_DEF_MSG	":44:Subscript out of range"
#define	_MSG_MMX_csh_subsout_FILE_CAT_NUM	uxsgicsh:44
#define	_SGI_DMMX_csh_subsout	":44"
#define	_SGI_MMX_csh_subsout	"uxsgicsh:44"
#define	_SGI_MMMX_csh_subsout	"uxsgicsh:44:Subscript out of range"
#define	_SGI_SMMX_csh_subsout	"Subscript out of range"
#define	_MSG_MMX_csh_badnbr_MSG_NUM	45
#define	_MSG_MMX_csh_badnbr_MSG_NUM_STR	":45"
#define	_MSG_MMX_csh_badnbr_CAT_NUM_STR	"uxsgicsh:45"
#define	_MSG_MMX_csh_badnbr_DEF_MSG	"Badly formed number"
#define	_MSG_MMX_csh_badnbr_CAT_NUM_STR_DEF_MSG	"uxsgicsh:45:Badly formed number"
#define	_MSG_MMX_csh_badnbr_MSG_NUM_STR_DEF_MSG	":45:Badly formed number"
#define	_MSG_MMX_csh_badnbr_FILE_CAT_NUM	uxsgicsh:45
#define	_SGI_DMMX_csh_badnbr	":45"
#define	_SGI_MMX_csh_badnbr	"uxsgicsh:45"
#define	_SGI_MMMX_csh_badnbr	"uxsgicsh:45:Badly formed number"
#define	_SGI_SMMX_csh_badnbr	"Badly formed number"
#define	_MSG_MMX_csh_nomorw_MSG_NUM	46
#define	_MSG_MMX_csh_nomorw_MSG_NUM_STR	":46"
#define	_MSG_MMX_csh_nomorw_CAT_NUM_STR	"uxsgicsh:46"
#define	_MSG_MMX_csh_nomorw_DEF_MSG	"No more words"
#define	_MSG_MMX_csh_nomorw_CAT_NUM_STR_DEF_MSG	"uxsgicsh:46:No more words"
#define	_MSG_MMX_csh_nomorw_MSG_NUM_STR_DEF_MSG	":46:No more words"
#define	_MSG_MMX_csh_nomorw_FILE_CAT_NUM	uxsgicsh:46
#define	_SGI_DMMX_csh_nomorw	":46"
#define	_SGI_MMX_csh_nomorw	"uxsgicsh:46"
#define	_SGI_MMMX_csh_nomorw	"uxsgicsh:46:No more words"
#define	_SGI_SMMX_csh_nomorw	"No more words"
#define	_MSG_MMX_csh_syntaxerr_MSG_NUM	47
#define	_MSG_MMX_csh_syntaxerr_MSG_NUM_STR	":47"
#define	_MSG_MMX_csh_syntaxerr_CAT_NUM_STR	"uxsgicsh:47"
#define	_MSG_MMX_csh_syntaxerr_DEF_MSG	"Syntax error"
#define	_MSG_MMX_csh_syntaxerr_CAT_NUM_STR_DEF_MSG	"uxsgicsh:47:Syntax error"
#define	_MSG_MMX_csh_syntaxerr_MSG_NUM_STR_DEF_MSG	":47:Syntax error"
#define	_MSG_MMX_csh_syntaxerr_FILE_CAT_NUM	uxsgicsh:47
#define	_SGI_DMMX_csh_syntaxerr	":47"
#define	_SGI_MMX_csh_syntaxerr	"uxsgicsh:47"
#define	_SGI_MMMX_csh_syntaxerr	"uxsgicsh:47:Syntax error"
#define	_SGI_SMMX_csh_syntaxerr	"Syntax error"
#define	_MSG_MMX_csh_mail_MSG_NUM	48
#define	_MSG_MMX_csh_mail_MSG_NUM_STR	":48"
#define	_MSG_MMX_csh_mail_CAT_NUM_STR	"uxsgicsh:48"
#define	_MSG_MMX_csh_mail_DEF_MSG	"You have mail"
#define	_MSG_MMX_csh_mail_CAT_NUM_STR_DEF_MSG	"uxsgicsh:48:You have mail"
#define	_MSG_MMX_csh_mail_MSG_NUM_STR_DEF_MSG	":48:You have mail"
#define	_MSG_MMX_csh_mail_FILE_CAT_NUM	uxsgicsh:48
#define	_SGI_DMMX_csh_mail	":48"
#define	_SGI_MMX_csh_mail	"uxsgicsh:48"
#define	_SGI_MMMX_csh_mail	"uxsgicsh:48:You have mail"
#define	_SGI_SMMX_csh_mail	"You have mail"
#define	_MSG_MMX_csh_nmail_MSG_NUM	49
#define	_MSG_MMX_csh_nmail_MSG_NUM_STR	":49"
#define	_MSG_MMX_csh_nmail_CAT_NUM_STR	"uxsgicsh:49"
#define	_MSG_MMX_csh_nmail_DEF_MSG	"You have new mail"
#define	_MSG_MMX_csh_nmail_CAT_NUM_STR_DEF_MSG	"uxsgicsh:49:You have new mail"
#define	_MSG_MMX_csh_nmail_MSG_NUM_STR_DEF_MSG	":49:You have new mail"
#define	_MSG_MMX_csh_nmail_FILE_CAT_NUM	uxsgicsh:49
#define	_SGI_DMMX_csh_nmail	":49"
#define	_SGI_MMX_csh_nmail	"uxsgicsh:49"
#define	_SGI_MMMX_csh_nmail	"uxsgicsh:49:You have new mail"
#define	_SGI_SMMX_csh_nmail	"You have new mail"
#define	_MSG_MMX_csh_mailin_MSG_NUM	50
#define	_MSG_MMX_csh_mailin_MSG_NUM_STR	":50"
#define	_MSG_MMX_csh_mailin_CAT_NUM_STR	"uxsgicsh:50"
#define	_MSG_MMX_csh_mailin_DEF_MSG	"Mail in %t"
#define	_MSG_MMX_csh_mailin_CAT_NUM_STR_DEF_MSG	"uxsgicsh:50:Mail in %t"
#define	_MSG_MMX_csh_mailin_MSG_NUM_STR_DEF_MSG	":50:Mail in %t"
#define	_MSG_MMX_csh_mailin_FILE_CAT_NUM	uxsgicsh:50
#define	_SGI_DMMX_csh_mailin	":50"
#define	_SGI_MMX_csh_mailin	"uxsgicsh:50"
#define	_SGI_MMMX_csh_mailin	"uxsgicsh:50:Mail in %t"
#define	_SGI_SMMX_csh_mailin	"Mail in %t"
#define	_MSG_MMX_csh_nmailin_MSG_NUM	51
#define	_MSG_MMX_csh_nmailin_MSG_NUM_STR	":51"
#define	_MSG_MMX_csh_nmailin_CAT_NUM_STR	"uxsgicsh:51"
#define	_MSG_MMX_csh_nmailin_DEF_MSG	"New mail in %t"
#define	_MSG_MMX_csh_nmailin_CAT_NUM_STR_DEF_MSG	"uxsgicsh:51:New mail in %t"
#define	_MSG_MMX_csh_nmailin_MSG_NUM_STR_DEF_MSG	":51:New mail in %t"
#define	_MSG_MMX_csh_nmailin_FILE_CAT_NUM	uxsgicsh:51
#define	_SGI_DMMX_csh_nmailin	":51"
#define	_SGI_MMX_csh_nmailin	"uxsgicsh:51"
#define	_SGI_MMMX_csh_nmailin	"uxsgicsh:51:New mail in %t"
#define	_SGI_SMMX_csh_nmailin	"New mail in %t"
#define	_MSG_MMX_csh_cantexec_MSG_NUM	52
#define	_MSG_MMX_csh_cantexec_MSG_NUM_STR	":52"
#define	_MSG_MMX_csh_cantexec_CAT_NUM_STR	"uxsgicsh:52"
#define	_MSG_MMX_csh_cantexec_DEF_MSG	"Cannot execute binary file"
#define	_MSG_MMX_csh_cantexec_CAT_NUM_STR_DEF_MSG	"uxsgicsh:52:Cannot execute binary file"
#define	_MSG_MMX_csh_cantexec_MSG_NUM_STR_DEF_MSG	":52:Cannot execute binary file"
#define	_MSG_MMX_csh_cantexec_FILE_CAT_NUM	uxsgicsh:52
#define	_SGI_DMMX_csh_cantexec	":52"
#define	_SGI_MMX_csh_cantexec	"uxsgicsh:52"
#define	_SGI_MMMX_csh_cantexec	"uxsgicsh:52:Cannot execute binary file"
#define	_SGI_SMMX_csh_cantexec	"Cannot execute binary file"
#define	_MSG_MMX_csh_setuid_MSG_NUM	53
#define	_MSG_MMX_csh_setuid_MSG_NUM_STR	":53"
#define	_MSG_MMX_csh_setuid_CAT_NUM_STR	"uxsgicsh:53"
#define	_MSG_MMX_csh_setuid_DEF_MSG	"%s: Setuid program execute permission denied"
#define	_MSG_MMX_csh_setuid_CAT_NUM_STR_DEF_MSG	"uxsgicsh:53:%s: Setuid program execute permission denied"
#define	_MSG_MMX_csh_setuid_MSG_NUM_STR_DEF_MSG	":53:%s: Setuid program execute permission denied"
#define	_MSG_MMX_csh_setuid_FILE_CAT_NUM	uxsgicsh:53
#define	_SGI_DMMX_csh_setuid	":53"
#define	_SGI_MMX_csh_setuid	"uxsgicsh:53"
#define	_SGI_MMMX_csh_setuid	"uxsgicsh:53:%s: Setuid program execute permission denied"
#define	_SGI_SMMX_csh_setuid	"%s: Setuid program execute permission denied"
#define	_MSG_MMX_csh_badcomp_MSG_NUM	54
#define	_MSG_MMX_csh_badcomp_MSG_NUM_STR	":54"
#define	_MSG_MMX_csh_badcomp_CAT_NUM_STR	"uxsgicsh:54"
#define	_MSG_MMX_csh_badcomp_DEF_MSG	"%s: Program not supported by architecture"
#define	_MSG_MMX_csh_badcomp_CAT_NUM_STR_DEF_MSG	"uxsgicsh:54:%s: Program not supported by architecture"
#define	_MSG_MMX_csh_badcomp_MSG_NUM_STR_DEF_MSG	":54:%s: Program not supported by architecture"
#define	_MSG_MMX_csh_badcomp_FILE_CAT_NUM	uxsgicsh:54
#define	_SGI_DMMX_csh_badcomp	":54"
#define	_SGI_MMX_csh_badcomp	"uxsgicsh:54"
#define	_SGI_MMMX_csh_badcomp	"uxsgicsh:54:%s: Program not supported by architecture"
#define	_SGI_SMMX_csh_badcomp	"%s: Program not supported by architecture"
#define	_MSG_MMX_csh_illchar_MSG_NUM	55
#define	_MSG_MMX_csh_illchar_MSG_NUM_STR	":55"
#define	_MSG_MMX_csh_illchar_CAT_NUM_STR	"uxsgicsh:55"
#define	_MSG_MMX_csh_illchar_DEF_MSG	"Illegal character in '%s' !"
#define	_MSG_MMX_csh_illchar_CAT_NUM_STR_DEF_MSG	"uxsgicsh:55:Illegal character in '%s' !"
#define	_MSG_MMX_csh_illchar_MSG_NUM_STR_DEF_MSG	":55:Illegal character in '%s' !"
#define	_MSG_MMX_csh_illchar_FILE_CAT_NUM	uxsgicsh:55
#define	_SGI_DMMX_csh_illchar	":55"
#define	_SGI_MMX_csh_illchar	"uxsgicsh:55"
#define	_SGI_MMMX_csh_illchar	"uxsgicsh:55:Illegal character in '%s' !"
#define	_SGI_SMMX_csh_illchar	"Illegal character in '%s' !"
#define	_MSG_MMX_csh_fntrunc_MSG_NUM	56
#define	_MSG_MMX_csh_fntrunc_MSG_NUM_STR	":56"
#define	_MSG_MMX_csh_fntrunc_CAT_NUM_STR	"uxsgicsh:56"
#define	_MSG_MMX_csh_fntrunc_DEF_MSG	"Filename '%s' truncated !"
#define	_MSG_MMX_csh_fntrunc_CAT_NUM_STR_DEF_MSG	"uxsgicsh:56:Filename '%s' truncated !"
#define	_MSG_MMX_csh_fntrunc_MSG_NUM_STR_DEF_MSG	":56:Filename '%s' truncated !"
#define	_MSG_MMX_csh_fntrunc_FILE_CAT_NUM	uxsgicsh:56
#define	_SGI_DMMX_csh_fntrunc	":56"
#define	_SGI_MMX_csh_fntrunc	"uxsgicsh:56"
#define	_SGI_MMMX_csh_fntrunc	"uxsgicsh:56:Filename '%s' truncated !"
#define	_SGI_SMMX_csh_fntrunc	"Filename '%s' truncated !"
#define	_MSG_MMX_csh_illenvvar_MSG_NUM	57
#define	_MSG_MMX_csh_illenvvar_MSG_NUM_STR	":57"
#define	_MSG_MMX_csh_illenvvar_CAT_NUM_STR	"uxsgicsh:57"
#define	_MSG_MMX_csh_illenvvar_DEF_MSG	"Environment variable '%s' ignored"
#define	_MSG_MMX_csh_illenvvar_CAT_NUM_STR_DEF_MSG	"uxsgicsh:57:Environment variable '%s' ignored"
#define	_MSG_MMX_csh_illenvvar_MSG_NUM_STR_DEF_MSG	":57:Environment variable '%s' ignored"
#define	_MSG_MMX_csh_illenvvar_FILE_CAT_NUM	uxsgicsh:57
#define	_SGI_DMMX_csh_illenvvar	":57"
#define	_SGI_MMX_csh_illenvvar	"uxsgicsh:57"
#define	_SGI_MMMX_csh_illenvvar	"uxsgicsh:57:Environment variable '%s' ignored"
#define	_SGI_SMMX_csh_illenvvar	"Environment variable '%s' ignored"
#define	_MSG_MMX_csh_ihppasswd_MSG_NUM	58
#define	_MSG_MMX_csh_ihppasswd_MSG_NUM_STR	":58"
#define	_MSG_MMX_csh_ihppasswd_CAT_NUM_STR	"uxsgicsh:58"
#define	_MSG_MMX_csh_ihppasswd_DEF_MSG	"Illegal character in home path of passwd entry"
#define	_MSG_MMX_csh_ihppasswd_CAT_NUM_STR_DEF_MSG	"uxsgicsh:58:Illegal character in home path of passwd entry"
#define	_MSG_MMX_csh_ihppasswd_MSG_NUM_STR_DEF_MSG	":58:Illegal character in home path of passwd entry"
#define	_MSG_MMX_csh_ihppasswd_FILE_CAT_NUM	uxsgicsh:58
#define	_SGI_DMMX_csh_ihppasswd	":58"
#define	_SGI_MMX_csh_ihppasswd	"uxsgicsh:58"
#define	_SGI_MMMX_csh_ihppasswd	"uxsgicsh:58:Illegal character in home path of passwd entry"
#define	_SGI_SMMX_csh_ihppasswd	"Illegal character in home path of passwd entry"
#define	_MSG_MMX_csh_unmatched_MSG_NUM	59
#define	_MSG_MMX_csh_unmatched_MSG_NUM_STR	":59"
#define	_MSG_MMX_csh_unmatched_CAT_NUM_STR	"uxsgicsh:59"
#define	_MSG_MMX_csh_unmatched_DEF_MSG	"Unmatched %s"
#define	_MSG_MMX_csh_unmatched_CAT_NUM_STR_DEF_MSG	"uxsgicsh:59:Unmatched %s"
#define	_MSG_MMX_csh_unmatched_MSG_NUM_STR_DEF_MSG	":59:Unmatched %s"
#define	_MSG_MMX_csh_unmatched_FILE_CAT_NUM	uxsgicsh:59
#define	_SGI_DMMX_csh_unmatched	":59"
#define	_SGI_MMX_csh_unmatched	"uxsgicsh:59"
#define	_SGI_MMMX_csh_unmatched	"uxsgicsh:59:Unmatched %s"
#define	_SGI_SMMX_csh_unmatched	"Unmatched %s"
#define	_MSG_MMX_csh_word2long_MSG_NUM	60
#define	_MSG_MMX_csh_word2long_MSG_NUM_STR	":60"
#define	_MSG_MMX_csh_word2long_CAT_NUM_STR	"uxsgicsh:60"
#define	_MSG_MMX_csh_word2long_DEF_MSG	"Word too long"
#define	_MSG_MMX_csh_word2long_CAT_NUM_STR_DEF_MSG	"uxsgicsh:60:Word too long"
#define	_MSG_MMX_csh_word2long_MSG_NUM_STR_DEF_MSG	":60:Word too long"
#define	_MSG_MMX_csh_word2long_FILE_CAT_NUM	uxsgicsh:60
#define	_SGI_DMMX_csh_word2long	":60"
#define	_SGI_MMX_csh_word2long	"uxsgicsh:60"
#define	_SGI_MMMX_csh_word2long	"uxsgicsh:60:Word too long"
#define	_SGI_SMMX_csh_word2long	"Word too long"
#define	_MSG_MMX_csh_line2long_MSG_NUM	61
#define	_MSG_MMX_csh_line2long_MSG_NUM_STR	":61"
#define	_MSG_MMX_csh_line2long_CAT_NUM_STR	"uxsgicsh:61"
#define	_MSG_MMX_csh_line2long_DEF_MSG	"Line too long"
#define	_MSG_MMX_csh_line2long_CAT_NUM_STR_DEF_MSG	"uxsgicsh:61:Line too long"
#define	_MSG_MMX_csh_line2long_MSG_NUM_STR_DEF_MSG	":61:Line too long"
#define	_MSG_MMX_csh_line2long_FILE_CAT_NUM	uxsgicsh:61
#define	_SGI_DMMX_csh_line2long	":61"
#define	_SGI_MMX_csh_line2long	"uxsgicsh:61"
#define	_SGI_MMMX_csh_line2long	"uxsgicsh:61:Line too long"
#define	_SGI_SMMX_csh_line2long	"Line too long"
#define	_MSG_MMX_csh_no0file_MSG_NUM	62
#define	_MSG_MMX_csh_no0file_MSG_NUM_STR	":62"
#define	_MSG_MMX_csh_no0file_CAT_NUM_STR	"uxsgicsh:62"
#define	_MSG_MMX_csh_no0file_DEF_MSG	"No file for $0"
#define	_MSG_MMX_csh_no0file_CAT_NUM_STR_DEF_MSG	"uxsgicsh:62:No file for $0"
#define	_MSG_MMX_csh_no0file_MSG_NUM_STR_DEF_MSG	":62:No file for $0"
#define	_MSG_MMX_csh_no0file_FILE_CAT_NUM	uxsgicsh:62
#define	_SGI_DMMX_csh_no0file	":62"
#define	_SGI_MMX_csh_no0file	"uxsgicsh:62"
#define	_SGI_MMMX_csh_no0file	"uxsgicsh:62:No file for $0"
#define	_SGI_SMMX_csh_no0file	"No file for $0"
#define	_MSG_MMX_csh_varsyntax_MSG_NUM	63
#define	_MSG_MMX_csh_varsyntax_MSG_NUM_STR	":63"
#define	_MSG_MMX_csh_varsyntax_CAT_NUM_STR	"uxsgicsh:63"
#define	_MSG_MMX_csh_varsyntax_DEF_MSG	"Variable syntax"
#define	_MSG_MMX_csh_varsyntax_CAT_NUM_STR_DEF_MSG	"uxsgicsh:63:Variable syntax"
#define	_MSG_MMX_csh_varsyntax_MSG_NUM_STR_DEF_MSG	":63:Variable syntax"
#define	_MSG_MMX_csh_varsyntax_FILE_CAT_NUM	uxsgicsh:63
#define	_SGI_DMMX_csh_varsyntax	":63"
#define	_SGI_MMX_csh_varsyntax	"uxsgicsh:63"
#define	_SGI_MMMX_csh_varsyntax	"uxsgicsh:63:Variable syntax"
#define	_SGI_SMMX_csh_varsyntax	"Variable syntax"
#define	_MSG_MMX_csh_badmodin_MSG_NUM	64
#define	_MSG_MMX_csh_badmodin_MSG_NUM_STR	":64"
#define	_MSG_MMX_csh_badmodin_CAT_NUM_STR	"uxsgicsh:64"
#define	_MSG_MMX_csh_badmodin_DEF_MSG	"Bad : mod in $"
#define	_MSG_MMX_csh_badmodin_CAT_NUM_STR_DEF_MSG	"uxsgicsh:64:Bad : mod in $"
#define	_MSG_MMX_csh_badmodin_MSG_NUM_STR_DEF_MSG	":64:Bad : mod in $"
#define	_MSG_MMX_csh_badmodin_FILE_CAT_NUM	uxsgicsh:64
#define	_SGI_DMMX_csh_badmodin	":64"
#define	_SGI_MMX_csh_badmodin	"uxsgicsh:64"
#define	_SGI_MMMX_csh_badmodin	"uxsgicsh:64:Bad : mod in $"
#define	_SGI_SMMX_csh_badmodin	"Bad : mod in $"
#define	_MSG_MMX_csh_divby0_MSG_NUM	65
#define	_MSG_MMX_csh_divby0_MSG_NUM_STR	":65"
#define	_MSG_MMX_csh_divby0_CAT_NUM_STR	"uxsgicsh:65"
#define	_MSG_MMX_csh_divby0_DEF_MSG	"Divide by 0"
#define	_MSG_MMX_csh_divby0_CAT_NUM_STR_DEF_MSG	"uxsgicsh:65:Divide by 0"
#define	_MSG_MMX_csh_divby0_MSG_NUM_STR_DEF_MSG	":65:Divide by 0"
#define	_MSG_MMX_csh_divby0_FILE_CAT_NUM	uxsgicsh:65
#define	_SGI_DMMX_csh_divby0	":65"
#define	_SGI_MMX_csh_divby0	"uxsgicsh:65"
#define	_SGI_MMMX_csh_divby0	"uxsgicsh:65:Divide by 0"
#define	_SGI_SMMX_csh_divby0	"Divide by 0"
#define	_MSG_MMX_csh_modby0_MSG_NUM	66
#define	_MSG_MMX_csh_modby0_MSG_NUM_STR	":66"
#define	_MSG_MMX_csh_modby0_CAT_NUM_STR	"uxsgicsh:66"
#define	_MSG_MMX_csh_modby0_DEF_MSG	"Mod by 0"
#define	_MSG_MMX_csh_modby0_CAT_NUM_STR_DEF_MSG	"uxsgicsh:66:Mod by 0"
#define	_MSG_MMX_csh_modby0_MSG_NUM_STR_DEF_MSG	":66:Mod by 0"
#define	_MSG_MMX_csh_modby0_FILE_CAT_NUM	uxsgicsh:66
#define	_SGI_DMMX_csh_modby0	":66"
#define	_SGI_MMX_csh_modby0	"uxsgicsh:66"
#define	_SGI_MMMX_csh_modby0	"uxsgicsh:66:Mod by 0"
#define	_SGI_SMMX_csh_modby0	"Mod by 0"
#define	_MSG_MMX_csh_badscal_MSG_NUM	67
#define	_MSG_MMX_csh_badscal_MSG_NUM_STR	":67"
#define	_MSG_MMX_csh_badscal_CAT_NUM_STR	"uxsgicsh:67"
#define	_MSG_MMX_csh_badscal_DEF_MSG	"Bad scaling; did you mean ``%st''?"
#define	_MSG_MMX_csh_badscal_CAT_NUM_STR_DEF_MSG	"uxsgicsh:67:Bad scaling; did you mean ``%st''?"
#define	_MSG_MMX_csh_badscal_MSG_NUM_STR_DEF_MSG	":67:Bad scaling; did you mean ``%st''?"
#define	_MSG_MMX_csh_badscal_FILE_CAT_NUM	uxsgicsh:67
#define	_SGI_DMMX_csh_badscal	":67"
#define	_SGI_MMX_csh_badscal	"uxsgicsh:67"
#define	_SGI_MMMX_csh_badscal	"uxsgicsh:67:Bad scaling; did you mean ``%st''?"
#define	_SGI_SMMX_csh_badscal	"Bad scaling; did you mean ``%st''?"
#define	_MSG_MMX_csh_cantsusp_MSG_NUM	68
#define	_MSG_MMX_csh_cantsusp_MSG_NUM_STR	":68"
#define	_MSG_MMX_csh_cantsusp_CAT_NUM_STR	"uxsgicsh:68"
#define	_MSG_MMX_csh_cantsusp_DEF_MSG	"Can't suspend a login shell (yet)"
#define	_MSG_MMX_csh_cantsusp_CAT_NUM_STR_DEF_MSG	"uxsgicsh:68:Can't suspend a login shell (yet)"
#define	_MSG_MMX_csh_cantsusp_MSG_NUM_STR_DEF_MSG	":68:Can't suspend a login shell (yet)"
#define	_MSG_MMX_csh_cantsusp_FILE_CAT_NUM	uxsgicsh:68
#define	_SGI_DMMX_csh_cantsusp	":68"
#define	_SGI_MMX_csh_cantsusp	"uxsgicsh:68"
#define	_SGI_MMMX_csh_cantsusp	"uxsgicsh:68:Can't suspend a login shell (yet)"
#define	_SGI_SMMX_csh_cantsusp	"Can't suspend a login shell (yet)"
#define	_MSG_MMX_csh_unkuser_MSG_NUM	69
#define	_MSG_MMX_csh_unkuser_MSG_NUM_STR	":69"
#define	_MSG_MMX_csh_unkuser_CAT_NUM_STR	"uxsgicsh:69"
#define	_MSG_MMX_csh_unkuser_DEF_MSG	"%s: Unknown user"
#define	_MSG_MMX_csh_unkuser_CAT_NUM_STR_DEF_MSG	"uxsgicsh:69:%s: Unknown user"
#define	_MSG_MMX_csh_unkuser_MSG_NUM_STR_DEF_MSG	":69:%s: Unknown user"
#define	_MSG_MMX_csh_unkuser_FILE_CAT_NUM	uxsgicsh:69
#define	_SGI_DMMX_csh_unkuser	":69"
#define	_SGI_MMX_csh_unkuser	"uxsgicsh:69"
#define	_SGI_MMMX_csh_unkuser	"uxsgicsh:69:%s: Unknown user"
#define	_SGI_SMMX_csh_unkuser	"%s: Unknown user"
#define	_MSG_MMX_csh_toomleft_MSG_NUM	70
#define	_MSG_MMX_csh_toomleft_MSG_NUM_STR	":70"
#define	_MSG_MMX_csh_toomleft_CAT_NUM_STR	"uxsgicsh:70"
#define	_MSG_MMX_csh_toomleft_DEF_MSG	"Too many words from ``"
#define	_MSG_MMX_csh_toomleft_CAT_NUM_STR_DEF_MSG	"uxsgicsh:70:Too many words from ``"
#define	_MSG_MMX_csh_toomleft_MSG_NUM_STR_DEF_MSG	":70:Too many words from ``"
#define	_MSG_MMX_csh_toomleft_FILE_CAT_NUM	uxsgicsh:70
#define	_SGI_DMMX_csh_toomleft	":70"
#define	_SGI_MMX_csh_toomleft	"uxsgicsh:70"
#define	_SGI_MMMX_csh_toomleft	"uxsgicsh:70:Too many words from ``"
#define	_SGI_SMMX_csh_toomleft	"Too many words from ``"
#define	_MSG_MMX_csh_arg2long_MSG_NUM	71
#define	_MSG_MMX_csh_arg2long_MSG_NUM_STR	":71"
#define	_MSG_MMX_csh_arg2long_CAT_NUM_STR	"uxsgicsh:71"
#define	_MSG_MMX_csh_arg2long_DEF_MSG	"Arguments too long"
#define	_MSG_MMX_csh_arg2long_CAT_NUM_STR_DEF_MSG	"uxsgicsh:71:Arguments too long"
#define	_MSG_MMX_csh_arg2long_MSG_NUM_STR_DEF_MSG	":71:Arguments too long"
#define	_MSG_MMX_csh_arg2long_FILE_CAT_NUM	uxsgicsh:71
#define	_SGI_DMMX_csh_arg2long	":71"
#define	_SGI_MMX_csh_arg2long	"uxsgicsh:71"
#define	_SGI_MMMX_csh_arg2long	"uxsgicsh:71:Arguments too long"
#define	_SGI_SMMX_csh_arg2long	"Arguments too long"
#define	_MSG_MMX_csh_path2long_MSG_NUM	72
#define	_MSG_MMX_csh_path2long_MSG_NUM_STR	":72"
#define	_MSG_MMX_csh_path2long_CAT_NUM_STR	"uxsgicsh:72"
#define	_MSG_MMX_csh_path2long_DEF_MSG	"Pathname too long"
#define	_MSG_MMX_csh_path2long_CAT_NUM_STR_DEF_MSG	"uxsgicsh:72:Pathname too long"
#define	_MSG_MMX_csh_path2long_MSG_NUM_STR_DEF_MSG	":72:Pathname too long"
#define	_MSG_MMX_csh_path2long_FILE_CAT_NUM	uxsgicsh:72
#define	_SGI_DMMX_csh_path2long	":72"
#define	_SGI_MMX_csh_path2long	"uxsgicsh:72"
#define	_SGI_MMMX_csh_path2long	"uxsgicsh:72:Pathname too long"
#define	_SGI_SMMX_csh_path2long	"Pathname too long"
#define	_MSG_MMX_csh_alloop_MSG_NUM	73
#define	_MSG_MMX_csh_alloop_MSG_NUM_STR	":73"
#define	_MSG_MMX_csh_alloop_CAT_NUM_STR	"uxsgicsh:73"
#define	_MSG_MMX_csh_alloop_DEF_MSG	"Alias loop"
#define	_MSG_MMX_csh_alloop_CAT_NUM_STR_DEF_MSG	"uxsgicsh:73:Alias loop"
#define	_MSG_MMX_csh_alloop_MSG_NUM_STR_DEF_MSG	":73:Alias loop"
#define	_MSG_MMX_csh_alloop_FILE_CAT_NUM	uxsgicsh:73
#define	_SGI_DMMX_csh_alloop	":73"
#define	_SGI_MMX_csh_alloop	"uxsgicsh:73"
#define	_SGI_MMMX_csh_alloop	"uxsgicsh:73:Alias loop"
#define	_SGI_SMMX_csh_alloop	"Alias loop"
#define	_MSG_MMX_csh_toomany_MSG_NUM	74
#define	_MSG_MMX_csh_toomany_MSG_NUM_STR	":74"
#define	_MSG_MMX_csh_toomany_CAT_NUM_STR	"uxsgicsh:74"
#define	_MSG_MMX_csh_toomany_DEF_MSG	"Too many %s's"
#define	_MSG_MMX_csh_toomany_CAT_NUM_STR_DEF_MSG	"uxsgicsh:74:Too many %s's"
#define	_MSG_MMX_csh_toomany_MSG_NUM_STR_DEF_MSG	":74:Too many %s's"
#define	_MSG_MMX_csh_toomany_FILE_CAT_NUM	uxsgicsh:74
#define	_SGI_DMMX_csh_toomany	":74"
#define	_SGI_MMX_csh_toomany	"uxsgicsh:74"
#define	_SGI_MMMX_csh_toomany	"uxsgicsh:74:Too many %s's"
#define	_SGI_SMMX_csh_toomany	"Too many %s's"
#define	_MSG_MMX_csh_usage_MSG_NUM	75
#define	_MSG_MMX_csh_usage_MSG_NUM_STR	":75"
#define	_MSG_MMX_csh_usage_CAT_NUM_STR	"uxsgicsh:75"
#define	_MSG_MMX_csh_usage_DEF_MSG	"Usage: %s"
#define	_MSG_MMX_csh_usage_CAT_NUM_STR_DEF_MSG	"uxsgicsh:75:Usage: %s"
#define	_MSG_MMX_csh_usage_MSG_NUM_STR_DEF_MSG	":75:Usage: %s"
#define	_MSG_MMX_csh_usage_FILE_CAT_NUM	uxsgicsh:75
#define	_SGI_DMMX_csh_usage	":75"
#define	_SGI_MMX_csh_usage	"uxsgicsh:75"
#define	_SGI_MMMX_csh_usage	"uxsgicsh:75:Usage: %s"
#define	_SGI_SMMX_csh_usage	"Usage: %s"
#define	_MSG_MMX_csh_fkfail_MSG_NUM	76
#define	_MSG_MMX_csh_fkfail_MSG_NUM_STR	":76"
#define	_MSG_MMX_csh_fkfail_CAT_NUM_STR	"uxsgicsh:76"
#define	_MSG_MMX_csh_fkfail_DEF_MSG	"Fork failed"
#define	_MSG_MMX_csh_fkfail_CAT_NUM_STR_DEF_MSG	"uxsgicsh:76:Fork failed"
#define	_MSG_MMX_csh_fkfail_MSG_NUM_STR_DEF_MSG	":76:Fork failed"
#define	_MSG_MMX_csh_fkfail_FILE_CAT_NUM	uxsgicsh:76
#define	_SGI_DMMX_csh_fkfail	":76"
#define	_SGI_MMX_csh_fkfail	"uxsgicsh:76"
#define	_SGI_MMMX_csh_fkfail	"uxsgicsh:76:Fork failed"
#define	_SGI_SMMX_csh_fkfail	"Fork failed"
#define	_MSG_MMX_csh_nojc1_MSG_NUM	77
#define	_MSG_MMX_csh_nojc1_MSG_NUM_STR	":77"
#define	_MSG_MMX_csh_nojc1_CAT_NUM_STR	"uxsgicsh:77"
#define	_MSG_MMX_csh_nojc1_DEF_MSG	"No job control in this shell"
#define	_MSG_MMX_csh_nojc1_CAT_NUM_STR_DEF_MSG	"uxsgicsh:77:No job control in this shell"
#define	_MSG_MMX_csh_nojc1_MSG_NUM_STR_DEF_MSG	":77:No job control in this shell"
#define	_MSG_MMX_csh_nojc1_FILE_CAT_NUM	uxsgicsh:77
#define	_SGI_DMMX_csh_nojc1	":77"
#define	_SGI_MMX_csh_nojc1	"uxsgicsh:77"
#define	_SGI_MMMX_csh_nojc1	"uxsgicsh:77:No job control in this shell"
#define	_SGI_SMMX_csh_nojc1	"No job control in this shell"
#define	_MSG_MMX_csh_nojc2_MSG_NUM	78
#define	_MSG_MMX_csh_nojc2_MSG_NUM_STR	":78"
#define	_MSG_MMX_csh_nojc2_CAT_NUM_STR	"uxsgicsh:78"
#define	_MSG_MMX_csh_nojc2_DEF_MSG	"No job control in subshell"
#define	_MSG_MMX_csh_nojc2_CAT_NUM_STR_DEF_MSG	"uxsgicsh:78:No job control in subshell"
#define	_MSG_MMX_csh_nojc2_MSG_NUM_STR_DEF_MSG	":78:No job control in subshell"
#define	_MSG_MMX_csh_nojc2_FILE_CAT_NUM	uxsgicsh:78
#define	_SGI_DMMX_csh_nojc2	":78"
#define	_SGI_MMX_csh_nojc2	"uxsgicsh:78"
#define	_SGI_MMMX_csh_nojc2	"uxsgicsh:78:No job control in subshell"
#define	_SGI_SMMX_csh_nojc2	"No job control in subshell"
#define	_MSG_MMX_csh_stjobs_MSG_NUM	79
#define	_MSG_MMX_csh_stjobs_MSG_NUM_STR	":79"
#define	_MSG_MMX_csh_stjobs_CAT_NUM_STR	"uxsgicsh:79"
#define	_MSG_MMX_csh_stjobs_DEF_MSG	"\nThere are stopped jobs"
#define	_MSG_MMX_csh_stjobs_CAT_NUM_STR_DEF_MSG	"uxsgicsh:79:\nThere are stopped jobs"
#define	_MSG_MMX_csh_stjobs_MSG_NUM_STR_DEF_MSG	":79:\nThere are stopped jobs"
#define	_MSG_MMX_csh_stjobs_FILE_CAT_NUM	uxsgicsh:79
#define	_SGI_DMMX_csh_stjobs	":79"
#define	_SGI_MMX_csh_stjobs	"uxsgicsh:79"
#define	_SGI_MMMX_csh_stjobs	"uxsgicsh:79:\nThere are stopped jobs"
#define	_SGI_SMMX_csh_stjobs	"\nThere are stopped jobs"
#define	_MSG_MMX_csh_nopipe_MSG_NUM	80
#define	_MSG_MMX_csh_nopipe_MSG_NUM_STR	":80"
#define	_MSG_MMX_csh_nopipe_CAT_NUM_STR	"uxsgicsh:80"
#define	_MSG_MMX_csh_nopipe_DEF_MSG	"Can't make pipe"
#define	_MSG_MMX_csh_nopipe_CAT_NUM_STR_DEF_MSG	"uxsgicsh:80:Can't make pipe"
#define	_MSG_MMX_csh_nopipe_MSG_NUM_STR_DEF_MSG	":80:Can't make pipe"
#define	_MSG_MMX_csh_nopipe_FILE_CAT_NUM	uxsgicsh:80
#define	_SGI_DMMX_csh_nopipe	":80"
#define	_SGI_MMX_csh_nopipe	"uxsgicsh:80"
#define	_SGI_MMMX_csh_nopipe	"uxsgicsh:80:Can't make pipe"
#define	_SGI_SMMX_csh_nopipe	"Can't make pipe"
#define	_MSG_MMX_csh_fexists_MSG_NUM	81
#define	_MSG_MMX_csh_fexists_MSG_NUM_STR	":81"
#define	_MSG_MMX_csh_fexists_CAT_NUM_STR	"uxsgicsh:81"
#define	_MSG_MMX_csh_fexists_DEF_MSG	"%s: File exists"
#define	_MSG_MMX_csh_fexists_CAT_NUM_STR_DEF_MSG	"uxsgicsh:81:%s: File exists"
#define	_MSG_MMX_csh_fexists_MSG_NUM_STR_DEF_MSG	":81:%s: File exists"
#define	_MSG_MMX_csh_fexists_FILE_CAT_NUM	uxsgicsh:81
#define	_SGI_DMMX_csh_fexists	":81"
#define	_SGI_MMX_csh_fexists	"uxsgicsh:81"
#define	_SGI_MMMX_csh_fexists	"uxsgicsh:81:%s: File exists"
#define	_SGI_SMMX_csh_fexists	"%s: File exists"
#define	_MSG_MMX_csh_expfull_MSG_NUM	82
#define	_MSG_MMX_csh_expfull_MSG_NUM_STR	":82"
#define	_MSG_MMX_csh_expfull_CAT_NUM_STR	"uxsgicsh:82"
#define	_MSG_MMX_csh_expfull_DEF_MSG	"Expansion buffer overflow"
#define	_MSG_MMX_csh_expfull_CAT_NUM_STR_DEF_MSG	"uxsgicsh:82:Expansion buffer overflow"
#define	_MSG_MMX_csh_expfull_MSG_NUM_STR_DEF_MSG	":82:Expansion buffer overflow"
#define	_MSG_MMX_csh_expfull_FILE_CAT_NUM	uxsgicsh:82
#define	_SGI_DMMX_csh_expfull	":82"
#define	_SGI_MMX_csh_expfull	"uxsgicsh:82"
#define	_SGI_MMMX_csh_expfull	"uxsgicsh:82:Expansion buffer overflow"
#define	_SGI_SMMX_csh_expfull	"Expansion buffer overflow"
#define	_MSG_MMX_csh_badbang_MSG_NUM	83
#define	_MSG_MMX_csh_badbang_MSG_NUM_STR	":83"
#define	_MSG_MMX_csh_badbang_CAT_NUM_STR	"uxsgicsh:83"
#define	_MSG_MMX_csh_badbang_DEF_MSG	"Bad ! form"
#define	_MSG_MMX_csh_badbang_CAT_NUM_STR_DEF_MSG	"uxsgicsh:83:Bad ! form"
#define	_MSG_MMX_csh_badbang_MSG_NUM_STR_DEF_MSG	":83:Bad ! form"
#define	_MSG_MMX_csh_badbang_FILE_CAT_NUM	uxsgicsh:83
#define	_SGI_DMMX_csh_badbang	":83"
#define	_SGI_MMX_csh_badbang	"uxsgicsh:83"
#define	_SGI_MMMX_csh_badbang	"uxsgicsh:83:Bad ! form"
#define	_SGI_SMMX_csh_badbang	"Bad ! form"
#define	_MSG_MMX_csh_noprevs_MSG_NUM	84
#define	_MSG_MMX_csh_noprevs_MSG_NUM_STR	":84"
#define	_MSG_MMX_csh_noprevs_CAT_NUM_STR	"uxsgicsh:84"
#define	_MSG_MMX_csh_noprevs_DEF_MSG	"No prev sub"
#define	_MSG_MMX_csh_noprevs_CAT_NUM_STR_DEF_MSG	"uxsgicsh:84:No prev sub"
#define	_MSG_MMX_csh_noprevs_MSG_NUM_STR_DEF_MSG	":84:No prev sub"
#define	_MSG_MMX_csh_noprevs_FILE_CAT_NUM	uxsgicsh:84
#define	_SGI_DMMX_csh_noprevs	":84"
#define	_SGI_MMX_csh_noprevs	"uxsgicsh:84"
#define	_SGI_MMMX_csh_noprevs	"uxsgicsh:84:No prev sub"
#define	_SGI_SMMX_csh_noprevs	"No prev sub"
#define	_MSG_MMX_csh_badsub_MSG_NUM	85
#define	_MSG_MMX_csh_badsub_MSG_NUM_STR	":85"
#define	_MSG_MMX_csh_badsub_CAT_NUM_STR	"uxsgicsh:85"
#define	_MSG_MMX_csh_badsub_DEF_MSG	"Bad substitute"
#define	_MSG_MMX_csh_badsub_CAT_NUM_STR_DEF_MSG	"uxsgicsh:85:Bad substitute"
#define	_MSG_MMX_csh_badsub_MSG_NUM_STR_DEF_MSG	":85:Bad substitute"
#define	_MSG_MMX_csh_badsub_FILE_CAT_NUM	uxsgicsh:85
#define	_SGI_DMMX_csh_badsub	":85"
#define	_SGI_MMX_csh_badsub	"uxsgicsh:85"
#define	_SGI_MMMX_csh_badsub	"uxsgicsh:85:Bad substitute"
#define	_SGI_SMMX_csh_badsub	"Bad substitute"
#define	_MSG_MMX_csh_noplhs_MSG_NUM	86
#define	_MSG_MMX_csh_noplhs_MSG_NUM_STR	":86"
#define	_MSG_MMX_csh_noplhs_CAT_NUM_STR	"uxsgicsh:86"
#define	_MSG_MMX_csh_noplhs_DEF_MSG	"No prev lhs"
#define	_MSG_MMX_csh_noplhs_CAT_NUM_STR_DEF_MSG	"uxsgicsh:86:No prev lhs"
#define	_MSG_MMX_csh_noplhs_MSG_NUM_STR_DEF_MSG	":86:No prev lhs"
#define	_MSG_MMX_csh_noplhs_FILE_CAT_NUM	uxsgicsh:86
#define	_SGI_DMMX_csh_noplhs	":86"
#define	_SGI_MMX_csh_noplhs	"uxsgicsh:86"
#define	_SGI_MMMX_csh_noplhs	"uxsgicsh:86:No prev lhs"
#define	_SGI_SMMX_csh_noplhs	"No prev lhs"
#define	_MSG_MMX_csh_rhs2long_MSG_NUM	87
#define	_MSG_MMX_csh_rhs2long_MSG_NUM_STR	":87"
#define	_MSG_MMX_csh_rhs2long_CAT_NUM_STR	"uxsgicsh:87"
#define	_MSG_MMX_csh_rhs2long_DEF_MSG	"Rhs too long"
#define	_MSG_MMX_csh_rhs2long_CAT_NUM_STR_DEF_MSG	"uxsgicsh:87:Rhs too long"
#define	_MSG_MMX_csh_rhs2long_MSG_NUM_STR_DEF_MSG	":87:Rhs too long"
#define	_MSG_MMX_csh_rhs2long_FILE_CAT_NUM	uxsgicsh:87
#define	_SGI_DMMX_csh_rhs2long	":87"
#define	_SGI_MMX_csh_rhs2long	"uxsgicsh:87"
#define	_SGI_MMMX_csh_rhs2long	"uxsgicsh:87:Rhs too long"
#define	_SGI_SMMX_csh_rhs2long	"Rhs too long"
#define	_MSG_MMX_csh_modfailed_MSG_NUM	88
#define	_MSG_MMX_csh_modfailed_MSG_NUM_STR	":88"
#define	_MSG_MMX_csh_modfailed_CAT_NUM_STR	"uxsgicsh:88"
#define	_MSG_MMX_csh_modfailed_DEF_MSG	"Modifier failed"
#define	_MSG_MMX_csh_modfailed_CAT_NUM_STR_DEF_MSG	"uxsgicsh:88:Modifier failed"
#define	_MSG_MMX_csh_modfailed_MSG_NUM_STR_DEF_MSG	":88:Modifier failed"
#define	_MSG_MMX_csh_modfailed_FILE_CAT_NUM	uxsgicsh:88
#define	_SGI_DMMX_csh_modfailed	":88"
#define	_SGI_MMX_csh_modfailed	"uxsgicsh:88"
#define	_SGI_MMMX_csh_modfailed	"uxsgicsh:88:Modifier failed"
#define	_SGI_SMMX_csh_modfailed	"Modifier failed"
#define	_MSG_MMX_csh_sbufov_MSG_NUM	89
#define	_MSG_MMX_csh_sbufov_MSG_NUM_STR	":89"
#define	_MSG_MMX_csh_sbufov_CAT_NUM_STR	"uxsgicsh:89"
#define	_MSG_MMX_csh_sbufov_DEF_MSG	"Substitution buffer overflow"
#define	_MSG_MMX_csh_sbufov_CAT_NUM_STR_DEF_MSG	"uxsgicsh:89:Substitution buffer overflow"
#define	_MSG_MMX_csh_sbufov_MSG_NUM_STR_DEF_MSG	":89:Substitution buffer overflow"
#define	_MSG_MMX_csh_sbufov_FILE_CAT_NUM	uxsgicsh:89
#define	_SGI_DMMX_csh_sbufov	":89"
#define	_SGI_MMX_csh_sbufov	"uxsgicsh:89"
#define	_SGI_MMMX_csh_sbufov	"uxsgicsh:89:Substitution buffer overflow"
#define	_SGI_SMMX_csh_sbufov	"Substitution buffer overflow"
#define	_MSG_MMX_csh_badbangsel_MSG_NUM	90
#define	_MSG_MMX_csh_badbangsel_MSG_NUM_STR	":90"
#define	_MSG_MMX_csh_badbangsel_CAT_NUM_STR	"uxsgicsh:90"
#define	_MSG_MMX_csh_badbangsel_DEF_MSG	"Bad ! arg selector"
#define	_MSG_MMX_csh_badbangsel_CAT_NUM_STR_DEF_MSG	"uxsgicsh:90:Bad ! arg selector"
#define	_MSG_MMX_csh_badbangsel_MSG_NUM_STR_DEF_MSG	":90:Bad ! arg selector"
#define	_MSG_MMX_csh_badbangsel_FILE_CAT_NUM	uxsgicsh:90
#define	_SGI_DMMX_csh_badbangsel	":90"
#define	_SGI_MMX_csh_badbangsel	"uxsgicsh:90"
#define	_SGI_MMMX_csh_badbangsel	"uxsgicsh:90:Bad ! arg selector"
#define	_SGI_SMMX_csh_badbangsel	"Bad ! arg selector"
#define	_MSG_MMX_csh_nopsrch_MSG_NUM	91
#define	_MSG_MMX_csh_nopsrch_MSG_NUM_STR	":91"
#define	_MSG_MMX_csh_nopsrch_CAT_NUM_STR	"uxsgicsh:91"
#define	_MSG_MMX_csh_nopsrch_DEF_MSG	"No prev search"
#define	_MSG_MMX_csh_nopsrch_CAT_NUM_STR_DEF_MSG	"uxsgicsh:91:No prev search"
#define	_MSG_MMX_csh_nopsrch_MSG_NUM_STR_DEF_MSG	":91:No prev search"
#define	_MSG_MMX_csh_nopsrch_FILE_CAT_NUM	uxsgicsh:91
#define	_SGI_DMMX_csh_nopsrch	":91"
#define	_SGI_MMX_csh_nopsrch	"uxsgicsh:91"
#define	_SGI_MMMX_csh_nopsrch	"uxsgicsh:91:No prev search"
#define	_SGI_SMMX_csh_nopsrch	"No prev search"
#define	_MSG_MMX_csh_evtnotfnd_MSG_NUM	92
#define	_MSG_MMX_csh_evtnotfnd_MSG_NUM_STR	":92"
#define	_MSG_MMX_csh_evtnotfnd_CAT_NUM_STR	"uxsgicsh:92"
#define	_MSG_MMX_csh_evtnotfnd_DEF_MSG	": Event not found"
#define	_MSG_MMX_csh_evtnotfnd_CAT_NUM_STR_DEF_MSG	"uxsgicsh:92:: Event not found"
#define	_MSG_MMX_csh_evtnotfnd_MSG_NUM_STR_DEF_MSG	":92:: Event not found"
#define	_MSG_MMX_csh_evtnotfnd_FILE_CAT_NUM	uxsgicsh:92
#define	_SGI_DMMX_csh_evtnotfnd	":92"
#define	_SGI_MMX_csh_evtnotfnd	"uxsgicsh:92"
#define	_SGI_MMMX_csh_evtnotfnd	"uxsgicsh:92:: Event not found"
#define	_SGI_SMMX_csh_evtnotfnd	": Event not found"
#define	_MSG_MMX_csh_illlocale_MSG_NUM	93
#define	_MSG_MMX_csh_illlocale_MSG_NUM_STR	":93"
#define	_MSG_MMX_csh_illlocale_CAT_NUM_STR	"uxsgicsh:93"
#define	_MSG_MMX_csh_illlocale_DEF_MSG	"%s: Invalid locale - csh locale unchanged"
#define	_MSG_MMX_csh_illlocale_CAT_NUM_STR_DEF_MSG	"uxsgicsh:93:%s: Invalid locale - csh locale unchanged"
#define	_MSG_MMX_csh_illlocale_MSG_NUM_STR_DEF_MSG	":93:%s: Invalid locale - csh locale unchanged"
#define	_MSG_MMX_csh_illlocale_FILE_CAT_NUM	uxsgicsh:93
#define	_SGI_DMMX_csh_illlocale	":93"
#define	_SGI_MMX_csh_illlocale	"uxsgicsh:93"
#define	_SGI_MMMX_csh_illlocale	"uxsgicsh:93:%s: Invalid locale - csh locale unchanged"
#define	_SGI_SMMX_csh_illlocale	"%s: Invalid locale - csh locale unchanged"
#define	_MSG_MMX_csh_notlogin_MSG_NUM	94
#define	_MSG_MMX_csh_notlogin_MSG_NUM_STR	":94"
#define	_MSG_MMX_csh_notlogin_CAT_NUM_STR	"uxsgicsh:94"
#define	_MSG_MMX_csh_notlogin_DEF_MSG	"Not login shell"
#define	_MSG_MMX_csh_notlogin_CAT_NUM_STR_DEF_MSG	"uxsgicsh:94:Not login shell"
#define	_MSG_MMX_csh_notlogin_MSG_NUM_STR_DEF_MSG	":94:Not login shell"
#define	_MSG_MMX_csh_notlogin_FILE_CAT_NUM	uxsgicsh:94
#define	_SGI_DMMX_csh_notlogin	":94"
#define	_SGI_MMX_csh_notlogin	"uxsgicsh:94"
#define	_SGI_MMMX_csh_notlogin	"uxsgicsh:94:Not login shell"
#define	_SGI_SMMX_csh_notlogin	"Not login shell"
#define	_MSG_MMX_csh_badflag_MSG_NUM	95
#define	_MSG_MMX_csh_badflag_MSG_NUM_STR	":95"
#define	_MSG_MMX_csh_badflag_CAT_NUM_STR	"uxsgicsh:95"
#define	_MSG_MMX_csh_badflag_DEF_MSG	"Unknown flag: -%s\n"
#define	_MSG_MMX_csh_badflag_CAT_NUM_STR_DEF_MSG	"uxsgicsh:95:Unknown flag: -%s\n"
#define	_MSG_MMX_csh_badflag_MSG_NUM_STR_DEF_MSG	":95:Unknown flag: -%s\n"
#define	_MSG_MMX_csh_badflag_FILE_CAT_NUM	uxsgicsh:95
#define	_SGI_DMMX_csh_badflag	":95"
#define	_SGI_MMX_csh_badflag	"uxsgicsh:95"
#define	_SGI_MMMX_csh_badflag	"uxsgicsh:95:Unknown flag: -%s\n"
#define	_SGI_SMMX_csh_badflag	"Unknown flag: -%s\n"
#define	_MSG_MMX_csh_nomem_MSG_NUM	96
#define	_MSG_MMX_csh_nomem_MSG_NUM_STR	":96"
#define	_MSG_MMX_csh_nomem_CAT_NUM_STR	"uxsgicsh:96"
#define	_MSG_MMX_csh_nomem_DEF_MSG	"No memory"
#define	_MSG_MMX_csh_nomem_CAT_NUM_STR_DEF_MSG	"uxsgicsh:96:No memory"
#define	_MSG_MMX_csh_nomem_MSG_NUM_STR_DEF_MSG	":96:No memory"
#define	_MSG_MMX_csh_nomem_FILE_CAT_NUM	uxsgicsh:96
#define	_SGI_DMMX_csh_nomem	":96"
#define	_SGI_MMX_csh_nomem	"uxsgicsh:96"
#define	_SGI_MMMX_csh_nomem	"uxsgicsh:96:No memory"
#define	_SGI_SMMX_csh_nomem	"No memory"
#define	_MSG_MMX_csh_badpllb_MSG_NUM	97
#define	_MSG_MMX_csh_badpllb_MSG_NUM_STR	":97"
#define	_MSG_MMX_csh_badpllb_CAT_NUM_STR	"uxsgicsh:97"
#define	_MSG_MMX_csh_badpllb_DEF_MSG	"Badly placed ("
#define	_MSG_MMX_csh_badpllb_CAT_NUM_STR_DEF_MSG	"uxsgicsh:97:Badly placed ("
#define	_MSG_MMX_csh_badpllb_MSG_NUM_STR_DEF_MSG	":97:Badly placed ("
#define	_MSG_MMX_csh_badpllb_FILE_CAT_NUM	uxsgicsh:97
#define	_SGI_DMMX_csh_badpllb	":97"
#define	_SGI_MMX_csh_badpllb	"uxsgicsh:97"
#define	_SGI_MMMX_csh_badpllb	"uxsgicsh:97:Badly placed ("
#define	_SGI_SMMX_csh_badpllb	"Badly placed ("
#define	_MSG_MMX_csh_missnamred_MSG_NUM	98
#define	_MSG_MMX_csh_missnamred_MSG_NUM_STR	":98"
#define	_MSG_MMX_csh_missnamred_CAT_NUM_STR	"uxsgicsh:98"
#define	_MSG_MMX_csh_missnamred_DEF_MSG	"Missing name for redirect"
#define	_MSG_MMX_csh_missnamred_CAT_NUM_STR_DEF_MSG	"uxsgicsh:98:Missing name for redirect"
#define	_MSG_MMX_csh_missnamred_MSG_NUM_STR_DEF_MSG	":98:Missing name for redirect"
#define	_MSG_MMX_csh_missnamred_FILE_CAT_NUM	uxsgicsh:98
#define	_SGI_DMMX_csh_missnamred	":98"
#define	_SGI_MMX_csh_missnamred	"uxsgicsh:98"
#define	_SGI_MMMX_csh_missnamred	"uxsgicsh:98:Missing name for redirect"
#define	_SGI_SMMX_csh_missnamred	"Missing name for redirect"
#define	_MSG_MMX_csh_ambored_MSG_NUM	99
#define	_MSG_MMX_csh_ambored_MSG_NUM_STR	":99"
#define	_MSG_MMX_csh_ambored_CAT_NUM_STR	"uxsgicsh:99"
#define	_MSG_MMX_csh_ambored_DEF_MSG	"Ambiguous output redirect"
#define	_MSG_MMX_csh_ambored_CAT_NUM_STR_DEF_MSG	"uxsgicsh:99:Ambiguous output redirect"
#define	_MSG_MMX_csh_ambored_MSG_NUM_STR_DEF_MSG	":99:Ambiguous output redirect"
#define	_MSG_MMX_csh_ambored_FILE_CAT_NUM	uxsgicsh:99
#define	_SGI_DMMX_csh_ambored	":99"
#define	_SGI_MMX_csh_ambored	"uxsgicsh:99"
#define	_SGI_MMMX_csh_ambored	"uxsgicsh:99:Ambiguous output redirect"
#define	_SGI_SMMX_csh_ambored	"Ambiguous output redirect"
#define	_MSG_MMX_csh_ambired_MSG_NUM	100
#define	_MSG_MMX_csh_ambired_MSG_NUM_STR	":100"
#define	_MSG_MMX_csh_ambired_CAT_NUM_STR	"uxsgicsh:100"
#define	_MSG_MMX_csh_ambired_DEF_MSG	"Ambiguous input redirect"
#define	_MSG_MMX_csh_ambired_CAT_NUM_STR_DEF_MSG	"uxsgicsh:100:Ambiguous input redirect"
#define	_MSG_MMX_csh_ambired_MSG_NUM_STR_DEF_MSG	":100:Ambiguous input redirect"
#define	_MSG_MMX_csh_ambired_FILE_CAT_NUM	uxsgicsh:100
#define	_SGI_DMMX_csh_ambired	":100"
#define	_SGI_MMX_csh_ambired	"uxsgicsh:100"
#define	_SGI_MMMX_csh_ambired	"uxsgicsh:100:Ambiguous input redirect"
#define	_SGI_SMMX_csh_ambired	"Ambiguous input redirect"
#define	_MSG_MMX_csh_cantred_MSG_NUM	101
#define	_MSG_MMX_csh_cantred_MSG_NUM_STR	":101"
#define	_MSG_MMX_csh_cantred_CAT_NUM_STR	"uxsgicsh:101"
#define	_MSG_MMX_csh_cantred_DEF_MSG	"Can't << within ()'s"
#define	_MSG_MMX_csh_cantred_CAT_NUM_STR_DEF_MSG	"uxsgicsh:101:Can't << within ()'s"
#define	_MSG_MMX_csh_cantred_MSG_NUM_STR_DEF_MSG	":101:Can't << within ()'s"
#define	_MSG_MMX_csh_cantred_FILE_CAT_NUM	uxsgicsh:101
#define	_SGI_DMMX_csh_cantred	":101"
#define	_SGI_MMX_csh_cantred	"uxsgicsh:101"
#define	_SGI_MMMX_csh_cantred	"uxsgicsh:101:Can't << within ()'s"
#define	_SGI_SMMX_csh_cantred	"Can't << within ()'s"
#define	_MSG_MMX_csh_badplbb_MSG_NUM	102
#define	_MSG_MMX_csh_badplbb_MSG_NUM_STR	":102"
#define	_MSG_MMX_csh_badplbb_CAT_NUM_STR	"uxsgicsh:102"
#define	_MSG_MMX_csh_badplbb_DEF_MSG	"Badly placed ()'s"
#define	_MSG_MMX_csh_badplbb_CAT_NUM_STR_DEF_MSG	"uxsgicsh:102:Badly placed ()'s"
#define	_MSG_MMX_csh_badplbb_MSG_NUM_STR_DEF_MSG	":102:Badly placed ()'s"
#define	_MSG_MMX_csh_badplbb_FILE_CAT_NUM	uxsgicsh:102
#define	_SGI_DMMX_csh_badplbb	":102"
#define	_SGI_MMX_csh_badplbb	"uxsgicsh:102"
#define	_SGI_MMMX_csh_badplbb	"uxsgicsh:102:Badly placed ()'s"
#define	_SGI_SMMX_csh_badplbb	"Badly placed ()'s"
#define	_MSG_MMX_csh_inv0cmd_MSG_NUM	103
#define	_MSG_MMX_csh_inv0cmd_MSG_NUM_STR	":103"
#define	_MSG_MMX_csh_inv0cmd_CAT_NUM_STR	"uxsgicsh:103"
#define	_MSG_MMX_csh_inv0cmd_DEF_MSG	"Invalid null command"
#define	_MSG_MMX_csh_inv0cmd_CAT_NUM_STR_DEF_MSG	"uxsgicsh:103:Invalid null command"
#define	_MSG_MMX_csh_inv0cmd_MSG_NUM_STR_DEF_MSG	":103:Invalid null command"
#define	_MSG_MMX_csh_inv0cmd_FILE_CAT_NUM	uxsgicsh:103
#define	_SGI_DMMX_csh_inv0cmd	":103"
#define	_SGI_MMX_csh_inv0cmd	"uxsgicsh:103"
#define	_SGI_MMMX_csh_inv0cmd	"uxsgicsh:103:Invalid null command"
#define	_SGI_SMMX_csh_inv0cmd	"Invalid null command"
#define	_MSG_MMX_csh_badbangmod_MSG_NUM	104
#define	_MSG_MMX_csh_badbangmod_MSG_NUM_STR	":104"
#define	_MSG_MMX_csh_badbangmod_CAT_NUM_STR	"uxsgicsh:104"
#define	_MSG_MMX_csh_badbangmod_DEF_MSG	"%s: Bad ! modifier"
#define	_MSG_MMX_csh_badbangmod_CAT_NUM_STR_DEF_MSG	"uxsgicsh:104:%s: Bad ! modifier"
#define	_MSG_MMX_csh_badbangmod_MSG_NUM_STR_DEF_MSG	":104:%s: Bad ! modifier"
#define	_MSG_MMX_csh_badbangmod_FILE_CAT_NUM	uxsgicsh:104
#define	_SGI_DMMX_csh_badbangmod	":104"
#define	_SGI_MMX_csh_badbangmod	"uxsgicsh:104"
#define	_SGI_MMMX_csh_badbangmod	"uxsgicsh:104:%s: Bad ! modifier"
#define	_SGI_SMMX_csh_badbangmod	"%s: Bad ! modifier"
#define	_MSG_MMX_csh_2manynames_MSG_NUM	105
#define	_MSG_MMX_csh_2manynames_MSG_NUM_STR	":105"
#define	_MSG_MMX_csh_2manynames_CAT_NUM_STR	"uxsgicsh:105"
#define	_MSG_MMX_csh_2manynames_DEF_MSG	"\nYikes! Too many names in passwd!"
#define	_MSG_MMX_csh_2manynames_CAT_NUM_STR_DEF_MSG	"uxsgicsh:105:\nYikes! Too many names in passwd!"
#define	_MSG_MMX_csh_2manynames_MSG_NUM_STR_DEF_MSG	":105:\nYikes! Too many names in passwd!"
#define	_MSG_MMX_csh_2manynames_FILE_CAT_NUM	uxsgicsh:105
#define	_SGI_DMMX_csh_2manynames	":105"
#define	_SGI_MMX_csh_2manynames	"uxsgicsh:105"
#define	_SGI_MMMX_csh_2manynames	"uxsgicsh:105:\nYikes! Too many names in passwd!"
#define	_SGI_SMMX_csh_2manynames	"\nYikes! Too many names in passwd!"
#define	_MSG_MMX_csh_2manyfiles_MSG_NUM	106
#define	_MSG_MMX_csh_2manyfiles_MSG_NUM_STR	":106"
#define	_MSG_MMX_csh_2manyfiles_CAT_NUM_STR	"uxsgicsh:106"
#define	_MSG_MMX_csh_2manyfiles_DEF_MSG	"\nYikes! Too many files!"
#define	_MSG_MMX_csh_2manyfiles_CAT_NUM_STR_DEF_MSG	"uxsgicsh:106:\nYikes! Too many files!"
#define	_MSG_MMX_csh_2manyfiles_MSG_NUM_STR_DEF_MSG	":106:\nYikes! Too many files!"
#define	_MSG_MMX_csh_2manyfiles_FILE_CAT_NUM	uxsgicsh:106
#define	_SGI_DMMX_csh_2manyfiles	":106"
#define	_SGI_MMX_csh_2manyfiles	"uxsgicsh:106"
#define	_SGI_MMMX_csh_2manyfiles	"uxsgicsh:106:\nYikes! Too many files!"
#define	_SGI_SMMX_csh_2manyfiles	"\nYikes! Too many files!"
#define	_MSG_MMX_csh_S_HUP_MSG_NUM	107
#define	_MSG_MMX_csh_S_HUP_MSG_NUM_STR	":107"
#define	_MSG_MMX_csh_S_HUP_CAT_NUM_STR	"uxsgicsh:107"
#define	_MSG_MMX_csh_S_HUP_DEF_MSG	"Hangup"
#define	_MSG_MMX_csh_S_HUP_CAT_NUM_STR_DEF_MSG	"uxsgicsh:107:Hangup"
#define	_MSG_MMX_csh_S_HUP_MSG_NUM_STR_DEF_MSG	":107:Hangup"
#define	_MSG_MMX_csh_S_HUP_FILE_CAT_NUM	uxsgicsh:107
#define	_SGI_DMMX_csh_S_HUP	":107"
#define	_SGI_MMX_csh_S_HUP	"uxsgicsh:107"
#define	_SGI_MMMX_csh_S_HUP	"uxsgicsh:107:Hangup"
#define	_SGI_SMMX_csh_S_HUP	"Hangup"
#define	_MSG_MMX_csh_S_INT_MSG_NUM	108
#define	_MSG_MMX_csh_S_INT_MSG_NUM_STR	":108"
#define	_MSG_MMX_csh_S_INT_CAT_NUM_STR	"uxsgicsh:108"
#define	_MSG_MMX_csh_S_INT_DEF_MSG	"Interrupt"
#define	_MSG_MMX_csh_S_INT_CAT_NUM_STR_DEF_MSG	"uxsgicsh:108:Interrupt"
#define	_MSG_MMX_csh_S_INT_MSG_NUM_STR_DEF_MSG	":108:Interrupt"
#define	_MSG_MMX_csh_S_INT_FILE_CAT_NUM	uxsgicsh:108
#define	_SGI_DMMX_csh_S_INT	":108"
#define	_SGI_MMX_csh_S_INT	"uxsgicsh:108"
#define	_SGI_MMMX_csh_S_INT	"uxsgicsh:108:Interrupt"
#define	_SGI_SMMX_csh_S_INT	"Interrupt"
#define	_MSG_MMX_csh_S_QUIT_MSG_NUM	109
#define	_MSG_MMX_csh_S_QUIT_MSG_NUM_STR	":109"
#define	_MSG_MMX_csh_S_QUIT_CAT_NUM_STR	"uxsgicsh:109"
#define	_MSG_MMX_csh_S_QUIT_DEF_MSG	"Quit"
#define	_MSG_MMX_csh_S_QUIT_CAT_NUM_STR_DEF_MSG	"uxsgicsh:109:Quit"
#define	_MSG_MMX_csh_S_QUIT_MSG_NUM_STR_DEF_MSG	":109:Quit"
#define	_MSG_MMX_csh_S_QUIT_FILE_CAT_NUM	uxsgicsh:109
#define	_SGI_DMMX_csh_S_QUIT	":109"
#define	_SGI_MMX_csh_S_QUIT	"uxsgicsh:109"
#define	_SGI_MMMX_csh_S_QUIT	"uxsgicsh:109:Quit"
#define	_SGI_SMMX_csh_S_QUIT	"Quit"
#define	_MSG_MMX_csh_S_ILL_MSG_NUM	110
#define	_MSG_MMX_csh_S_ILL_MSG_NUM_STR	":110"
#define	_MSG_MMX_csh_S_ILL_CAT_NUM_STR	"uxsgicsh:110"
#define	_MSG_MMX_csh_S_ILL_DEF_MSG	"Illegal instruction"
#define	_MSG_MMX_csh_S_ILL_CAT_NUM_STR_DEF_MSG	"uxsgicsh:110:Illegal instruction"
#define	_MSG_MMX_csh_S_ILL_MSG_NUM_STR_DEF_MSG	":110:Illegal instruction"
#define	_MSG_MMX_csh_S_ILL_FILE_CAT_NUM	uxsgicsh:110
#define	_SGI_DMMX_csh_S_ILL	":110"
#define	_SGI_MMX_csh_S_ILL	"uxsgicsh:110"
#define	_SGI_MMMX_csh_S_ILL	"uxsgicsh:110:Illegal instruction"
#define	_SGI_SMMX_csh_S_ILL	"Illegal instruction"
#define	_MSG_MMX_csh_S_TRAP_MSG_NUM	111
#define	_MSG_MMX_csh_S_TRAP_MSG_NUM_STR	":111"
#define	_MSG_MMX_csh_S_TRAP_CAT_NUM_STR	"uxsgicsh:111"
#define	_MSG_MMX_csh_S_TRAP_DEF_MSG	"Trace/BPT trap"
#define	_MSG_MMX_csh_S_TRAP_CAT_NUM_STR_DEF_MSG	"uxsgicsh:111:Trace/BPT trap"
#define	_MSG_MMX_csh_S_TRAP_MSG_NUM_STR_DEF_MSG	":111:Trace/BPT trap"
#define	_MSG_MMX_csh_S_TRAP_FILE_CAT_NUM	uxsgicsh:111
#define	_SGI_DMMX_csh_S_TRAP	":111"
#define	_SGI_MMX_csh_S_TRAP	"uxsgicsh:111"
#define	_SGI_MMMX_csh_S_TRAP	"uxsgicsh:111:Trace/BPT trap"
#define	_SGI_SMMX_csh_S_TRAP	"Trace/BPT trap"
#define	_MSG_MMX_csh_S_ABRT_MSG_NUM	112
#define	_MSG_MMX_csh_S_ABRT_MSG_NUM_STR	":112"
#define	_MSG_MMX_csh_S_ABRT_CAT_NUM_STR	"uxsgicsh:112"
#define	_MSG_MMX_csh_S_ABRT_DEF_MSG	"Abort"
#define	_MSG_MMX_csh_S_ABRT_CAT_NUM_STR_DEF_MSG	"uxsgicsh:112:Abort"
#define	_MSG_MMX_csh_S_ABRT_MSG_NUM_STR_DEF_MSG	":112:Abort"
#define	_MSG_MMX_csh_S_ABRT_FILE_CAT_NUM	uxsgicsh:112
#define	_SGI_DMMX_csh_S_ABRT	":112"
#define	_SGI_MMX_csh_S_ABRT	"uxsgicsh:112"
#define	_SGI_MMMX_csh_S_ABRT	"uxsgicsh:112:Abort"
#define	_SGI_SMMX_csh_S_ABRT	"Abort"
#define	_MSG_MMX_csh_S_EMT_MSG_NUM	113
#define	_MSG_MMX_csh_S_EMT_MSG_NUM_STR	":113"
#define	_MSG_MMX_csh_S_EMT_CAT_NUM_STR	"uxsgicsh:113"
#define	_MSG_MMX_csh_S_EMT_DEF_MSG	"Emulator trap"
#define	_MSG_MMX_csh_S_EMT_CAT_NUM_STR_DEF_MSG	"uxsgicsh:113:Emulator trap"
#define	_MSG_MMX_csh_S_EMT_MSG_NUM_STR_DEF_MSG	":113:Emulator trap"
#define	_MSG_MMX_csh_S_EMT_FILE_CAT_NUM	uxsgicsh:113
#define	_SGI_DMMX_csh_S_EMT	":113"
#define	_SGI_MMX_csh_S_EMT	"uxsgicsh:113"
#define	_SGI_MMMX_csh_S_EMT	"uxsgicsh:113:Emulator trap"
#define	_SGI_SMMX_csh_S_EMT	"Emulator trap"
#define	_MSG_MMX_csh_S_FPE_MSG_NUM	114
#define	_MSG_MMX_csh_S_FPE_MSG_NUM_STR	":114"
#define	_MSG_MMX_csh_S_FPE_CAT_NUM_STR	"uxsgicsh:114"
#define	_MSG_MMX_csh_S_FPE_DEF_MSG	"Arithmetic exception"
#define	_MSG_MMX_csh_S_FPE_CAT_NUM_STR_DEF_MSG	"uxsgicsh:114:Arithmetic exception"
#define	_MSG_MMX_csh_S_FPE_MSG_NUM_STR_DEF_MSG	":114:Arithmetic exception"
#define	_MSG_MMX_csh_S_FPE_FILE_CAT_NUM	uxsgicsh:114
#define	_SGI_DMMX_csh_S_FPE	":114"
#define	_SGI_MMX_csh_S_FPE	"uxsgicsh:114"
#define	_SGI_MMMX_csh_S_FPE	"uxsgicsh:114:Arithmetic exception"
#define	_SGI_SMMX_csh_S_FPE	"Arithmetic exception"
#define	_MSG_MMX_csh_S_KILL_MSG_NUM	115
#define	_MSG_MMX_csh_S_KILL_MSG_NUM_STR	":115"
#define	_MSG_MMX_csh_S_KILL_CAT_NUM_STR	"uxsgicsh:115"
#define	_MSG_MMX_csh_S_KILL_DEF_MSG	"Killed"
#define	_MSG_MMX_csh_S_KILL_CAT_NUM_STR_DEF_MSG	"uxsgicsh:115:Killed"
#define	_MSG_MMX_csh_S_KILL_MSG_NUM_STR_DEF_MSG	":115:Killed"
#define	_MSG_MMX_csh_S_KILL_FILE_CAT_NUM	uxsgicsh:115
#define	_SGI_DMMX_csh_S_KILL	":115"
#define	_SGI_MMX_csh_S_KILL	"uxsgicsh:115"
#define	_SGI_MMMX_csh_S_KILL	"uxsgicsh:115:Killed"
#define	_SGI_SMMX_csh_S_KILL	"Killed"
#define	_MSG_MMX_csh_S_BUS_MSG_NUM	116
#define	_MSG_MMX_csh_S_BUS_MSG_NUM_STR	":116"
#define	_MSG_MMX_csh_S_BUS_CAT_NUM_STR	"uxsgicsh:116"
#define	_MSG_MMX_csh_S_BUS_DEF_MSG	"Bus error"
#define	_MSG_MMX_csh_S_BUS_CAT_NUM_STR_DEF_MSG	"uxsgicsh:116:Bus error"
#define	_MSG_MMX_csh_S_BUS_MSG_NUM_STR_DEF_MSG	":116:Bus error"
#define	_MSG_MMX_csh_S_BUS_FILE_CAT_NUM	uxsgicsh:116
#define	_SGI_DMMX_csh_S_BUS	":116"
#define	_SGI_MMX_csh_S_BUS	"uxsgicsh:116"
#define	_SGI_MMMX_csh_S_BUS	"uxsgicsh:116:Bus error"
#define	_SGI_SMMX_csh_S_BUS	"Bus error"
#define	_MSG_MMX_csh_S_SEGV_MSG_NUM	117
#define	_MSG_MMX_csh_S_SEGV_MSG_NUM_STR	":117"
#define	_MSG_MMX_csh_S_SEGV_CAT_NUM_STR	"uxsgicsh:117"
#define	_MSG_MMX_csh_S_SEGV_DEF_MSG	"Segmentation fault"
#define	_MSG_MMX_csh_S_SEGV_CAT_NUM_STR_DEF_MSG	"uxsgicsh:117:Segmentation fault"
#define	_MSG_MMX_csh_S_SEGV_MSG_NUM_STR_DEF_MSG	":117:Segmentation fault"
#define	_MSG_MMX_csh_S_SEGV_FILE_CAT_NUM	uxsgicsh:117
#define	_SGI_DMMX_csh_S_SEGV	":117"
#define	_SGI_MMX_csh_S_SEGV	"uxsgicsh:117"
#define	_SGI_MMMX_csh_S_SEGV	"uxsgicsh:117:Segmentation fault"
#define	_SGI_SMMX_csh_S_SEGV	"Segmentation fault"
#define	_MSG_MMX_csh_S_SYS_MSG_NUM	118
#define	_MSG_MMX_csh_S_SYS_MSG_NUM_STR	":118"
#define	_MSG_MMX_csh_S_SYS_CAT_NUM_STR	"uxsgicsh:118"
#define	_MSG_MMX_csh_S_SYS_DEF_MSG	"Bad system call"
#define	_MSG_MMX_csh_S_SYS_CAT_NUM_STR_DEF_MSG	"uxsgicsh:118:Bad system call"
#define	_MSG_MMX_csh_S_SYS_MSG_NUM_STR_DEF_MSG	":118:Bad system call"
#define	_MSG_MMX_csh_S_SYS_FILE_CAT_NUM	uxsgicsh:118
#define	_SGI_DMMX_csh_S_SYS	":118"
#define	_SGI_MMX_csh_S_SYS	"uxsgicsh:118"
#define	_SGI_MMMX_csh_S_SYS	"uxsgicsh:118:Bad system call"
#define	_SGI_SMMX_csh_S_SYS	"Bad system call"
#define	_MSG_MMX_csh_S_PIPE_MSG_NUM	119
#define	_MSG_MMX_csh_S_PIPE_MSG_NUM_STR	":119"
#define	_MSG_MMX_csh_S_PIPE_CAT_NUM_STR	"uxsgicsh:119"
#define	_MSG_MMX_csh_S_PIPE_DEF_MSG	"Broken pipe"
#define	_MSG_MMX_csh_S_PIPE_CAT_NUM_STR_DEF_MSG	"uxsgicsh:119:Broken pipe"
#define	_MSG_MMX_csh_S_PIPE_MSG_NUM_STR_DEF_MSG	":119:Broken pipe"
#define	_MSG_MMX_csh_S_PIPE_FILE_CAT_NUM	uxsgicsh:119
#define	_SGI_DMMX_csh_S_PIPE	":119"
#define	_SGI_MMX_csh_S_PIPE	"uxsgicsh:119"
#define	_SGI_MMMX_csh_S_PIPE	"uxsgicsh:119:Broken pipe"
#define	_SGI_SMMX_csh_S_PIPE	"Broken pipe"
#define	_MSG_MMX_csh_S_ALRM_MSG_NUM	120
#define	_MSG_MMX_csh_S_ALRM_MSG_NUM_STR	":120"
#define	_MSG_MMX_csh_S_ALRM_CAT_NUM_STR	"uxsgicsh:120"
#define	_MSG_MMX_csh_S_ALRM_DEF_MSG	"Alarm clock"
#define	_MSG_MMX_csh_S_ALRM_CAT_NUM_STR_DEF_MSG	"uxsgicsh:120:Alarm clock"
#define	_MSG_MMX_csh_S_ALRM_MSG_NUM_STR_DEF_MSG	":120:Alarm clock"
#define	_MSG_MMX_csh_S_ALRM_FILE_CAT_NUM	uxsgicsh:120
#define	_SGI_DMMX_csh_S_ALRM	":120"
#define	_SGI_MMX_csh_S_ALRM	"uxsgicsh:120"
#define	_SGI_MMMX_csh_S_ALRM	"uxsgicsh:120:Alarm clock"
#define	_SGI_SMMX_csh_S_ALRM	"Alarm clock"
#define	_MSG_MMX_csh_S_TERM_MSG_NUM	121
#define	_MSG_MMX_csh_S_TERM_MSG_NUM_STR	":121"
#define	_MSG_MMX_csh_S_TERM_CAT_NUM_STR	"uxsgicsh:121"
#define	_MSG_MMX_csh_S_TERM_DEF_MSG	"Terminated"
#define	_MSG_MMX_csh_S_TERM_CAT_NUM_STR_DEF_MSG	"uxsgicsh:121:Terminated"
#define	_MSG_MMX_csh_S_TERM_MSG_NUM_STR_DEF_MSG	":121:Terminated"
#define	_MSG_MMX_csh_S_TERM_FILE_CAT_NUM	uxsgicsh:121
#define	_SGI_DMMX_csh_S_TERM	":121"
#define	_SGI_MMX_csh_S_TERM	"uxsgicsh:121"
#define	_SGI_MMMX_csh_S_TERM	"uxsgicsh:121:Terminated"
#define	_SGI_SMMX_csh_S_TERM	"Terminated"
#define	_MSG_MMX_csh_S_USR1_MSG_NUM	122
#define	_MSG_MMX_csh_S_USR1_MSG_NUM_STR	":122"
#define	_MSG_MMX_csh_S_USR1_CAT_NUM_STR	"uxsgicsh:122"
#define	_MSG_MMX_csh_S_USR1_DEF_MSG	"User defined signal 1"
#define	_MSG_MMX_csh_S_USR1_CAT_NUM_STR_DEF_MSG	"uxsgicsh:122:User defined signal 1"
#define	_MSG_MMX_csh_S_USR1_MSG_NUM_STR_DEF_MSG	":122:User defined signal 1"
#define	_MSG_MMX_csh_S_USR1_FILE_CAT_NUM	uxsgicsh:122
#define	_SGI_DMMX_csh_S_USR1	":122"
#define	_SGI_MMX_csh_S_USR1	"uxsgicsh:122"
#define	_SGI_MMMX_csh_S_USR1	"uxsgicsh:122:User defined signal 1"
#define	_SGI_SMMX_csh_S_USR1	"User defined signal 1"
#define	_MSG_MMX_csh_S_USR2_MSG_NUM	123
#define	_MSG_MMX_csh_S_USR2_MSG_NUM_STR	":123"
#define	_MSG_MMX_csh_S_USR2_CAT_NUM_STR	"uxsgicsh:123"
#define	_MSG_MMX_csh_S_USR2_DEF_MSG	"User defined signal 2"
#define	_MSG_MMX_csh_S_USR2_CAT_NUM_STR_DEF_MSG	"uxsgicsh:123:User defined signal 2"
#define	_MSG_MMX_csh_S_USR2_MSG_NUM_STR_DEF_MSG	":123:User defined signal 2"
#define	_MSG_MMX_csh_S_USR2_FILE_CAT_NUM	uxsgicsh:123
#define	_SGI_DMMX_csh_S_USR2	":123"
#define	_SGI_MMX_csh_S_USR2	"uxsgicsh:123"
#define	_SGI_MMMX_csh_S_USR2	"uxsgicsh:123:User defined signal 2"
#define	_SGI_SMMX_csh_S_USR2	"User defined signal 2"
#define	_MSG_MMX_csh_S_CHLD_MSG_NUM	124
#define	_MSG_MMX_csh_S_CHLD_MSG_NUM_STR	":124"
#define	_MSG_MMX_csh_S_CHLD_CAT_NUM_STR	"uxsgicsh:124"
#define	_MSG_MMX_csh_S_CHLD_DEF_MSG	"Child exited"
#define	_MSG_MMX_csh_S_CHLD_CAT_NUM_STR_DEF_MSG	"uxsgicsh:124:Child exited"
#define	_MSG_MMX_csh_S_CHLD_MSG_NUM_STR_DEF_MSG	":124:Child exited"
#define	_MSG_MMX_csh_S_CHLD_FILE_CAT_NUM	uxsgicsh:124
#define	_SGI_DMMX_csh_S_CHLD	":124"
#define	_SGI_MMX_csh_S_CHLD	"uxsgicsh:124"
#define	_SGI_MMMX_csh_S_CHLD	"uxsgicsh:124:Child exited"
#define	_SGI_SMMX_csh_S_CHLD	"Child exited"
#define	_MSG_MMX_csh_S_PWR_MSG_NUM	125
#define	_MSG_MMX_csh_S_PWR_MSG_NUM_STR	":125"
#define	_MSG_MMX_csh_S_PWR_CAT_NUM_STR	"uxsgicsh:125"
#define	_MSG_MMX_csh_S_PWR_DEF_MSG	"Power failed"
#define	_MSG_MMX_csh_S_PWR_CAT_NUM_STR_DEF_MSG	"uxsgicsh:125:Power failed"
#define	_MSG_MMX_csh_S_PWR_MSG_NUM_STR_DEF_MSG	":125:Power failed"
#define	_MSG_MMX_csh_S_PWR_FILE_CAT_NUM	uxsgicsh:125
#define	_SGI_DMMX_csh_S_PWR	":125"
#define	_SGI_MMX_csh_S_PWR	"uxsgicsh:125"
#define	_SGI_MMMX_csh_S_PWR	"uxsgicsh:125:Power failed"
#define	_SGI_SMMX_csh_S_PWR	"Power failed"
#define	_MSG_MMX_csh_S_WINCH_MSG_NUM	126
#define	_MSG_MMX_csh_S_WINCH_MSG_NUM_STR	":126"
#define	_MSG_MMX_csh_S_WINCH_CAT_NUM_STR	"uxsgicsh:126"
#define	_MSG_MMX_csh_S_WINCH_DEF_MSG	"Window size changed"
#define	_MSG_MMX_csh_S_WINCH_CAT_NUM_STR_DEF_MSG	"uxsgicsh:126:Window size changed"
#define	_MSG_MMX_csh_S_WINCH_MSG_NUM_STR_DEF_MSG	":126:Window size changed"
#define	_MSG_MMX_csh_S_WINCH_FILE_CAT_NUM	uxsgicsh:126
#define	_SGI_DMMX_csh_S_WINCH	":126"
#define	_SGI_MMX_csh_S_WINCH	"uxsgicsh:126"
#define	_SGI_MMMX_csh_S_WINCH	"uxsgicsh:126:Window size changed"
#define	_SGI_SMMX_csh_S_WINCH	"Window size changed"
#define	_MSG_MMX_csh_S_URG_MSG_NUM	127
#define	_MSG_MMX_csh_S_URG_MSG_NUM_STR	":127"
#define	_MSG_MMX_csh_S_URG_CAT_NUM_STR	"uxsgicsh:127"
#define	_MSG_MMX_csh_S_URG_DEF_MSG	"Urgent I/O condition"
#define	_MSG_MMX_csh_S_URG_CAT_NUM_STR_DEF_MSG	"uxsgicsh:127:Urgent I/O condition"
#define	_MSG_MMX_csh_S_URG_MSG_NUM_STR_DEF_MSG	":127:Urgent I/O condition"
#define	_MSG_MMX_csh_S_URG_FILE_CAT_NUM	uxsgicsh:127
#define	_SGI_DMMX_csh_S_URG	":127"
#define	_SGI_MMX_csh_S_URG	"uxsgicsh:127"
#define	_SGI_MMMX_csh_S_URG	"uxsgicsh:127:Urgent I/O condition"
#define	_SGI_SMMX_csh_S_URG	"Urgent I/O condition"
#define	_MSG_MMX_csh_S_POLL_MSG_NUM	128
#define	_MSG_MMX_csh_S_POLL_MSG_NUM_STR	":128"
#define	_MSG_MMX_csh_S_POLL_CAT_NUM_STR	"uxsgicsh:128"
#define	_MSG_MMX_csh_S_POLL_DEF_MSG	"Pollable event occurred"
#define	_MSG_MMX_csh_S_POLL_CAT_NUM_STR_DEF_MSG	"uxsgicsh:128:Pollable event occurred"
#define	_MSG_MMX_csh_S_POLL_MSG_NUM_STR_DEF_MSG	":128:Pollable event occurred"
#define	_MSG_MMX_csh_S_POLL_FILE_CAT_NUM	uxsgicsh:128
#define	_SGI_DMMX_csh_S_POLL	":128"
#define	_SGI_MMX_csh_S_POLL	"uxsgicsh:128"
#define	_SGI_MMMX_csh_S_POLL	"uxsgicsh:128:Pollable event occurred"
#define	_SGI_SMMX_csh_S_POLL	"Pollable event occurred"
#define	_MSG_MMX_csh_S_STOP_MSG_NUM	129
#define	_MSG_MMX_csh_S_STOP_MSG_NUM_STR	":129"
#define	_MSG_MMX_csh_S_STOP_CAT_NUM_STR	"uxsgicsh:129"
#define	_MSG_MMX_csh_S_STOP_DEF_MSG	"Stopped (signal)"
#define	_MSG_MMX_csh_S_STOP_CAT_NUM_STR_DEF_MSG	"uxsgicsh:129:Stopped (signal)"
#define	_MSG_MMX_csh_S_STOP_MSG_NUM_STR_DEF_MSG	":129:Stopped (signal)"
#define	_MSG_MMX_csh_S_STOP_FILE_CAT_NUM	uxsgicsh:129
#define	_SGI_DMMX_csh_S_STOP	":129"
#define	_SGI_MMX_csh_S_STOP	"uxsgicsh:129"
#define	_SGI_MMMX_csh_S_STOP	"uxsgicsh:129:Stopped (signal)"
#define	_SGI_SMMX_csh_S_STOP	"Stopped (signal)"
#define	_MSG_MMX_csh_S_TSTP_MSG_NUM	130
#define	_MSG_MMX_csh_S_TSTP_MSG_NUM_STR	":130"
#define	_MSG_MMX_csh_S_TSTP_CAT_NUM_STR	"uxsgicsh:130"
#define	_MSG_MMX_csh_S_TSTP_DEF_MSG	"Stopped"
#define	_MSG_MMX_csh_S_TSTP_CAT_NUM_STR_DEF_MSG	"uxsgicsh:130:Stopped"
#define	_MSG_MMX_csh_S_TSTP_MSG_NUM_STR_DEF_MSG	":130:Stopped"
#define	_MSG_MMX_csh_S_TSTP_FILE_CAT_NUM	uxsgicsh:130
#define	_SGI_DMMX_csh_S_TSTP	":130"
#define	_SGI_MMX_csh_S_TSTP	"uxsgicsh:130"
#define	_SGI_MMMX_csh_S_TSTP	"uxsgicsh:130:Stopped"
#define	_SGI_SMMX_csh_S_TSTP	"Stopped"
#define	_MSG_MMX_csh_S_CONT_MSG_NUM	131
#define	_MSG_MMX_csh_S_CONT_MSG_NUM_STR	":131"
#define	_MSG_MMX_csh_S_CONT_CAT_NUM_STR	"uxsgicsh:131"
#define	_MSG_MMX_csh_S_CONT_DEF_MSG	"Continued"
#define	_MSG_MMX_csh_S_CONT_CAT_NUM_STR_DEF_MSG	"uxsgicsh:131:Continued"
#define	_MSG_MMX_csh_S_CONT_MSG_NUM_STR_DEF_MSG	":131:Continued"
#define	_MSG_MMX_csh_S_CONT_FILE_CAT_NUM	uxsgicsh:131
#define	_SGI_DMMX_csh_S_CONT	":131"
#define	_SGI_MMX_csh_S_CONT	"uxsgicsh:131"
#define	_SGI_MMMX_csh_S_CONT	"uxsgicsh:131:Continued"
#define	_SGI_SMMX_csh_S_CONT	"Continued"
#define	_MSG_MMX_csh_S_TTIN_MSG_NUM	132
#define	_MSG_MMX_csh_S_TTIN_MSG_NUM_STR	":132"
#define	_MSG_MMX_csh_S_TTIN_CAT_NUM_STR	"uxsgicsh:132"
#define	_MSG_MMX_csh_S_TTIN_DEF_MSG	"Stopped (tty input)"
#define	_MSG_MMX_csh_S_TTIN_CAT_NUM_STR_DEF_MSG	"uxsgicsh:132:Stopped (tty input)"
#define	_MSG_MMX_csh_S_TTIN_MSG_NUM_STR_DEF_MSG	":132:Stopped (tty input)"
#define	_MSG_MMX_csh_S_TTIN_FILE_CAT_NUM	uxsgicsh:132
#define	_SGI_DMMX_csh_S_TTIN	":132"
#define	_SGI_MMX_csh_S_TTIN	"uxsgicsh:132"
#define	_SGI_MMMX_csh_S_TTIN	"uxsgicsh:132:Stopped (tty input)"
#define	_SGI_SMMX_csh_S_TTIN	"Stopped (tty input)"
#define	_MSG_MMX_csh_S_TTOU_MSG_NUM	133
#define	_MSG_MMX_csh_S_TTOU_MSG_NUM_STR	":133"
#define	_MSG_MMX_csh_S_TTOU_CAT_NUM_STR	"uxsgicsh:133"
#define	_MSG_MMX_csh_S_TTOU_DEF_MSG	"Stopped (tty output)"
#define	_MSG_MMX_csh_S_TTOU_CAT_NUM_STR_DEF_MSG	"uxsgicsh:133:Stopped (tty output)"
#define	_MSG_MMX_csh_S_TTOU_MSG_NUM_STR_DEF_MSG	":133:Stopped (tty output)"
#define	_MSG_MMX_csh_S_TTOU_FILE_CAT_NUM	uxsgicsh:133
#define	_SGI_DMMX_csh_S_TTOU	":133"
#define	_SGI_MMX_csh_S_TTOU	"uxsgicsh:133"
#define	_SGI_MMMX_csh_S_TTOU	"uxsgicsh:133:Stopped (tty output)"
#define	_SGI_SMMX_csh_S_TTOU	"Stopped (tty output)"
#define	_MSG_MMX_csh_S_VTALRM_MSG_NUM	134
#define	_MSG_MMX_csh_S_VTALRM_MSG_NUM_STR	":134"
#define	_MSG_MMX_csh_S_VTALRM_CAT_NUM_STR	"uxsgicsh:134"
#define	_MSG_MMX_csh_S_VTALRM_DEF_MSG	"Virtual timer expired"
#define	_MSG_MMX_csh_S_VTALRM_CAT_NUM_STR_DEF_MSG	"uxsgicsh:134:Virtual timer expired"
#define	_MSG_MMX_csh_S_VTALRM_MSG_NUM_STR_DEF_MSG	":134:Virtual timer expired"
#define	_MSG_MMX_csh_S_VTALRM_FILE_CAT_NUM	uxsgicsh:134
#define	_SGI_DMMX_csh_S_VTALRM	":134"
#define	_SGI_MMX_csh_S_VTALRM	"uxsgicsh:134"
#define	_SGI_MMMX_csh_S_VTALRM	"uxsgicsh:134:Virtual timer expired"
#define	_SGI_SMMX_csh_S_VTALRM	"Virtual timer expired"
#define	_MSG_MMX_csh_S_PROF_MSG_NUM	135
#define	_MSG_MMX_csh_S_PROF_MSG_NUM_STR	":135"
#define	_MSG_MMX_csh_S_PROF_CAT_NUM_STR	"uxsgicsh:135"
#define	_MSG_MMX_csh_S_PROF_DEF_MSG	"Profiling timer expired"
#define	_MSG_MMX_csh_S_PROF_CAT_NUM_STR_DEF_MSG	"uxsgicsh:135:Profiling timer expired"
#define	_MSG_MMX_csh_S_PROF_MSG_NUM_STR_DEF_MSG	":135:Profiling timer expired"
#define	_MSG_MMX_csh_S_PROF_FILE_CAT_NUM	uxsgicsh:135
#define	_SGI_DMMX_csh_S_PROF	":135"
#define	_SGI_MMX_csh_S_PROF	"uxsgicsh:135"
#define	_SGI_MMMX_csh_S_PROF	"uxsgicsh:135:Profiling timer expired"
#define	_SGI_SMMX_csh_S_PROF	"Profiling timer expired"
#define	_MSG_MMX_csh_S_XCPU_MSG_NUM	136
#define	_MSG_MMX_csh_S_XCPU_MSG_NUM_STR	":136"
#define	_MSG_MMX_csh_S_XCPU_CAT_NUM_STR	"uxsgicsh:136"
#define	_MSG_MMX_csh_S_XCPU_DEF_MSG	"Cputime limit exceeded"
#define	_MSG_MMX_csh_S_XCPU_CAT_NUM_STR_DEF_MSG	"uxsgicsh:136:Cputime limit exceeded"
#define	_MSG_MMX_csh_S_XCPU_MSG_NUM_STR_DEF_MSG	":136:Cputime limit exceeded"
#define	_MSG_MMX_csh_S_XCPU_FILE_CAT_NUM	uxsgicsh:136
#define	_SGI_DMMX_csh_S_XCPU	":136"
#define	_SGI_MMX_csh_S_XCPU	"uxsgicsh:136"
#define	_SGI_MMMX_csh_S_XCPU	"uxsgicsh:136:Cputime limit exceeded"
#define	_SGI_SMMX_csh_S_XCPU	"Cputime limit exceeded"
#define	_MSG_MMX_csh_S_XFSZ_MSG_NUM	137
#define	_MSG_MMX_csh_S_XFSZ_MSG_NUM_STR	":137"
#define	_MSG_MMX_csh_S_XFSZ_CAT_NUM_STR	"uxsgicsh:137"
#define	_MSG_MMX_csh_S_XFSZ_DEF_MSG	"Filesize limit exceeded"
#define	_MSG_MMX_csh_S_XFSZ_CAT_NUM_STR_DEF_MSG	"uxsgicsh:137:Filesize limit exceeded"
#define	_MSG_MMX_csh_S_XFSZ_MSG_NUM_STR_DEF_MSG	":137:Filesize limit exceeded"
#define	_MSG_MMX_csh_S_XFSZ_FILE_CAT_NUM	uxsgicsh:137
#define	_SGI_DMMX_csh_S_XFSZ	":137"
#define	_SGI_MMX_csh_S_XFSZ	"uxsgicsh:137"
#define	_SGI_MMMX_csh_S_XFSZ	"uxsgicsh:137:Filesize limit exceeded"
#define	_SGI_SMMX_csh_S_XFSZ	"Filesize limit exceeded"
#define	_MSG_MMX_csh_S_32_MSG_NUM	138
#define	_MSG_MMX_csh_S_32_MSG_NUM_STR	":138"
#define	_MSG_MMX_csh_S_32_CAT_NUM_STR	"uxsgicsh:138"
#define	_MSG_MMX_csh_S_32_DEF_MSG	"Signal 32"
#define	_MSG_MMX_csh_S_32_CAT_NUM_STR_DEF_MSG	"uxsgicsh:138:Signal 32"
#define	_MSG_MMX_csh_S_32_MSG_NUM_STR_DEF_MSG	":138:Signal 32"
#define	_MSG_MMX_csh_S_32_FILE_CAT_NUM	uxsgicsh:138
#define	_SGI_DMMX_csh_S_32	":138"
#define	_SGI_MMX_csh_S_32	"uxsgicsh:138"
#define	_SGI_MMMX_csh_S_32	"uxsgicsh:138:Signal 32"
#define	_SGI_SMMX_csh_S_32	"Signal 32"
#define	_MSG_MMX_csh_S_DEFAULTSTR_MSG_NUM	139
#define	_MSG_MMX_csh_S_DEFAULTSTR_MSG_NUM_STR	":139"
#define	_MSG_MMX_csh_S_DEFAULTSTR_CAT_NUM_STR	"uxsgicsh:139"
#define	_MSG_MMX_csh_S_DEFAULTSTR_DEF_MSG	"Signal %-14d"
#define	_MSG_MMX_csh_S_DEFAULTSTR_CAT_NUM_STR_DEF_MSG	"uxsgicsh:139:Signal %-14d"
#define	_MSG_MMX_csh_S_DEFAULTSTR_MSG_NUM_STR_DEF_MSG	":139:Signal %-14d"
#define	_MSG_MMX_csh_S_DEFAULTSTR_FILE_CAT_NUM	uxsgicsh:139
#define	_SGI_DMMX_csh_S_DEFAULTSTR	":139"
#define	_SGI_MMX_csh_S_DEFAULTSTR	"uxsgicsh:139"
#define	_SGI_MMMX_csh_S_DEFAULTSTR	"uxsgicsh:139:Signal %-14d"
#define	_SGI_SMMX_csh_S_DEFAULTSTR	"Signal %-14d"
#define	_MSG_MMX_csh_core_MSG_NUM	140
#define	_MSG_MMX_csh_core_MSG_NUM_STR	":140"
#define	_MSG_MMX_csh_core_CAT_NUM_STR	"uxsgicsh:140"
#define	_MSG_MMX_csh_core_DEF_MSG	" (core dumped)"
#define	_MSG_MMX_csh_core_CAT_NUM_STR_DEF_MSG	"uxsgicsh:140: (core dumped)"
#define	_MSG_MMX_csh_core_MSG_NUM_STR_DEF_MSG	":140: (core dumped)"
#define	_MSG_MMX_csh_core_FILE_CAT_NUM	uxsgicsh:140
#define	_SGI_DMMX_csh_core	":140"
#define	_SGI_MMX_csh_core	"uxsgicsh:140"
#define	_SGI_MMMX_csh_core	"uxsgicsh:140: (core dumped)"
#define	_SGI_SMMX_csh_core	" (core dumped)"
#define	_MSG_MMX_csh_done_MSG_NUM	141
#define	_MSG_MMX_csh_done_MSG_NUM_STR	":141"
#define	_MSG_MMX_csh_done_CAT_NUM_STR	"uxsgicsh:141"
#define	_MSG_MMX_csh_done_DEF_MSG	"Done"
#define	_MSG_MMX_csh_done_CAT_NUM_STR_DEF_MSG	"uxsgicsh:141:Done"
#define	_MSG_MMX_csh_done_MSG_NUM_STR_DEF_MSG	":141:Done"
#define	_MSG_MMX_csh_done_FILE_CAT_NUM	uxsgicsh:141
#define	_SGI_DMMX_csh_done	":141"
#define	_SGI_MMX_csh_done	"uxsgicsh:141"
#define	_SGI_MMMX_csh_done	"uxsgicsh:141:Done"
#define	_SGI_SMMX_csh_done	"Done"
#define	_MSG_MMX_csh_run_MSG_NUM	142
#define	_MSG_MMX_csh_run_MSG_NUM_STR	":142"
#define	_MSG_MMX_csh_run_CAT_NUM_STR	"uxsgicsh:142"
#define	_MSG_MMX_csh_run_DEF_MSG	"Running "
#define	_MSG_MMX_csh_run_CAT_NUM_STR_DEF_MSG	"uxsgicsh:142:Running "
#define	_MSG_MMX_csh_run_MSG_NUM_STR_DEF_MSG	":142:Running "
#define	_MSG_MMX_csh_run_FILE_CAT_NUM	uxsgicsh:142
#define	_SGI_DMMX_csh_run	":142"
#define	_SGI_MMX_csh_run	"uxsgicsh:142"
#define	_SGI_MMMX_csh_run	"uxsgicsh:142:Running "
#define	_SGI_SMMX_csh_run	"Running "
#define	_MSG_MMX_csh_exit_MSG_NUM	143
#define	_MSG_MMX_csh_exit_MSG_NUM_STR	":143"
#define	_MSG_MMX_csh_exit_CAT_NUM_STR	"uxsgicsh:143"
#define	_MSG_MMX_csh_exit_DEF_MSG	"Exit %-16d"
#define	_MSG_MMX_csh_exit_CAT_NUM_STR_DEF_MSG	"uxsgicsh:143:Exit %-16d"
#define	_MSG_MMX_csh_exit_MSG_NUM_STR_DEF_MSG	":143:Exit %-16d"
#define	_MSG_MMX_csh_exit_FILE_CAT_NUM	uxsgicsh:143
#define	_SGI_DMMX_csh_exit	":143"
#define	_SGI_MMX_csh_exit	"uxsgicsh:143"
#define	_SGI_MMMX_csh_exit	"uxsgicsh:143:Exit %-16d"
#define	_SGI_SMMX_csh_exit	"Exit %-16d"
#define	_MSG_MMX_csh_uselogout_MSG_NUM	144
#define	_MSG_MMX_csh_uselogout_MSG_NUM_STR	":144"
#define	_MSG_MMX_csh_uselogout_CAT_NUM_STR	"uxsgicsh:144"
#define	_MSG_MMX_csh_uselogout_DEF_MSG	"Use \"logout\" to logout"
#define	_MSG_MMX_csh_uselogout_CAT_NUM_STR_DEF_MSG	"uxsgicsh:144:Use \"logout\" to logout"
#define	_MSG_MMX_csh_uselogout_MSG_NUM_STR_DEF_MSG	":144:Use \"logout\" to logout"
#define	_MSG_MMX_csh_uselogout_FILE_CAT_NUM	uxsgicsh:144
#define	_SGI_DMMX_csh_uselogout	":144"
#define	_SGI_MMX_csh_uselogout	"uxsgicsh:144"
#define	_SGI_MMMX_csh_uselogout	"uxsgicsh:144:Use \"logout\" to logout"
#define	_SGI_SMMX_csh_uselogout	"Use \"logout\" to logout"
#define	_MSG_MMX_csh_useexit_MSG_NUM	145
#define	_MSG_MMX_csh_useexit_MSG_NUM_STR	":145"
#define	_MSG_MMX_csh_useexit_CAT_NUM_STR	"uxsgicsh:145"
#define	_MSG_MMX_csh_useexit_DEF_MSG	"Use \"exit\" to leave csh"
#define	_MSG_MMX_csh_useexit_CAT_NUM_STR_DEF_MSG	"uxsgicsh:145:Use \"exit\" to leave csh"
#define	_MSG_MMX_csh_useexit_MSG_NUM_STR_DEF_MSG	":145:Use \"exit\" to leave csh"
#define	_MSG_MMX_csh_useexit_FILE_CAT_NUM	uxsgicsh:145
#define	_SGI_DMMX_csh_useexit	":145"
#define	_SGI_MMX_csh_useexit	"uxsgicsh:145"
#define	_SGI_MMMX_csh_useexit	"uxsgicsh:145:Use \"exit\" to leave csh"
#define	_SGI_SMMX_csh_useexit	"Use \"exit\" to leave csh"
#define	_MSG_MMX_csh_alrdstp_MSG_NUM	146
#define	_MSG_MMX_csh_alrdstp_MSG_NUM_STR	":146"
#define	_MSG_MMX_csh_alrdstp_CAT_NUM_STR	"uxsgicsh:146"
#define	_MSG_MMX_csh_alrdstp_DEF_MSG	"%s: Already stopped"
#define	_MSG_MMX_csh_alrdstp_CAT_NUM_STR_DEF_MSG	"uxsgicsh:146:%s: Already stopped"
#define	_MSG_MMX_csh_alrdstp_MSG_NUM_STR_DEF_MSG	":146:%s: Already stopped"
#define	_MSG_MMX_csh_alrdstp_FILE_CAT_NUM	uxsgicsh:146
#define	_SGI_DMMX_csh_alrdstp	":146"
#define	_SGI_MMX_csh_alrdstp	"uxsgicsh:146"
#define	_SGI_MMMX_csh_alrdstp	"uxsgicsh:146:%s: Already stopped"
#define	_SGI_SMMX_csh_alrdstp	"%s: Already stopped"
#define	_MSG_MMX_csh_ridpat_MSG_NUM	147
#define	_MSG_MMX_csh_ridpat_MSG_NUM_STR	":147"
#define	_MSG_MMX_csh_ridpat_CAT_NUM_STR	"uxsgicsh:147"
#define	_MSG_MMX_csh_ridpat_DEF_MSG	"Ridiculously long path truncated"
#define	_MSG_MMX_csh_ridpat_CAT_NUM_STR_DEF_MSG	"uxsgicsh:147:Ridiculously long path truncated"
#define	_MSG_MMX_csh_ridpat_MSG_NUM_STR_DEF_MSG	":147:Ridiculously long path truncated"
#define	_MSG_MMX_csh_ridpat_FILE_CAT_NUM	uxsgicsh:147
#define	_SGI_DMMX_csh_ridpat	":147"
#define	_SGI_MMX_csh_ridpat	"uxsgicsh:147"
#define	_SGI_MMMX_csh_ridpat	"uxsgicsh:147:Ridiculously long path truncated"
#define	_SGI_SMMX_csh_ridpat	"Ridiculously long path truncated"
#define	_MSG_MMX_csh_badcurdir_MSG_NUM	148
#define	_MSG_MMX_csh_badcurdir_MSG_NUM_STR	":148"
#define	_MSG_MMX_csh_badcurdir_CAT_NUM_STR	"uxsgicsh:148"
#define	_MSG_MMX_csh_badcurdir_DEF_MSG	"Cannot determine current working directory"
#define	_MSG_MMX_csh_badcurdir_CAT_NUM_STR_DEF_MSG	"uxsgicsh:148:Cannot determine current working directory"
#define	_MSG_MMX_csh_badcurdir_MSG_NUM_STR_DEF_MSG	":148:Cannot determine current working directory"
#define	_MSG_MMX_csh_badcurdir_FILE_CAT_NUM	uxsgicsh:148
#define	_SGI_DMMX_csh_badcurdir	":148"
#define	_SGI_MMX_csh_badcurdir	"uxsgicsh:148"
#define	_SGI_MMMX_csh_badcurdir	"uxsgicsh:148:Cannot determine current working directory"
#define	_SGI_SMMX_csh_badcurdir	"Cannot determine current working directory"
