#include <mkmsgs.h>
#define	_MSG_UXSYSADM_1_MSG_NUM	1
#define	_MSG_UXSYSADM_1_MSG_NUM_STR	":1"
#define	_MSG_UXSYSADM_1_CAT_NUM_STR	"uxsysadm:1"
#define	_MSG_UXSYSADM_1_DEF_MSG	"Incorrect usage\n"
#define	_MSG_UXSYSADM_1_CAT_NUM_STR_DEF_MSG	"uxsysadm:1:Incorrect usage\n"
#define	_MSG_UXSYSADM_1_MSG_NUM_STR_DEF_MSG	":1:Incorrect usage\n"
#define	_MSG_UXSYSADM_1_FILE_CAT_NUM	uxsysadm:1
#define	_SGI_DUXSYSADM_1	":1"
#define	_SGI_UXSYSADM_1	"uxsysadm:1"
#define	_SGI_MUXSYSADM_1	"uxsysadm:1:Incorrect usage\n"
#define	_SGI_SUXSYSADM_1	"Incorrect usage\n"
#define	_MSG_UXSYSADM_2_MSG_NUM	2
#define	_MSG_UXSYSADM_2_MSG_NUM_STR	":2"
#define	_MSG_UXSYSADM_2_CAT_NUM_STR	"uxsysadm:2"
#define	_MSG_UXSYSADM_2_DEF_MSG	"Usage: mvdir fromdir newname\n"
#define	_MSG_UXSYSADM_2_CAT_NUM_STR_DEF_MSG	"uxsysadm:2:Usage: mvdir fromdir newname\n"
#define	_MSG_UXSYSADM_2_MSG_NUM_STR_DEF_MSG	":2:Usage: mvdir fromdir newname\n"
#define	_MSG_UXSYSADM_2_FILE_CAT_NUM	uxsysadm:2
#define	_SGI_DUXSYSADM_2	":2"
#define	_SGI_UXSYSADM_2	"uxsysadm:2"
#define	_SGI_MUXSYSADM_2	"uxsysadm:2:Usage: mvdir fromdir newname\n"
#define	_SGI_SUXSYSADM_2	"Usage: mvdir fromdir newname\n"
#define	_MSG_UXSYSADM_3_MSG_NUM	3
#define	_MSG_UXSYSADM_3_MSG_NUM_STR	":3"
#define	_MSG_UXSYSADM_3_CAT_NUM_STR	"uxsysadm:3"
#define	_MSG_UXSYSADM_3_DEF_MSG	"Cannot move '.'\n"
#define	_MSG_UXSYSADM_3_CAT_NUM_STR_DEF_MSG	"uxsysadm:3:Cannot move '.'\n"
#define	_MSG_UXSYSADM_3_MSG_NUM_STR_DEF_MSG	":3:Cannot move '.'\n"
#define	_MSG_UXSYSADM_3_FILE_CAT_NUM	uxsysadm:3
#define	_SGI_DUXSYSADM_3	":3"
#define	_SGI_UXSYSADM_3	"uxsysadm:3"
#define	_SGI_MUXSYSADM_3	"uxsysadm:3:Cannot move '.'\n"
#define	_SGI_SUXSYSADM_3	"Cannot move '.'\n"
#define	_MSG_UXSYSADM_4_MSG_NUM	4
#define	_MSG_UXSYSADM_4_MSG_NUM_STR	":4"
#define	_MSG_UXSYSADM_4_CAT_NUM_STR	"uxsysadm:4"
#define	_MSG_UXSYSADM_4_DEF_MSG	"%s exists\n"
#define	_MSG_UXSYSADM_4_CAT_NUM_STR_DEF_MSG	"uxsysadm:4:%s exists\n"
#define	_MSG_UXSYSADM_4_MSG_NUM_STR_DEF_MSG	":4:%s exists\n"
#define	_MSG_UXSYSADM_4_FILE_CAT_NUM	uxsysadm:4
#define	_SGI_DUXSYSADM_4	":4"
#define	_SGI_UXSYSADM_4	"uxsysadm:4"
#define	_SGI_MUXSYSADM_4	"uxsysadm:4:%s exists\n"
#define	_SGI_SUXSYSADM_4	"%s exists\n"
#define	_MSG_UXSYSADM_5_MSG_NUM	5
#define	_MSG_UXSYSADM_5_MSG_NUM_STR	":5"
#define	_MSG_UXSYSADM_5_CAT_NUM_STR	"uxsysadm:5"
#define	_MSG_UXSYSADM_5_DEF_MSG	"%s must be a directory\n"
#define	_MSG_UXSYSADM_5_CAT_NUM_STR_DEF_MSG	"uxsysadm:5:%s must be a directory\n"
#define	_MSG_UXSYSADM_5_MSG_NUM_STR_DEF_MSG	":5:%s must be a directory\n"
#define	_MSG_UXSYSADM_5_FILE_CAT_NUM	uxsysadm:5
#define	_SGI_DUXSYSADM_5	":5"
#define	_SGI_UXSYSADM_5	"uxsysadm:5"
#define	_SGI_MUXSYSADM_5	"uxsysadm:5:%s must be a directory\n"
#define	_SGI_SUXSYSADM_5	"%s must be a directory\n"
#define	_MSG_UXSYSADM_6_MSG_NUM	6
#define	_MSG_UXSYSADM_6_MSG_NUM_STR	":6"
#define	_MSG_UXSYSADM_6_CAT_NUM_STR	"uxsysadm:6"
#define	_MSG_UXSYSADM_6_DEF_MSG	"Arguments have common path\n"
#define	_MSG_UXSYSADM_6_CAT_NUM_STR_DEF_MSG	"uxsysadm:6:Arguments have common path\n"
#define	_MSG_UXSYSADM_6_MSG_NUM_STR_DEF_MSG	":6:Arguments have common path\n"
#define	_MSG_UXSYSADM_6_FILE_CAT_NUM	uxsysadm:6
#define	_SGI_DUXSYSADM_6	":6"
#define	_SGI_UXSYSADM_6	"uxsysadm:6"
#define	_SGI_MUXSYSADM_6	"uxsysadm:6:Arguments have common path\n"
#define	_SGI_SUXSYSADM_6	"Arguments have common path\n"
#define	_MSG_UXSYSADM_7_MSG_NUM	7
#define	_MSG_UXSYSADM_7_MSG_NUM_STR	":7"
#define	_MSG_UXSYSADM_7_CAT_NUM_STR	"uxsysadm:7"
#define	_MSG_UXSYSADM_7_DEF_MSG	"Cannot link to %s\n"
#define	_MSG_UXSYSADM_7_CAT_NUM_STR_DEF_MSG	"uxsysadm:7:Cannot link to %s\n"
#define	_MSG_UXSYSADM_7_MSG_NUM_STR_DEF_MSG	":7:Cannot link to %s\n"
#define	_MSG_UXSYSADM_7_FILE_CAT_NUM	uxsysadm:7
#define	_SGI_DUXSYSADM_7	":7"
#define	_SGI_UXSYSADM_7	"uxsysadm:7"
#define	_SGI_MUXSYSADM_7	"uxsysadm:7:Cannot link to %s\n"
#define	_SGI_SUXSYSADM_7	"Cannot link to %s\n"
#define	_MSG_UXSYSADM_8_MSG_NUM	8
#define	_MSG_UXSYSADM_8_MSG_NUM_STR	":8"
#define	_MSG_UXSYSADM_8_CAT_NUM_STR	"uxsysadm:8"
#define	_MSG_UXSYSADM_8_DEF_MSG	"using default CSWIDTH.\n"
#define	_MSG_UXSYSADM_8_CAT_NUM_STR_DEF_MSG	"uxsysadm:8:using default CSWIDTH.\n"
#define	_MSG_UXSYSADM_8_MSG_NUM_STR_DEF_MSG	":8:using default CSWIDTH.\n"
#define	_MSG_UXSYSADM_8_FILE_CAT_NUM	uxsysadm:8
#define	_SGI_DUXSYSADM_8	":8"
#define	_SGI_UXSYSADM_8	"uxsysadm:8"
#define	_SGI_MUXSYSADM_8	"uxsysadm:8:using default CSWIDTH.\n"
#define	_SGI_SUXSYSADM_8	"using default CSWIDTH.\n"
#define	_MSG_UXSYSADM_9_MSG_NUM	9
#define	_MSG_UXSYSADM_9_MSG_NUM_STR	":9"
#define	_MSG_UXSYSADM_9_CAT_NUM_STR	"uxsysadm:9"
#define	_MSG_UXSYSADM_9_DEF_MSG	"Usage: eucset [ cswidth ]\n       eucset -p\n"
#define	_MSG_UXSYSADM_9_CAT_NUM_STR_DEF_MSG	"uxsysadm:9:Usage: eucset [ cswidth ]\n       eucset -p\n"
#define	_MSG_UXSYSADM_9_MSG_NUM_STR_DEF_MSG	":9:Usage: eucset [ cswidth ]\n       eucset -p\n"
#define	_MSG_UXSYSADM_9_FILE_CAT_NUM	uxsysadm:9
#define	_SGI_DUXSYSADM_9	":9"
#define	_SGI_UXSYSADM_9	"uxsysadm:9"
#define	_SGI_MUXSYSADM_9	"uxsysadm:9:Usage: eucset [ cswidth ]\n       eucset -p\n"
#define	_SGI_SUXSYSADM_9	"Usage: eucset [ cswidth ]\n       eucset -p\n"
#define	_MSG_UXSYSADM_10_MSG_NUM	10
#define	_MSG_UXSYSADM_10_MSG_NUM_STR	":10"
#define	_MSG_UXSYSADM_10_CAT_NUM_STR	"uxsysadm:10"
#define	_MSG_UXSYSADM_10_DEF_MSG	"%s failed\n"
#define	_MSG_UXSYSADM_10_CAT_NUM_STR_DEF_MSG	"uxsysadm:10:%s failed\n"
#define	_MSG_UXSYSADM_10_MSG_NUM_STR_DEF_MSG	":10:%s failed\n"
#define	_MSG_UXSYSADM_10_FILE_CAT_NUM	uxsysadm:10
#define	_SGI_DUXSYSADM_10	":10"
#define	_SGI_UXSYSADM_10	"uxsysadm:10"
#define	_SGI_MUXSYSADM_10	"uxsysadm:10:%s failed\n"
#define	_SGI_SUXSYSADM_10	"%s failed\n"
#define	_MSG_UXSYSADM_11_MSG_NUM	11
#define	_MSG_UXSYSADM_11_MSG_NUM_STR	":11"
#define	_MSG_UXSYSADM_11_CAT_NUM_STR	"uxsysadm:11"
#define	_MSG_UXSYSADM_11_DEF_MSG	"bad cswidth format\n"
#define	_MSG_UXSYSADM_11_CAT_NUM_STR_DEF_MSG	"uxsysadm:11:bad cswidth format\n"
#define	_MSG_UXSYSADM_11_MSG_NUM_STR_DEF_MSG	":11:bad cswidth format\n"
#define	_MSG_UXSYSADM_11_FILE_CAT_NUM	uxsysadm:11
#define	_SGI_DUXSYSADM_11	":11"
#define	_SGI_UXSYSADM_11	"uxsysadm:11"
#define	_SGI_MUXSYSADM_11	"uxsysadm:11:bad cswidth format\n"
#define	_SGI_SUXSYSADM_11	"bad cswidth format\n"
#define	_MSG_UXSYSADM_12_MSG_NUM	12
#define	_MSG_UXSYSADM_12_MSG_NUM_STR	":12"
#define	_MSG_UXSYSADM_12_CAT_NUM_STR	"uxsysadm:12"
#define	_MSG_UXSYSADM_12_DEF_MSG	"Usage: wchrtbl [-n] [-s] [ - | file ] "
#define	_MSG_UXSYSADM_12_CAT_NUM_STR_DEF_MSG	"uxsysadm:12:Usage: wchrtbl [-n] [-s] [ - | file ] "
#define	_MSG_UXSYSADM_12_MSG_NUM_STR_DEF_MSG	":12:Usage: wchrtbl [-n] [-s] [ - | file ] "
#define	_MSG_UXSYSADM_12_FILE_CAT_NUM	uxsysadm:12
#define	_SGI_DUXSYSADM_12	":12"
#define	_SGI_UXSYSADM_12	"uxsysadm:12"
#define	_SGI_MUXSYSADM_12	"uxsysadm:12:Usage: wchrtbl [-n] [-s] [ - | file ] "
#define	_SGI_SUXSYSADM_12	"Usage: wchrtbl [-n] [-s] [ - | file ] "
#define	_MSG_UXSYSADM_13_MSG_NUM	13
#define	_MSG_UXSYSADM_13_MSG_NUM_STR	":13"
#define	_MSG_UXSYSADM_13_CAT_NUM_STR	"uxsysadm:13"
#define	_MSG_UXSYSADM_13_DEF_MSG	"%s: name of output file for \"LC_CTYPE\" is not specified"
#define	_MSG_UXSYSADM_13_CAT_NUM_STR_DEF_MSG	"uxsysadm:13:%s: name of output file for \"LC_CTYPE\" is not specified"
#define	_MSG_UXSYSADM_13_MSG_NUM_STR_DEF_MSG	":13:%s: name of output file for \"LC_CTYPE\" is not specified"
#define	_MSG_UXSYSADM_13_FILE_CAT_NUM	uxsysadm:13
#define	_SGI_DUXSYSADM_13	":13"
#define	_SGI_UXSYSADM_13	"uxsysadm:13"
#define	_SGI_MUXSYSADM_13	"uxsysadm:13:%s: name of output file for \"LC_CTYPE\" is not specified"
#define	_SGI_SUXSYSADM_13	"%s: name of output file for \"LC_CTYPE\" is not specified"
#define	_MSG_UXSYSADM_14_MSG_NUM	14
#define	_MSG_UXSYSADM_14_MSG_NUM_STR	":14"
#define	_MSG_UXSYSADM_14_CAT_NUM_STR	"uxsysadm:14"
#define	_MSG_UXSYSADM_14_DEF_MSG	"%s: incorrect character class name \"%s\""
#define	_MSG_UXSYSADM_14_CAT_NUM_STR_DEF_MSG	"uxsysadm:14:%s: incorrect character class name \"%s\""
#define	_MSG_UXSYSADM_14_MSG_NUM_STR_DEF_MSG	":14:%s: incorrect character class name \"%s\""
#define	_MSG_UXSYSADM_14_FILE_CAT_NUM	uxsysadm:14
#define	_SGI_DUXSYSADM_14	":14"
#define	_SGI_UXSYSADM_14	"uxsysadm:14"
#define	_SGI_MUXSYSADM_14	"uxsysadm:14:%s: incorrect character class name \"%s\""
#define	_SGI_SUXSYSADM_14	"%s: incorrect character class name \"%s\""
#define	_MSG_UXSYSADM_15_MSG_NUM	15
#define	_MSG_UXSYSADM_15_MSG_NUM_STR	":15"
#define	_MSG_UXSYSADM_15_CAT_NUM_STR	"uxsysadm:15"
#define	_MSG_UXSYSADM_15_DEF_MSG	"%s: --- %s --- left angle bracket  \"<\" is missing"
#define	_MSG_UXSYSADM_15_CAT_NUM_STR_DEF_MSG	"uxsysadm:15:%s: --- %s --- left angle bracket  \"<\" is missing"
#define	_MSG_UXSYSADM_15_MSG_NUM_STR_DEF_MSG	":15:%s: --- %s --- left angle bracket  \"<\" is missing"
#define	_MSG_UXSYSADM_15_FILE_CAT_NUM	uxsysadm:15
#define	_SGI_DUXSYSADM_15	":15"
#define	_SGI_UXSYSADM_15	"uxsysadm:15"
#define	_SGI_MUXSYSADM_15	"uxsysadm:15:%s: --- %s --- left angle bracket  \"<\" is missing"
#define	_SGI_SUXSYSADM_15	"%s: --- %s --- left angle bracket  \"<\" is missing"
#define	_MSG_UXSYSADM_16_MSG_NUM	16
#define	_MSG_UXSYSADM_16_MSG_NUM_STR	":16"
#define	_MSG_UXSYSADM_16_CAT_NUM_STR	"uxsysadm:16"
#define	_MSG_UXSYSADM_16_DEF_MSG	"%s: --- %s --- right angle bracket  \">\" is missing"
#define	_MSG_UXSYSADM_16_CAT_NUM_STR_DEF_MSG	"uxsysadm:16:%s: --- %s --- right angle bracket  \">\" is missing"
#define	_MSG_UXSYSADM_16_MSG_NUM_STR_DEF_MSG	":16:%s: --- %s --- right angle bracket  \">\" is missing"
#define	_MSG_UXSYSADM_16_FILE_CAT_NUM	uxsysadm:16
#define	_SGI_DUXSYSADM_16	":16"
#define	_SGI_UXSYSADM_16	"uxsysadm:16"
#define	_SGI_MUXSYSADM_16	"uxsysadm:16:%s: --- %s --- right angle bracket  \">\" is missing"
#define	_SGI_SUXSYSADM_16	"%s: --- %s --- right angle bracket  \">\" is missing"
#define	_MSG_UXSYSADM_17_MSG_NUM	17
#define	_MSG_UXSYSADM_17_MSG_NUM_STR	":17"
#define	_MSG_UXSYSADM_17_CAT_NUM_STR	"uxsysadm:17"
#define	_MSG_UXSYSADM_17_DEF_MSG	"%s: --- %s --- wrong input specification \"%s\""
#define	_MSG_UXSYSADM_17_CAT_NUM_STR_DEF_MSG	"uxsysadm:17:%s: --- %s --- wrong input specification \"%s\""
#define	_MSG_UXSYSADM_17_MSG_NUM_STR_DEF_MSG	":17:%s: --- %s --- wrong input specification \"%s\""
#define	_MSG_UXSYSADM_17_FILE_CAT_NUM	uxsysadm:17
#define	_SGI_DUXSYSADM_17	":17"
#define	_SGI_UXSYSADM_17	"uxsysadm:17"
#define	_SGI_MUXSYSADM_17	"uxsysadm:17:%s: --- %s --- wrong input specification \"%s\""
#define	_SGI_SUXSYSADM_17	"%s: --- %s --- wrong input specification \"%s\""
#define	_MSG_UXSYSADM_18_MSG_NUM	18
#define	_MSG_UXSYSADM_18_MSG_NUM_STR	":18"
#define	_MSG_UXSYSADM_18_CAT_NUM_STR	"uxsysadm:18"
#define	_MSG_UXSYSADM_18_DEF_MSG	"%s: --- %s --- number out of range \"%s\""
#define	_MSG_UXSYSADM_18_CAT_NUM_STR_DEF_MSG	"uxsysadm:18:%s: --- %s --- number out of range \"%s\""
#define	_MSG_UXSYSADM_18_MSG_NUM_STR_DEF_MSG	":18:%s: --- %s --- number out of range \"%s\""
#define	_MSG_UXSYSADM_18_FILE_CAT_NUM	uxsysadm:18
#define	_SGI_DUXSYSADM_18	":18"
#define	_SGI_UXSYSADM_18	"uxsysadm:18"
#define	_SGI_MUXSYSADM_18	"uxsysadm:18:%s: --- %s --- number out of range \"%s\""
#define	_SGI_SUXSYSADM_18	"%s: --- %s --- number out of range \"%s\""
#define	_MSG_UXSYSADM_19_MSG_NUM	19
#define	_MSG_UXSYSADM_19_MSG_NUM_STR	":19"
#define	_MSG_UXSYSADM_19_CAT_NUM_STR	"uxsysadm:19"
#define	_MSG_UXSYSADM_19_DEF_MSG	"%s: --- %s --- nonblank character after (\"\\\") on the same line"
#define	_MSG_UXSYSADM_19_CAT_NUM_STR_DEF_MSG	"uxsysadm:19:%s: --- %s --- nonblank character after (\"\\\") on the same line"
#define	_MSG_UXSYSADM_19_MSG_NUM_STR_DEF_MSG	":19:%s: --- %s --- nonblank character after (\"\\\") on the same line"
#define	_MSG_UXSYSADM_19_FILE_CAT_NUM	uxsysadm:19
#define	_SGI_DUXSYSADM_19	":19"
#define	_SGI_UXSYSADM_19	"uxsysadm:19"
#define	_SGI_MUXSYSADM_19	"uxsysadm:19:%s: --- %s --- nonblank character after (\"\\\") on the same line"
#define	_SGI_SUXSYSADM_19	"%s: --- %s --- nonblank character after (\"\\\") on the same line"
#define	_MSG_UXSYSADM_20_MSG_NUM	20
#define	_MSG_UXSYSADM_20_MSG_NUM_STR	":20"
#define	_MSG_UXSYSADM_20_CAT_NUM_STR	"uxsysadm:20"
#define	_MSG_UXSYSADM_20_DEF_MSG	"%s: --- %s --- wrong upper limit \"%s\""
#define	_MSG_UXSYSADM_20_CAT_NUM_STR_DEF_MSG	"uxsysadm:20:%s: --- %s --- wrong upper limit \"%s\""
#define	_MSG_UXSYSADM_20_MSG_NUM_STR_DEF_MSG	":20:%s: --- %s --- wrong upper limit \"%s\""
#define	_MSG_UXSYSADM_20_FILE_CAT_NUM	uxsysadm:20
#define	_SGI_DUXSYSADM_20	":20"
#define	_SGI_UXSYSADM_20	"uxsysadm:20"
#define	_SGI_MUXSYSADM_20	"uxsysadm:20:%s: --- %s --- wrong upper limit \"%s\""
#define	_SGI_SUXSYSADM_20	"%s: --- %s --- wrong upper limit \"%s\""
#define	_MSG_UXSYSADM_21_MSG_NUM	21
#define	_MSG_UXSYSADM_21_MSG_NUM_STR	":21"
#define	_MSG_UXSYSADM_21_CAT_NUM_STR	"uxsysadm:21"
#define	_MSG_UXSYSADM_21_DEF_MSG	"%s: --- %s --- wrong character \"%c\""
#define	_MSG_UXSYSADM_21_CAT_NUM_STR_DEF_MSG	"uxsysadm:21:%s: --- %s --- wrong character \"%c\""
#define	_MSG_UXSYSADM_21_MSG_NUM_STR_DEF_MSG	":21:%s: --- %s --- wrong character \"%c\""
#define	_MSG_UXSYSADM_21_FILE_CAT_NUM	uxsysadm:21
#define	_SGI_DUXSYSADM_21	":21"
#define	_SGI_UXSYSADM_21	"uxsysadm:21"
#define	_SGI_MUXSYSADM_21	"uxsysadm:21:%s: --- %s --- wrong character \"%c\""
#define	_SGI_SUXSYSADM_21	"%s: --- %s --- wrong character \"%c\""
#define	_MSG_UXSYSADM_22_MSG_NUM	22
#define	_MSG_UXSYSADM_22_MSG_NUM_STR	":22"
#define	_MSG_UXSYSADM_22_CAT_NUM_STR	"uxsysadm:22"
#define	_MSG_UXSYSADM_22_DEF_MSG	"%s: --- %s --- number expected"
#define	_MSG_UXSYSADM_22_CAT_NUM_STR_DEF_MSG	"uxsysadm:22:%s: --- %s --- number expected"
#define	_MSG_UXSYSADM_22_MSG_NUM_STR_DEF_MSG	":22:%s: --- %s --- number expected"
#define	_MSG_UXSYSADM_22_FILE_CAT_NUM	uxsysadm:22
#define	_SGI_DUXSYSADM_22	":22"
#define	_SGI_UXSYSADM_22	"uxsysadm:22"
#define	_SGI_MUXSYSADM_22	"uxsysadm:22:%s: --- %s --- number expected"
#define	_SGI_SUXSYSADM_22	"%s: --- %s --- number expected"
#define	_MSG_UXSYSADM_23_MSG_NUM	23
#define	_MSG_UXSYSADM_23_MSG_NUM_STR	":23"
#define	_MSG_UXSYSADM_23_CAT_NUM_STR	"uxsysadm:23"
#define	_MSG_UXSYSADM_23_DEF_MSG	"%s: --- %s --- too many range \"-\" characters"
#define	_MSG_UXSYSADM_23_CAT_NUM_STR_DEF_MSG	"uxsysadm:23:%s: --- %s --- too many range \"-\" characters"
#define	_MSG_UXSYSADM_23_MSG_NUM_STR_DEF_MSG	":23:%s: --- %s --- too many range \"-\" characters"
#define	_MSG_UXSYSADM_23_FILE_CAT_NUM	uxsysadm:23
#define	_SGI_DUXSYSADM_23	":23"
#define	_SGI_UXSYSADM_23	"uxsysadm:23"
#define	_SGI_MUXSYSADM_23	"uxsysadm:23:%s: --- %s --- too many range \"-\" characters"
#define	_SGI_SUXSYSADM_23	"%s: --- %s --- too many range \"-\" characters"
#define	_MSG_UXSYSADM_24_MSG_NUM	24
#define	_MSG_UXSYSADM_24_MSG_NUM_STR	":24"
#define	_MSG_UXSYSADM_24_CAT_NUM_STR	"uxsysadm:24"
#define	_MSG_UXSYSADM_24_DEF_MSG	"%s: --- %s --- wrong specification, %s"
#define	_MSG_UXSYSADM_24_CAT_NUM_STR_DEF_MSG	"uxsysadm:24:%s: --- %s --- wrong specification, %s"
#define	_MSG_UXSYSADM_24_MSG_NUM_STR_DEF_MSG	":24:%s: --- %s --- wrong specification, %s"
#define	_MSG_UXSYSADM_24_FILE_CAT_NUM	uxsysadm:24
#define	_SGI_DUXSYSADM_24	":24"
#define	_SGI_UXSYSADM_24	"uxsysadm:24"
#define	_SGI_MUXSYSADM_24	"uxsysadm:24:%s: --- %s --- wrong specification, %s"
#define	_SGI_SUXSYSADM_24	"%s: --- %s --- wrong specification, %s"
#define	_MSG_UXSYSADM_25_MSG_NUM	25
#define	_MSG_UXSYSADM_25_MSG_NUM_STR	":25"
#define	_MSG_UXSYSADM_25_CAT_NUM_STR	"uxsysadm:25"
#define	_MSG_UXSYSADM_25_DEF_MSG	"malloc error"
#define	_MSG_UXSYSADM_25_CAT_NUM_STR_DEF_MSG	"uxsysadm:25:malloc error"
#define	_MSG_UXSYSADM_25_MSG_NUM_STR_DEF_MSG	":25:malloc error"
#define	_MSG_UXSYSADM_25_FILE_CAT_NUM	uxsysadm:25
#define	_SGI_DUXSYSADM_25	":25"
#define	_SGI_UXSYSADM_25	"uxsysadm:25"
#define	_SGI_MUXSYSADM_25	"uxsysadm:25:malloc error"
#define	_SGI_SUXSYSADM_25	"malloc error"
#define	_MSG_UXSYSADM_26_MSG_NUM	26
#define	_MSG_UXSYSADM_26_MSG_NUM_STR	":26"
#define	_MSG_UXSYSADM_26_CAT_NUM_STR	"uxsysadm:26"
#define	_MSG_UXSYSADM_26_DEF_MSG	"%s: --- %s --- wrong specification"
#define	_MSG_UXSYSADM_26_CAT_NUM_STR_DEF_MSG	"uxsysadm:26:%s: --- %s --- wrong specification"
#define	_MSG_UXSYSADM_26_MSG_NUM_STR_DEF_MSG	":26:%s: --- %s --- wrong specification"
#define	_MSG_UXSYSADM_26_FILE_CAT_NUM	uxsysadm:26
#define	_SGI_DUXSYSADM_26	":26"
#define	_SGI_UXSYSADM_26	"uxsysadm:26"
#define	_SGI_MUXSYSADM_26	"uxsysadm:26:%s: --- %s --- wrong specification"
#define	_SGI_SUXSYSADM_26	"%s: --- %s --- wrong specification"
#define	_MSG_UXSYSADM_27_MSG_NUM	27
#define	_MSG_UXSYSADM_27_MSG_NUM_STR	":27"
#define	_MSG_UXSYSADM_27_CAT_NUM_STR	"uxsysadm:27"
#define	_MSG_UXSYSADM_27_DEF_MSG	"%s: name of output file for \"LC_NUMERIC\" is not specified"
#define	_MSG_UXSYSADM_27_CAT_NUM_STR_DEF_MSG	"uxsysadm:27:%s: name of output file for \"LC_NUMERIC\" is not specified"
#define	_MSG_UXSYSADM_27_MSG_NUM_STR_DEF_MSG	":27:%s: name of output file for \"LC_NUMERIC\" is not specified"
#define	_MSG_UXSYSADM_27_FILE_CAT_NUM	uxsysadm:27
#define	_SGI_DUXSYSADM_27	":27"
#define	_SGI_UXSYSADM_27	"uxsysadm:27"
#define	_SGI_MUXSYSADM_27	"uxsysadm:27:%s: name of output file for \"LC_NUMERIC\" is not specified"
#define	_SGI_SUXSYSADM_27	"%s: name of output file for \"LC_NUMERIC\" is not specified"
#define	_MSG_UXSYSADM_28_MSG_NUM	28
#define	_MSG_UXSYSADM_28_MSG_NUM_STR	":28"
#define	_MSG_UXSYSADM_28_CAT_NUM_STR	"uxsysadm:28"
#define	_MSG_UXSYSADM_28_DEF_MSG	"%s: \"decimal_point\" or \"thousands_sep\" must be specified"
#define	_MSG_UXSYSADM_28_CAT_NUM_STR_DEF_MSG	"uxsysadm:28:%s: \"decimal_point\" or \"thousands_sep\" must be specified"
#define	_MSG_UXSYSADM_28_MSG_NUM_STR_DEF_MSG	":28:%s: \"decimal_point\" or \"thousands_sep\" must be specified"
#define	_MSG_UXSYSADM_28_FILE_CAT_NUM	uxsysadm:28
#define	_SGI_DUXSYSADM_28	":28"
#define	_SGI_UXSYSADM_28	"uxsysadm:28"
#define	_SGI_MUXSYSADM_28	"uxsysadm:28:%s: \"decimal_point\" or \"thousands_sep\" must be specified"
#define	_SGI_SUXSYSADM_28	"%s: \"decimal_point\" or \"thousands_sep\" must be specified"
#define	_MSG_UXSYSADM_29_MSG_NUM	29
#define	_MSG_UXSYSADM_29_MSG_NUM_STR	":29"
#define	_MSG_UXSYSADM_29_CAT_NUM_STR	"uxsysadm:29"
#define	_MSG_UXSYSADM_29_DEF_MSG	"%s: character classification and conversion information must be specified"
#define	_MSG_UXSYSADM_29_CAT_NUM_STR_DEF_MSG	"uxsysadm:29:%s: character classification and conversion information must be specified"
#define	_MSG_UXSYSADM_29_MSG_NUM_STR_DEF_MSG	":29:%s: character classification and conversion information must be specified"
#define	_MSG_UXSYSADM_29_FILE_CAT_NUM	uxsysadm:29
#define	_SGI_DUXSYSADM_29	":29"
#define	_SGI_UXSYSADM_29	"uxsysadm:29"
#define	_SGI_MUXSYSADM_29	"uxsysadm:29:%s: character classification and conversion information must be specified"
#define	_SGI_SUXSYSADM_29	"%s: character classification and conversion information must be specified"
#define	_MSG_UXSYSADM_30_MSG_NUM	30
#define	_MSG_UXSYSADM_30_MSG_NUM_STR	":30"
#define	_MSG_UXSYSADM_30_CAT_NUM_STR	"uxsysadm:30"
#define	_MSG_UXSYSADM_30_DEF_MSG	"%s: same output file name used in \"LC_CTYPE\" and \"LC_NUMERIC\""
#define	_MSG_UXSYSADM_30_CAT_NUM_STR_DEF_MSG	"uxsysadm:30:%s: same output file name used in \"LC_CTYPE\" and \"LC_NUMERIC\""
#define	_MSG_UXSYSADM_30_MSG_NUM_STR_DEF_MSG	":30:%s: same output file name used in \"LC_CTYPE\" and \"LC_NUMERIC\""
#define	_MSG_UXSYSADM_30_FILE_CAT_NUM	uxsysadm:30
#define	_SGI_DUXSYSADM_30	":30"
#define	_SGI_UXSYSADM_30	"uxsysadm:30"
#define	_SGI_MUXSYSADM_30	"uxsysadm:30:%s: same output file name used in \"LC_CTYPE\" and \"LC_NUMERIC\""
#define	_SGI_SUXSYSADM_30	"%s: same output file name used in \"LC_CTYPE\" and \"LC_NUMERIC\""
#define	_MSG_UXSYSADM_31_MSG_NUM	31
#define	_MSG_UXSYSADM_31_MSG_NUM_STR	":31"
#define	_MSG_UXSYSADM_31_CAT_NUM_STR	"uxsysadm:31"
#define	_MSG_UXSYSADM_31_DEF_MSG	"%s: character class \"LC_CTYPE%d\" duplicated"
#define	_MSG_UXSYSADM_31_CAT_NUM_STR_DEF_MSG	"uxsysadm:31:%s: character class \"LC_CTYPE%d\" duplicated"
#define	_MSG_UXSYSADM_31_MSG_NUM_STR_DEF_MSG	":31:%s: character class \"LC_CTYPE%d\" duplicated"
#define	_MSG_UXSYSADM_31_FILE_CAT_NUM	uxsysadm:31
#define	_SGI_DUXSYSADM_31	":31"
#define	_SGI_UXSYSADM_31	"uxsysadm:31"
#define	_SGI_MUXSYSADM_31	"uxsysadm:31:%s: character class \"LC_CTYPE%d\" duplicated"
#define	_SGI_SUXSYSADM_31	"%s: character class \"LC_CTYPE%d\" duplicated"
#define	_MSG_UXSYSADM_32_MSG_NUM	32
#define	_MSG_UXSYSADM_32_MSG_NUM_STR	":32"
#define	_MSG_UXSYSADM_32_CAT_NUM_STR	"uxsysadm:32"
#define	_MSG_UXSYSADM_32_DEF_MSG	"%s: character class table \"LC_CTYPE%d\" exhausted"
#define	_MSG_UXSYSADM_32_CAT_NUM_STR_DEF_MSG	"uxsysadm:32:%s: character class table \"LC_CTYPE%d\" exhausted"
#define	_MSG_UXSYSADM_32_MSG_NUM_STR_DEF_MSG	":32:%s: character class table \"LC_CTYPE%d\" exhausted"
#define	_MSG_UXSYSADM_32_FILE_CAT_NUM	uxsysadm:32
#define	_SGI_DUXSYSADM_32	":32"
#define	_SGI_UXSYSADM_32	"uxsysadm:32"
#define	_SGI_MUXSYSADM_32	"uxsysadm:32:%s: character class table \"LC_CTYPE%d\" exhausted"
#define	_SGI_SUXSYSADM_32	"%s: character class table \"LC_CTYPE%d\" exhausted"
#define	_MSG_UXSYSADM_33_MSG_NUM	33
#define	_MSG_UXSYSADM_33_MSG_NUM_STR	":33"
#define	_MSG_UXSYSADM_33_CAT_NUM_STR	"uxsysadm:33"
#define	_MSG_UXSYSADM_33_DEF_MSG	"standard input"
#define	_MSG_UXSYSADM_33_CAT_NUM_STR_DEF_MSG	"uxsysadm:33:standard input"
#define	_MSG_UXSYSADM_33_MSG_NUM_STR_DEF_MSG	":33:standard input"
#define	_MSG_UXSYSADM_33_FILE_CAT_NUM	uxsysadm:33
#define	_SGI_DUXSYSADM_33	":33"
#define	_SGI_UXSYSADM_33	"uxsysadm:33"
#define	_SGI_MUXSYSADM_33	"uxsysadm:33:standard input"
#define	_SGI_SUXSYSADM_33	"standard input"
#define	_MSG_UXSYSADM_34_MSG_NUM	34
#define	_MSG_UXSYSADM_34_MSG_NUM_STR	":34"
#define	_MSG_UXSYSADM_34_CAT_NUM_STR	"uxsysadm:34"
#define	_MSG_UXSYSADM_34_DEF_MSG	"Idx (%d) too large...\n"
#define	_MSG_UXSYSADM_34_CAT_NUM_STR_DEF_MSG	"uxsysadm:34:Idx (%d) too large...\n"
#define	_MSG_UXSYSADM_34_MSG_NUM_STR_DEF_MSG	":34:Idx (%d) too large...\n"
#define	_MSG_UXSYSADM_34_FILE_CAT_NUM	uxsysadm:34
#define	_SGI_DUXSYSADM_34	":34"
#define	_SGI_UXSYSADM_34	"uxsysadm:34"
#define	_SGI_MUXSYSADM_34	"uxsysadm:34:Idx (%d) too large...\n"
#define	_SGI_SUXSYSADM_34	"Idx (%d) too large...\n"
#define	_MSG_UXSYSADM_35_MSG_NUM	35
#define	_MSG_UXSYSADM_35_MSG_NUM_STR	":35"
#define	_MSG_UXSYSADM_35_CAT_NUM_STR	"uxsysadm:35"
#define	_MSG_UXSYSADM_35_DEF_MSG	"\n\t/* multiple byte character width information */\n\n"
#define	_MSG_UXSYSADM_35_CAT_NUM_STR_DEF_MSG	"uxsysadm:35:\n\t/* multiple byte character width information */\n\n"
#define	_MSG_UXSYSADM_35_MSG_NUM_STR_DEF_MSG	":35:\n\t/* multiple byte character width information */\n\n"
#define	_MSG_UXSYSADM_35_FILE_CAT_NUM	uxsysadm:35
#define	_SGI_DUXSYSADM_35	":35"
#define	_SGI_UXSYSADM_35	"uxsysadm:35"
#define	_SGI_MUXSYSADM_35	"uxsysadm:35:\n\t/* multiple byte character width information */\n\n"
#define	_SGI_SUXSYSADM_35	"\n\t/* multiple byte character width information */\n\n"
#define	_MSG_UXSYSADM_36_MSG_NUM	36
#define	_MSG_UXSYSADM_36_MSG_NUM_STR	":36"
#define	_MSG_UXSYSADM_36_CAT_NUM_STR	"uxsysadm:36"
#define	_MSG_UXSYSADM_36_DEF_MSG	"\t *		%s  CHARACTER  SET                \n"
#define	_MSG_UXSYSADM_36_CAT_NUM_STR_DEF_MSG	"uxsysadm:36:\t *		%s  CHARACTER  SET                \n"
#define	_MSG_UXSYSADM_36_MSG_NUM_STR_DEF_MSG	":36:\t *		%s  CHARACTER  SET                \n"
#define	_MSG_UXSYSADM_36_FILE_CAT_NUM	uxsysadm:36
#define	_SGI_DUXSYSADM_36	":36"
#define	_SGI_UXSYSADM_36	"uxsysadm:36"
#define	_SGI_MUXSYSADM_36	"uxsysadm:36:\t *		%s  CHARACTER  SET                \n"
#define	_SGI_SUXSYSADM_36	"\t *		%s  CHARACTER  SET                \n"
#define	_MSG_UXSYSADM_37_MSG_NUM	37
#define	_MSG_UXSYSADM_37_MSG_NUM_STR	":37"
#define	_MSG_UXSYSADM_37_CAT_NUM_STR	"uxsysadm:37"
#define	_MSG_UXSYSADM_37_DEF_MSG	"\t/* The first 257 characters are used to determine\n"
#define	_MSG_UXSYSADM_37_CAT_NUM_STR_DEF_MSG	"uxsysadm:37:\t/* The first 257 characters are used to determine\n"
#define	_MSG_UXSYSADM_37_MSG_NUM_STR_DEF_MSG	":37:\t/* The first 257 characters are used to determine\n"
#define	_MSG_UXSYSADM_37_FILE_CAT_NUM	uxsysadm:37
#define	_SGI_DUXSYSADM_37	":37"
#define	_SGI_UXSYSADM_37	"uxsysadm:37"
#define	_SGI_MUXSYSADM_37	"uxsysadm:37:\t/* The first 257 characters are used to determine\n"
#define	_SGI_SUXSYSADM_37	"\t/* The first 257 characters are used to determine\n"
#define	_MSG_UXSYSADM_38_MSG_NUM	38
#define	_MSG_UXSYSADM_38_MSG_NUM_STR	":38"
#define	_MSG_UXSYSADM_38_CAT_NUM_STR	"uxsysadm:38"
#define	_MSG_UXSYSADM_38_DEF_MSG	"\t * the character class */\n\n"
#define	_MSG_UXSYSADM_38_CAT_NUM_STR_DEF_MSG	"uxsysadm:38:\t * the character class */\n\n"
#define	_MSG_UXSYSADM_38_MSG_NUM_STR_DEF_MSG	":38:\t * the character class */\n\n"
#define	_MSG_UXSYSADM_38_FILE_CAT_NUM	uxsysadm:38
#define	_SGI_DUXSYSADM_38	":38"
#define	_SGI_UXSYSADM_38	"uxsysadm:38"
#define	_SGI_MUXSYSADM_38	"uxsysadm:38:\t * the character class */\n\n"
#define	_SGI_SUXSYSADM_38	"\t * the character class */\n\n"
#define	_MSG_UXSYSADM_39_MSG_NUM	39
#define	_MSG_UXSYSADM_39_MSG_NUM_STR	":39"
#define	_MSG_UXSYSADM_39_CAT_NUM_STR	"uxsysadm:39"
#define	_MSG_UXSYSADM_39_DEF_MSG	"\n\n\t/* The next 257 characters are used for \n"
#define	_MSG_UXSYSADM_39_CAT_NUM_STR_DEF_MSG	"uxsysadm:39:\n\n\t/* The next 257 characters are used for \n"
#define	_MSG_UXSYSADM_39_MSG_NUM_STR_DEF_MSG	":39:\n\n\t/* The next 257 characters are used for \n"
#define	_MSG_UXSYSADM_39_FILE_CAT_NUM	uxsysadm:39
#define	_SGI_DUXSYSADM_39	":39"
#define	_SGI_UXSYSADM_39	"uxsysadm:39"
#define	_SGI_MUXSYSADM_39	"uxsysadm:39:\n\n\t/* The next 257 characters are used for \n"
#define	_SGI_SUXSYSADM_39	"\n\n\t/* The next 257 characters are used for \n"
#define	_MSG_UXSYSADM_40_MSG_NUM	40
#define	_MSG_UXSYSADM_40_MSG_NUM_STR	":40"
#define	_MSG_UXSYSADM_40_CAT_NUM_STR	"uxsysadm:40"
#define	_MSG_UXSYSADM_40_DEF_MSG	"\t * upper-to-lower and lower-to-upper conversion */\n\n"
#define	_MSG_UXSYSADM_40_CAT_NUM_STR_DEF_MSG	"uxsysadm:40:\t * upper-to-lower and lower-to-upper conversion */\n\n"
#define	_MSG_UXSYSADM_40_MSG_NUM_STR_DEF_MSG	":40:\t * upper-to-lower and lower-to-upper conversion */\n\n"
#define	_MSG_UXSYSADM_40_FILE_CAT_NUM	uxsysadm:40
#define	_SGI_DUXSYSADM_40	":40"
#define	_SGI_UXSYSADM_40	"uxsysadm:40"
#define	_SGI_MUXSYSADM_40	"uxsysadm:40:\t * upper-to-lower and lower-to-upper conversion */\n\n"
#define	_SGI_SUXSYSADM_40	"\t * upper-to-lower and lower-to-upper conversion */\n\n"
#define	_MSG_UXSYSADM_41_MSG_NUM	41
#define	_MSG_UXSYSADM_41_MSG_NUM_STR	":41"
#define	_MSG_UXSYSADM_41_CAT_NUM_STR	"uxsysadm:41"
#define	_MSG_UXSYSADM_41_DEF_MSG	"\n\n\t/*  CSWIDTH INFORMATION                           */\n"
#define	_MSG_UXSYSADM_41_CAT_NUM_STR_DEF_MSG	"uxsysadm:41:\n\n\t/*  CSWIDTH INFORMATION                           */\n"
#define	_MSG_UXSYSADM_41_MSG_NUM_STR_DEF_MSG	":41:\n\n\t/*  CSWIDTH INFORMATION                           */\n"
#define	_MSG_UXSYSADM_41_FILE_CAT_NUM	uxsysadm:41
#define	_SGI_DUXSYSADM_41	":41"
#define	_SGI_UXSYSADM_41	"uxsysadm:41"
#define	_SGI_MUXSYSADM_41	"uxsysadm:41:\n\n\t/*  CSWIDTH INFORMATION                           */\n"
#define	_SGI_SUXSYSADM_41	"\n\n\t/*  CSWIDTH INFORMATION                           */\n"
#define	_MSG_UXSYSADM_42_MSG_NUM	42
#define	_MSG_UXSYSADM_42_MSG_NUM_STR	":42"
#define	_MSG_UXSYSADM_42_CAT_NUM_STR	"uxsysadm:42"
#define	_MSG_UXSYSADM_42_DEF_MSG	"\t/*                    byte width <> screen width  */\n"
#define	_MSG_UXSYSADM_42_CAT_NUM_STR_DEF_MSG	"uxsysadm:42:\t/*                    byte width <> screen width  */\n"
#define	_MSG_UXSYSADM_42_MSG_NUM_STR_DEF_MSG	":42:\t/*                    byte width <> screen width  */\n"
#define	_MSG_UXSYSADM_42_FILE_CAT_NUM	uxsysadm:42
#define	_SGI_DUXSYSADM_42	":42"
#define	_SGI_UXSYSADM_42	"uxsysadm:42"
#define	_SGI_MUXSYSADM_42	"uxsysadm:42:\t/*                    byte width <> screen width  */\n"
#define	_SGI_SUXSYSADM_42	"\t/*                    byte width <> screen width  */\n"
#define	_MSG_UXSYSADM_43_MSG_NUM	43
#define	_MSG_UXSYSADM_43_MSG_NUM_STR	":43"
#define	_MSG_UXSYSADM_43_CAT_NUM_STR	"uxsysadm:43"
#define	_MSG_UXSYSADM_43_DEF_MSG	"\n\t/* MAXIMUM CHARACTER WIDTH        %d               */\n"
#define	_MSG_UXSYSADM_43_CAT_NUM_STR_DEF_MSG	"uxsysadm:43:\n\t/* MAXIMUM CHARACTER WIDTH        %d               */\n"
#define	_MSG_UXSYSADM_43_MSG_NUM_STR_DEF_MSG	":43:\n\t/* MAXIMUM CHARACTER WIDTH        %d               */\n"
#define	_MSG_UXSYSADM_43_FILE_CAT_NUM	uxsysadm:43
#define	_SGI_DUXSYSADM_43	":43"
#define	_SGI_UXSYSADM_43	"uxsysadm:43"
#define	_SGI_MUXSYSADM_43	"uxsysadm:43:\n\t/* MAXIMUM CHARACTER WIDTH        %d               */\n"
#define	_SGI_SUXSYSADM_43	"\n\t/* MAXIMUM CHARACTER WIDTH        %d               */\n"
#define	_MSG_UXSYSADM_44_MSG_NUM	44
#define	_MSG_UXSYSADM_44_MSG_NUM_STR	":44"
#define	_MSG_UXSYSADM_44_CAT_NUM_STR	"uxsysadm:44"
#define	_MSG_UXSYSADM_44_DEF_MSG	"\n\n\t/* The next entries point to wctype tables */\n"
#define	_MSG_UXSYSADM_44_CAT_NUM_STR_DEF_MSG	"uxsysadm:44:\n\n\t/* The next entries point to wctype tables */\n"
#define	_MSG_UXSYSADM_44_MSG_NUM_STR_DEF_MSG	":44:\n\n\t/* The next entries point to wctype tables */\n"
#define	_MSG_UXSYSADM_44_FILE_CAT_NUM	uxsysadm:44
#define	_SGI_DUXSYSADM_44	":44"
#define	_SGI_UXSYSADM_44	"uxsysadm:44"
#define	_SGI_MUXSYSADM_44	"uxsysadm:44:\n\n\t/* The next entries point to wctype tables */\n"
#define	_SGI_SUXSYSADM_44	"\n\n\t/* The next entries point to wctype tables */\n"
#define	_MSG_UXSYSADM_45_MSG_NUM	45
#define	_MSG_UXSYSADM_45_MSG_NUM_STR	":45"
#define	_MSG_UXSYSADM_45_CAT_NUM_STR	"uxsysadm:45"
#define	_MSG_UXSYSADM_45_DEF_MSG	"\t/*          and have upper and lower limit */\n\n"
#define	_MSG_UXSYSADM_45_CAT_NUM_STR_DEF_MSG	"uxsysadm:45:\t/*          and have upper and lower limit */\n\n"
#define	_MSG_UXSYSADM_45_MSG_NUM_STR_DEF_MSG	":45:\t/*          and have upper and lower limit */\n\n"
#define	_MSG_UXSYSADM_45_FILE_CAT_NUM	uxsysadm:45
#define	_SGI_DUXSYSADM_45	":45"
#define	_SGI_UXSYSADM_45	"uxsysadm:45"
#define	_SGI_MUXSYSADM_45	"uxsysadm:45:\t/*          and have upper and lower limit */\n\n"
#define	_SGI_SUXSYSADM_45	"\t/*          and have upper and lower limit */\n\n"
#define	_MSG_UXSYSADM_46_MSG_NUM	46
#define	_MSG_UXSYSADM_46_MSG_NUM_STR	":46"
#define	_MSG_UXSYSADM_46_CAT_NUM_STR	"uxsysadm:46"
#define	_MSG_UXSYSADM_46_DEF_MSG	"\n\n\t/* The folowing table is used to determine\n"
#define	_MSG_UXSYSADM_46_CAT_NUM_STR_DEF_MSG	"uxsysadm:46:\n\n\t/* The folowing table is used to determine\n"
#define	_MSG_UXSYSADM_46_MSG_NUM_STR_DEF_MSG	":46:\n\n\t/* The folowing table is used to determine\n"
#define	_MSG_UXSYSADM_46_FILE_CAT_NUM	uxsysadm:46
#define	_SGI_DUXSYSADM_46	":46"
#define	_SGI_UXSYSADM_46	"uxsysadm:46"
#define	_SGI_MUXSYSADM_46	"uxsysadm:46:\n\n\t/* The folowing table is used to determine\n"
#define	_SGI_SUXSYSADM_46	"\n\n\t/* The folowing table is used to determine\n"
#define	_MSG_UXSYSADM_47_MSG_NUM	47
#define	_MSG_UXSYSADM_47_MSG_NUM_STR	":47"
#define	_MSG_UXSYSADM_47_CAT_NUM_STR	"uxsysadm:47"
#define	_MSG_UXSYSADM_47_DEF_MSG	"\t * the character class for supplementary code sets */\n\n"
#define	_MSG_UXSYSADM_47_CAT_NUM_STR_DEF_MSG	"uxsysadm:47:\t * the character class for supplementary code sets */\n\n"
#define	_MSG_UXSYSADM_47_MSG_NUM_STR_DEF_MSG	":47:\t * the character class for supplementary code sets */\n\n"
#define	_MSG_UXSYSADM_47_FILE_CAT_NUM	uxsysadm:47
#define	_SGI_DUXSYSADM_47	":47"
#define	_SGI_UXSYSADM_47	"uxsysadm:47"
#define	_SGI_MUXSYSADM_47	"uxsysadm:47:\t * the character class for supplementary code sets */\n\n"
#define	_SGI_SUXSYSADM_47	"\t * the character class for supplementary code sets */\n\n"
#define	_MSG_WCHRTBL_POSIX_WARN_MSG_NUM	48
#define	_MSG_WCHRTBL_POSIX_WARN_MSG_NUM_STR	":48"
#define	_MSG_WCHRTBL_POSIX_WARN_CAT_NUM_STR	"uxsysadm:48"
#define	_MSG_WCHRTBL_POSIX_WARN_DEF_MSG	"Warning: locale is not POSIX-compliant because 0x%x is not in %s\n"
#define	_MSG_WCHRTBL_POSIX_WARN_CAT_NUM_STR_DEF_MSG	"uxsysadm:48:Warning: locale is not POSIX-compliant because 0x%x is not in %s\n"
#define	_MSG_WCHRTBL_POSIX_WARN_MSG_NUM_STR_DEF_MSG	":48:Warning: locale is not POSIX-compliant because 0x%x is not in %s\n"
#define	_MSG_WCHRTBL_POSIX_WARN_FILE_CAT_NUM	uxsysadm:48
#define	_SGI_DWCHRTBL_POSIX_WARN	":48"
#define	_SGI_WCHRTBL_POSIX_WARN	"uxsysadm:48"
#define	_SGI_MWCHRTBL_POSIX_WARN	"uxsysadm:48:Warning: locale is not POSIX-compliant because 0x%x is not in %s\n"
#define	_SGI_SWCHRTBL_POSIX_WARN	"Warning: locale is not POSIX-compliant because 0x%x is not in %s\n"
#define	_MSG_WCHRTBL_NO_ENCODING_MSG_NUM	49
#define	_MSG_WCHRTBL_NO_ENCODING_MSG_NUM_STR	":49"
#define	_MSG_WCHRTBL_NO_ENCODING_CAT_NUM_STR	"uxsysadm:49"
#define	_MSG_WCHRTBL_NO_ENCODING_DEF_MSG	"%s: No encoding name specified"
#define	_MSG_WCHRTBL_NO_ENCODING_CAT_NUM_STR_DEF_MSG	"uxsysadm:49:%s: No encoding name specified"
#define	_MSG_WCHRTBL_NO_ENCODING_MSG_NUM_STR_DEF_MSG	":49:%s: No encoding name specified"
#define	_MSG_WCHRTBL_NO_ENCODING_FILE_CAT_NUM	uxsysadm:49
#define	_SGI_DWCHRTBL_NO_ENCODING	":49"
#define	_SGI_WCHRTBL_NO_ENCODING	"uxsysadm:49"
#define	_SGI_MWCHRTBL_NO_ENCODING	"uxsysadm:49:%s: No encoding name specified"
#define	_SGI_SWCHRTBL_NO_ENCODING	"%s: No encoding name specified"
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_MSG_NUM	50
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_MSG_NUM_STR	":50"
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_CAT_NUM_STR	"uxsysadm:50"
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_DEF_MSG	"%s: Cannot open mbtowc() converter for encoding %s"
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_CAT_NUM_STR_DEF_MSG	"uxsysadm:50:%s: Cannot open mbtowc() converter for encoding %s"
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_MSG_NUM_STR_DEF_MSG	":50:%s: Cannot open mbtowc() converter for encoding %s"
#define	_MSG_WCHRTBL_CANT_OPEN_MBTOWC_FILE_CAT_NUM	uxsysadm:50
#define	_SGI_DWCHRTBL_CANT_OPEN_MBTOWC	":50"
#define	_SGI_WCHRTBL_CANT_OPEN_MBTOWC	"uxsysadm:50"
#define	_SGI_MWCHRTBL_CANT_OPEN_MBTOWC	"uxsysadm:50:%s: Cannot open mbtowc() converter for encoding %s"
#define	_SGI_SWCHRTBL_CANT_OPEN_MBTOWC	"%s: Cannot open mbtowc() converter for encoding %s"
#define	_MSG_WCHRTBL_MBTOWC_FAILED_MSG_NUM	51
#define	_MSG_WCHRTBL_MBTOWC_FAILED_MSG_NUM_STR	":51"
#define	_MSG_WCHRTBL_MBTOWC_FAILED_CAT_NUM_STR	"uxsysadm:51"
#define	_MSG_WCHRTBL_MBTOWC_FAILED_DEF_MSG	"%s: mbtowc() conversion failed for 0x%x"
#define	_MSG_WCHRTBL_MBTOWC_FAILED_CAT_NUM_STR_DEF_MSG	"uxsysadm:51:%s: mbtowc() conversion failed for 0x%x"
#define	_MSG_WCHRTBL_MBTOWC_FAILED_MSG_NUM_STR_DEF_MSG	":51:%s: mbtowc() conversion failed for 0x%x"
#define	_MSG_WCHRTBL_MBTOWC_FAILED_FILE_CAT_NUM	uxsysadm:51
#define	_SGI_DWCHRTBL_MBTOWC_FAILED	":51"
#define	_SGI_WCHRTBL_MBTOWC_FAILED	"uxsysadm:51"
#define	_SGI_MWCHRTBL_MBTOWC_FAILED	"uxsysadm:51:%s: mbtowc() conversion failed for 0x%x"
#define	_SGI_SWCHRTBL_MBTOWC_FAILED	"%s: mbtowc() conversion failed for 0x%x"
