#include <mkmsgs.h>
#define	_MSG_INCORRECT_USAGE_MSG_NUM	1
#define	_MSG_INCORRECT_USAGE_MSG_NUM_STR	":1"
#define	_MSG_INCORRECT_USAGE_CAT_NUM_STR	"uxue:1"
#define	_MSG_INCORRECT_USAGE_DEF_MSG	"Incorrect usage\n"
#define	_MSG_INCORRECT_USAGE_CAT_NUM_STR_DEF_MSG	"uxue:1:Incorrect usage\n"
#define	_MSG_INCORRECT_USAGE_MSG_NUM_STR_DEF_MSG	":1:Incorrect usage\n"
#define	_MSG_INCORRECT_USAGE_FILE_CAT_NUM	uxue:1
#define	_SGI_DINCORRECT_USAGE	":1"
#define	_SGI_INCORRECT_USAGE	"uxue:1"
#define	_SGI_MINCORRECT_USAGE	"uxue:1:Incorrect usage\n"
#define	_SGI_SINCORRECT_USAGE	"Incorrect usage\n"
#define	_MSG_UXUE_2_MSG_NUM	2
#define	_MSG_UXUE_2_MSG_NUM_STR	":2"
#define	_MSG_UXUE_2_CAT_NUM_STR	"uxue:2"
#define	_MSG_UXUE_2_DEF_MSG	"Usage: banner \"up to 10 char arg string\" . . .\n"
#define	_MSG_UXUE_2_CAT_NUM_STR_DEF_MSG	"uxue:2:Usage: banner \"up to 10 char arg string\" . . .\n"
#define	_MSG_UXUE_2_MSG_NUM_STR_DEF_MSG	":2:Usage: banner \"up to 10 char arg string\" . . .\n"
#define	_MSG_UXUE_2_FILE_CAT_NUM	uxue:2
#define	_SGI_DUXUE_2	":2"
#define	_SGI_UXUE_2	"uxue:2"
#define	_SGI_MUXUE_2	"uxue:2:Usage: banner \"up to 10 char arg string\" . . .\n"
#define	_SGI_SUXUE_2	"Usage: banner \"up to 10 char arg string\" . . .\n"
#define	_MSG_CANNOT_OPEN_FORMAT_MSG_NUM	3
#define	_MSG_CANNOT_OPEN_FORMAT_MSG_NUM_STR	":3"
#define	_MSG_CANNOT_OPEN_FORMAT_CAT_NUM_STR	"uxue:3"
#define	_MSG_CANNOT_OPEN_FORMAT_DEF_MSG	"Cannot open %s: %s\n"
#define	_MSG_CANNOT_OPEN_FORMAT_CAT_NUM_STR_DEF_MSG	"uxue:3:Cannot open %s: %s\n"
#define	_MSG_CANNOT_OPEN_FORMAT_MSG_NUM_STR_DEF_MSG	":3:Cannot open %s: %s\n"
#define	_MSG_CANNOT_OPEN_FORMAT_FILE_CAT_NUM	uxue:3
#define	_SGI_DCANNOT_OPEN_FORMAT	":3"
#define	_SGI_CANNOT_OPEN_FORMAT	"uxue:3"
#define	_SGI_MCANNOT_OPEN_FORMAT	"uxue:3:Cannot open %s: %s\n"
#define	_SGI_SCANNOT_OPEN_FORMAT	"Cannot open %s: %s\n"
#define	_MSG_NOHUP_USAGE_MSG_NUM	4
#define	_MSG_NOHUP_USAGE_MSG_NUM_STR	":4"
#define	_MSG_NOHUP_USAGE_CAT_NUM_STR	"uxue:4"
#define	_MSG_NOHUP_USAGE_DEF_MSG	"Usage: nohup command arg ...\n"
#define	_MSG_NOHUP_USAGE_CAT_NUM_STR_DEF_MSG	"uxue:4:Usage: nohup command arg ...\n"
#define	_MSG_NOHUP_USAGE_MSG_NUM_STR_DEF_MSG	":4:Usage: nohup command arg ...\n"
#define	_MSG_NOHUP_USAGE_FILE_CAT_NUM	uxue:4
#define	_SGI_DNOHUP_USAGE	":4"
#define	_SGI_NOHUP_USAGE	"uxue:4"
#define	_SGI_MNOHUP_USAGE	"uxue:4:Usage: nohup command arg ...\n"
#define	_SGI_SNOHUP_USAGE	"Usage: nohup command arg ...\n"
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_MSG_NUM	5
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_MSG_NUM_STR	":5"
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_CAT_NUM_STR	"uxue:5"
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_DEF_MSG	"Sending output to %s\n"
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_CAT_NUM_STR_DEF_MSG	"uxue:5:Sending output to %s\n"
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_MSG_NUM_STR_DEF_MSG	":5:Sending output to %s\n"
#define	_MSG_SENDING_OUTPUT_TO_NOUT_FILE_FILE_CAT_NUM	uxue:5
#define	_SGI_DSENDING_OUTPUT_TO_NOUT_FILE	":5"
#define	_SGI_SENDING_OUTPUT_TO_NOUT_FILE	"uxue:5"
#define	_SGI_MSENDING_OUTPUT_TO_NOUT_FILE	"uxue:5:Sending output to %s\n"
#define	_SGI_SSENDING_OUTPUT_TO_NOUT_FILE	"Sending output to %s\n"
#define	_MSG_ERR_MSG_FOR_EXECVP_MSG_NUM	6
#define	_MSG_ERR_MSG_FOR_EXECVP_MSG_NUM_STR	":6"
#define	_MSG_ERR_MSG_FOR_EXECVP_CAT_NUM_STR	"uxue:6"
#define	_MSG_ERR_MSG_FOR_EXECVP_DEF_MSG	"%s: %s\n"
#define	_MSG_ERR_MSG_FOR_EXECVP_CAT_NUM_STR_DEF_MSG	"uxue:6:%s: %s\n"
#define	_MSG_ERR_MSG_FOR_EXECVP_MSG_NUM_STR_DEF_MSG	":6:%s: %s\n"
#define	_MSG_ERR_MSG_FOR_EXECVP_FILE_CAT_NUM	uxue:6
#define	_SGI_DERR_MSG_FOR_EXECVP	":6"
#define	_SGI_ERR_MSG_FOR_EXECVP	"uxue:6"
#define	_SGI_MERR_MSG_FOR_EXECVP	"uxue:6:%s: %s\n"
#define	_SGI_SERR_MSG_FOR_EXECVP	"%s: %s\n"
#define	_MSG_UXUE_7_MSG_NUM	7
#define	_MSG_UXUE_7_MSG_NUM_STR	":7"
#define	_MSG_UXUE_7_CAT_NUM_STR	"uxue:7"
#define	_MSG_UXUE_7_DEF_MSG	"Switch failed: %s\n"
#define	_MSG_UXUE_7_CAT_NUM_STR_DEF_MSG	"uxue:7:Switch failed: %s\n"
#define	_MSG_UXUE_7_MSG_NUM_STR_DEF_MSG	":7:Switch failed: %s\n"
#define	_MSG_UXUE_7_FILE_CAT_NUM	uxue:7
#define	_SGI_DUXUE_7	":7"
#define	_SGI_UXUE_7	"uxue:7"
#define	_SGI_MUXUE_7	"uxue:7:Switch failed: %s\n"
#define	_SGI_SUXUE_7	"Switch failed: %s\n"
#define	_MSG_UXUE_8_MSG_NUM	8
#define	_MSG_UXUE_8_MSG_NUM_STR	":8"
#define	_MSG_UXUE_8_CAT_NUM_STR	"uxue:8"
#define	_MSG_UXUE_8_DEF_MSG	"Resuming %s\n"
#define	_MSG_UXUE_8_CAT_NUM_STR_DEF_MSG	"uxue:8:Resuming %s\n"
#define	_MSG_UXUE_8_MSG_NUM_STR_DEF_MSG	":8:Resuming %s\n"
#define	_MSG_UXUE_8_FILE_CAT_NUM	uxue:8
#define	_SGI_DUXUE_8	":8"
#define	_SGI_UXUE_8	"uxue:8"
#define	_SGI_MUXUE_8	"uxue:8:Resuming %s\n"
#define	_SGI_SUXUE_8	"Resuming %s\n"
#define	_MSG_UXUE_9_MSG_NUM	9
#define	_MSG_UXUE_9_MSG_NUM_STR	":9"
#define	_MSG_UXUE_9_CAT_NUM_STR	"uxue:9"
#define	_MSG_UXUE_9_DEF_MSG	"chown() on %s failed: %s\n"
#define	_MSG_UXUE_9_CAT_NUM_STR_DEF_MSG	"uxue:9:chown() on %s failed: %s\n"
#define	_MSG_UXUE_9_MSG_NUM_STR_DEF_MSG	":9:chown() on %s failed: %s\n"
#define	_MSG_UXUE_9_FILE_CAT_NUM	uxue:9
#define	_SGI_DUXUE_9	":9"
#define	_SGI_UXUE_9	"uxue:9"
#define	_SGI_MUXUE_9	"uxue:9:chown() on %s failed: %s\n"
#define	_SGI_SUXUE_9	"chown() on %s failed: %s\n"
#define	_MSG_UXUE_10_MSG_NUM	10
#define	_MSG_UXUE_10_MSG_NUM_STR	":10"
#define	_MSG_UXUE_10_CAT_NUM_STR	"uxue:10"
#define	_MSG_UXUE_10_DEF_MSG	"Virtual tty ioctl failed: %s\n"
#define	_MSG_UXUE_10_CAT_NUM_STR_DEF_MSG	"uxue:10:Virtual tty ioctl failed: %s\n"
#define	_MSG_UXUE_10_MSG_NUM_STR_DEF_MSG	":10:Virtual tty ioctl failed: %s\n"
#define	_MSG_UXUE_10_FILE_CAT_NUM	uxue:10
#define	_SGI_DUXUE_10	":10"
#define	_SGI_UXUE_10	"uxue:10"
#define	_SGI_MUXUE_10	"uxue:10:Virtual tty ioctl failed: %s\n"
#define	_SGI_SUXUE_10	"Virtual tty ioctl failed: %s\n"
#define	_MSG_UXUE_11_MSG_NUM	11
#define	_MSG_UXUE_11_MSG_NUM_STR	":11"
#define	_MSG_UXUE_11_CAT_NUM_STR	"uxue:11"
#define	_MSG_UXUE_11_DEF_MSG	"Trying to save bad tty %d\n"
#define	_MSG_UXUE_11_CAT_NUM_STR_DEF_MSG	"uxue:11:Trying to save bad tty %d\n"
#define	_MSG_UXUE_11_MSG_NUM_STR_DEF_MSG	":11:Trying to save bad tty %d\n"
#define	_MSG_UXUE_11_FILE_CAT_NUM	uxue:11
#define	_SGI_DUXUE_11	":11"
#define	_SGI_UXUE_11	"uxue:11"
#define	_SGI_MUXUE_11	"uxue:11:Trying to save bad tty %d\n"
#define	_SGI_SUXUE_11	"Trying to save bad tty %d\n"
#define	_MSG_UXUE_12_MSG_NUM	12
#define	_MSG_UXUE_12_MSG_NUM_STR	":12"
#define	_MSG_UXUE_12_CAT_NUM_STR	"uxue:12"
#define	_MSG_UXUE_12_DEF_MSG	"Savetty ioctl fails %d\n"
#define	_MSG_UXUE_12_CAT_NUM_STR_DEF_MSG	"uxue:12:Savetty ioctl fails %d\n"
#define	_MSG_UXUE_12_MSG_NUM_STR_DEF_MSG	":12:Savetty ioctl fails %d\n"
#define	_MSG_UXUE_12_FILE_CAT_NUM	uxue:12
#define	_SGI_DUXUE_12	":12"
#define	_SGI_UXUE_12	"uxue:12"
#define	_SGI_MUXUE_12	"uxue:12:Savetty ioctl fails %d\n"
#define	_SGI_SUXUE_12	"Savetty ioctl fails %d\n"
#define	_MSG_UXUE_13_MSG_NUM	13
#define	_MSG_UXUE_13_MSG_NUM_STR	":13"
#define	_MSG_UXUE_13_CAT_NUM_STR	"uxue:13"
#define	_MSG_UXUE_13_DEF_MSG	"Trying to reset bad tty %d\n"
#define	_MSG_UXUE_13_CAT_NUM_STR_DEF_MSG	"uxue:13:Trying to reset bad tty %d\n"
#define	_MSG_UXUE_13_MSG_NUM_STR_DEF_MSG	":13:Trying to reset bad tty %d\n"
#define	_MSG_UXUE_13_FILE_CAT_NUM	uxue:13
#define	_SGI_DUXUE_13	":13"
#define	_SGI_UXUE_13	"uxue:13"
#define	_SGI_MUXUE_13	"uxue:13:Trying to reset bad tty %d\n"
#define	_SGI_SUXUE_13	"Trying to reset bad tty %d\n"
#define	_MSG_UXUE_14_MSG_NUM	14
#define	_MSG_UXUE_14_MSG_NUM_STR	":14"
#define	_MSG_UXUE_14_CAT_NUM_STR	"uxue:14"
#define	_MSG_UXUE_14_DEF_MSG	"Resettty ioctl fails %d\n"
#define	_MSG_UXUE_14_CAT_NUM_STR_DEF_MSG	"uxue:14:Resettty ioctl fails %d\n"
#define	_MSG_UXUE_14_MSG_NUM_STR_DEF_MSG	":14:Resettty ioctl fails %d\n"
#define	_MSG_UXUE_14_FILE_CAT_NUM	uxue:14
#define	_SGI_DUXUE_14	":14"
#define	_SGI_UXUE_14	"uxue:14"
#define	_SGI_MUXUE_14	"uxue:14:Resettty ioctl fails %d\n"
#define	_SGI_SUXUE_14	"Resettty ioctl fails %d\n"
#define	_MSG_UXUE_15_MSG_NUM	15
#define	_MSG_UXUE_15_MSG_NUM_STR	":15"
#define	_MSG_UXUE_15_CAT_NUM_STR	"uxue:15"
#define	_MSG_UXUE_15_DEF_MSG	"Layer %s already exists\n"
#define	_MSG_UXUE_15_CAT_NUM_STR_DEF_MSG	"uxue:15:Layer %s already exists\n"
#define	_MSG_UXUE_15_MSG_NUM_STR_DEF_MSG	":15:Layer %s already exists\n"
#define	_MSG_UXUE_15_FILE_CAT_NUM	uxue:15
#define	_SGI_DUXUE_15	":15"
#define	_SGI_UXUE_15	"uxue:15"
#define	_SGI_MUXUE_15	"uxue:15:Layer %s already exists\n"
#define	_SGI_SUXUE_15	"Layer %s already exists\n"
#define	_MSG_UXUE_16_MSG_NUM	16
#define	_MSG_UXUE_16_MSG_NUM_STR	":16"
#define	_MSG_UXUE_16_CAT_NUM_STR	"uxue:16"
#define	_MSG_UXUE_16_DEF_MSG	"Only %d layers allowed\n"
#define	_MSG_UXUE_16_CAT_NUM_STR_DEF_MSG	"uxue:16:Only %d layers allowed\n"
#define	_MSG_UXUE_16_MSG_NUM_STR_DEF_MSG	":16:Only %d layers allowed\n"
#define	_MSG_UXUE_16_FILE_CAT_NUM	uxue:16
#define	_SGI_DUXUE_16	":16"
#define	_SGI_UXUE_16	"uxue:16"
#define	_SGI_MUXUE_16	"uxue:16:Only %d layers allowed\n"
#define	_SGI_SUXUE_16	"Only %d layers allowed\n"
#define	_MSG_UXUE_17_MSG_NUM	17
#define	_MSG_UXUE_17_MSG_NUM_STR	":17"
#define	_MSG_UXUE_17_CAT_NUM_STR	"uxue:17"
#define	_MSG_UXUE_17_DEF_MSG	"Layer %s not found\n"
#define	_MSG_UXUE_17_CAT_NUM_STR_DEF_MSG	"uxue:17:Layer %s not found\n"
#define	_MSG_UXUE_17_MSG_NUM_STR_DEF_MSG	":17:Layer %s not found\n"
#define	_MSG_UXUE_17_FILE_CAT_NUM	uxue:17
#define	_SGI_DUXUE_17	":17"
#define	_SGI_UXUE_17	"uxue:17"
#define	_SGI_MUXUE_17	"uxue:17:Layer %s not found\n"
#define	_SGI_SUXUE_17	"Layer %s not found\n"
#define	_MSG_UXUE_18_MSG_NUM	18
#define	_MSG_UXUE_18_MSG_NUM_STR	":18"
#define	_MSG_UXUE_18_CAT_NUM_STR	"uxue:18"
#define	_MSG_UXUE_18_DEF_MSG	"Cannot open pipe for synchronization: %s\n"
#define	_MSG_UXUE_18_CAT_NUM_STR_DEF_MSG	"uxue:18:Cannot open pipe for synchronization: %s\n"
#define	_MSG_UXUE_18_MSG_NUM_STR_DEF_MSG	":18:Cannot open pipe for synchronization: %s\n"
#define	_MSG_UXUE_18_FILE_CAT_NUM	uxue:18
#define	_SGI_DUXUE_18	":18"
#define	_SGI_UXUE_18	"uxue:18"
#define	_SGI_MUXUE_18	"uxue:18:Cannot open pipe for synchronization: %s\n"
#define	_SGI_SUXUE_18	"Cannot open pipe for synchronization: %s\n"
#define	_MSG_UXUE_19_MSG_NUM	19
#define	_MSG_UXUE_19_MSG_NUM_STR	":19"
#define	_MSG_UXUE_19_CAT_NUM_STR	"uxue:19"
#define	_MSG_UXUE_19_DEF_MSG	"Cannot set group or user id: %s\n"
#define	_MSG_UXUE_19_CAT_NUM_STR_DEF_MSG	"uxue:19:Cannot set group or user id: %s\n"
#define	_MSG_UXUE_19_MSG_NUM_STR_DEF_MSG	":19:Cannot set group or user id: %s\n"
#define	_MSG_UXUE_19_FILE_CAT_NUM	uxue:19
#define	_SGI_DUXUE_19	":19"
#define	_SGI_UXUE_19	"uxue:19"
#define	_SGI_MUXUE_19	"uxue:19:Cannot set group or user id: %s\n"
#define	_SGI_SUXUE_19	"Cannot set group or user id: %s\n"
#define	_MSG_UXUE_20_MSG_NUM	20
#define	_MSG_UXUE_20_MSG_NUM_STR	":20"
#define	_MSG_UXUE_20_CAT_NUM_STR	"uxue:20"
#define	_MSG_UXUE_20_DEF_MSG	"Virtual tty open failed: %s\n"
#define	_MSG_UXUE_20_CAT_NUM_STR_DEF_MSG	"uxue:20:Virtual tty open failed: %s\n"
#define	_MSG_UXUE_20_MSG_NUM_STR_DEF_MSG	":20:Virtual tty open failed: %s\n"
#define	_MSG_UXUE_20_FILE_CAT_NUM	uxue:20
#define	_SGI_DUXUE_20	":20"
#define	_SGI_UXUE_20	"uxue:20"
#define	_SGI_MUXUE_20	"uxue:20:Virtual tty open failed: %s\n"
#define	_SGI_SUXUE_20	"Virtual tty open failed: %s\n"
#define	_MSG_UXUE_21_MSG_NUM	21
#define	_MSG_UXUE_21_MSG_NUM_STR	":21"
#define	_MSG_UXUE_21_CAT_NUM_STR	"uxue:21"
#define	_MSG_UXUE_21_DEF_MSG	"Error on virtual tty open\n"
#define	_MSG_UXUE_21_CAT_NUM_STR_DEF_MSG	"uxue:21:Error on virtual tty open\n"
#define	_MSG_UXUE_21_MSG_NUM_STR_DEF_MSG	":21:Error on virtual tty open\n"
#define	_MSG_UXUE_21_FILE_CAT_NUM	uxue:21
#define	_SGI_DUXUE_21	":21"
#define	_SGI_UXUE_21	"uxue:21"
#define	_SGI_MUXUE_21	"uxue:21:Error on virtual tty open\n"
#define	_SGI_SUXUE_21	"Error on virtual tty open\n"
#define	_MSG_UXUE_22_MSG_NUM	22
#define	_MSG_UXUE_22_MSG_NUM_STR	":22"
#define	_MSG_UXUE_22_CAT_NUM_STR	"uxue:22"
#define	_MSG_UXUE_22_DEF_MSG	"Synchronization problem: %s\n"
#define	_MSG_UXUE_22_CAT_NUM_STR_DEF_MSG	"uxue:22:Synchronization problem: %s\n"
#define	_MSG_UXUE_22_MSG_NUM_STR_DEF_MSG	":22:Synchronization problem: %s\n"
#define	_MSG_UXUE_22_FILE_CAT_NUM	uxue:22
#define	_SGI_DUXUE_22	":22"
#define	_SGI_UXUE_22	"uxue:22"
#define	_SGI_MUXUE_22	"uxue:22:Synchronization problem: %s\n"
#define	_SGI_SUXUE_22	"Synchronization problem: %s\n"
#define	_MSG_UXUE_23_MSG_NUM	23
#define	_MSG_UXUE_23_MSG_NUM_STR	":23"
#define	_MSG_UXUE_23_CAT_NUM_STR	"uxue:23"
#define	_MSG_UXUE_23_DEF_MSG	"Cannot execute %s: %s\n"
#define	_MSG_UXUE_23_CAT_NUM_STR_DEF_MSG	"uxue:23:Cannot execute %s: %s\n"
#define	_MSG_UXUE_23_MSG_NUM_STR_DEF_MSG	":23:Cannot execute %s: %s\n"
#define	_MSG_UXUE_23_FILE_CAT_NUM	uxue:23
#define	_SGI_DUXUE_23	":23"
#define	_SGI_UXUE_23	"uxue:23"
#define	_SGI_MUXUE_23	"uxue:23:Cannot execute %s: %s\n"
#define	_SGI_SUXUE_23	"Cannot execute %s: %s\n"
#define	_MSG_UXUE_24_MSG_NUM	24
#define	_MSG_UXUE_24_MSG_NUM_STR	":24"
#define	_MSG_UXUE_24_CAT_NUM_STR	"uxue:24"
#define	_MSG_UXUE_24_DEF_MSG	"fork() failed: %s\n"
#define	_MSG_UXUE_24_CAT_NUM_STR_DEF_MSG	"uxue:24:fork() failed: %s\n"
#define	_MSG_UXUE_24_MSG_NUM_STR_DEF_MSG	":24:fork() failed: %s\n"
#define	_MSG_UXUE_24_FILE_CAT_NUM	uxue:24
#define	_SGI_DUXUE_24	":24"
#define	_SGI_UXUE_24	"uxue:24"
#define	_SGI_MUXUE_24	"uxue:24:fork() failed: %s\n"
#define	_SGI_SUXUE_24	"fork() failed: %s\n"
#define	_MSG_UXUE_25_MSG_NUM	25
#define	_MSG_UXUE_25_MSG_NUM_STR	":25"
#define	_MSG_UXUE_25_CAT_NUM_STR	"uxue:25"
#define	_MSG_UXUE_25_DEF_MSG	"block name [name ...]\n"
#define	_MSG_UXUE_25_CAT_NUM_STR_DEF_MSG	"uxue:25:block name [name ...]\n"
#define	_MSG_UXUE_25_MSG_NUM_STR_DEF_MSG	":25:block name [name ...]\n"
#define	_MSG_UXUE_25_FILE_CAT_NUM	uxue:25
#define	_SGI_DUXUE_25	":25"
#define	_SGI_UXUE_25	"uxue:25"
#define	_SGI_MUXUE_25	"uxue:25:block name [name ...]\n"
#define	_SGI_SUXUE_25	"block name [name ...]\n"
#define	_MSG_UXUE_26_MSG_NUM	26
#define	_MSG_UXUE_26_MSG_NUM_STR	":26"
#define	_MSG_UXUE_26_CAT_NUM_STR	"uxue:26"
#define	_MSG_UXUE_26_DEF_MSG	"create [name]\n"
#define	_MSG_UXUE_26_CAT_NUM_STR_DEF_MSG	"uxue:26:create [name]\n"
#define	_MSG_UXUE_26_MSG_NUM_STR_DEF_MSG	":26:create [name]\n"
#define	_MSG_UXUE_26_FILE_CAT_NUM	uxue:26
#define	_SGI_DUXUE_26	":26"
#define	_SGI_UXUE_26	"uxue:26"
#define	_SGI_MUXUE_26	"uxue:26:create [name]\n"
#define	_SGI_SUXUE_26	"create [name]\n"
#define	_MSG_UXUE_27_MSG_NUM	27
#define	_MSG_UXUE_27_MSG_NUM_STR	":27"
#define	_MSG_UXUE_27_CAT_NUM_STR	"uxue:27"
#define	_MSG_UXUE_27_DEF_MSG	"delete name [name ...]\n"
#define	_MSG_UXUE_27_CAT_NUM_STR_DEF_MSG	"uxue:27:delete name [name ...]\n"
#define	_MSG_UXUE_27_MSG_NUM_STR_DEF_MSG	":27:delete name [name ...]\n"
#define	_MSG_UXUE_27_FILE_CAT_NUM	uxue:27
#define	_SGI_DUXUE_27	":27"
#define	_SGI_UXUE_27	"uxue:27"
#define	_SGI_MUXUE_27	"uxue:27:delete name [name ...]\n"
#define	_SGI_SUXUE_27	"delete name [name ...]\n"
#define	_MSG_UXUE_28_MSG_NUM	28
#define	_MSG_UXUE_28_MSG_NUM_STR	":28"
#define	_MSG_UXUE_28_CAT_NUM_STR	"uxue:28"
#define	_MSG_UXUE_28_DEF_MSG	"help or ?\n"
#define	_MSG_UXUE_28_CAT_NUM_STR_DEF_MSG	"uxue:28:help or ?\n"
#define	_MSG_UXUE_28_MSG_NUM_STR_DEF_MSG	":28:help or ?\n"
#define	_MSG_UXUE_28_FILE_CAT_NUM	uxue:28
#define	_SGI_DUXUE_28	":28"
#define	_SGI_UXUE_28	"uxue:28"
#define	_SGI_MUXUE_28	"uxue:28:help or ?\n"
#define	_SGI_SUXUE_28	"help or ?\n"
#define	_MSG_UXUE_29_MSG_NUM	29
#define	_MSG_UXUE_29_MSG_NUM_STR	":29"
#define	_MSG_UXUE_29_CAT_NUM_STR	"uxue:29"
#define	_MSG_UXUE_29_DEF_MSG	"layers [-l] [name ...]\n"
#define	_MSG_UXUE_29_CAT_NUM_STR_DEF_MSG	"uxue:29:layers [-l] [name ...]\n"
#define	_MSG_UXUE_29_MSG_NUM_STR_DEF_MSG	":29:layers [-l] [name ...]\n"
#define	_MSG_UXUE_29_FILE_CAT_NUM	uxue:29
#define	_SGI_DUXUE_29	":29"
#define	_SGI_UXUE_29	"uxue:29"
#define	_SGI_MUXUE_29	"uxue:29:layers [-l] [name ...]\n"
#define	_SGI_SUXUE_29	"layers [-l] [name ...]\n"
#define	_MSG_UXUE_30_MSG_NUM	30
#define	_MSG_UXUE_30_MSG_NUM_STR	":30"
#define	_MSG_UXUE_30_CAT_NUM_STR	"uxue:30"
#define	_MSG_UXUE_30_DEF_MSG	"quit\n"
#define	_MSG_UXUE_30_CAT_NUM_STR_DEF_MSG	"uxue:30:quit\n"
#define	_MSG_UXUE_30_MSG_NUM_STR_DEF_MSG	":30:quit\n"
#define	_MSG_UXUE_30_FILE_CAT_NUM	uxue:30
#define	_SGI_DUXUE_30	":30"
#define	_SGI_UXUE_30	"uxue:30"
#define	_SGI_MUXUE_30	"uxue:30:quit\n"
#define	_SGI_SUXUE_30	"quit\n"
#define	_MSG_UXUE_31_MSG_NUM	31
#define	_MSG_UXUE_31_MSG_NUM_STR	":31"
#define	_MSG_UXUE_31_CAT_NUM_STR	"uxue:31"
#define	_MSG_UXUE_31_DEF_MSG	"toggle\n"
#define	_MSG_UXUE_31_CAT_NUM_STR_DEF_MSG	"uxue:31:toggle\n"
#define	_MSG_UXUE_31_MSG_NUM_STR_DEF_MSG	":31:toggle\n"
#define	_MSG_UXUE_31_FILE_CAT_NUM	uxue:31
#define	_SGI_DUXUE_31	":31"
#define	_SGI_UXUE_31	"uxue:31"
#define	_SGI_MUXUE_31	"uxue:31:toggle\n"
#define	_SGI_SUXUE_31	"toggle\n"
#define	_MSG_UXUE_32_MSG_NUM	32
#define	_MSG_UXUE_32_MSG_NUM_STR	":32"
#define	_MSG_UXUE_32_CAT_NUM_STR	"uxue:32"
#define	_MSG_UXUE_32_DEF_MSG	"resume [name]\n"
#define	_MSG_UXUE_32_CAT_NUM_STR_DEF_MSG	"uxue:32:resume [name]\n"
#define	_MSG_UXUE_32_MSG_NUM_STR_DEF_MSG	":32:resume [name]\n"
#define	_MSG_UXUE_32_FILE_CAT_NUM	uxue:32
#define	_SGI_DUXUE_32	":32"
#define	_SGI_UXUE_32	"uxue:32"
#define	_SGI_MUXUE_32	"uxue:32:resume [name]\n"
#define	_SGI_SUXUE_32	"resume [name]\n"
#define	_MSG_UXUE_33_MSG_NUM	33
#define	_MSG_UXUE_33_MSG_NUM_STR	":33"
#define	_MSG_UXUE_33_CAT_NUM_STR	"uxue:33"
#define	_MSG_UXUE_33_DEF_MSG	"unblock name [name ...]\n"
#define	_MSG_UXUE_33_CAT_NUM_STR_DEF_MSG	"uxue:33:unblock name [name ...]\n"
#define	_MSG_UXUE_33_MSG_NUM_STR_DEF_MSG	":33:unblock name [name ...]\n"
#define	_MSG_UXUE_33_FILE_CAT_NUM	uxue:33
#define	_SGI_DUXUE_33	":33"
#define	_SGI_UXUE_33	"uxue:33"
#define	_SGI_MUXUE_33	"uxue:33:unblock name [name ...]\n"
#define	_SGI_SUXUE_33	"unblock name [name ...]\n"
#define	_MSG_UXUE_34_MSG_NUM	34
#define	_MSG_UXUE_34_MSG_NUM_STR	":34"
#define	_MSG_UXUE_34_CAT_NUM_STR	"uxue:34"
#define	_MSG_UXUE_34_DEF_MSG	"No control channels available: %s\n"
#define	_MSG_UXUE_34_CAT_NUM_STR_DEF_MSG	"uxue:34:No control channels available: %s\n"
#define	_MSG_UXUE_34_MSG_NUM_STR_DEF_MSG	":34:No control channels available: %s\n"
#define	_MSG_UXUE_34_FILE_CAT_NUM	uxue:34
#define	_SGI_DUXUE_34	":34"
#define	_SGI_UXUE_34	"uxue:34"
#define	_SGI_MUXUE_34	"uxue:34:No control channels available: %s\n"
#define	_SGI_SUXUE_34	"No control channels available: %s\n"
#define	_MSG_UXUE_35_MSG_NUM	35
#define	_MSG_UXUE_35_MSG_NUM_STR	":35"
#define	_MSG_UXUE_35_CAT_NUM_STR	"uxue:35"
#define	_MSG_UXUE_35_DEF_MSG	"SXT driver not configured: %s\n"
#define	_MSG_UXUE_35_CAT_NUM_STR_DEF_MSG	"uxue:35:SXT driver not configured: %s\n"
#define	_MSG_UXUE_35_MSG_NUM_STR_DEF_MSG	":35:SXT driver not configured: %s\n"
#define	_MSG_UXUE_35_FILE_CAT_NUM	uxue:35
#define	_SGI_DUXUE_35	":35"
#define	_SGI_UXUE_35	"uxue:35"
#define	_SGI_MUXUE_35	"uxue:35:SXT driver not configured: %s\n"
#define	_SGI_SUXUE_35	"SXT driver not configured: %s\n"
#define	_MSG_UXUE_36_MSG_NUM	36
#define	_MSG_UXUE_36_MSG_NUM_STR	":36"
#define	_MSG_UXUE_36_CAT_NUM_STR	"uxue:36"
#define	_MSG_UXUE_36_DEF_MSG	"No memory for kernel configuration: %s\n"
#define	_MSG_UXUE_36_CAT_NUM_STR_DEF_MSG	"uxue:36:No memory for kernel configuration: %s\n"
#define	_MSG_UXUE_36_MSG_NUM_STR_DEF_MSG	":36:No memory for kernel configuration: %s\n"
#define	_MSG_UXUE_36_FILE_CAT_NUM	uxue:36
#define	_SGI_DUXUE_36	":36"
#define	_SGI_UXUE_36	"uxue:36"
#define	_SGI_MUXUE_36	"uxue:36:No memory for kernel configuration: %s\n"
#define	_SGI_SUXUE_36	"No memory for kernel configuration: %s\n"
#define	_MSG_UXUE_37_MSG_NUM	37
#define	_MSG_UXUE_37_MSG_NUM_STR	":37"
#define	_MSG_UXUE_37_CAT_NUM_STR	"uxue:37"
#define	_MSG_UXUE_37_DEF_MSG	"Not using a tty device: %s\n"
#define	_MSG_UXUE_37_CAT_NUM_STR_DEF_MSG	"uxue:37:Not using a tty device: %s\n"
#define	_MSG_UXUE_37_MSG_NUM_STR_DEF_MSG	":37:Not using a tty device: %s\n"
#define	_MSG_UXUE_37_FILE_CAT_NUM	uxue:37
#define	_SGI_DUXUE_37	":37"
#define	_SGI_UXUE_37	"uxue:37"
#define	_SGI_MUXUE_37	"uxue:37:Not using a tty device: %s\n"
#define	_SGI_SUXUE_37	"Not using a tty device: %s\n"
#define	_MSG_UXUE_38_MSG_NUM	38
#define	_MSG_UXUE_38_MSG_NUM_STR	":38"
#define	_MSG_UXUE_38_CAT_NUM_STR	"uxue:38"
#define	_MSG_UXUE_38_DEF_MSG	"Out of streams buffers: %s\n"
#define	_MSG_UXUE_38_CAT_NUM_STR_DEF_MSG	"uxue:38:Out of streams buffers: %s\n"
#define	_MSG_UXUE_38_MSG_NUM_STR_DEF_MSG	":38:Out of streams buffers: %s\n"
#define	_MSG_UXUE_38_FILE_CAT_NUM	uxue:38
#define	_SGI_DUXUE_38	":38"
#define	_SGI_UXUE_38	"uxue:38"
#define	_SGI_MUXUE_38	"uxue:38:Out of streams buffers: %s\n"
#define	_SGI_SUXUE_38	"Out of streams buffers: %s\n"
#define	_MSG_UXUE_39_MSG_NUM	39
#define	_MSG_UXUE_39_MSG_NUM_STR	":39"
#define	_MSG_UXUE_39_CAT_NUM_STR	"uxue:39"
#define	_MSG_UXUE_39_DEF_MSG	"Multiplex failed: %s\n"
#define	_MSG_UXUE_39_CAT_NUM_STR_DEF_MSG	"uxue:39:Multiplex failed: %s\n"
#define	_MSG_UXUE_39_MSG_NUM_STR_DEF_MSG	":39:Multiplex failed: %s\n"
#define	_MSG_UXUE_39_FILE_CAT_NUM	uxue:39
#define	_SGI_DUXUE_39	":39"
#define	_SGI_UXUE_39	"uxue:39"
#define	_SGI_MUXUE_39	"uxue:39:Multiplex failed: %s\n"
#define	_SGI_SUXUE_39	"Multiplex failed: %s\n"
#define	_MSG_UXUE_40_MSG_NUM	40
#define	_MSG_UXUE_40_MSG_NUM_STR	":40"
#define	_MSG_UXUE_40_CAT_NUM_STR	"uxue:40"
#define	_MSG_UXUE_40_DEF_MSG	"Real tty open failed: %s\n"
#define	_MSG_UXUE_40_CAT_NUM_STR_DEF_MSG	"uxue:40:Real tty open failed: %s\n"
#define	_MSG_UXUE_40_MSG_NUM_STR_DEF_MSG	":40:Real tty open failed: %s\n"
#define	_MSG_UXUE_40_FILE_CAT_NUM	uxue:40
#define	_SGI_DUXUE_40	":40"
#define	_SGI_UXUE_40	"uxue:40"
#define	_SGI_MUXUE_40	"uxue:40:Real tty open failed: %s\n"
#define	_SGI_SUXUE_40	"Real tty open failed: %s\n"
#define	_MSG_UXUE_41_MSG_NUM	41
#define	_MSG_UXUE_41_MSG_NUM_STR	":41"
#define	_MSG_UXUE_41_CAT_NUM_STR	"uxue:41"
#define	_MSG_UXUE_41_DEF_MSG	"Could not reset permissions on sxt devices\n"
#define	_MSG_UXUE_41_CAT_NUM_STR_DEF_MSG	"uxue:41:Could not reset permissions on sxt devices\n"
#define	_MSG_UXUE_41_MSG_NUM_STR_DEF_MSG	":41:Could not reset permissions on sxt devices\n"
#define	_MSG_UXUE_41_FILE_CAT_NUM	uxue:41
#define	_SGI_DUXUE_41	":41"
#define	_SGI_UXUE_41	"uxue:41"
#define	_SGI_MUXUE_41	"uxue:41:Could not reset permissions on sxt devices\n"
#define	_SGI_SUXUE_41	"Could not reset permissions on sxt devices\n"
#define	_MSG_UXUE_42_MSG_NUM	42
#define	_MSG_UXUE_42_MSG_NUM_STR	":42"
#define	_MSG_UXUE_42_CAT_NUM_STR	"uxue:42"
#define	_MSG_UXUE_42_DEF_MSG	"ioctl() I_UNLINK failed: %s\n"
#define	_MSG_UXUE_42_CAT_NUM_STR_DEF_MSG	"uxue:42:ioctl() I_UNLINK failed: %s\n"
#define	_MSG_UXUE_42_MSG_NUM_STR_DEF_MSG	":42:ioctl() I_UNLINK failed: %s\n"
#define	_MSG_UXUE_42_FILE_CAT_NUM	uxue:42
#define	_SGI_DUXUE_42	":42"
#define	_SGI_UXUE_42	"uxue:42"
#define	_SGI_MUXUE_42	"uxue:42:ioctl() I_UNLINK failed: %s\n"
#define	_SGI_SUXUE_42	"ioctl() I_UNLINK failed: %s\n"
#define	_MSG_UXUE_43_MSG_NUM	43
#define	_MSG_UXUE_43_MSG_NUM_STR	":43"
#define	_MSG_UXUE_43_CAT_NUM_STR	"uxue:43"
#define	_MSG_UXUE_43_DEF_MSG	"Cannot invoke shl from within layers\n"
#define	_MSG_UXUE_43_CAT_NUM_STR_DEF_MSG	"uxue:43:Cannot invoke shl from within layers\n"
#define	_MSG_UXUE_43_MSG_NUM_STR_DEF_MSG	":43:Cannot invoke shl from within layers\n"
#define	_MSG_UXUE_43_FILE_CAT_NUM	uxue:43
#define	_SGI_DUXUE_43	":43"
#define	_SGI_UXUE_43	"uxue:43"
#define	_SGI_MUXUE_43	"uxue:43:Cannot invoke shl from within layers\n"
#define	_SGI_SUXUE_43	"Cannot invoke shl from within layers\n"
#define	_MSG_UXUE_44_MSG_NUM	44
#define	_MSG_UXUE_44_MSG_NUM_STR	":44"
#define	_MSG_UXUE_44_CAT_NUM_STR	"uxue:44"
#define	_MSG_UXUE_44_DEF_MSG	"Cannot find your utmp entry\n"
#define	_MSG_UXUE_44_CAT_NUM_STR_DEF_MSG	"uxue:44:Cannot find your utmp entry\n"
#define	_MSG_UXUE_44_MSG_NUM_STR_DEF_MSG	":44:Cannot find your utmp entry\n"
#define	_MSG_UXUE_44_FILE_CAT_NUM	uxue:44
#define	_SGI_DUXUE_44	":44"
#define	_SGI_UXUE_44	"uxue:44"
#define	_SGI_MUXUE_44	"uxue:44:Cannot find your utmp entry\n"
#define	_SGI_SUXUE_44	"Cannot find your utmp entry\n"
#define	_MSG_UXUE_45_MSG_NUM	45
#define	_MSG_UXUE_45_MSG_NUM_STR	":45"
#define	_MSG_UXUE_45_CAT_NUM_STR	"uxue:45"
#define	_MSG_UXUE_45_DEF_MSG	"Cannot determine your login terminal\n"
#define	_MSG_UXUE_45_CAT_NUM_STR_DEF_MSG	"uxue:45:Cannot determine your login terminal\n"
#define	_MSG_UXUE_45_MSG_NUM_STR_DEF_MSG	":45:Cannot determine your login terminal\n"
#define	_MSG_UXUE_45_FILE_CAT_NUM	uxue:45
#define	_SGI_DUXUE_45	":45"
#define	_SGI_UXUE_45	"uxue:45"
#define	_SGI_MUXUE_45	"uxue:45:Cannot determine your login terminal\n"
#define	_SGI_SUXUE_45	"Cannot determine your login terminal\n"
#define	_MSG_UXUE_46_MSG_NUM	46
#define	_MSG_UXUE_46_MSG_NUM_STR	":46"
#define	_MSG_UXUE_46_CAT_NUM_STR	"uxue:46"
#define	_MSG_UXUE_46_DEF_MSG	"Switch to channel 0 failed: %s\n"
#define	_MSG_UXUE_46_CAT_NUM_STR_DEF_MSG	"uxue:46:Switch to channel 0 failed: %s\n"
#define	_MSG_UXUE_46_MSG_NUM_STR_DEF_MSG	":46:Switch to channel 0 failed: %s\n"
#define	_MSG_UXUE_46_FILE_CAT_NUM	uxue:46
#define	_SGI_DUXUE_46	":46"
#define	_SGI_UXUE_46	"uxue:46"
#define	_SGI_MUXUE_46	"uxue:46:Switch to channel 0 failed: %s\n"
#define	_SGI_SUXUE_46	"Switch to channel 0 failed: %s\n"
#define	_MSG_UXUE_47_MSG_NUM	47
#define	_MSG_UXUE_47_MSG_NUM_STR	":47"
#define	_MSG_UXUE_47_CAT_NUM_STR	"uxue:47"
#define	_MSG_UXUE_47_DEF_MSG	"There may still be shl layers running\n"
#define	_MSG_UXUE_47_CAT_NUM_STR_DEF_MSG	"uxue:47:There may still be shl layers running\n"
#define	_MSG_UXUE_47_MSG_NUM_STR_DEF_MSG	":47:There may still be shl layers running\n"
#define	_MSG_UXUE_47_FILE_CAT_NUM	uxue:47
#define	_SGI_DUXUE_47	":47"
#define	_SGI_UXUE_47	"uxue:47"
#define	_SGI_MUXUE_47	"uxue:47:There may still be shl layers running\n"
#define	_SGI_SUXUE_47	"There may still be shl layers running\n"
#define	_MSG_UXUE_48_MSG_NUM	48
#define	_MSG_UXUE_48_MSG_NUM_STR	":48"
#define	_MSG_UXUE_48_CAT_NUM_STR	"uxue:48"
#define	_MSG_UXUE_48_DEF_MSG	"ioctl() SXTIOCSTAT failed: %s\n"
#define	_MSG_UXUE_48_CAT_NUM_STR_DEF_MSG	"uxue:48:ioctl() SXTIOCSTAT failed: %s\n"
#define	_MSG_UXUE_48_MSG_NUM_STR_DEF_MSG	":48:ioctl() SXTIOCSTAT failed: %s\n"
#define	_MSG_UXUE_48_FILE_CAT_NUM	uxue:48
#define	_SGI_DUXUE_48	":48"
#define	_SGI_UXUE_48	"uxue:48"
#define	_SGI_MUXUE_48	"uxue:48:ioctl() SXTIOCSTAT failed: %s\n"
#define	_SGI_SUXUE_48	"ioctl() SXTIOCSTAT failed: %s\n"
#define	_MSG_UXUE_49_MSG_NUM	49
#define	_MSG_UXUE_49_MSG_NUM_STR	":49"
#define	_MSG_UXUE_49_CAT_NUM_STR	"uxue:49"
#define	_MSG_UXUE_49_DEF_MSG	" blocked on input\n"
#define	_MSG_UXUE_49_CAT_NUM_STR_DEF_MSG	"uxue:49: blocked on input\n"
#define	_MSG_UXUE_49_MSG_NUM_STR_DEF_MSG	":49: blocked on input\n"
#define	_MSG_UXUE_49_FILE_CAT_NUM	uxue:49
#define	_SGI_DUXUE_49	":49"
#define	_SGI_UXUE_49	"uxue:49"
#define	_SGI_MUXUE_49	"uxue:49: blocked on input\n"
#define	_SGI_SUXUE_49	" blocked on input\n"
#define	_MSG_UXUE_50_MSG_NUM	50
#define	_MSG_UXUE_50_MSG_NUM_STR	":50"
#define	_MSG_UXUE_50_CAT_NUM_STR	"uxue:50"
#define	_MSG_UXUE_50_DEF_MSG	" blocked on output\n"
#define	_MSG_UXUE_50_CAT_NUM_STR_DEF_MSG	"uxue:50: blocked on output\n"
#define	_MSG_UXUE_50_MSG_NUM_STR_DEF_MSG	":50: blocked on output\n"
#define	_MSG_UXUE_50_FILE_CAT_NUM	uxue:50
#define	_SGI_DUXUE_50	":50"
#define	_SGI_UXUE_50	"uxue:50"
#define	_SGI_MUXUE_50	"uxue:50: blocked on output\n"
#define	_SGI_SUXUE_50	" blocked on output\n"
#define	_MSG_UXUE_51_MSG_NUM	51
#define	_MSG_UXUE_51_MSG_NUM_STR	":51"
#define	_MSG_UXUE_51_CAT_NUM_STR	"uxue:51"
#define	_MSG_UXUE_51_DEF_MSG	" executing or awaiting input\n"
#define	_MSG_UXUE_51_CAT_NUM_STR_DEF_MSG	"uxue:51: executing or awaiting input\n"
#define	_MSG_UXUE_51_MSG_NUM_STR_DEF_MSG	":51: executing or awaiting input\n"
#define	_MSG_UXUE_51_FILE_CAT_NUM	uxue:51
#define	_SGI_DUXUE_51	":51"
#define	_SGI_UXUE_51	"uxue:51"
#define	_SGI_MUXUE_51	"uxue:51: executing or awaiting input\n"
#define	_SGI_SUXUE_51	" executing or awaiting input\n"
#define	_MSG_UXUE_52_MSG_NUM	52
#define	_MSG_UXUE_52_MSG_NUM_STR	":52"
#define	_MSG_UXUE_52_CAT_NUM_STR	"uxue:52"
#define	_MSG_UXUE_52_DEF_MSG	"Syntax error\n"
#define	_MSG_UXUE_52_CAT_NUM_STR_DEF_MSG	"uxue:52:Syntax error\n"
#define	_MSG_UXUE_52_MSG_NUM_STR_DEF_MSG	":52:Syntax error\n"
#define	_MSG_UXUE_52_FILE_CAT_NUM	uxue:52
#define	_SGI_DUXUE_52	":52"
#define	_SGI_UXUE_52	"uxue:52"
#define	_SGI_MUXUE_52	"uxue:52:Syntax error\n"
#define	_SGI_SUXUE_52	"Syntax error\n"
#define	_MSG_UXUE_53_MSG_NUM	53
#define	_MSG_UXUE_53_MSG_NUM_STR	":53"
#define	_MSG_UXUE_53_CAT_NUM_STR	"uxue:53"
#define	_MSG_UXUE_53_DEF_MSG	"Illegal tabs\n"
#define	_MSG_UXUE_53_CAT_NUM_STR_DEF_MSG	"uxue:53:Illegal tabs\n"
#define	_MSG_UXUE_53_MSG_NUM_STR_DEF_MSG	":53:Illegal tabs\n"
#define	_MSG_UXUE_53_FILE_CAT_NUM	uxue:53
#define	_SGI_DUXUE_53	":53"
#define	_SGI_UXUE_53	"uxue:53"
#define	_SGI_MUXUE_53	"uxue:53:Illegal tabs\n"
#define	_SGI_SUXUE_53	"Illegal tabs\n"
#define	_MSG_UXUE_54_MSG_NUM	54
#define	_MSG_UXUE_54_MSG_NUM_STR	":54"
#define	_MSG_UXUE_54_CAT_NUM_STR	"uxue:54"
#define	_MSG_UXUE_54_DEF_MSG	"Unknown tab code\n"
#define	_MSG_UXUE_54_CAT_NUM_STR_DEF_MSG	"uxue:54:Unknown tab code\n"
#define	_MSG_UXUE_54_MSG_NUM_STR_DEF_MSG	":54:Unknown tab code\n"
#define	_MSG_UXUE_54_FILE_CAT_NUM	uxue:54
#define	_SGI_DUXUE_54	":54"
#define	_SGI_UXUE_54	"uxue:54"
#define	_SGI_MUXUE_54	"uxue:54:Unknown tab code\n"
#define	_SGI_SUXUE_54	"Unknown tab code\n"
#define	_MSG_UXUE_55_MSG_NUM	55
#define	_MSG_UXUE_55_MSG_NUM_STR	":55"
#define	_MSG_UXUE_55_CAT_NUM_STR	"uxue:55"
#define	_MSG_UXUE_55_DEF_MSG	"Illegal increment\n"
#define	_MSG_UXUE_55_CAT_NUM_STR_DEF_MSG	"uxue:55:Illegal increment\n"
#define	_MSG_UXUE_55_MSG_NUM_STR_DEF_MSG	":55:Illegal increment\n"
#define	_MSG_UXUE_55_FILE_CAT_NUM	uxue:55
#define	_SGI_DUXUE_55	":55"
#define	_SGI_UXUE_55	"uxue:55"
#define	_SGI_MUXUE_55	"uxue:55:Illegal increment\n"
#define	_SGI_SUXUE_55	"Illegal increment\n"
#define	_MSG_UXUE_56_MSG_NUM	56
#define	_MSG_UXUE_56_MSG_NUM_STR	":56"
#define	_MSG_UXUE_56_CAT_NUM_STR	"uxue:56"
#define	_MSG_UXUE_56_DEF_MSG	"File indirection\n"
#define	_MSG_UXUE_56_CAT_NUM_STR_DEF_MSG	"uxue:56:File indirection\n"
#define	_MSG_UXUE_56_MSG_NUM_STR_DEF_MSG	":56:File indirection\n"
#define	_MSG_UXUE_56_FILE_CAT_NUM	uxue:56
#define	_SGI_DUXUE_56	":56"
#define	_SGI_UXUE_56	"uxue:56"
#define	_SGI_MUXUE_56	"uxue:56:File indirection\n"
#define	_SGI_SUXUE_56	"File indirection\n"
#define	_MSG_UXUE_57_MSG_NUM	57
#define	_MSG_UXUE_57_MSG_NUM_STR	":57"
#define	_MSG_UXUE_57_CAT_NUM_STR	"uxue:57"
#define	_MSG_UXUE_57_DEF_MSG	"ioctl() failed: %s\n"
#define	_MSG_UXUE_57_CAT_NUM_STR_DEF_MSG	"uxue:57:ioctl() failed: %s\n"
#define	_MSG_UXUE_57_MSG_NUM_STR_DEF_MSG	":57:ioctl() failed: %s\n"
#define	_MSG_UXUE_57_FILE_CAT_NUM	uxue:57
#define	_SGI_DUXUE_57	":57"
#define	_SGI_UXUE_57	"uxue:57"
#define	_SGI_MUXUE_57	"uxue:57:ioctl() failed: %s\n"
#define	_SGI_SUXUE_57	"ioctl() failed: %s\n"
